Hoist alloca to entry early
matter-labs/era-compiler-llvm pull request #133
Opened 2022-11-03 10:22 UTC by akiramenai

2023-02-19 19:25 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-02-20 11:46 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                1.151 ║
║ Best                               38.554 ║
║ Worst                             -57.908 ║
║ Total                               1.045 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               70.886 ║
║ Worst                             -900.000 ║
║ Total                               1.420 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.111 ║
║ Best                                5.675 ║
║ Worst                             -28.354 ║
║ Total                              -1.232 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                5.842 ║
║ Best                               15.980 ║
║ Worst                               0.000 ║
║ Total                               5.195 ║
╚═══════════════════════════════════════════╝

```

2023-02-20 13:34 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                1.151 ║
║ Best                               38.554 ║
║ Worst                             -57.908 ║
║ Total                               1.045 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               70.886 ║
║ Worst                             -900.000 ║
║ Total                               1.420 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.111 ║
║ Best                                5.675 ║
║ Worst                             -28.354 ║
║ Total                              -1.232 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                5.842 ║
║ Best                               15.980 ║
║ Worst                               0.000 ║
║ Total                               5.195 ║
╚═══════════════════════════════════════════╝

```

2023-02-21 02:56 UTC, hedgar2017 commented
Do we know what causes the size regression?

2023-02-21 12:32 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                1.151 ║
║ Best                               38.554 ║
║ Worst                             -57.908 ║
║ Total                               1.045 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               70.886 ║
║ Worst                             -900.000 ║
║ Total                               1.420 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.111 ║
║ Best                                5.675 ║
║ Worst                             -28.354 ║
║ Total                              -1.232 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                5.842 ║
║ Best                               15.980 ║
║ Worst                               0.000 ║
║ Total                               5.195 ║
╚═══════════════════════════════════════════╝

```

2023-02-24 19:53 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                1.151 ║
║ Best                               38.554 ║
║ Worst                             -57.908 ║
║ Total                               1.045 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               70.886 ║
║ Worst                             -900.000 ║
║ Total                               0.464 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.111 ║
║ Best                                5.675 ║
║ Worst                             -28.354 ║
║ Total                              -1.232 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.900 ║
║ Best                                8.087 ║
║ Worst                              -1.282 ║
║ Total                               1.198 ║
╚═══════════════════════════════════════════╝

```

2023-02-24 22:59 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                1.151 ║
║ Best                               38.554 ║
║ Worst                             -57.908 ║
║ Total                               1.045 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               70.886 ║
║ Worst                             -900.000 ║
║ Total                               0.464 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.111 ║
║ Best                                5.675 ║
║ Worst                             -28.354 ║
║ Total                              -1.232 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.900 ║
║ Best                                8.087 ║
║ Worst                              -1.282 ║
║ Total                               1.198 ║
╚═══════════════════════════════════════════╝

```

2023-02-25 00:43 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                1.151 ║
║ Best                               38.554 ║
║ Worst                             -57.908 ║
║ Total                               1.045 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               70.886 ║
║ Worst                             -900.000 ║
║ Total                               0.462 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.111 ║
║ Best                                5.675 ║
║ Worst                             -28.354 ║
║ Total                              -1.232 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.900 ║
║ Best                                8.087 ║
║ Worst                              -1.282 ║
║ Total                               1.198 ║
╚═══════════════════════════════════════════╝

```

2023-02-25 09:44 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                1.151 ║
║ Best                               38.554 ║
║ Worst                             -57.908 ║
║ Total                               1.045 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               70.886 ║
║ Worst                             -900.000 ║
║ Total                               0.464 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.111 ║
║ Best                                5.675 ║
║ Worst                             -28.354 ║
║ Total                              -1.232 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.900 ║
║ Best                                8.087 ║
║ Worst                              -1.282 ║
║ Total                               1.198 ║
╚═══════════════════════════════════════════╝

```

2023-02-27 19:46 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                1.151 ║
║ Best                               38.554 ║
║ Worst                             -57.908 ║
║ Total                               1.045 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               70.886 ║
║ Worst                             -900.000 ║
║ Total                               0.464 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.111 ║
║ Best                                5.675 ║
║ Worst                             -28.354 ║
║ Total                              -1.232 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.900 ║
║ Best                                8.087 ║
║ Worst                              -1.282 ║
║ Total                               1.198 ║
╚═══════════════════════════════════════════╝

```

2023-02-28 10:16 UTC, akiramenai commented
`./bin/opt -Oz --time-passes ~/compiler-llvm/compiler-tester/trace/tests_solidity_complex_defi_UniswapV2Router01_UniswapV2Pair_ERC20_ERC20.sol.ERC20.unoptimized.ll`

Gives
```
===-------------------------------------------------------------------------===
                      ... Pass execution timing report ...
===-------------------------------------------------------------------------===
  Total Execution Time: 0.3311 seconds (0.3329 wall clock)

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  ---Instr---  --- Name ---
   0.0875 ( 28.1%)   0.0059 ( 30.4%)   0.0934 ( 28.2%)   0.0938 ( 28.2%)  494086213  ModuleInlinerWrapperPass
   0.0866 ( 27.8%)   0.0055 ( 28.3%)   0.0921 ( 27.8%)   0.0925 ( 27.8%)  489216870  DevirtSCCRepeatedPass
   0.0660 ( 21.2%)   0.0011 (  5.9%)   0.0672 ( 20.3%)   0.0677 ( 20.3%)  385575741  InstCombinePass
   0.0073 (  2.3%)   0.0002 (  1.1%)   0.0075 (  2.3%)   0.0076 (  2.3%)   44561715  IndVarSimplifyPass
   0.0041 (  1.3%)   0.0003 (  1.8%)   0.0044 (  1.3%)   0.0044 (  1.3%)   22897072  SimplifyCFGPass
   0.0039 (  1.3%)   0.0002 (  1.0%)   0.0041 (  1.2%)   0.0041 (  1.2%)   21437341  GVNPass
   0.0038 (  1.2%)   0.0003 (  1.6%)   0.0041 (  1.2%)   0.0041 (  1.2%)   20094300  EarlyCSEPass
   0.0037 (  1.2%)   0.0001 (  0.5%)   0.0038 (  1.1%)   0.0038 (  1.1%)   21538082  CorrelatedValuePropagationPass
   0.0034 (  1.1%)   0.0003 (  1.5%)   0.0037 (  1.1%)   0.0037 (  1.1%)   17705635  InlinerPass
   0.0027 (  0.9%)   0.0006 (  3.0%)   0.0033 (  1.0%)   0.0034 (  1.0%)   15689544  BlockFrequencyAnalysis
   0.0030 (  0.9%)   0.0002 (  1.2%)   0.0032 (  1.0%)   0.0033 (  1.0%)   14980547  IPSCCPPass
   ```
   After the transformation, and
   ```
   ===-------------------------------------------------------------------------===
                      ... Pass execution timing report ...
===-------------------------------------------------------------------------===
  Total Execution Time: 0.2381 seconds (0.2383 wall clock)

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  ---Instr---  --- Name ---
   0.0624 ( 27.8%)   0.0041 ( 30.6%)   0.0665 ( 27.9%)   0.0665 ( 27.9%)  394273323  ModuleInlinerWrapperPass
   0.0620 ( 27.6%)   0.0039 ( 29.2%)   0.0659 ( 27.7%)   0.0659 ( 27.7%)  391878229  DevirtSCCRepeatedPass
   0.0524 ( 23.3%)   0.0007 (  5.3%)   0.0531 ( 22.3%)   0.0531 ( 22.3%)  341820170  InstCombinePass
   0.0049 (  2.2%)   0.0002 (  1.3%)   0.0051 (  2.1%)   0.0051 (  2.1%)   32461144  IndVarSimplifyPass
   0.0033 (  1.5%)   0.0002 (  1.5%)   0.0035 (  1.5%)   0.0035 (  1.5%)   22073028  EarlyCSEPass
   0.0028 (  1.2%)   0.0002 (  1.7%)   0.0030 (  1.3%)   0.0030 (  1.3%)   16282034  GVNPass
   0.0025 (  1.1%)   0.0002 (  1.8%)   0.0028 (  1.2%)   0.0028 (  1.2%)   14414712  InlinerPass
   0.0026 (  1.1%)   0.0002 (  1.2%)   0.0027 (  1.1%)   0.0027 (  1.1%)   16373984  SimplifyCFGPass
   0.0024 (  1.1%)   0.0001 (  0.5%)   0.0025 (  1.0%)   0.0025 (  1.1%)   15988383  CorrelatedValuePropagationPass
   0.0020 (  0.9%)   0.0004 (  3.0%)   0.0024 (  1.0%)   0.0024 (  1.0%)   12313394  BlockFrequencyAnalysis
   ```
before. I previously run it in debug mode and it was my mistake. So the passes seems to do more checks and transformations, yet I'm not confident that it fully explains the difference in CI running time.

2023-02-28 10:21 UTC, akiramenai commented
Codegen seems to be affected as well.
For the aforementioned contract now:
```
===-------------------------------------------------------------------------===
                      ... Pass execution timing report ...
===-------------------------------------------------------------------------===
  Total Execution Time: 0.0562 seconds (0.0565 wall clock)

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  ---Instr---  --- Name ---
   0.0232 ( 52.2%)   0.0062 ( 52.3%)   0.0293 ( 52.2%)   0.0295 ( 52.3%)  133040472  SyncVM DAG->DAG Pattern Instruction Selection
   0.0041 (  9.2%)   0.0010 (  8.7%)   0.0051 (  9.1%)   0.0051 (  9.1%)   26493019  Greedy Register Allocator
   0.0013 (  3.0%)   0.0003 (  2.5%)   0.0016 (  2.9%)   0.0016 (  2.9%)   10515404  SyncVM Assembly Printer
   0.0011 (  2.4%)   0.0001 (  0.8%)   0.0012 (  2.1%)   0.0012 (  2.0%)    6060411  CodeGen Prepare
   0.0004 (  1.0%)   0.0005 (  4.3%)   0.0009 (  1.7%)   0.0009 (  1.6%)   14395557  Machine Module Information
   0.0004 (  1.0%)   0.0004 (  3.3%)   0.0008 (  1.5%)   0.0009 (  1.5%)   12328284  Dominator Tree Construction #2
   0.0004 (  0.9%)   0.0004 (  3.5%)   0.0008 (  1.4%)   0.0008 (  1.4%)   12029811  Function Alias Analysis Results #2
   0.0003 (  0.8%)   0.0004 (  3.1%)   0.0007 (  1.3%)   0.0007 (  1.3%)   11949292  Basic Alias Analysis (stateless AA impl) #3
   0.0007 (  1.5%)   0.0001 (  0.5%)   0.0007 (  1.3%)   0.0007 (  1.3%)    3768350  Link runtime library into the module
   0.0006 (  1.3%)   0.0001 (  0.7%)   0.0007 (  1.2%)   0.0007 (  1.2%)    4603223  Live Interval Analysis
   0.0006 (  1.3%)   0.0000 (  0.2%)   0.0006 (  1.1%)   0.0006 (  1.1%)    4807904  Machine Common Subexpression Elimination
   0.0005 (  1.2%)   0.0001 (  0.4%)   0.0006 (  1.1%)   0.0006 (  1.1%)    4504768  Live Variable Analysis
```
Before the PR:
```
===-------------------------------------------------------------------------===
                      ... Pass execution timing report ...
===-------------------------------------------------------------------------===
  Total Execution Time: 0.0463 seconds (0.0462 wall clock)

   ---User Time---   --System Time--   --User+System--   ---Wall Time---  ---Instr---  --- Name ---
   0.0192 ( 52.3%)   0.0060 ( 63.6%)   0.0253 ( 54.6%)   0.0253 ( 54.7%)  104221333  SyncVM DAG->DAG Pattern Instruction Selection
   0.0033 (  8.9%)   0.0010 ( 10.4%)   0.0043 (  9.2%)   0.0043 (  9.2%)   19959051  Greedy Register Allocator
   0.0014 (  3.7%)   0.0003 (  3.0%)   0.0017 (  3.6%)   0.0016 (  3.6%)   10136097  SyncVM Assembly Printer
   0.0010 (  2.7%)   0.0001 (  0.6%)   0.0011 (  2.3%)   0.0011 (  2.3%)    5141157  CodeGen Prepare
   0.0008 (  2.1%)   0.0001 (  0.6%)   0.0008 (  1.8%)   0.0008 (  1.8%)    3478916  Link runtime library into the module
   0.0006 (  1.6%)   0.0000 (  0.1%)   0.0006 (  1.3%)   0.0006 (  1.3%)    4301476  Machine Common Subexpression Elimination
   0.0005 (  1.4%)   0.0001 (  0.7%)   0.0006 (  1.2%)   0.0006 (  1.2%)    3016830  Live Interval Analysis
   0.0005 (  1.4%)   0.0000 (  0.4%)   0.0006 (  1.2%)   0.0006 (  1.2%)    3636181  Live Variable Analysis
```

2023-03-02 20:37 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.747 ║
║ Best                               44.755 ║
║ Worst                             -60.442 ║
║ Total                               0.606 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.386 ║
║ Best                               74.292 ║
║ Worst                             -900.000 ║
║ Total                               0.175 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.196 ║
║ Best                                5.663 ║
║ Worst                             -28.408 ║
║ Total                              -1.348 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.421 ║
║ Best                                9.213 ║
║ Worst                              -1.385 ║
║ Total                               0.503 ║
╚═══════════════════════════════════════════╝

```

2023-03-02 21:34 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.145 ║
║ Best                               44.755 ║
║ Worst                             -60.442 ║
║ Total                               0.059 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.285 ║
║ Best                               74.292 ║
║ Worst                             -154.286 ║
║ Total                               0.157 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.551 ║
║ Best                                1.385 ║
║ Worst                             -28.408 ║
║ Total                              -1.670 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.021 ║
║ Best                                9.213 ║
║ Worst                              -1.327 ║
║ Total                               0.232 ║
╚═══════════════════════════════════════════╝

```

2023-03-02 23:19 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.747 ║
║ Best                               44.755 ║
║ Worst                             -60.442 ║
║ Total                               0.606 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.386 ║
║ Best                               74.292 ║
║ Worst                             -900.000 ║
║ Total                               0.175 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.196 ║
║ Best                                5.663 ║
║ Worst                             -28.408 ║
║ Total                              -1.348 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.421 ║
║ Best                                9.213 ║
║ Worst                              -1.385 ║
║ Total                               0.503 ║
╚═══════════════════════════════════════════╝

```

2023-03-06 15:49 UTC, lialan commented
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.747 ║
║ Best                               44.755 ║
║ Worst                             -60.442 ║
║ Total                               0.606 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.386 ║
║ Best                               74.292 ║
║ Worst                             -900.000 ║
║ Total                               0.175 ║
╚═══════════════════════════════════════════╝
```

Wow this is wild.

2023-03-06 16:52 UTC, hedgar2017 requested changes
What are we going to do with this patch?

2023-03-07 14:36 UTC, lialan reviewed
Generally LGTM, as the utility is coming from PTX, and the operation is safe on IR level.

But I am curious about the performance impact. Some have super big impacts (900% degradation, which is highly suspicious because we only move instructions around in this patch), are we sure we should swallow that? 

My guess is this degradation again relates to additional register spills and reloads. Perhaps we should make sure it is what we think is?

2023-03-07 14:36 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMTargetMachine.cpp
> +        }
I fee like logically we should move the LinkRuntmePass before AllocaHoisting, so AllocaHoisting can cover the newly introduced runtime functions.

But this will not make any sensible changes, so I am okay with it.

2023-03-07 14:36 UTC, lialan commented on llvm/lib/Transforms/Utils/AllocaHoisting.cpp
> +bool llvm::HoistAllocaToEntry(Function &F) {
I know this utility comes from PTX backend, but any reason we do not include it in a class?

If it is coming from upstream, it would be good to include such information in the commit message.

2023-03-09 11:49 UTC, akiramenai commented
We decided to postpone with this PR until we get better understanding of the optimization pipeline.

2023-05-16 19:37 UTC, akiramenai commented
Needs additional research
https://linear.app/matterlabs/issue/CPR-1106/investigate-why-early-alloca-hoisting-doesnt-always-help

2023-05-16 19:37 UTC, closed without merging