Improve runtime linkage
matter-labs/era-compiler-llvm pull request #202
Opened 2023-02-13 14:35 UTC by akiramenai

The PR consists of 3 patches. The first one addresses issue of compilation time increase due to early runtime linkage:
```
Split runtime in two parts: runtime and stdlib. Stdlib is the part to be
linked and internalized in the beginning of opt pipeline. Then global
DCE removes the unused parts. So small contracts doesn't blow up and
affect compilation time. Runtime is linked in the beginning of llc
pipeline.

This solution replaces previously used internalize-early,
internalize-late function attributes.
```
The remaining two, remove local changes in old pm pipeline.

2023-02-17 11:12 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.364 ║
║ Best                                3.478 ║
║ Worst                             -13.494 ║
║ Total                              -0.317 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                3.125 ║
║ Worst                             -12.727 ║
║ Total                              -0.012 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.055 ║
║ Best                                0.786 ║
║ Worst                             -13.494 ║
║ Total                              -0.279 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.541 ║
║ Best                                0.047 ║
║ Worst                              -2.113 ║
║ Total                              -0.247 ║
╚═══════════════════════════════════════════╝

```

2023-02-17 14:43 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.364 ║
║ Best                                3.478 ║
║ Worst                             -13.494 ║
║ Total                              -0.317 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                3.125 ║
║ Worst                             -12.727 ║
║ Total                              -0.012 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.055 ║
║ Best                                0.786 ║
║ Worst                             -13.494 ║
║ Total                              -0.279 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.541 ║
║ Best                                0.047 ║
║ Worst                              -2.113 ║
║ Total                              -0.247 ║
╚═══════════════════════════════════════════╝

```

2023-02-17 22:48 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.019 ║
║ Best                                2.326 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-02-18 10:09 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.019 ║
║ Best                                2.326 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-02-18 15:07 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.019 ║
║ Best                                2.326 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-02-18 20:24 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.019 ║
║ Best                                2.326 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-02-21 02:25 UTC, lialan approved these changes
Just a typo, otherwise LGTM.

2023-02-21 02:25 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMLinkRuntime.cpp
> +  SyncVMLinkRuntime(bool IsRuntimeLinage = false)
nit: typo.

2023-02-21 02:25 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMLinkRuntime.cpp
> +  bool IsRuntimeLinage;
nit: typo here too.

2023-02-21 12:38 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.019 ║
║ Best                                2.326 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-02-21 14:08 UTC, hedgar2017 requested changes
Let's rename 'ergs' => 'gas' in this PR.

2023-02-21 16:04 UTC, akiramenai commented
@hedgar2017 did it in a separate one as renaming has nothing to do with linkage.

2023-02-21 18:00 UTC, hedgar2017 approved these changes

2023-02-21 18:29 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.019 ║
║ Best                                2.326 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-02-22 14:11 UTC, akiramenai commented
All 18 failures are due to `context.set_gas_per_pubdata`, so I'm pushing without double check.

2023-02-22 14:11 UTC, merged