Do not optimize memcpy of size is bigger than i64
matter-labs/era-compiler-llvm pull request #215
Opened 2023-03-09 15:30 UTC by lialan

Just a quick fix to avoid crashing in LLVM, regardless of the correctness of frontend emitted IR.

2023-03-09 15:32 UTC, lialan commented
This is really a half-baked, very quick solution, it just make the backend avoid crashing.

2023-03-09 15:56 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-03-09 15:59 UTC, akiramenai commented
Please note that the failing test is marked as ignored in compiler-tester. So please attach a regression one to the patch to make sure that not just LibCallSimplifier doesn't crash, but also the rest of the pipeline doesn't assume i64 size limit for memcpy.

2023-03-09 22:13 UTC, lialan commented
Manual workflow: https://github.com/matter-labs/compiler-llvm/actions/runs/4378366128/jobs/7663018915

2023-03-10 01:56 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-03-10 02:33 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-03-10 08:24 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMLowerIntrinsics.cpp
> +  APInt CopyLenAPInt;
good place to initialize with a lambda.

2023-03-10 08:24 UTC, akiramenai commented on llvm/lib/Analysis/MemoryLocation.cpp
> +    auto T = Call->getParent()->getParent()->getParent()->getTargetTriple();
`getModule()`

2023-03-10 08:24 UTC, akiramenai commented on llvm/lib/Analysis/MemoryLocation.cpp
> +      case Intrinsic::memset:
We don't support anything but `memcpy` anyway (They won't be lowered correctly). So it might be worth to make everything but `memcpy` unreachable.

2023-03-10 08:24 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMLowerIntrinsics.cpp
> +  //assert(BytesCopied == CopyLen->getZExtValue() &&
`CopyLenAPInt`

2023-03-10 08:24 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMLowerIntrinsics.cpp
> +  APInt CopyLenAPInt;
nitpicking: `CopyLenVal` might be a better name since all the computations below are in `APInt`s, it doesn't make sense to pinpoint it in this particular variable name.

2023-03-10 08:24 UTC, akiramenai commented on llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp
> +static bool isHandleableSize(Value* Size) {
nitpicking: `isInt64` or something alike would be better. Handleable is too vague. `APInt` is handleable in principle, it's just unhandled.

2023-03-10 14:35 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-03-10 15:43 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-03-11 18:00 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-03-11 23:08 UTC, lialan commented on llvm/lib/Analysis/MemoryLocation.cpp
> +      case Intrinsic::memset:
I am not sure if this statement is correct, please see this run: https://github.com/matter-labs/compiler-llvm/actions/runs/4393409768/jobs/7693785877

```
Call Instruction:   call void @llvm.lifetime.start.p0(i64 64, ptr nonnull %ZKSYNC_NEAR_CALL_tuple2_near_call_return_pointer_argument.i)
[657](https://github.com/matter-labs/compiler-llvm/actions/runs/4393409768/jobs/7693785877#step:16:658)
Unexpected intrinsic for SyncVM target with Intrinsic ID: 167
[658](https://github.com/matter-labs/compiler-llvm/actions/runs/4393409768/jobs/7693785877#step:16:659)
UNREACHABLE executed at /__w/compiler-llvm/compiler-llvm/compiler-tester/llvm/llvm/lib/Analysis/MemoryLocation.cpp:200!
```

2023-03-11 23:19 UTC, lialan commented on llvm/lib/Analysis/MemoryLocation.cpp
> +      case Intrinsic::memset:
Okay, so `lifetime` intrinsics serve as hints in inliner, and is inserted in CodeExtractor. We should ignore these intrinsics in the check.

2023-03-11 23:41 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-03-12 14:34 UTC, lialan commented on llvm/lib/Analysis/MemoryLocation.cpp
> +    auto T = Call->getParent()->getParent()->getParent()->getTargetTriple();
done.

2023-03-12 14:34 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMLowerIntrinsics.cpp
> +  APInt CopyLenAPInt;
right. updated.

2023-03-12 14:34 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMLowerIntrinsics.cpp
> +  //assert(BytesCopied == CopyLen->getZExtValue() &&
Updated.

2023-03-12 14:34 UTC, lialan commented on llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp
> +static bool isHandleableSize(Value* Size) {
Indeed a better name. updated.

2023-03-12 21:21 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-03-12 23:17 UTC, lialan commented on llvm/lib/Analysis/MemoryLocation.cpp
> +      case Intrinsic::memset:
Oh, so there are some memcpy/memmove generic unit tests, so we cannot exclude them.

2023-03-13 14:19 UTC, akiramenai requested changes
Please add llc test cases.

2023-03-13 14:19 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMLowerIntrinsics.cpp
> +  APInt CopyLenVal = [&] {
Explicit capturing `CopyLen` by value is preferable as it's a pointer.

2023-03-13 14:19 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMLowerIntrinsics.cpp
> +    if (ConstantInt *LenC = dyn_cast<ConstantInt>(CopyLen)) {
Sorry, haven't noticed it first time, but `CopyLen` is a `ConstantInt` so how can we reach `else` here?

2023-03-13 14:19 UTC, akiramenai commented on llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp
> +static bool isInt64(Value* Size) {
`isInt64Constant` (sorry, forgot about that we are casting from Value to ConstInt) is more precise, and the comment below is not relevant to `isInt64` function which merely checks if Size meets the requirement, it should be put to the call sites. It's also better to rephrase that sizes bigger than i64 aren't handled yet, "can't" implies impossibility to handle in principle.

2023-03-13 14:19 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/memintrinsics.ll
> +}
Can we check that we have a proper codegen for a known size memcpy as well?

2023-03-13 19:52 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMLowerIntrinsics.cpp
> +    if (ConstantInt *LenC = dyn_cast<ConstantInt>(CopyLen)) {
This is indeed correct for known loops.

2023-03-14 12:22 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-03-14 13:47 UTC, lialan commented on llvm/test/CodeGen/SyncVM/memintrinsics.ll
> +}
Yes, added llc tests.

2023-03-14 13:47 UTC, lialan commented on llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp
> +static bool isInt64(Value* Size) {
Updated

2023-03-14 13:47 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMLowerIntrinsics.cpp
> +    if (ConstantInt *LenC = dyn_cast<ConstantInt>(CopyLen)) {
Updated

2023-03-14 13:48 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMLowerIntrinsics.cpp
> +  APInt CopyLenVal = [&] {
Removed lambda.

2023-03-14 14:26 UTC, akiramenai commented on llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp
> +// On SyncVM target, we allow sizes up to 256bits because we allow i256 datatype,
clang-format please

2023-03-14 14:26 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/memintrinsics.ll
> +define fastcc void @huge-copysize0(i256 addrspace(0)* %dest, i256 addrspace(0)* %src) {
Could we check that the number of iterations is derived from number of bytes to copy, i.e. 81129638414606681695789005144064 / 32 or something.

2023-03-14 15:20 UTC, lialan commented on llvm/test/CodeGen/SyncVM/memintrinsics.ll
> +define fastcc void @huge-copysize0(i256 addrspace(0)* %dest, i256 addrspace(0)* %src) {
I actually have 2 smaller tests down in this file to check that: 
1. if the known value is dividable by 32
2. not dividable by 32

I don't mind check the big values as well.

2023-03-14 16:03 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/memintrinsics.ll
> +define fastcc void @huge-copysize0(i256 addrspace(0)* %dest, i256 addrspace(0)* %src) {
I mostly concerned not with the loop structure. We have other tests to check it. I concerned with the number of iterations, it must not be truncated, so having for instance 2^65 * 32 + 3 * 32 number of bytes to be copied, there must be 2^65 + 3 iterations, not 3 (the result if somewhere in the pipeline we truncated to i64).

2023-03-14 20:02 UTC, akiramenai approved these changes
LGTM, please squash

2023-03-14 20:12 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-03-14 20:47 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-03-15 00:42 UTC, merged