Clean up unused code according to coverage report
matter-labs/era-compiler-llvm pull request #216
Opened 2023-03-21 00:49 UTC by lialan

2023-03-21 01:18 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-03-22 20:15 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-04-03 09:57 UTC, akiramenai requested changes

2023-04-03 09:57 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMExpandPseudoInsts.cpp
> +      } else if (MI.getOpcode() == SyncVM::LOADCONST) {
Could you explain how has it worked before?

2023-04-03 09:57 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMRegisterInfo.cpp
> +    assert(Offset < 0 && "On SyncVM, offset cannot be positive");
Nothing technically prevent us from having it, i.e. the VM supports. Solidity doesn't produce negative offsets, we don't have much tests to cover negative offsets, etc, but in principle if we (or our partners) ever support C++ or something alike, negative offsets will be of need. So I prefer to keep the original implementation.

2023-04-03 15:46 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMRegisterInfo.cpp
> +    assert(Offset < 0 && "On SyncVM, offset cannot be positive");
It is actually stated in the spec that stack addressing mode does not allow zero or positive offsets.

But you are right, I found this security feature too strict for backend implementation. We should either update the spec or do this assert to guard this off.

2023-04-06 10:47 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMExpandPseudoInsts.cpp
> +      } else if (MI.getOpcode() == SyncVM::LOADCONST) {
My previous comments were wrong: I just moved the LOADCONST around to make the cod e more concise.

2023-04-09 21:06 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMRegisterInfo.cpp
> +    assert(Offset < 0 && "On SyncVM, offset cannot be positive");
I missed that we are calculating the offset here based on the frame structure. We indeed should never have it negative or something went wrong with the frame construction. So, let's go with your option.

2023-04-09 21:18 UTC, akiramenai approved these changes
Please squash

2023-05-07 05:32 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-05-07 13:07 UTC, merged