Allow arbitrary offset for GEP
matter-labs/era-compiler-llvm pull request #223
Opened 2023-04-14 22:22 UTC by lialan

2023-04-14 22:49 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-04-17 11:20 UTC, akiramenai requested changes
Tests are missing

2023-04-17 11:20 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +      TmpOffset = Builder.getInt(Offset);
My personal solution was
```
TmpOffset = Builder.getInt(Offset.sext(256));
```
Please add a test which trigger offset addition with different bitness of APInts.

2023-04-17 12:28 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +      TmpOffset = Builder.getInt(Offset);
Updated

2023-04-17 12:28 UTC, lialan commented
Added the test @akiramenai mentioned and another 128bit test.

2023-04-17 12:56 UTC, akiramenai approved these changes

2023-04-17 13:13 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-04-17 17:31 UTC, hedgar2017 approved these changes

2023-04-17 17:31 UTC, hedgar2017 requested changes

2023-04-17 17:31 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +      TmpOffset = Builder.getInt(Offset.sext(256));
sext?

2023-04-17 19:08 UTC, hedgar2017 approved these changes

2023-04-17 19:08 UTC, merged