Support and fold uaddo/umulo/usubo
matter-labs/era-compiler-llvm pull request #225
Opened 2023-04-19 12:15 UTC by lialan

2023-04-19 14:41 UTC, lialan commented
Also saw this pattern that we can fold:
```
add     r1, r2, r3
add     r3, r0, stack-[1]               ; 32-byte Folded Spill
```

note that the second add is a a spill so we must fold after register allocation.

2023-04-19 17:46 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-04-20 01:24 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-04-26 12:17 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.040 ║
║ Best                               18.868 ║
║ Worst                              -2.410 ║
║ Total                               0.081 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.021 ║
║ Best                               22.078 ║
║ Worst                              -0.676 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.417 ║
║ Best                                4.011 ║
║ Worst                              -0.208 ║
║ Total                               0.417 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.503 ║
║ Best                                9.201 ║
║ Worst                              -0.169 ║
║ Total                               0.068 ║
╚═══════════════════════════════════════════╝

```

2023-04-27 02:00 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.040 ║
║ Best                               18.868 ║
║ Worst                              -2.410 ║
║ Total                               0.081 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.021 ║
║ Best                               22.078 ║
║ Worst                              -0.676 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.417 ║
║ Best                                4.011 ║
║ Worst                              -0.208 ║
║ Total                               0.417 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.503 ║
║ Best                                9.201 ║
║ Worst                              -0.169 ║
║ Total                               0.068 ║
╚═══════════════════════════════════════════╝

```

2023-04-27 12:47 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.040 ║
║ Best                               18.868 ║
║ Worst                              -2.410 ║
║ Total                               0.081 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.021 ║
║ Best                               22.078 ║
║ Worst                              -0.676 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.417 ║
║ Best                                4.011 ║
║ Worst                              -0.208 ║
║ Total                               0.417 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.503 ║
║ Best                                9.201 ║
║ Worst                              -0.169 ║
║ Total                               0.068 ║
╚═══════════════════════════════════════════╝

```

2023-05-03 03:57 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.040 ║
║ Best                               18.868 ║
║ Worst                              -2.410 ║
║ Total                               0.081 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.021 ║
║ Best                               22.078 ║
║ Worst                              -0.676 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.417 ║
║ Best                                4.011 ║
║ Worst                              -0.208 ║
║ Total                               0.417 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.503 ║
║ Best                                9.201 ║
║ Worst                              -0.169 ║
║ Total                               0.068 ║
╚═══════════════════════════════════════════╝

```

2023-05-03 21:10 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.040 ║
║ Best                               18.868 ║
║ Worst                              -2.410 ║
║ Total                               0.081 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.021 ║
║ Best                               22.078 ║
║ Worst                              -0.676 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.417 ║
║ Best                                4.011 ║
║ Worst                              -0.208 ║
║ Total                               0.417 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.503 ║
║ Best                                9.201 ║
║ Worst                              -0.169 ║
║ Total                               0.068 ║
╚═══════════════════════════════════════════╝

```

2023-05-08 22:35 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.087 ║
║ Best                               18.868 ║
║ Worst                              -2.410 ║
║ Total                               0.101 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.038 ║
║ Best                               22.078 ║
║ Worst                              -0.676 ║
║ Total                               0.008 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.427 ║
║ Best                                4.011 ║
║ Worst                              -0.208 ║
║ Total                               0.419 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.523 ║
║ Best                                9.201 ║
║ Worst                              -0.169 ║
║ Total                               0.192 ║
╚═══════════════════════════════════════════╝

```

2023-05-09 14:29 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.087 ║
║ Best                               18.868 ║
║ Worst                              -2.410 ║
║ Total                               0.101 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.046 ║
║ Best                               22.078 ║
║ Worst                              -0.676 ║
║ Total                               0.009 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.427 ║
║ Best                                4.011 ║
║ Worst                              -0.208 ║
║ Total                               0.419 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.529 ║
║ Best                                9.201 ║
║ Worst                              -0.169 ║
║ Total                               0.234 ║
╚═══════════════════════════════════════════╝

```

2023-05-09 22:14 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.087 ║
║ Best                               18.868 ║
║ Worst                              -2.410 ║
║ Total                               0.101 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.046 ║
║ Best                               22.078 ║
║ Worst                              -0.676 ║
║ Total                               0.009 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.427 ║
║ Best                                4.011 ║
║ Worst                              -0.208 ║
║ Total                               0.419 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.529 ║
║ Best                                9.201 ║
║ Worst                              -0.169 ║
║ Total                               0.234 ║
╚═══════════════════════════════════════════╝

```

2023-05-10 07:51 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.087 ║
║ Best                               18.868 ║
║ Worst                              -2.410 ║
║ Total                               0.101 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.046 ║
║ Best                               22.078 ║
║ Worst                              -0.676 ║
║ Total                               0.009 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.427 ║
║ Best                                4.011 ║
║ Worst                              -0.208 ║
║ Total                               0.419 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.529 ║
║ Best                                9.201 ║
║ Worst                              -0.169 ║
║ Total                               0.234 ║
╚═══════════════════════════════════════════╝

```

2023-05-10 21:22 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.087 ║
║ Best                               18.868 ║
║ Worst                              -2.410 ║
║ Total                               0.101 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.046 ║
║ Best                               22.078 ║
║ Worst                              -0.676 ║
║ Total                               0.009 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.427 ║
║ Best                                4.011 ║
║ Worst                              -0.208 ║
║ Total                               0.419 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.529 ║
║ Best                                9.201 ║
║ Worst                              -0.169 ║
║ Total                               0.234 ║
╚═══════════════════════════════════════════╝

```

2023-05-15 20:13 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.087 ║
║ Best                               18.868 ║
║ Worst                              -2.410 ║
║ Total                               0.101 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.046 ║
║ Best                               22.078 ║
║ Worst                              -0.676 ║
║ Total                               0.009 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.427 ║
║ Best                                4.011 ║
║ Worst                              -0.208 ║
║ Total                               0.419 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.529 ║
║ Best                                9.201 ║
║ Worst                              -0.169 ║
║ Total                               0.234 ║
╚═══════════════════════════════════════════╝

```

2023-05-16 22:23 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.090 ║
║ Best                               18.868 ║
║ Worst                               0.000 ║
║ Total                               0.110 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.047 ║
║ Best                               22.078 ║
║ Worst                              -0.083 ║
║ Total                               0.011 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.467 ║
║ Best                                4.011 ║
║ Worst                               0.000 ║
║ Total                               0.505 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.533 ║
║ Best                                9.201 ║
║ Worst                               0.000 ║
║ Total                               0.236 ║
╚═══════════════════════════════════════════╝

```

2023-05-17 01:21 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.090 ║
║ Best                               18.868 ║
║ Worst                               0.000 ║
║ Total                               0.110 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.047 ║
║ Best                               22.078 ║
║ Worst                              -0.083 ║
║ Total                               0.011 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.467 ║
║ Best                                4.011 ║
║ Worst                               0.000 ║
║ Total                               0.505 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.533 ║
║ Best                                9.201 ║
║ Worst                               0.000 ║
║ Total                               0.236 ║
╚═══════════════════════════════════════════╝

```

2023-05-19 13:24 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.138 ║
║ Best                               26.415 ║
║ Worst                               0.000 ║
║ Total                               0.194 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.067 ║
║ Best                               33.974 ║
║ Worst                              -0.368 ║
║ Total                               0.022 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.666 ║
║ Best                                5.158 ║
║ Worst                               0.000 ║
║ Total                               0.773 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.726 ║
║ Best                               12.342 ║
║ Worst                               0.000 ║
║ Total                               0.321 ║
╚═══════════════════════════════════════════╝

```

2023-05-19 20:51 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.138 ║
║ Best                               26.415 ║
║ Worst                               0.000 ║
║ Total                               0.194 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.067 ║
║ Best                               33.974 ║
║ Worst                              -0.368 ║
║ Total                               0.022 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.666 ║
║ Best                                5.158 ║
║ Worst                               0.000 ║
║ Total                               0.773 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.726 ║
║ Best                               12.342 ║
║ Worst                               0.000 ║
║ Total                               0.321 ║
╚═══════════════════════════════════════════╝

```

2023-05-22 15:38 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.138 ║
║ Best                               26.415 ║
║ Worst                               0.000 ║
║ Total                               0.194 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.067 ║
║ Best                               33.974 ║
║ Worst                              -0.368 ║
║ Total                               0.022 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.666 ║
║ Best                                5.158 ║
║ Worst                               0.000 ║
║ Total                               0.773 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.726 ║
║ Best                               12.342 ║
║ Worst                               0.000 ║
║ Total                               0.321 ║
╚═══════════════════════════════════════════╝

```

2023-05-23 17:54 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.137 ║
║ Best                               26.415 ║
║ Worst                               0.000 ║
║ Total                               0.190 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.067 ║
║ Best                               33.974 ║
║ Worst                              -0.368 ║
║ Total                               0.022 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.666 ║
║ Best                                5.158 ║
║ Worst                               0.000 ║
║ Total                               0.773 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.726 ║
║ Best                               12.342 ║
║ Worst                               0.000 ║
║ Total                               0.321 ║
╚═══════════════════════════════════════════╝

```

2023-05-23 22:09 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.137 ║
║ Best                               26.415 ║
║ Worst                               0.000 ║
║ Total                               0.190 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.067 ║
║ Best                               33.974 ║
║ Worst                              -0.368 ║
║ Total                               0.022 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.666 ║
║ Best                                5.158 ║
║ Worst                               0.000 ║
║ Total                               0.773 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.726 ║
║ Best                               12.342 ║
║ Worst                               0.000 ║
║ Total                               0.321 ║
╚═══════════════════════════════════════════╝

```

2023-05-24 16:48 UTC, akiramenai requested changes
Need documentation and cleanup

2023-05-24 16:48 UTC, akiramenai commented on llvm/lib/Target/SyncVM/MCTargetDesc/SyncVMInstPrinter.cpp
> +  case SyncVMCC::COND_OF: // Overflow is same as LT
Redundant comment, obvious from code.

2023-05-24 16:48 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVM.h
> +  COND_OF,       /// An Overflow flag, cannot be reversed
It worth documenting the enumeration describing why we need reversible and non-reversible versions of OF.

2023-05-24 16:48 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +  bool rearrangeOverflowHandlingBranches(Function &F);
Worth describing intent.

2023-05-24 16:48 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +      // %5 = call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 %4, i32 1),
Please remove irrelevant metadata from the example.

2023-05-24 16:48 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +        FBB->moveAfter(BB);
Is it still profitable if there are more than one use which meet the criteria? I mean if it still profitable to move subsequent FBBs after the 1st one and put branch probability to TBB.

2023-05-24 16:48 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +                  llvm::ConstantAsMetadata::get(
Please document the meaning

2023-05-24 16:48 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMExpandPseudoInsts.cpp
> +    {SyncVM::MULrrr_v, SyncVM::MULrrrr_v},
I get it why you call lhs a pseudo, though it's not obvious at glance, yet, can we do this transformation in the post-isel hook?

2023-05-24 16:48 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +  auto MatchedUArithO = [&] {
Please extract as function.

2023-05-24 16:48 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +      auto Call = dyn_cast<CallInst>(&I);
Worth extracting _a function_ similar to `MatchedUArithO`.

2023-05-24 16:48 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +    SDVTList VTs = DAG.getVTList(MVT::i256);
Redundant as MVT::i256 should work as well as the list.

2023-05-24 16:48 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +      case ISD::UADDO:
A map is much simpler way do describe correspondence between the original SD Node and you plan to generate.

2023-05-24 16:48 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +        DAG.ReplaceAllUsesOfValueWith(MatchedUArithO.getValue(0), FoldedArith.getValue(0));
Please reformat

2023-05-24 16:48 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.td
> +def : Pat<(SyncVMMul_v GR256:$rs0, GR256:$rs1), (MULrrr_v GR256:$rs0, GR256:$rs1, 0)>;
I don't get why can't we select MULrrrr_v here with `(MULrrr_v GR256:$rs0, GR256:$rs1, R0, 0)` what is the purpose of introducing new pseudo instructions?

2023-05-24 16:48 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +  ; Call the uadd.with.overflow intrinsic
Comments are redundant. They literally explain what is written in IR. Can we check generated asm instead?

2023-05-24 16:48 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +; CHECK: jump.lt
CHECK-NEXT?

2023-05-24 16:48 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +
Please check that selects on OF work as expected as well as branches.

2023-05-24 18:31 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.td
> +def : Pat<(SyncVMMul_v GR256:$rs0, GR256:$rs1), (MULrrr_v GR256:$rs0, GR256:$rs1, 0)>;
Instruction such as `MULrrrr_v` has two outputs. Here we are dealing with a single value node, so we will need a single valued node for that.

2023-05-24 18:36 UTC, lialan commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +  ; Call the uadd.with.overflow intrinsic
We could, but we are not doing anything with these tests. these tests are put here to make sure we are not crashing on those tests, while making optimizations on other test cases.

2023-05-24 19:03 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +    SDVTList VTs = DAG.getVTList(MVT::i256);
removed

2023-05-24 21:10 UTC, lialan commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +; CHECK: jump.lt
done

2023-05-24 21:11 UTC, lialan commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +
If you are referring to the last test (modulo_sub), it is not yet examined or optimized yet, it is just something Shamatar mentioned and we should look into it later.

2023-05-24 21:12 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.td
> +def : Pat<(SyncVMMul_v GR256:$rs0, GR256:$rs1), (MULrrr_v GR256:$rs0, GR256:$rs1, 0)>;
Actually, I was wrong. Those pseudo instructions are removed as of now.

2023-05-24 21:12 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +        DAG.ReplaceAllUsesOfValueWith(MatchedUArithO.getValue(0), FoldedArith.getValue(0));
done.

2023-05-24 21:15 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +      // %5 = call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 %4, i32 1),
removed.

2023-05-24 21:15 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +  bool rearrangeOverflowHandlingBranches(Function &F);
added some descriptions.

2023-05-24 21:15 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVM.h
> +  COND_OF,       /// An Overflow flag, cannot be reversed
added

2023-05-24 21:15 UTC, lialan commented on llvm/lib/Target/SyncVM/MCTargetDesc/SyncVMInstPrinter.cpp
> +  case SyncVMCC::COND_OF: // Overflow is same as LT
cleaned up.

2023-05-24 21:30 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +        FBB->moveAfter(BB);
Of course hardware ISA will have more uses than us because they have hot and cold parts. But for us, this particular transformation is related to utilize flag register in place of the second result of uaddo, instead of extracting it with some other code sequences. 

Such use looks quite unique to us.

2023-05-24 22:32 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.137 ║
║ Best                               26.415 ║
║ Worst                               0.000 ║
║ Total                               0.190 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.067 ║
║ Best                               33.974 ║
║ Worst                              -0.368 ║
║ Total                               0.022 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.666 ║
║ Best                                5.158 ║
║ Worst                               0.000 ║
║ Total                               0.773 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.726 ║
║ Best                               12.342 ║
║ Worst                               0.000 ║
║ Total                               0.321 ║
╚═══════════════════════════════════════════╝

```

2023-05-25 00:48 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +                  llvm::ConstantAsMetadata::get(
done.

2023-05-25 00:49 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMExpandPseudoInsts.cpp
> +    {SyncVM::MULrrr_v, SyncVM::MULrrrr_v},
So now I removed the pseudos completely.

2023-05-25 00:49 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +  auto MatchedUArithO = [&] {
done.

2023-05-25 00:52 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +      case ISD::UADDO:
yup, updated.

2023-05-25 00:52 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +      auto Call = dyn_cast<CallInst>(&I);
updated.

2023-05-25 01:13 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +  auto MatchedUArithO = [&] {
updated

2023-05-25 01:13 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +      auto Call = dyn_cast<CallInst>(&I);
yup, updated

2023-05-25 01:14 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +      case ISD::UADDO:
updated

2023-05-25 02:11 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +        DAG.ReplaceAllUsesOfValueWith(MatchedUArithO.getValue(0), FoldedArith.getValue(0));
done.

2023-05-25 05:24 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +        FBB->moveAfter(BB);
I meant if we use call results twice let's say and jump on them twice, is it profitable to do the transformation for both FBB and change probability for both TBB. Can we add a regression test?

2023-05-25 05:37 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +
Although branches are the way we are going to use uaddo etc most of the time, i1 output can also be used in select where same logic of non-reversibility and preference of OF over !OF applies. If it's easy to support (<= 0.5 days) I'd recommend to implement, otherwise please create a follow up ticket.

2023-05-25 06:30 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +  // We have a specific pattern to match in ISEL for custom lowering of
Too vague. What about
Since overflow flag is not reversible, it's beneficial for us to put a false successor after BB conditionally jumps on addition, subtraction or multiplication with overflow. In that case later we can directly use overflow flag of an operation in a conditional jump and fall through or jump unconditionally to the false successor.

2023-05-25 06:34 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +    case ISD::UADDO:
You've already checked that via `OpcodeMap.count(Op.getOpcode())`, `switch` is redundant.

2023-05-25 06:36 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +      auto LoweredOPC = OpcodeMap.find(OPC)->second;
just use `at` instead of assert + find.

2023-05-25 06:37 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +      ops.push_back(Chain);
brace initialisation is better here, or even inlace at the line below

2023-05-25 06:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +    case SyncVM::ADDrrr_v:
isFlagSetting && isAdd, isSub or isMul instead of switch. Or even isFlagSetting is enough.

2023-05-25 06:40 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.td
> +
redundant empty lines

2023-05-25 06:43 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +; CHECK-NEXT: jump.lt
Btw, `jump.of` will be much less confusing for a potential reader. Could we check if it's supported or ask @shamatar to make `of` be a synonym for `lt` in assembly?

2023-05-25 06:45 UTC, shamatar commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +; CHECK-NEXT: jump.lt
I think it’s possible to use both, it’s only a parser feature

2023-05-25 06:46 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +        FBB->moveAfter(BB);
Sorry, I'm an idiot. There might only be one terminator and uses are in different basic blocks.
I would say though, that for the comment it makes sense to add "to fall though FBB instead of unconditional jumping to it", though have you checked that the standard that reorders BB won't do the job for us based on non-reversibility?

2023-05-25 06:48 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +                      ISD::STACKSAVE, ISD::STACKRESTORE, ISD::TRAP, ISD::BRCOND},
Could you please make sure to run clang-format on your entire patch every time you submit it for a review?

2023-05-25 06:51 UTC, akiramenai requested changes
Much better now, thanks. Yet additional cleanup and clarification is of need.

2023-05-25 06:53 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +; CHECK-NEXT: jump.lt
Great, `jump.of` is preferable then. It expresses intent better.

2023-05-25 06:59 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +  // We have a specific pattern to match in ISEL for custom lowering of
Actually this is a wrong description, but I keep it to show the level of explicitness I think is beneficial for a reader. I still don't quite understand what is essential and what is auxiliary among what the function is doing.

2023-05-25 15:19 UTC, lialan commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +
created a ticket: https://linear.app/matterlabs/issue/CPR-1110/fold-arithmetic-overflow-with-select

2023-05-25 15:46 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +    case SyncVM::ADDrrr_v:
you are right. This is updated.

2023-05-25 15:46 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +      ops.push_back(Chain);
Yup, updated.

2023-05-25 15:46 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +      auto LoweredOPC = OpcodeMap.find(OPC)->second;
updated

2023-05-25 15:46 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +    case ISD::UADDO:
Indeed. This part is revamped.

2023-05-25 15:53 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +        FBB->moveAfter(BB);
I have updated the explanation on the code again, there I tried to summarize the scenario and explain why we need this.

2023-05-25 15:53 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.td
> +
removed.

2023-05-25 16:01 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +  // We have a specific pattern to match in ISEL for custom lowering of
Updated the comment again. Please check again.

2023-05-25 16:01 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +                      ISD::STACKSAVE, ISD::STACKRESTORE, ISD::TRAP, ISD::BRCOND},
Apologies, they are updated.

2023-05-25 18:46 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +  // We have a specific pattern to match in ISEL for custom lowering of
I updated the comment

2023-05-25 19:19 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.137 ║
║ Best                               26.415 ║
║ Worst                               0.000 ║
║ Total                               0.190 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.067 ║
║ Best                               33.974 ║
║ Worst                              -0.368 ║
║ Total                               0.022 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.666 ║
║ Best                                5.158 ║
║ Worst                               0.000 ║
║ Total                               0.773 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.726 ║
║ Best                               12.342 ║
║ Worst                               0.000 ║
║ Total                               0.321 ║
╚═══════════════════════════════════════════╝

```

2023-05-29 21:09 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.155 ║
║ Best                               26.415 ║
║ Worst                               0.000 ║
║ Total                               0.239 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.075 ║
║ Best                               33.974 ║
║ Worst                              -0.368 ║
║ Total                               0.025 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.891 ║
║ Best                                6.610 ║
║ Worst                               0.000 ║
║ Total                               1.075 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.774 ║
║ Best                               12.342 ║
║ Worst                               0.000 ║
║ Total                               0.346 ║
╚═══════════════════════════════════════════╝

```

2023-05-31 19:57 UTC, lialan commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +; CHECK-NEXT: jump.lt
@akiramenai so I added the emitting of `jump.of` in this patch, just need to wait for CI to pick up the change in assembly definition and run green.

2023-06-01 15:04 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.155 ║
║ Best                               26.415 ║
║ Worst                               0.000 ║
║ Total                               0.239 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.075 ║
║ Best                               33.974 ║
║ Worst                              -0.368 ║
║ Total                               0.025 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.891 ║
║ Best                                6.610 ║
║ Worst                               0.000 ║
║ Total                               1.075 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.774 ║
║ Best                               12.342 ║
║ Worst                               0.000 ║
║ Total                               0.346 ║
╚═══════════════════════════════════════════╝

```

2023-06-03 12:16 UTC, akiramenai requested changes
It looks like `rearrangeOverflowHandlingBranches` can be improved. Also some patterns in td seems to be missing (or oppositely redundant).

2023-06-03 12:16 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +          if (Branch) {
Style: Early exit is preferred in LLVM coding style guide. E.g. `if (!Branch || !Branch->isConditional()) continue;`. And filtering iterator is even better than early exit as it expresses the intent more lucidly.
I also confused a bit now as I counted brackets (that's why early exit is preferred), it seems that if there are more then one branch predicated on the same extract value, we only transform the last one. Is it intended?
Please also add a test for whatever behaviour is expected.

2023-06-03 12:16 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +    SDValue FoldedArith;
Style: better to define and initialize with `DAG.getNode` below.

2023-06-03 12:16 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +  if (SDValue MatchedUArithO = matchingOverflowArithmeticOperation(Cond)) {
Nit: early exit is preferred.

2023-06-03 12:16 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +  if (SyncVMInstrInfo::isFlagSettingInstruction(MI.getOpcode())) {
Style: redundant brackets.

2023-06-03 12:16 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.td
> +def : Pat<(SyncVMAdd_v (load_code memaddr:$rs0), GR256:$rs1),
Can we use commutativity somehow? Otherwise other patterns (x, z) should also be described.

2023-06-03 12:16 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.td
> +def : Pat<(SyncVMSub_v GR256:$rs0, GR256:$rs1), (SUBrrr_v GR256:$rs0, GR256:$rs1, 0)>;
r, i, x, c, y, s, z * 2 there must be 14 patterns in total. Here is 12. Also please order patterns across all operations in some consistent way.

2023-06-03 12:16 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +target datalayout = "E-p:256:256-i8:256:256:256-i256:256:256-S32-a:256:256"
If some patterns missed above produce suboptimal code, please add tests here.

2023-06-03 21:12 UTC, lialan commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +target datalayout = "E-p:256:256-i8:256:256:256-i256:256:256-S32-a:256:256"
added more tests.

2023-06-03 21:28 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.td
> +def : Pat<(SyncVMAdd_v (load_code memaddr:$rs0), GR256:$rs1),
I added missing patterns. 

AFAIK commutativity for custom SDnode is not expressible in Tablegen yet (verified with ChatGPT, and also checked other backend's node), so basically we have to explicitly check both lhs/rhs.

2023-06-03 21:28 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.td
> +def : Pat<(SyncVMSub_v GR256:$rs0, GR256:$rs1), (SUBrrr_v GR256:$rs0, GR256:$rs1, 0)>;
Added missing patterns, and rearranged them in a more consistent way.

2023-06-03 21:29 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +  if (SyncVMInstrInfo::isFlagSettingInstruction(MI.getOpcode())) {
removed

2023-06-03 21:30 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +  if (SDValue MatchedUArithO = matchingOverflowArithmeticOperation(Cond)) {
updated

2023-06-03 21:34 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +    SDValue FoldedArith;
updated

2023-06-03 22:40 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.159 ║
║ Best                               26.415 ║
║ Worst                               0.000 ║
║ Total                               0.245 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.082 ║
║ Best                               33.974 ║
║ Worst                              -0.368 ║
║ Total                               0.023 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.886 ║
║ Best                                6.610 ║
║ Worst                               0.000 ║
║ Total                               1.116 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.796 ║
║ Best                               12.342 ║
║ Worst                               0.000 ║
║ Total                               0.363 ║
╚═══════════════════════════════════════════╝

```

2023-06-04 02:26 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +          if (Branch) {
Updated the code to use early exit and iterator + lambda to get a cleaner structure. The original code indeed contains a lot of `continue`s which is a bit hard to follow.

I've also updated the code about handling `Branch`, and restrict the criteria to only modifying the branching instruction that co-exist with the overflow intrinsic in the same BB, because if they are not in the same BB, we are not folding them anyway. So the selecting logic can only return at most 1 candidate branch.

2023-06-04 03:39 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.159 ║
║ Best                               26.415 ║
║ Worst                               0.000 ║
║ Total                               0.245 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.082 ║
║ Best                               33.974 ║
║ Worst                              -0.368 ║
║ Total                               0.023 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.886 ║
║ Best                                6.610 ║
║ Worst                               0.000 ║
║ Total                               1.116 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.796 ║
║ Best                               12.342 ║
║ Worst                               0.000 ║
║ Total                               0.363 ║
╚═══════════════════════════════════════════╝

```

2023-06-05 09:52 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +        // same basicblock:
You don't check that use is in the same BB, do you?

2023-06-05 09:53 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +                TBB = Branch->getSuccessor(0);
Better is no not to do side effect while searching. Moving it away also allow you to not to initialise FBB, TBB with nullptr.

2023-06-05 13:19 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +        // same basicblock:
Huh, I think I messed the code up when doing local rebasing. code I have pushed the update.

2023-06-05 13:21 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +                TBB = Branch->getSuccessor(0);
Good suggestion for fewer lines of code. Updated.

2023-06-06 02:53 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.159 ║
║ Best                               26.415 ║
║ Worst                               0.000 ║
║ Total                               0.245 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.081 ║
║ Best                               33.974 ║
║ Worst                              -0.368 ║
║ Total                               0.023 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.886 ║
║ Best                                6.610 ║
║ Worst                               0.000 ║
║ Total                               1.116 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.796 ║
║ Best                               12.342 ║
║ Worst                               0.000 ║
║ Total                               0.363 ║
╚═══════════════════════════════════════════╝

```

2023-06-06 13:42 UTC, akiramenai approved these changes
LGTM, please squash.

2023-06-06 13:42 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCodegenPrepare.cpp
> +        if (it == ExtractValue->user_end()) {
Style: redundant braces

2023-06-06 14:51 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.159 ║
║ Best                               26.415 ║
║ Worst                               0.000 ║
║ Total                               0.245 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.081 ║
║ Best                               33.974 ║
║ Worst                              -0.368 ║
║ Total                               0.023 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.886 ║
║ Best                                6.610 ║
║ Worst                               0.000 ║
║ Total                               1.116 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.796 ║
║ Best                               12.342 ║
║ Worst                               0.000 ║
║ Total                               0.363 ║
╚═══════════════════════════════════════════╝

```

2023-06-06 18:01 UTC, merged