Move LLVM git version tracking to lib/Support
matter-labs/era-compiler-llvm pull request #226
Opened 2023-04-19 13:45 UTC by akiramenai

2023-04-19 13:52 UTC, akiramenai commented on llvm/lib/Support/CMakeLists.txt
> +# SyncVM local begin
@hedgar2017 we might additionally guard this one with a CMake option, so LLVM version is only calculated if it specified. It'd additionally allow to slightly boost compilation time for development process where tracking the version is not needed. In CI build / build scripts the option will be enabled (by default at least). What do you think?

2023-04-19 13:52 UTC, akiramenai commented
Number of targets to build for just a version change reduced to 311 on my machine.

2023-04-19 14:19 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-04-19 14:23 UTC, lialan approved these changes
@hedgar2017 It is up to you to decide if a guard described by Dmitry is necessary, but overall  the current change LGTM.

2023-04-19 14:58 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-04-19 15:04 UTC, hedgar2017 commented on llvm/lib/Support/CMakeLists.txt
> +# SyncVM local begin
Is it 100% that we cannot keep both incremental compilation as before and version ID in all cases?

We need this option in both release and development process. Initially we added the commit ID to see what commit the compiler-tester was build with, so the versionless build may be only useful for LLVM devs internally.

2023-04-19 15:05 UTC, hedgar2017 requested changes
https://github.com/matter-labs/compiler-llvm/pull/226/files#r1171482155

2023-04-19 15:10 UTC, hedgar2017 commented on llvm/lib/Support/CMakeLists.txt
> +# SyncVM local begin
I'll get a MacBook Pro Max with 100 cores soon and I probably won't care compiling 300 TUs every time. Some users will though.

I'm more concerned about us nuked the incremental compilation for the sake of having a mere version identifier and now we need a CMAKE flag just to toggle it.

But 300 TUs is not 2100 and it's acceptable I think. Just curious if there is a better way.

2023-04-19 20:44 UTC, hedgar2017 commented on llvm/lib/Support/CMakeLists.txt
> +# SyncVM local begin
If it's impossible to do another way, let's add a CMAKE flag.

2023-04-23 20:02 UTC, akiramenai commented on llvm/lib/Support/CMakeLists.txt
> +# SyncVM local begin
Did it more precise. ~160 targets now. Still everything needs to be relinked, but it can't be helped. I think not to guard it, now the effect on incremental build is not that important.

2023-04-23 21:37 UTC, hedgar2017 approved these changes
Awesome! Let's merge.

2023-04-24 09:51 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-04-24 11:43 UTC, merged