Combine a reload with its uses
matter-labs/era-compiler-llvm pull request #227
Opened 2023-04-26 12:25 UTC by akiramenai

Introduce a pass that combines add src, r0, rN with rN uses where it's
possible. The transformation is done in post-RA pipeline.

2023-04-26 21:32 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.001 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.000 ║
║ Best                               29.070 ║
║ Worst                              -3.333 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-04-28 09:26 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.001 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.000 ║
║ Best                               29.070 ║
║ Worst                              -3.333 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-05-17 12:44 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.036 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.091 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.037 ║
║ Best                               29.070 ║
║ Worst                              -3.333 ║
║ Total                               0.017 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.278 ║
║ Best                                2.647 ║
║ Worst                               0.000 ║
║ Total                               0.416 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.088 ║
║ Best                                1.026 ║
║ Worst                               0.000 ║
║ Total                               0.214 ║
╚═══════════════════════════════════════════╝

```

2023-05-18 14:36 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.029 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.080 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.036 ║
║ Best                               29.070 ║
║ Worst                              -3.333 ║
║ Total                               0.017 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.275 ║
║ Best                                2.647 ║
║ Worst                               0.000 ║
║ Total                               0.407 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.087 ║
║ Best                                0.789 ║
║ Worst                               0.000 ║
║ Total                               0.218 ║
╚═══════════════════════════════════════════╝

```

2023-05-19 01:46 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.051 ║
║ Best                                6.833 ║
║ Worst                               0.000 ║
║ Total                               0.139 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.047 ║
║ Best                               29.070 ║
║ Worst                              -3.333 ║
║ Total                               0.024 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.460 ║
║ Best                                6.833 ║
║ Worst                               0.000 ║
║ Total                               0.699 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.236 ║
║ Best                                4.111 ║
║ Worst                               0.000 ║
║ Total                               0.645 ║
╚═══════════════════════════════════════════╝

```

2023-05-19 16:20 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.051 ║
║ Best                                6.833 ║
║ Worst                               0.000 ║
║ Total                               0.139 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.047 ║
║ Best                               29.070 ║
║ Worst                              -3.333 ║
║ Total                               0.024 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.460 ║
║ Best                                6.833 ║
║ Worst                               0.000 ║
║ Total                               0.699 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.236 ║
║ Best                                4.111 ║
║ Worst                               0.000 ║
║ Total                               0.645 ║
╚═══════════════════════════════════════════╝

```

2023-05-19 21:04 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.065 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.181 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.079 ║
║ Best                               29.070 ║
║ Worst                              -3.333 ║
║ Total                               0.041 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.647 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.922 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.311 ║
║ Best                                4.243 ║
║ Worst                               0.000 ║
║ Total                               0.782 ║
╚═══════════════════════════════════════════╝

```

2023-05-20 21:03 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.065 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.181 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.079 ║
║ Best                               29.070 ║
║ Worst                              -3.333 ║
║ Total                               0.041 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.647 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.922 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.311 ║
║ Best                                4.243 ║
║ Worst                               0.000 ║
║ Total                               0.782 ║
╚═══════════════════════════════════════════╝

```

2023-05-21 16:00 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.066 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.181 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.114 ║
║ Best                               29.070 ║
║ Worst                              -3.333 ║
║ Total                               0.049 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.647 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.923 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.328 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.789 ║
╚═══════════════════════════════════════════╝

```

2023-05-23 11:17 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.067 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.182 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.114 ║
║ Best                               29.070 ║
║ Worst                              -3.333 ║
║ Total                               0.049 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.650 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.927 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.329 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.789 ║
╚═══════════════════════════════════════════╝

```

2023-05-26 16:58 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.068 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.191 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.136 ║
║ Best                               29.070 ║
║ Worst                              -3.333 ║
║ Total                               0.059 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.736 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               1.026 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.383 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.829 ║
╚═══════════════════════════════════════════╝

```

2023-05-29 21:14 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.066 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.178 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.134 ║
║ Best                               13.290 ║
║ Worst                              -3.333 ║
║ Total                               0.062 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.654 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.905 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.330 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.805 ║
╚═══════════════════════════════════════════╝

```

2023-05-30 12:34 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.066 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.178 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               29.070 ║
║ Worst                              -3.333 ║
║ Total                               0.062 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.654 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.905 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.330 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.805 ║
╚═══════════════════════════════════════════╝

```

2023-05-30 13:33 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.066 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.178 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.134 ║
║ Best                               13.290 ║
║ Worst                              -3.333 ║
║ Total                               0.062 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.654 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.905 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.330 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.805 ║
╚═══════════════════════════════════════════╝

```

2023-05-30 21:38 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.066 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.178 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.134 ║
║ Best                               13.290 ║
║ Worst                              -3.333 ║
║ Total                               0.062 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.654 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.905 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.330 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.805 ║
╚═══════════════════════════════════════════╝

```

2023-06-01 07:27 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.066 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.178 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.134 ║
║ Best                               13.290 ║
║ Worst                              -3.333 ║
║ Total                               0.062 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.654 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.905 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.330 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.805 ║
╚═══════════════════════════════════════════╝

```

2023-06-01 18:35 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.066 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.178 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.134 ║
║ Best                               13.290 ║
║ Worst                              -3.333 ║
║ Total                               0.062 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.654 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.905 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.330 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.805 ║
╚═══════════════════════════════════════════╝

```

2023-06-05 11:10 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                6.997 ║
║ Worst                               0.000 ║
║ Total                               0.192 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.134 ║
║ Best                               14.380 ║
║ Worst                              -3.333 ║
║ Total                               0.058 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.750 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               1.077 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.370 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.795 ║
╚═══════════════════════════════════════════╝

```

2023-06-07 21:39 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.064 ║
║ Best                                6.997 ║
║ Worst                               0.000 ║
║ Total                               0.192 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.134 ║
║ Best                               14.380 ║
║ Worst                              -3.333 ║
║ Total                               0.058 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.754 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               1.082 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.373 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.798 ║
╚═══════════════════════════════════════════╝

```

2023-06-07 21:54 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCombineReloadUse.cpp
> +bool SyncVMCombineReloadUse::isReloadInst(MachineInstr &MI) const {
We can use `MI->getFoldedSpillSize` and `MI->getFoldedRestoreSize` to identify load and spill instructions.

2023-06-07 22:03 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCombineReloadUse.cpp
> +/// Combine reload and reload-like instructions with their usages.
Spills and reloads are very alike, they are just MOV instructions. And I assume you will deal with spills after implementing reloads in a same pass framework.

So maybe come up with a better name for the pass?

2023-06-07 22:16 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineReloadUse.cpp
> +/// Combine reload and reload-like instructions with their usages.
Probably. Maybe I would need to recompute RDA though to be able to do it in a single pass. So let me postpone it until closer to the decision.

2023-06-07 22:20 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineReloadUse.cpp
> +bool SyncVMCombineReloadUse::isReloadInst(MachineInstr &MI) const {
Well, I prefer it to work with a reload-like instruction instead of pure reloads. Things like loading from a global counts as well. Perhaps we'll clean up some `.td` patterns later on if we can rely on this pass to do the job. There are too much duplications there...

2023-06-07 22:25 UTC, akiramenai commented
Extracted instruction mapping part into https://github.com/matter-labs/compiler-llvm/pull/242

2023-06-07 22:26 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrFormats.td
>    bits<3> OperandAddrMode = OpndAddrNotSet.Value;
now `OperandAddrMode` is redundant with `OperandAM`, so we can safely remove it.

2023-06-15 14:00 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                6.997 ║
║ Worst                               0.000 ║
║ Total                               0.192 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               14.380 ║
║ Worst                              -0.147 ║
║ Total                               0.058 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.754 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               1.082 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.373 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.798 ║
╚═══════════════════════════════════════════╝

```

2023-06-16 06:39 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                6.997 ║
║ Worst                               0.000 ║
║ Total                               0.192 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               14.380 ║
║ Worst                              -0.147 ║
║ Total                               0.058 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.754 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               1.082 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.373 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.798 ║
╚═══════════════════════════════════════════╝

```

2023-06-16 13:20 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                6.997 ║
║ Worst                               0.000 ║
║ Total                               0.192 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               14.380 ║
║ Worst                              -0.147 ║
║ Total                               0.058 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.754 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               1.082 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.373 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.798 ║
╚═══════════════════════════════════════════╝

```

2023-06-16 15:46 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                6.997 ║
║ Worst                               0.000 ║
║ Total                               0.192 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               14.380 ║
║ Worst                              -0.147 ║
║ Total                               0.058 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.754 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               1.082 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.373 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.798 ║
╚═══════════════════════════════════════════╝

```

2023-06-21 17:24 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                6.997 ║
║ Worst                               0.000 ║
║ Total                               0.192 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               14.380 ║
║ Worst                              -0.147 ║
║ Total                               0.059 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.754 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               1.082 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.373 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.798 ║
╚═══════════════════════════════════════════╝

```

2023-06-22 21:10 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                6.997 ║
║ Worst                               0.000 ║
║ Total                               0.192 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               14.380 ║
║ Worst                              -0.147 ║
║ Total                               0.059 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.754 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               1.082 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.373 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.798 ║
╚═══════════════════════════════════════════╝

```

2023-06-23 14:59 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                6.997 ║
║ Worst                               0.000 ║
║ Total                               0.192 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               14.380 ║
║ Worst                              -0.147 ║
║ Total                               0.059 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.754 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               1.082 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.373 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.798 ║
╚═══════════════════════════════════════════╝

```

2023-06-23 23:06 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                6.997 ║
║ Worst                               0.000 ║
║ Total                               0.192 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               14.380 ║
║ Worst                              -0.147 ║
║ Total                               0.059 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.754 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               1.082 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.373 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.798 ║
╚═══════════════════════════════════════════╝

```

2023-06-24 03:46 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                6.997 ║
║ Worst                               0.000 ║
║ Total                               0.192 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               14.380 ║
║ Worst                               0.000 ║
║ Total                               0.059 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.026 ║
║ Best                                8.463 ║
║ Worst                              -0.006 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.754 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               1.082 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.373 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.798 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.018 ║
║ Best                                0.965 ║
║ Worst                               0.000 ║
║ Total                               0.028 ║
╚═══════════════════════════════════════════╝

```

2023-06-26 13:48 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                6.997 ║
║ Worst                               0.000 ║
║ Total                               0.192 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               14.380 ║
║ Worst                               0.000 ║
║ Total                               0.059 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.026 ║
║ Best                                8.463 ║
║ Worst                              -0.006 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.754 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               1.082 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.373 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.798 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.018 ║
║ Best                                0.965 ║
║ Worst                               0.000 ║
║ Total                               0.028 ║
╚═══════════════════════════════════════════╝

```

2023-07-01 08:07 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                7.732 ║
║ Worst                               0.000 ║
║ Total                               0.191 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               14.380 ║
║ Worst                               0.000 ║
║ Total                               0.058 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.026 ║
║ Best                                8.463 ║
║ Worst                              -0.006 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.745 ║
║ Best                                7.732 ║
║ Worst                               0.000 ║
║ Total                               1.176 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.318 ║
║ Best                                2.157 ║
║ Worst                               0.000 ║
║ Total                               0.887 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.014 ║
║ Best                                0.933 ║
║ Worst                               0.000 ║
║ Total                               0.026 ║
╚═══════════════════════════════════════════╝

```

2023-07-02 11:09 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                7.732 ║
║ Worst                               0.000 ║
║ Total                               0.191 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               14.380 ║
║ Worst                               0.000 ║
║ Total                               0.058 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.026 ║
║ Best                                8.463 ║
║ Worst                              -0.006 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.745 ║
║ Best                                7.732 ║
║ Worst                               0.000 ║
║ Total                               1.176 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.318 ║
║ Best                                2.157 ║
║ Worst                               0.000 ║
║ Total                               0.887 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.014 ║
║ Best                                0.933 ║
║ Worst                               0.000 ║
║ Total                               0.026 ║
╚═══════════════════════════════════════════╝

```

2023-07-04 13:52 UTC, vladimirradosavljevic approved these changes
LGTM, just few nits and questions.

2023-07-04 13:52 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineReloadUse.cpp
> +  std::vector<std::tuple<MachineInstr *, SmallPtrSet<MachineInstr *, 4>>>
Use std::pair instead of std::tuple?

2023-07-04 13:52 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineReloadUse.cpp
> +                if (ReachingDefs.size() != 1)
Should we be paranoid and check that only `ReachingDef` is actually `MI`?

2023-07-04 13:52 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineReloadUse.cpp
> +                if (TII->getCCCode(**ReachingDefs.begin()) !=
Is this needed, since we check this in `isReloadInst`, or this is left for future optimizations in case we want to allow more ReachingDefs?

2023-07-04 13:52 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +#include <unordered_map>
This is not needed.

2023-07-04 13:52 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineReloadUse.cpp
> +                if (std::any_of(std::next(MI.getIterator()), Use->getIterator(),
Will this cover case where we will go through all instructions between Reload and Use if Reload is in 0, and use is in 3?
```
    0
  /   \
 1     2
  \   /
    3
```

2023-07-05 03:38 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineReloadUse.cpp
> +                if (std::any_of(std::next(MI.getIterator()), Use->getIterator(),
No, but we already restricted reload and use to be in the same bb, which is often the case. You example needs additional work to check instruction properties across the CFG. I will create a ticket for that.

2023-07-05 03:59 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineReloadUse.cpp
> +                if (TII->getCCCode(**ReachingDefs.begin()) !=
This check is that def is unconditional, not a reload.

2023-07-05 09:32 UTC, vladimirradosavljevic requested changes
Since `hasSRInAddressingMode` is not returning true for `zrr_s` variants, we should fix it before this PR lands.

Regarding RDA, just want to make sure I didn't miss something. In order to safely combine a reload with its uses, we are doing following:
1. Find a reload instruction and take Def register.
2. Call `getGlobalUses` with reload and def register to get users.
3. For each user, make sure `getGlobalReachingDefs` is returning exactly 1 instruction, and it should be reload as we are traversing over users of reload instruction.

When you added assert for 3. point, it started failing. Is this because I missed something for 3. point, or perhaps I misunderstood RDA API?

2023-07-05 09:35 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineReloadUse.cpp
> +                if (std::any_of(std::next(MI.getIterator()), Use->getIterator(),
Got it, thanks!

2023-07-05 14:26 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.002 ║
║ Best                                3.460 ║
║ Worst                               0.000 ║
║ Total                               0.010 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.001 ║
║ Best                                5.499 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                3.110 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.007 ║
║ Best                                0.343 ║
║ Worst                               0.000 ║
║ Total                               0.009 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.001 ║
║ Best                                0.239 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.015 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-07-05 23:23 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.002 ║
║ Best                                3.460 ║
║ Worst                               0.000 ║
║ Total                               0.010 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.001 ║
║ Best                                5.499 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                3.110 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.007 ║
║ Best                                0.343 ║
║ Worst                               0.000 ║
║ Total                               0.009 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.001 ║
║ Best                                0.239 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.015 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-07-06 04:47 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                7.732 ║
║ Worst                               0.000 ║
║ Total                               0.191 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               14.380 ║
║ Worst                               0.000 ║
║ Total                               0.058 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.026 ║
║ Best                                8.463 ║
║ Worst                              -0.006 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.745 ║
║ Best                                7.732 ║
║ Worst                               0.000 ║
║ Total                               1.176 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.318 ║
║ Best                                2.157 ║
║ Worst                               0.000 ║
║ Total                               0.887 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.014 ║
║ Best                                0.933 ║
║ Worst                               0.000 ║
║ Total                               0.026 ║
╚═══════════════════════════════════════════╝

```

2023-07-06 10:02 UTC, vladimirradosavljevic approved these changes
LGTM, without debugging artifacts.

2023-07-06 10:02 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineReloadUse.cpp
> +                if (TII->getCCCode(**ReachingDefs.begin()) !=
Since, ReachingDef is MI, and MI is reload instruction, I think this is safe to remove.

2023-07-06 11:10 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                7.732 ║
║ Worst                               0.000 ║
║ Total                               0.191 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               14.380 ║
║ Worst                               0.000 ║
║ Total                               0.058 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.026 ║
║ Best                                8.463 ║
║ Worst                              -0.006 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.745 ║
║ Best                                7.732 ║
║ Worst                               0.000 ║
║ Total                               1.176 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.318 ║
║ Best                                2.157 ║
║ Worst                               0.000 ║
║ Total                               0.887 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.014 ║
║ Best                                0.933 ║
║ Worst                               0.000 ║
║ Total                               0.026 ║
╚═══════════════════════════════════════════╝

```

2023-07-06 20:13 UTC, merged