[EVM] Adding integer instructions.
matter-labs/era-compiler-llvm pull request #233
Opened 2023-05-23 22:47 UTC by PavelKopyl

Adding integer instructions.
- Arithmetic
- Logical
- Bitwise
- Shift
- Comparison

TODO: Handle following corner cases of EVM architecture
     - (a / 0)
     - (a % 0)

2023-05-24 00:05 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-05-24 14:53 UTC, lialan commented
seeing this in the CI test results:
`error: unable to get target for 'evm', see --version and --triple.`
Better fix it?

2023-05-24 16:17 UTC, PavelKopyl commented
Yep. It seems we need to fix the CI a bit, otherwise reviewers should trust me, or build and perform ninja check-llvm by themselves...)

2023-06-01 07:44 UTC, akiramenai requested changes
Logic around materialising of big constants seems detrimental because `PUSH32` could materialize i256 if I get it right.

2023-06-01 07:44 UTC, akiramenai commented on llvm/test/CodeGen/EVM/intrinsic.ll
> +  %res = call i256 @llvm.evm.addmod(i256 %rs1, i256 %rs2, i256 %rs3)
We should probably create a ticket to optimise `(rem (add nuw x, y), z)` to `addmod`, same for `mulmod`.

2023-06-01 07:44 UTC, akiramenai commented on llvm/test/CodeGen/EVM/mul.ll
> +; CHECK: SUB [[REG3:\$[0-9]+]], [[REG2]], [[REG1]]
It looks like CONST can hold imm256, can't we materialize `-500000` directly?

2023-06-01 07:44 UTC, akiramenai commented on llvm/test/CodeGen/EVM/sext.ll
> +}
What would happen for more exotic types? Are they accessible from Solidity?
P.S. If to handle these types properly we need to add some non-trivial logic to LLVM legalizer, it's better to create follow-up ticket and postpone.

2023-06-01 07:44 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMAsmPrinter.cpp
> +  EVMMCInstLower MCInstLowering(OutContext, VRegMapping, MF->getRegInfo());
Could you explain why is it of need? It doesn't seem to be connected with the rest of the patch.

2023-06-01 07:44 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMInstrInfo.td
> +def : Pat<(neg_imm128:$imm),
EVM has `PUSH32` instruction, doesn't it. So these complex materialisation doesn't look good.

2023-06-01 10:44 UTC, PavelKopyl commented
> Logic around materialising of big constants seems detrimental because `PUSH32` could materialize i256 if I get it right.

Thank you for reviewing this!
Could you, please clarify a bit what is exactly you mean? The way integers are materialized via CONST_I256 instruction? Anyway, CONST_I256 will be converted to the appropriate PUSH instruction while stackification, depending on the actually size of the immediate.

2023-06-01 10:44 UTC, PavelKopyl commented on llvm/test/CodeGen/EVM/intrinsic.ll
> +  %res = call i256 @llvm.evm.addmod(i256 %rs1, i256 %rs2, i256 %rs3)
OK, I'll create the ticket, or add patterns for this.

2023-06-01 11:12 UTC, PavelKopyl commented on llvm/test/CodeGen/EVM/mul.ll
> +; CHECK: SUB [[REG3:\$[0-9]+]], [[REG2]], [[REG1]]
Indeed, I'd like to discuss materialization of negative immediates.

Yes, CONST_I256 can hold -500000, but that would require all the 32 bytes to encode it and most of them will be non-zero bytes.  As I understand (after reading EVM documentation and other articles), all these 32 bytes need will be a part of the code for which we need to pay "Wei". On the other hand, the following transformation should be beneficial at the point of "Wei":
 
 ```
CONST_I256 (-500000) // to be transformed to: PUSH32 (1 byte) + 32 bytes of the immediate 
  - > 
 CONST_i256 0 // to be transformed to: PUSH0(1 byte)
 CONST_i256 500000 // to be transformed to: PUSH3 (1 byte) + 3 bytes of the immediate
 SUB // to be transformed to: SUB (1 byte)
```
 
 Also there is a difference in Wei price for zero byte and non-zero.
 There are some calculations about this here: https://medium.com/@hayeah/how-to-decipher-a-smart-contract-method-call-8ee980311603 (though it's not official documentation)
 
 I'm not 100% sure in that at the moment, so we could drop this complication and come back to this question later.

2023-06-01 11:18 UTC, PavelKopyl commented on llvm/test/CodeGen/EVM/sext.ll
> +}
I guess this should work with all the integer types from i8 to i256. The only exotic type I have in mind - is i160 that corresponds to the 'address' of the contract (if I understand it right). But that depends on our Solidity FE, will it generate i160 of expand it to i256?

2023-06-01 11:20 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMInstrInfo.td
> +def : Pat<(neg_imm128:$imm),
Please, check above my explanation of the negative integers materialization. This is the same topic.

2023-06-01 11:27 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMAsmPrinter.cpp
> +  EVMMCInstLower MCInstLowering(OutContext, VRegMapping, MF->getRegInfo());
I added `MCContext &Ctx` field to VMMCInstLower class to be able to print big (> 64bits) immediates:

```
       auto Str = new (Ctx) SmallString<80>();
        CImmVal.toStringUnsigned(*Str);
        MCOp = MCOperand::createExpr(EVMCImmMCExpr::create(*Str, Ctx));
```

So, I'm just passing it to the  EVMMCInstLower ctor.

2023-06-01 15:21 UTC, hedgar2017 commented on llvm/test/CodeGen/EVM/sext.ll
> +}
For now there is no way to pass type information from Solidity, so all cells are i256 by default.

2023-06-02 10:34 UTC, akiramenai commented on llvm/test/CodeGen/EVM/mul.ll
> +; CHECK: SUB [[REG3:\$[0-9]+]], [[REG2]], [[REG1]]
Ok, LGTM then

2023-06-02 10:37 UTC, akiramenai commented on llvm/test/CodeGen/EVM/sext.ll
> +}
Can't we just write a single test rather than guess and check for codegen? Use any iN with N divisible to 8 but not power of 2. If codegen is ok, add CHECK if it's not ticket + todo to not to forget when/if we start to care.

2023-06-02 10:37 UTC, akiramenai approved these changes
LGTM but a single test case to be added.

2023-06-02 17:41 UTC, PavelKopyl commented on llvm/test/CodeGen/EVM/sext.ll
> +}
My initial intention was to check generation of this instruction for each integer **machine** type available on ISelDAG (MVT:: i8, i16, i32, i64, i128, /*i256, i5128/).  The thing is that the pattern for generation SIGNEXTEND will not work for other types. The following code

`%res = sext i40 %rs1 to i256`

get `expanded` into

```
	SHL $3, %rs1, 216
	SAR $4, $3, 216
```

because i40 is extended EVT (EVT.isExtended() == true). It is hardcoded in getOperationAction() to exactly expand such nodes. Please, note the generated code is valid, but is not optimal. 

The only way to enable generation of SIGNEXTEND with such extended types it to add them to Machine types, the same way as you did it for i256. For me this seems a bit overkill, as FE shouldn't generate these exotic types.
Anyway we can add these types to MVT Ince required.

I can add one more test to this file demonstrating 'sexp' also gets lowered for exotic types, but non-optimally. 
Is it OK?

2023-06-06 19:23 UTC, merged