Replace imm 0 with r0 for sub!, select
matter-labs/era-compiler-llvm pull request #235
Opened 2023-05-26 20:30 UTC by akiramenai

It makes sub! combinable with reload of its argument and allows to fold (op (select.cc x, y), z) into (op y, z) + (op.cc x, z). The patch only makes preliminary work and doesn't perform transformations themselves.

2023-05-26 20:33 UTC, akiramenai commented
Related issue: https://linear.app/matterlabs/issue/CPR-1129/fold-op-selectcc-x-y-z-into-op-y-z-opcc-x-z

2023-05-26 20:36 UTC, akiramenai commented
Part of #227 work which improved results from
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.067 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.182 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.114 ║
║ Best                               29.070 ║
║ Worst                              -3.333 ║
║ Total                               0.049 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.650 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.927 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.329 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.789 ║
╚═══════════════════════════════════════════╝
```
to
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.068 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               0.191 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.136 ║
║ Best                               29.070 ║
║ Worst                              -3.333 ║
║ Total                               0.059 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.736 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               1.026 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.383 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.829 ║
╚═══════════════════════════════════════════╝
```

2023-05-26 21:20 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-05-27 12:18 UTC, lialan requested changes
LGTM generally, but we could do a little bit better. Let me know if you think this is not necessary.

2023-05-27 12:18 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.td
> +// r0 is profitable than imm 0 because makes sub! x, r0 combinable with x = load y.
nit: more profitable than ... because it makes..

2023-05-27 12:18 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCombineFlagSetting.cpp
> -  if (MI.getOpcode() == SyncVM::SUBxrr_v && MI.getOperand(2).isReg() &&
If I understand it correctly, we emit `sub! x, r0` for a `select` node. But we could fold both `sub! x, r0` and `sub.s! 0, x` here, because we could emit latter patern when we are really testing if a variable is really 0.

or ... we just convert `sub.s! 0, x` into `sub! x, r0` somewhere before it because latter is potentially more profitable.

2023-05-28 08:25 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineFlagSetting.cpp
> -  if (MI.getOpcode() == SyncVM::SUBxrr_v && MI.getOperand(2).isReg() &&
The patch makes DAG to emit comparison with 0 as `sub! x, r0`, so what do you mean by "we could emit latter patern when we are really testing if a variable is really 0"?

2023-05-28 13:55 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.td
> +// r0 is profitable than imm 0 because makes sub! x, r0 combinable with x = load y.
Fixed

2023-05-28 14:34 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-05-29 03:07 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCombineFlagSetting.cpp
> -  if (MI.getOpcode() == SyncVM::SUBxrr_v && MI.getOperand(2).isReg() &&
Oh, what I meant was: we still might emit `sub.s! 0, x` for `SyncVMcmp`, so we might want to do either one of the followings:
1. also tries to fold `sub.s! 0, x` in `SyncVMCombineFlagSetting` pass, or
2. convert `sub.s! 0, x` to `sub! x, r0` before `SyncVMCombineFlagSetting`

2023-05-29 05:26 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineFlagSetting.cpp
> -  if (MI.getOpcode() == SyncVM::SUBxrr_v && MI.getOperand(2).isReg() &&
How might we? The pattern with 0 we introduce in very this patch has priority over the pattern with imm other than 0. Cmp only live in DAG Isel. Benchmarks shown we regressed nothing, so I still don't understand why to maintain code I removed.

2023-05-29 13:14 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMCombineFlagSetting.cpp
> -  if (MI.getOpcode() == SyncVM::SUBxrr_v && MI.getOperand(2).isReg() &&
I missed the particular line's effect. Indeed we are not using imm 0 any more.

2023-05-29 15:03 UTC, merged