Folding overflowing intrinsics with select
matter-labs/era-compiler-llvm pull request #239
Opened 2023-05-31 01:52 UTC by lialan

2023-05-31 01:53 UTC, lialan commented
okay ... I have to change base branch to `dev-15` to trigger CI. But it is not supposed to be merged directly. It should be merged to #225

2023-07-31 01:46 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.004 ║
║ Best                                6.452 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                               11.111 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.001 ║
║ Best                                7.477 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.024 ║
║ Best                                0.964 ║
║ Worst                               0.000 ║
║ Total                               0.034 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.038 ║
║ Best                                1.152 ║
║ Worst                               0.000 ║
║ Total                               0.134 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.002 ║
║ Best                                0.141 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╚═══════════════════════════════════════════╝

```

2023-07-31 13:17 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.004 ║
║ Best                                6.452 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                               11.111 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.001 ║
║ Best                                7.477 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.024 ║
║ Best                                0.964 ║
║ Worst                               0.000 ║
║ Total                               0.034 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.038 ║
║ Best                                1.152 ║
║ Worst                               0.000 ║
║ Total                               0.134 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.002 ║
║ Best                                0.141 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╚═══════════════════════════════════════════╝

```

2023-07-31 15:33 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.004 ║
║ Best                                6.452 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                               11.111 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.001 ║
║ Best                                7.477 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.024 ║
║ Best                                0.964 ║
║ Worst                               0.000 ║
║ Total                               0.034 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.038 ║
║ Best                                1.152 ║
║ Worst                               0.000 ║
║ Total                               0.134 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.002 ║
║ Best                                0.141 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╚═══════════════════════════════════════════╝

```

2023-08-01 18:36 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.004 ║
║ Best                                6.452 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                               11.111 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.001 ║
║ Best                                7.477 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.024 ║
║ Best                                0.964 ║
║ Worst                               0.000 ║
║ Total                               0.034 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.038 ║
║ Best                                1.152 ║
║ Worst                               0.000 ║
║ Total                               0.134 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.002 ║
║ Best                                0.141 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╚═══════════════════════════════════════════╝

```

2023-08-02 12:45 UTC, akiramenai requested changes

2023-08-02 12:45 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMExpandSelect.cpp
> +      // COND_OF is an alias for COND_LT
It's not quite the case. Before start folding we only had flags from sub, and LT is the flag set by sub. We introduced OF to tell different semantic as LLVM doesn't expect flags to have different meaning depending on which instruction set them. For instance, I worry about mul, as the spec says:
```
◦ LT_OF is set if overflow occurs, i.e. op1×op2≥2
◦ EQ is set if resultlow=0.
◦ GT is set if LT_OF and EQ are cleared.
```
So GT doesn't seem to be a proper reversal of OF, 0 is the corner case.
Can we have an execution test to cover that nuances?

2023-08-02 12:45 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +; CHECK-NEXT: add.ge  r2, r0, r1
Can we have a test checking for lt/of, not the reversal?

2023-08-02 14:40 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMExpandSelect.cpp
> +      // COND_OF is an alias for COND_LT
@akiramenai We introduced OF because we do not want passes earlier in the pipeline to reverse it into GE. Here at this very late stage, I think flipping is okay provided that no other alterations after it.

BTW, I think you meant GE instead of GT? LT_OF's reverse is GE.

2023-08-02 15:14 UTC, lialan commented on llvm/test/CodeGen/SyncVM/overflow.ll
> +; CHECK-NEXT: add.ge  r2, r0, r1
done. added test to show `.of` instructions generated.

2023-08-02 15:49 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.004 ║
║ Best                                6.452 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                               11.111 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.001 ║
║ Best                                7.477 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.024 ║
║ Best                                0.964 ║
║ Worst                               0.000 ║
║ Total                               0.034 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.038 ║
║ Best                                1.152 ║
║ Worst                               0.000 ║
║ Total                               0.134 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.002 ║
║ Best                                0.141 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╚═══════════════════════════════════════════╝

```

2023-08-02 17:08 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.004 ║
║ Best                                6.452 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                               11.111 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.001 ║
║ Best                                7.477 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.024 ║
║ Best                                0.964 ║
║ Worst                               0.000 ║
║ Total                               0.034 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.038 ║
║ Best                                1.152 ║
║ Worst                               0.000 ║
║ Total                               0.134 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.002 ║
║ Best                                0.141 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╚═══════════════════════════════════════════╝

```

2023-08-03 05:22 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMExpandSelect.cpp
> +      // COND_OF is an alias for COND_LT
@lialan I see... with the spec in coq it looks like we can reverse OF, can't we? I mean our OF which can only be set by an overflowing instruction. All instruction that can set OF allow to use GE as its reverse.
If so, why do we want earlier passes to avoid reversing in that case? And (not in scope of this patch) it looks that we can reverse OF in combine flag setting pass. Am I right?

2023-08-03 05:25 UTC, akiramenai approved these changes
Please squash.

2023-08-03 13:26 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.004 ║
║ Best                                6.452 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                               11.111 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.001 ║
║ Best                                7.477 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.024 ║
║ Best                                0.964 ║
║ Worst                               0.000 ║
║ Total                               0.034 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.038 ║
║ Best                                1.152 ║
║ Worst                               0.000 ║
║ Total                               0.134 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.002 ║
║ Best                                0.141 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╚═══════════════════════════════════════════╝

```

2023-08-03 14:05 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMExpandSelect.cpp
> +      // COND_OF is an alias for COND_LT
@akiramenai There was a reason specifically for that, pertaining to machine block placement pass reversing OF to GE and cause havoc. We had a discussion on this, and Shamatar was there too. Can't remember the details, perhaps we discussed it on the now-retired mattermost.

let me get back to you if I find anything.

2023-08-03 14:05 UTC, merged