Instruction mappings for addr modes and argument swap
matter-labs/era-compiler-llvm pull request #242
Opened 2023-06-07 22:25 UTC by akiramenai

The patch implements mapping to access instruction families with different input and output addressing modes, and swap argument flags. It also add missing fat pointer patterns to make mappings complete.

2023-06-07 23:10 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.001 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.001 ║
║ Best                                0.000 ║
║ Worst                              -3.333 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-06-08 00:53 UTC, lialan requested changes
Generally LGTM, just a little bit more details.

2023-06-08 00:53 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMISelLowering.cpp
> +#include <unordered_map>
@FlashSheridan here

2023-06-08 00:53 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrFormats.td
>    bits<3> OperandAddrMode = OpndAddrNotSet.Value;
Now we can remove `OperandAddrMode` and `DestAddrMode`. `bits` is not as good as `int` in TableGen I think.

2023-06-08 00:53 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrFormats.td
> +  let ValueCols = [["0"], ["1"], ["2"], ["3"]];
Maybe some comments about what 0, 1, 2, 3 represents.

or you can try the way `OperandAddrMode` organizes, which uses names instead of integer values for easier to understand.

2023-06-08 06:43 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrFormats.td
>    bits<3> OperandAddrMode = OpndAddrNotSet.Value;
We might need bits for encoding, don't we? And there is possibility we start debugger work soon which might require binary output.
So, let me create a ticket for this duplication.

2023-06-08 06:52 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrFormats.td
>    bits<3> OperandAddrMode = OpndAddrNotSet.Value;
https://linear.app/matterlabs/issue/CPR-1154/remove-duplication-between-operandaddrmode-and-operandam-in-td-files

2023-06-08 09:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrFormats.td
> +  let ValueCols = [["0"], ["1"], ["2"], ["3"]];
I've actually tried twice. I previously reported that bit vectors aren't good for keys (and indeed I used to produce semantically incorrect `.inc` files), but it seems that Hexagon managed to use them. Now I failed to produce tables for mappings, but otherwise `.inc` file is correct.
So with this particular comment (though I agree magic numbers are evil), I'd prefer to postpone and track as https://linear.app/matterlabs/issue/CPR-1154/remove-duplication-between-operandaddrmode-and-operandam-in-td-files. It seems that we don't need `OperandAM` at all. This patch as it is makes C++ code more concise, while our `td`s are messy anyway. And I'd wait for coq spec to be ready before to clean up `td`s. Even if we aren't going to generate `td`s from the spec, I'd use the exactly same terminology in `td`s as it is in the spec.
@lialan @hedgar2017 @sayon what do you think?

2023-06-08 12:53 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrFormats.td
> +  let ValueCols = [["0"], ["1"], ["2"], ["3"]];
@akiramenai I tried to use `string` instead of int, and it works in my case. So maybe just change int to string and use something like `rr`, `sr` to represent that.

But I don't object we do that in the ticket.

2023-06-08 12:55 UTC, lialan approved these changes
Since we know what to do with the issues we discussed here, it is LGTM now.

2023-06-08 15:28 UTC, lialan commented
@akiramenai A friendly reminder that we need to turn on commit signatures. But it seems like it is not enforced yet.

2023-06-09 13:39 UTC, akiramenai commented
@lialan thanks. Will learn it and start using with the next patch.

2023-06-09 13:39 UTC, merged