Enable the machine outliner for SyncVM
matter-labs/era-compiler-llvm pull request #243
Opened 2023-06-09 15:14 UTC by vladimirradosavljevic

2023-06-13 11:33 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.898 ║
║ Best                               45.104 ║
║ Worst                               0.000 ║
║ Total                               3.713 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -49.504 ║
║ Total                              -2.925 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                8.304 ║
║ Best                               31.070 ║
║ Worst                               0.000 ║
║ Total                              14.194 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -7.809 ║
║ Best                                0.000 ║
║ Worst                             -19.046 ║
║ Total                              -7.132 ║
╚═══════════════════════════════════════════╝

```

2023-06-13 19:50 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.569 ║
║ Best                               37.020 ║
║ Worst                               0.000 ║
║ Total                               2.049 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -28.777 ║
║ Total                              -2.108 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                4.694 ║
║ Best                               31.070 ║
║ Worst                               0.000 ║
║ Total                               9.181 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -6.407 ║
║ Best                                0.000 ║
║ Worst                             -17.312 ║
║ Total                              -6.160 ║
╚═══════════════════════════════════════════╝

```

2023-06-14 12:31 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.682 ║
║ Best                               37.020 ║
║ Worst                               0.000 ║
║ Total                               2.369 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -34.286 ║
║ Total                              -2.110 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                5.588 ║
║ Best                               31.070 ║
║ Worst                               0.000 ║
║ Total                              10.406 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -6.781 ║
║ Best                                0.000 ║
║ Worst                             -17.573 ║
║ Total                              -6.305 ║
╚═══════════════════════════════════════════╝

```

2023-06-16 07:52 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.682 ║
║ Best                               37.020 ║
║ Worst                               0.000 ║
║ Total                               2.369 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -34.286 ║
║ Total                              -2.110 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                5.588 ║
║ Best                               31.070 ║
║ Worst                               0.000 ║
║ Total                              10.406 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -6.781 ║
║ Best                                0.000 ║
║ Worst                             -17.573 ║
║ Total                              -6.305 ║
╚═══════════════════════════════════════════╝

```

2023-06-16 16:04 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.682 ║
║ Best                               37.020 ║
║ Worst                               0.000 ║
║ Total                               2.369 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -34.286 ║
║ Total                              -2.110 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                5.588 ║
║ Best                               31.070 ║
║ Worst                               0.000 ║
║ Total                              10.406 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -6.781 ║
║ Best                                0.000 ║
║ Worst                             -17.573 ║
║ Total                              -6.305 ║
╚═══════════════════════════════════════════╝

```

2023-06-16 19:03 UTC, lialan requested changes
Good quality of code, just some places we need to revisit.

2023-06-16 19:03 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +  unsigned FlagsSetInAll = 0xF;
nit: define some macros for magic numbers to make it easier to read.

2023-06-16 19:03 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +    if (RepeatedSequenceLocs.size() < 2)
nit: again, can improve readability by avoid using magic numbers. same for the `CallOverhead` and `FrameOverhead` below.

2023-06-16 19:03 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +  MBB.insert(MBB.end(), BuildMI(MF, DebugLoc(), get(SyncVM::RET)));
nit: can use previous instruction's DebugLoc. Same for the one in `insertOutlinedCall`

2023-06-16 19:03 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +  if (!MBB.pred_empty()) {
should this be `succ_empty`?

2023-06-16 19:03 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +                  return I.getDesc().hasImplicitDefOfPhysReg(SyncVM::Flags);
I think you mean `hasImplicitUseOfPhyReg` here

2023-06-17 18:17 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +  if (!MBB.pred_empty()) {
It shouldn't be.
But style: early return is preferred.

2023-06-19 10:16 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +  unsigned FlagsSetInAll = 0xF;
Done.

2023-06-19 10:16 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +    if (RepeatedSequenceLocs.size() < 2)
Done.

2023-06-19 10:16 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +  MBB.insert(MBB.end(), BuildMI(MF, DebugLoc(), get(SyncVM::RET)));
Done.

2023-06-19 10:49 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +  if (!MBB.pred_empty()) {
@lialan In case we don't have predecessors and MBB has no Flags instructions, we know that it is not propagating Flags across MBBs. Check for Flags instructions was missing, so I have added it, and updated test to reflect this possible issue.
@akiramenai Added early return.

2023-06-19 10:56 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +                  return I.getDesc().hasImplicitDefOfPhysReg(SyncVM::Flags);
I'm looking for the Defs, not the Uses.
Please look at the following example:
```
...
Inst1 -> def Flags
....
Inst2 -> def Flags
....
jc dest, cc
```

We don't want to remove Inst1 from the list of candidates as we have Inst2 that defines flags and jc that uses it. Also, we want to remove Inst2.

2023-06-19 11:31 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.684 ║
║ Best                               37.020 ║
║ Worst                               0.000 ║
║ Total                               2.371 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -34.286 ║
║ Total                              -2.112 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                5.588 ║
║ Best                               31.070 ║
║ Worst                               0.000 ║
║ Total                              10.406 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -6.781 ║
║ Best                                0.000 ║
║ Worst                             -17.573 ║
║ Total                              -6.305 ║
╚═══════════════════════════════════════════╝

```

2023-06-19 13:03 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.684 ║
║ Best                               37.020 ║
║ Worst                               0.000 ║
║ Total                               2.371 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -34.286 ║
║ Total                              -2.112 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                5.588 ║
║ Best                               31.070 ║
║ Worst                               0.000 ║
║ Total                              10.406 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -6.781 ║
║ Best                                0.000 ║
║ Worst                             -17.573 ║
║ Total                              -6.305 ║
╚═══════════════════════════════════════════╝

```

2023-06-19 14:07 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +                  return I.getDesc().hasImplicitDefOfPhysReg(SyncVM::Flags);
Thanks. Maybe add this example to the comments above to show the intention.

2023-06-19 15:04 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +                  return I.getDesc().hasImplicitDefOfPhysReg(SyncVM::Flags);
Sure, will do that.

2023-06-20 10:41 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.684 ║
║ Best                               37.020 ║
║ Worst                               0.000 ║
║ Total                               2.371 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -34.286 ║
║ Total                              -2.112 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                5.588 ║
║ Best                               31.070 ║
║ Worst                               0.000 ║
║ Total                              10.406 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -6.781 ║
║ Best                                0.000 ║
║ Worst                             -17.573 ║
║ Total                              -6.305 ║
╚═══════════════════════════════════════════╝

```

2023-06-20 14:01 UTC, lialan approved these changes
LGTM, just do remember to turn it off by default.

2023-06-20 14:01 UTC, lialan commented on .github/workflows/compiler-integration-tests.yml
> +             CodeGen/SyncVM/machine-outliner.mir"
yeah compile-twice has been broken for some tests for some while now.

And I think the upstream is not caring too much about it as well? @FlashSheridan

2023-06-20 14:01 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +  return true;
do remember to update this when checking in. The number hurts. :-)

2023-06-20 14:01 UTC, lialan commented on llvm/test/CodeGen/SyncVM/machine-outliner.mir
> +    $r1 = ANDrrr_v $r1, $r2, 0, implicit-def $flags
c'est bon.

Just a comment to discuss: If flags are seen as ephemeral values, and it does not live (or we should not trust it) if we go beyond BB boundaries, then I am curious if machine verifier will complain line 147 to have a use-before-def of flags reg error, because verifier can work on the scope of a BB.

But what we have right now does no harm.

2023-06-20 15:15 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +  return true;
Done.

2023-06-20 15:16 UTC, vladimirradosavljevic commented
@lialan Thanks for a review!

2023-06-20 15:19 UTC, vladimirradosavljevic commented on llvm/test/CodeGen/SyncVM/machine-outliner.mir
> +    $r1 = ANDrrr_v $r1, $r2, 0, implicit-def $flags
This is a good point, but for some reason, verifier is not complaining at all. I assume when we start implementing such optimizations, we will need to add Flags register in MBB liveins.

2023-06-20 15:34 UTC, FlashSheridan commented on .github/workflows/compiler-integration-tests.yml
> +             CodeGen/SyncVM/machine-outliner.mir"
I’m afraid so:

> Filed https://github.com/llvm/llvm-project/issues/61462, no response yet, so not clear how serious the maintainers are about --compile-twice and/or asan.

https://linear.app/matterlabs/issue/CPR-1045#comment-03c2f235

2023-06-20 16:20 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-06-20 21:15 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +  // TODO: Remove this once issue with heap growth is fixed in VM.
Can we create a ticket which is blocked by the VM part (and put the number here)? If I remember right @sayon had raised it.

2023-06-21 10:29 UTC, akiramenai approved these changes
LGTM assuming flag handling logic will go off after switching to dynamic jumps.

2023-06-21 12:11 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +  // TODO: Remove this once issue with heap growth is fixed in VM.
When we switch to `jump` implementation, we can remove this as we won't do `near_call` `ret` where this problem occurs, so comment wise, I suggest to leave it as is. What do you think?

@sayon Do we have a VM ticket for this issue?

2023-06-21 12:12 UTC, vladimirradosavljevic commented
@akiramenai Yes, we will remove flag handling logic when we switch to jumps. Thanks for a review!

2023-06-22 08:00 UTC, merged