[SyncVM] Use jumps for Machine Outlining
matter-labs/era-compiler-llvm pull request #253
Opened 2023-06-23 12:49 UTC by vladimirradosavljevic

Use jumps for Machine Outlining instead of using near_call and ret.

2023-06-23 12:55 UTC, vladimirradosavljevic commented
As far as I understood @akiramenai, we need to add support in assembly and in linker in order to try this.

2023-06-23 13:25 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-06-23 21:54 UTC, akiramenai commented
@vladimirradosavljevic it's highly likely that we need. We haven't used labels in const section or as non call/br immediates before.

2023-06-27 13:02 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-06-29 14:50 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.256 ║
║ Best                               35.608 ║
║ Worst                               0.000 ║
║ Total                               1.277 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.038 ║
║ Worst                             -45.652 ║
║ Total                              -1.338 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.139 ║
║ Best                               11.076 ║
║ Worst                             -37.573 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                2.147 ║
║ Best                               16.696 ║
║ Worst                               0.000 ║
║ Total                               4.750 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -2.387 ║
║ Best                                0.000 ║
║ Worst                             -13.328 ║
║ Total                              -4.943 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.122 ║
║ Best                                2.812 ║
║ Worst                              -7.224 ║
║ Total                              -0.108 ║
╚═══════════════════════════════════════════╝

```

2023-07-03 13:47 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.512 ║
║ Best                               39.763 ║
║ Worst                              -3.077 ║
║ Total                               2.216 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -53.974 ║
║ Total                              -2.231 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                               15.884 ║
║ Worst                             -37.130 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                4.366 ║
║ Best                               21.516 ║
║ Worst                               0.000 ║
║ Total                               8.329 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -6.586 ║
║ Best                                0.000 ║
║ Worst                             -20.585 ║
║ Total                              -6.209 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.562 ║
║ Best                                2.938 ║
║ Worst                              -6.582 ║
║ Total                              -0.127 ║
╚═══════════════════════════════════════════╝

```

2023-07-03 15:17 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.512 ║
║ Best                               39.763 ║
║ Worst                              -3.077 ║
║ Total                               2.216 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -53.974 ║
║ Total                              -2.231 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                               15.884 ║
║ Worst                             -37.130 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                4.366 ║
║ Best                               21.516 ║
║ Worst                               0.000 ║
║ Total                               8.329 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -6.586 ║
║ Best                                0.000 ║
║ Worst                             -20.585 ║
║ Total                              -6.209 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.562 ║
║ Best                                2.938 ║
║ Worst                              -6.582 ║
║ Total                              -0.127 ║
╚═══════════════════════════════════════════╝

```

2023-07-04 11:19 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.509 ║
║ Best                               39.278 ║
║ Worst                               0.000 ║
║ Total                               2.207 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -53.191 ║
║ Total                              -2.200 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.347 ║
║ Best                               15.884 ║
║ Worst                             -33.713 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                4.357 ║
║ Best                               21.516 ║
║ Worst                               0.000 ║
║ Total                               8.318 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -6.529 ║
║ Best                                0.000 ║
║ Worst                             -19.692 ║
║ Total                              -6.196 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.551 ║
║ Best                                3.116 ║
║ Worst                              -6.582 ║
║ Total                              -0.126 ║
╚═══════════════════════════════════════════╝

```

2023-07-04 15:25 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.509 ║
║ Best                               39.278 ║
║ Worst                               0.000 ║
║ Total                               2.207 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -53.191 ║
║ Total                              -2.200 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.347 ║
║ Best                               15.884 ║
║ Worst                             -33.713 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                4.357 ║
║ Best                               21.516 ║
║ Worst                               0.000 ║
║ Total                               8.318 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -6.529 ║
║ Best                                0.000 ║
║ Worst                             -19.692 ║
║ Total                              -6.196 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.551 ║
║ Best                                3.116 ║
║ Worst                              -6.582 ║
║ Total                              -0.126 ║
╚═══════════════════════════════════════════╝

```

2023-07-05 11:16 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.509 ║
║ Best                               39.278 ║
║ Worst                               0.000 ║
║ Total                               2.207 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -53.191 ║
║ Total                              -2.200 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.347 ║
║ Best                               15.884 ║
║ Worst                             -33.713 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                4.357 ║
║ Best                               21.516 ║
║ Worst                               0.000 ║
║ Total                               8.318 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -6.529 ║
║ Best                                0.000 ║
║ Worst                             -19.692 ║
║ Total                              -6.196 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.551 ║
║ Best                                3.116 ║
║ Worst                              -6.582 ║
║ Total                              -0.126 ║
╚═══════════════════════════════════════════╝

```

2023-07-06 10:39 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.509 ║
║ Best                               39.278 ║
║ Worst                               0.000 ║
║ Total                               2.207 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -53.191 ║
║ Total                              -2.200 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.347 ║
║ Best                               15.884 ║
║ Worst                             -33.713 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                4.357 ║
║ Best                               21.516 ║
║ Worst                               0.000 ║
║ Total                               8.318 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -6.529 ║
║ Best                                0.000 ║
║ Worst                             -19.692 ║
║ Total                              -6.196 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.551 ║
║ Best                                3.116 ║
║ Worst                              -6.582 ║
║ Total                              -0.126 ║
╚═══════════════════════════════════════════╝

```

2023-07-06 15:27 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.509 ║
║ Best                               39.278 ║
║ Worst                               0.000 ║
║ Total                               2.207 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -53.191 ║
║ Total                              -2.200 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.347 ║
║ Best                               15.884 ║
║ Worst                             -33.713 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                4.357 ║
║ Best                               21.516 ║
║ Worst                               0.000 ║
║ Total                               8.318 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -6.529 ║
║ Best                                0.000 ║
║ Worst                             -19.692 ║
║ Total                              -6.196 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.551 ║
║ Best                                3.116 ║
║ Worst                              -6.582 ║
║ Total                              -0.126 ║
╚═══════════════════════════════════════════╝

```

2023-07-07 09:06 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.505 ║
║ Best                               39.278 ║
║ Worst                               0.000 ║
║ Total                               2.182 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -53.191 ║
║ Total                              -2.200 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.346 ║
║ Best                               15.744 ║
║ Worst                             -33.713 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                4.332 ║
║ Best                               21.548 ║
║ Worst                               0.000 ║
║ Total                               8.240 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -6.521 ║
║ Best                                0.000 ║
║ Worst                             -19.692 ║
║ Total                              -6.189 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.550 ║
║ Best                                3.119 ║
║ Worst                              -6.615 ║
║ Total                              -0.125 ║
╚═══════════════════════════════════════════╝

```

2023-07-07 14:23 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.263 ║
║ Best                               29.572 ║
║ Worst                               0.000 ║
║ Total                               0.916 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.344 ║
║ Best                                0.000 ║
║ Worst                             -34.694 ║
║ Total                              -0.099 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.142 ║
║ Best                                9.651 ║
║ Worst                             -21.123 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.856 ║
║ Best                               10.803 ║
║ Worst                               0.000 ║
║ Total                               2.321 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -1.479 ║
║ Best                                0.000 ║
║ Worst                              -8.451 ║
║ Total                              -1.233 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.201 ║
║ Best                                0.549 ║
║ Worst                              -5.263 ║
║ Total                              -0.023 ║
╚═══════════════════════════════════════════╝

```

2023-07-10 12:30 UTC, akiramenai requested changes
Mostly stylistic issues, but const_cast and the way we treat advance SP need to be explained.

2023-07-10 12:30 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVM.h
> +enum TOF {
Abbreviation is barely readable w/o go to definition. Batter to name it as the comment above suggests.

2023-07-10 12:30 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +  int64_t StackOffset = -1;
If I get it right, you name the literal to avoid `-1 /* StackOffset */` style usage. May I ask you to add `const` then? Otherwise passing int like this make me think that probably int is accepted by reference.

2023-07-10 12:30 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +    return It->isReg() && It->getReg() == SyncVM::SP && !(It + 2)->isImm();
You repeat `It->isReg() && It->getReg() == SyncVM::SP`, may we extract it as a function? It also might worth to make an utility which classifies stack access (e.g. global static, global, local static, local), it's usable across passes.
Also need to capture a lambda inside another one to call it looks like an abuse of the feature to me.

2023-07-10 12:30 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +      Overhead += get(SyncVM::NOPSP).getSize();
Don't we assume here that the very first outline candidate a function is a part of will indeed be outlined?

2023-07-10 12:30 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +      const_cast<outliner::OutlinedFunction &>(OF).Candidates.front();
Do we really need to strip const here?

2023-07-10 12:30 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
>  void SyncVMInstrInfo::buildOutlinedFrame(
Since we change calling conventions for outlined functions, it worth documenting them in this and the following method _declaration_.

2023-07-10 12:30 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +  int RetSymOffset = 0;
Nitpicking: Here I can't guess `int&`, but `const` qualifier still might be preferable.

2023-07-10 14:39 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVM.h
> +enum TOF {
Done. Named it as TargetOperandFlags.

2023-07-10 14:40 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +  int64_t StackOffset = -1;
I removed the literal and used `-1 /* StackOffset */` style.

2023-07-10 14:41 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +    return It->isReg() && It->getReg() == SyncVM::SP && !(It + 2)->isImm();
I have created two functions `classifyStackAccess` and `hasInvalidRelativeStackAccess`. Please share if you want me to change it.

2023-07-10 14:44 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +      Overhead += get(SyncVM::NOPSP).getSize();
Here, we are calculating overhead for creating calls and creating outlined frame. After that, common code is [calculating](https://github.com/matter-labs/compiler-llvm/blob/331b78d08983d821836cfc0c37ffaa681167b94b/llvm/lib/CodeGen/MachineOutliner.cpp#L600) whether is beneficial to outline, so here, we just need to add to only one candidate if we need to add stack advance instruction.

2023-07-10 14:44 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +      const_cast<outliner::OutlinedFunction &>(OF).Candidates.front();
Managed to remove ugly const_cast.

2023-07-10 14:44 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
>  void SyncVMInstrInfo::buildOutlinedFrame(
Done.

2023-07-10 14:45 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +  int RetSymOffset = 0;
Like above, choose to use `0 /* RetSymOffset */ `style.

2023-07-10 15:19 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.263 ║
║ Best                               29.572 ║
║ Worst                               0.000 ║
║ Total                               0.916 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.344 ║
║ Best                                0.000 ║
║ Worst                             -34.694 ║
║ Total                              -0.099 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.142 ║
║ Best                                9.651 ║
║ Worst                             -21.123 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.856 ║
║ Best                               10.803 ║
║ Worst                               0.000 ║
║ Total                               2.321 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -1.479 ║
║ Best                                0.000 ║
║ Worst                              -8.451 ║
║ Total                              -1.233 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.201 ║
║ Best                                0.549 ║
║ Worst                              -5.263 ║
║ Total                              -0.023 ║
╚═══════════════════════════════════════════╝

```

2023-07-10 19:09 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +      Overhead += get(SyncVM::NOPSP).getSize();
So it seem like I approximately understood. My question was about the following.
Let's assume there are 2 marginally beneficial candidates for a function with empty frame. Necessity to add `NOPSP` shift it beyond this margin, but we account for `NOPSP` once, and the first candidate fail to outline, but the second one succeed. Could it happen? Will it only be an optimization issue (I saw code below relies on the first candidate as well)? Can we add a test case for it?

2023-07-10 19:15 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.h
> +  /// Since we don't need to follow calling convention ABI for outlined
It might sound too demanding on documentation and I will accept patch w/o it, but the idea behind my previous request was to read from the head file that the frame contains return address unlike it's done for any other call and instead of ret we use jump to it. If we separate this info among `buildOutlinedFrame`, `insertOutlinedCall` one can understand what is happening w/o reading the definitions.

2023-07-10 19:19 UTC, akiramenai reviewed
Can we have a test where first candidate fails to outline in a frameless function because of outlining cost and there is at least one more candidate? The rest look good, thanks.

2023-07-10 19:22 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +    return It->isReg() && It->getReg() == SyncVM::SP && !(It + 2)->isImm();
That is good enough.
Btw, when we have it? Big offsets with `CImm` or symbols?

2023-07-11 08:41 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +    return It->isReg() && It->getReg() == SyncVM::SP && !(It + 2)->isImm();
I would say, `CImm` if we can encode it inside instruction, symbols otherwise.

2023-07-11 08:50 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +      Overhead += get(SyncVM::NOPSP).getSize();
This calculation is only for a whole sequence where all candidates have same instructions, and MachineOutliner is checking if it is beneficial to outline whole sequence, and not candidates itself as part of some sequence. Also, MachineOutliner algorithm is not reusing overhead calculation for candidates, as it is recreating new candidates just before call to this function[1]. This is why we can just add this overhead to one candidate, so it can affect benefit calculation of a sequence as a whole.

[1] [Dropping](https://github.com/matter-labs/compiler-llvm/blob/188eb4e7e588240f3b034238ea97282257575dcd/llvm/lib/CodeGen/MachineOutliner.cpp#L537) all previous candidates from a sequence.
[Adding](https://github.com/matter-labs/compiler-llvm/blob/188eb4e7e588240f3b034238ea97282257575dcd/llvm/lib/CodeGen/MachineOutliner.cpp#L574) new candidates in a sequence.

2023-07-11 08:52 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.h
> +  /// Since we don't need to follow calling convention ABI for outlined
It is not too demanding and I agree with you. Will add more comments for `buildOutlinedFrame` and `insertOutlinedCall` in a header file.

2023-07-11 08:57 UTC, vladimirradosavljevic commented
> Can we have a test where first candidate fails to outline in a frameless function because of outlining cost and there is at least one more candidate? The rest look good, thanks.

I will add test case where it is not beneficial to outline because we need to add stack advance instruction. This test case will have 3 candidates with size of 4 instructions, and calculation will be like this:

```
Outlined cost:     2 (call overhead) * 3 (candidates) + 
                   4 (sequence size) + 1 (jump to return) +
                   1 (stack advance instruction) = 12
Non-Outlined cost: 3 (candidates) * 4 (sequence size) = 12
```

2023-07-11 10:32 UTC, vladimirradosavljevic commented
Addressed comments + included improvement from [262](https://github.com/matter-labs/compiler-llvm/pull/262).

2023-07-11 11:03 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.268 ║
║ Best                               29.572 ║
║ Worst                               0.000 ║
║ Total                               0.942 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -34.694 ║
║ Total                              -0.121 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.158 ║
║ Best                                9.651 ║
║ Worst                             -21.123 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.865 ║
║ Best                               11.088 ║
║ Worst                               0.000 ║
║ Total                               2.342 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -1.533 ║
║ Best                                0.000 ║
║ Worst                              -8.507 ║
║ Total                              -1.245 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.212 ║
║ Best                                0.576 ║
║ Worst                              -5.263 ║
║ Total                              -0.024 ║
╚═══════════════════════════════════════════╝

```

2023-07-11 12:29 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +      Overhead += get(SyncVM::NOPSP).getSize();
Thanks for clarification!

2023-07-11 12:31 UTC, akiramenai approved these changes
LGTM, thanks

2023-07-12 15:00 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.292 ║
║ Best                               29.572 ║
║ Worst                               0.000 ║
║ Total                               0.991 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                0.000 ║
║ Worst                             -34.694 ║
║ Total                              -0.150 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.155 ║
║ Best                                9.643 ║
║ Worst                             -21.783 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.849 ║
║ Best                               11.074 ║
║ Worst                               0.000 ║
║ Total                               2.275 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -1.535 ║
║ Best                                0.000 ║
║ Worst                             -10.304 ║
║ Total                              -1.251 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.213 ║
║ Best                                0.498 ║
║ Worst                              -5.263 ║
║ Total                              -0.024 ║
╚═══════════════════════════════════════════╝

```

2023-07-14 08:08 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.503 ║
║ Best                               29.572 ║
║ Worst                               0.000 ║
║ Total                               1.336 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.327 ║
║ Best                                0.000 ║
║ Worst                             -34.694 ║
║ Total                              -0.126 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.128 ║
║ Best                               11.413 ║
║ Worst                             -21.783 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                2.448 ║
║ Best                               11.987 ║
║ Worst                               0.000 ║
║ Total                               2.805 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -1.524 ║
║ Best                                0.000 ║
║ Worst                             -10.436 ║
║ Total                              -1.242 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.211 ║
║ Best                                0.511 ║
║ Worst                              -4.211 ║
║ Total                              -0.022 ║
╚═══════════════════════════════════════════╝

```

2023-07-14 12:50 UTC, akiramenai requested changes
Ideally we should do something about machine-outliner-reruns because it changes behaviour for other targets.

2023-07-14 12:50 UTC, akiramenai commented on llvm/lib/CodeGen/MachineOutliner.cpp
> +    "machine-outliner-reruns", cl::init(5), cl::Hidden,
Can we somehow make 5 default for SyncVM only. We don't run codegen tests for other targets now, but still it make sense to not to interfere.

2023-07-14 12:50 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.h
> +inline StackAccess classifyStackAccess(MachineInstr::mop_iterator Op) {
`const_mop_iterator` is enough for the purpose, same below.

2023-07-14 12:50 UTC, akiramenai commented on llvm/include/llvm/CodeGen/TargetInstrInfo.h
> +  /// Do a fixup post outline.
SyncVM local begin / end

2023-07-14 14:08 UTC, vladimirradosavljevic commented on llvm/lib/CodeGen/MachineOutliner.cpp
> +    "machine-outliner-reruns", cl::init(5), cl::Hidden,
Done. Added `defaultOutlineReruns` hook in `TargetInstrInfo`.

2023-07-14 14:08 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.h
> +inline StackAccess classifyStackAccess(MachineInstr::mop_iterator Op) {
Done.

2023-07-14 14:08 UTC, vladimirradosavljevic commented on llvm/include/llvm/CodeGen/TargetInstrInfo.h
> +  /// Do a fixup post outline.
Done.

2023-07-14 14:16 UTC, akiramenai approved these changes

2023-07-14 14:46 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.503 ║
║ Best                               29.572 ║
║ Worst                               0.000 ║
║ Total                               1.336 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.327 ║
║ Best                                0.000 ║
║ Worst                             -34.694 ║
║ Total                              -0.126 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.128 ║
║ Best                               11.413 ║
║ Worst                             -21.783 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                2.448 ║
║ Best                               11.987 ║
║ Worst                               0.000 ║
║ Total                               2.805 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -1.524 ║
║ Best                                0.000 ║
║ Worst                             -10.436 ║
║ Total                              -1.242 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.211 ║
║ Best                                0.511 ║
║ Worst                              -4.211 ║
║ Total                              -0.022 ║
╚═══════════════════════════════════════════╝

```

2023-07-17 12:03 UTC, merged