Enabling target independent LIT tests with EVM backend
matter-labs/era-compiler-llvm pull request #254
Opened 2023-06-24 02:34 UTC by PavelKopyl

1. Cherry-pick: "LLVM Handle i256 length properly in memcpy optimizer"
2. [EVM] Expand memcpy, memset and memmov intrinsics into loops.
3. [TESTS] Expect fail or disable some tests for 'evm' target.
4. [EVM] Support sext for MVT::i1 type. Add lowering of external symbols.
5. [EVM] Disable jump tables building for EVM.
6. [EVM] Adding a pass that moves ARGUMENT instructions to the top of the first BB.
7. [EVM][CI] Enable lit tests with both default and opt verification options.

2023-06-24 03:09 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-06-27 12:39 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-06-27 13:27 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-06-27 16:34 UTC, FlashSheridan commented on .github/workflows/compiler-integration-tests.yml
> +          target-llvm/build-final/bin/llvm-lit -vv -s --debug --xfail "${XFAILS}" "-Dllc=${BINDIR}/llc ${LLC_OPTS}" llvm/llvm/test/CodeGen/EVM/
A belated comment (I think the change goes back to e074f146), but the `-vv` option produces a lot of output (e.g. [jobs/9784727048#step:15:103](https://github.com/matter-labs/compiler-llvm/actions/runs/5389995173/jobs/9784727048#step:15:103)) here and in the “opt verification options” step below.  It also seems odd in combination with `-s`.  (If you need the verbosity for debugging CI, I suggest adding `-vv` back for a manual Workflow run.)

2023-06-27 16:46 UTC, FlashSheridan commented on .github/workflows/compiler-integration-tests.yml
> -            --verify-regalloc \
Could you add a comment to prevent this deletion getting propagated back to the main branch, and perhaps explaining why the flag needed to be removed for EVM?

2023-06-27 16:52 UTC, FlashSheridan commented on .github/workflows/compiler-integration-tests.yml
> +          ./target-llvm/build-final/bin/llvm-lit -vv -s --debug --xfail "${XFAILS}" "-Dopt=${BINDIR}/opt ${OPT_OPTS}" './llvm/llvm/test/CodeGen/'
Second `-vv -s`, discussed above.

2023-06-27 20:38 UTC, PavelKopyl commented on .github/workflows/compiler-integration-tests.yml
> +          target-llvm/build-final/bin/llvm-lit -vv -s --debug --xfail "${XFAILS}" "-Dllc=${BINDIR}/llc ${LLC_OPTS}" llvm/llvm/test/CodeGen/EVM/
OK, did I get it right that you suggest to remove "-vv" from the default CI, but use it manually when required?

2023-06-27 20:54 UTC, FlashSheridan commented on .github/workflows/compiler-integration-tests.yml
> +          target-llvm/build-final/bin/llvm-lit -vv -s --debug --xfail "${XFAILS}" "-Dllc=${BINDIR}/llc ${LLC_OPTS}" llvm/llvm/test/CodeGen/EVM/
Yes, which (if we get consensus) would presumably be (part of) a PR into the default branch.

2023-06-27 21:10 UTC, PavelKopyl commented on .github/workflows/compiler-integration-tests.yml
> +          target-llvm/build-final/bin/llvm-lit -vv -s --debug --xfail "${XFAILS}" "-Dllc=${BINDIR}/llc ${LLC_OPTS}" llvm/llvm/test/CodeGen/EVM/
OK, I'll also make a PR for the main branch.

2023-06-27 21:12 UTC, PavelKopyl commented on .github/workflows/compiler-integration-tests.yml
> +          target-llvm/build-final/bin/llvm-lit -vv -s --debug --xfail "${XFAILS}" "-Dllc=${BINDIR}/llc ${LLC_OPTS}" llvm/llvm/test/CodeGen/EVM/
I'll need to cherry-pick it anyway, as dev-15-evm will not be merged to the main branch in the near future.

2023-06-28 10:57 UTC, PavelKopyl commented on .github/workflows/compiler-integration-tests.yml
> +          target-llvm/build-final/bin/llvm-lit -vv -s --debug --xfail "${XFAILS}" "-Dllc=${BINDIR}/llc ${LLC_OPTS}" llvm/llvm/test/CodeGen/EVM/
I've checked what generates an additional output ([jobs/9784727048#step:15:103](https://github.com/matter-labs/compiler-llvm/actions/runs/5389995173/jobs/9784727048#step:15:103)). It seems "--debug" is responsible for that. "-vv" prints out additional information in case of test fails, which is useful, I think.

2023-06-28 13:08 UTC, PavelKopyl commented on .github/workflows/compiler-integration-tests.yml
> -            --verify-regalloc \
Added.

2023-06-28 15:27 UTC, FlashSheridan commented on .github/workflows/compiler-integration-tests.yml
> +          target-llvm/build-final/bin/llvm-lit -vv -s --debug --xfail "${XFAILS}" "-Dllc=${BINDIR}/llc ${LLC_OPTS}" llvm/llvm/test/CodeGen/EVM/
Good points, thank you.  LGTM for the Lit invocation and comment, not qualified to judge the rest.

2023-07-04 15:44 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-07-07 13:27 UTC, akiramenai requested changes

2023-07-07 13:27 UTC, akiramenai commented on llvm/test/CodeGen/Generic/print-arith-fp.ll
> +; UNSUPPORTED: evm
Redundant

2023-07-07 13:27 UTC, akiramenai commented on llvm/test/CodeGen/MLRegalloc/default-eviction-advisor.ll
> +
Redundant empty line

2023-07-07 13:27 UTC, akiramenai commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp
> +    if (!TM.getTargetTriple().isSyncVM() && !TM.getTargetTriple().isEVM()) {
I think it's ok to use signed comparison in lower switch for EVM, so please remove the change.

2023-07-07 13:27 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMArgumentMove.cpp
> +// This is all hopefully a temporary solution until we find a better solution
Temporary they said :)

2023-07-07 13:27 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMArgumentMove.cpp
> +  for (MachineInstr &MI : EntryMBB) {
`std/llvm::find`?

2023-07-07 13:27 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMISelLowering.cpp
> +  // if (CLI.IsVarArg)
?

2023-07-07 13:27 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMLowerIntrinsics.cpp
> +void CreateMemCpyLoopKnownSize(Instruction *InsertBefore, Value *SrcAddr,
If this is more temporary than Wasm design choice above, I'm ok to keep as it is, if you expect it to persist, better is to extract the functions as an utility and commit it to dev-15, then rebase on top and reuse in EVM.

2023-07-07 13:27 UTC, akiramenai commented on llvm/test/CodeGen/EVM/memcpy-expansion.ll
> +; RUN: llc --mtriple=evm -stop-before verify < %s | FileCheck %s
Please note that PPC + NVPTX pipeline will update the structure, so it might male sense to relax thing a bit (see corresponding PRs to SyncVM)

2023-07-10 11:42 UTC, PavelKopyl commented on llvm/test/CodeGen/Generic/print-arith-fp.ll
> +; UNSUPPORTED: evm
Done.

2023-07-10 11:42 UTC, PavelKopyl commented on llvm/test/CodeGen/MLRegalloc/default-eviction-advisor.ll
> +
Done.

2023-07-10 11:43 UTC, PavelKopyl commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp
> +    if (!TM.getTargetTriple().isSyncVM() && !TM.getTargetTriple().isEVM()) {
Yes, for EVM it doesn't matter, so I removed these changes.

2023-07-10 11:44 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMArgumentMove.cpp
> +// This is all hopefully a temporary solution until we find a better solution
It seems they still have not yet come to a better solution.

2023-07-10 11:45 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMArgumentMove.cpp
> +  for (MachineInstr &MI : EntryMBB) {
Done.

2023-07-10 12:02 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMISelLowering.cpp
> +  // if (CLI.IsVarArg)
EVM doesn't support varargs functions, that is true, but many target independent LIT tests contain calls to variadic functions.  I formally enabled variadic function calls just to be able to pass those LIT tests. Otherwise, I have to additionally disable ~20 tests. As I understand the same trick was made in SyncVM (which also doesn't support varargs).

2023-07-10 12:18 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMLowerIntrinsics.cpp
> +void CreateMemCpyLoopKnownSize(Instruction *InsertBefore, Value *SrcAddr,
I think this is a final solution, as the code does what we need for both targets, and I do not see how this can be replaced by the existing target independent solution. So, I'll move these two functions to Transform/Utils.

2023-07-10 12:18 UTC, PavelKopyl commented on llvm/test/CodeGen/EVM/memcpy-expansion.ll
> +; RUN: llc --mtriple=evm -stop-before verify < %s | FileCheck %s
Done.

2023-07-10 17:54 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMArgumentMove.cpp
> +  for (MachineInstr &MI : EntryMBB) {
Have you pushed it?

2023-07-10 20:25 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-07-11 11:21 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMLowerIntrinsics.cpp
> +void CreateMemCpyLoopKnownSize(Instruction *InsertBefore, Value *SrcAddr,
The patch that moves memcpy expansion was merged to the evm-15, but in order to use it I need to rebase dev-15-evm branch which is restricted. Let's jus cherry-pick that patch here. Then it will be remove automatically once rebased on top of dev-15.

2023-07-11 12:37 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-07-13 08:28 UTC, akiramenai approved these changes
LGTM with minor remarks.
Please pay attention to commit structure when pushing.

2023-07-13 08:28 UTC, akiramenai commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp
> +      // SyncVM local end
Could we avoid reformatting pieces we haven't touched?

2023-07-13 08:28 UTC, akiramenai commented on llvm/include/llvm/Transforms/Utils/LowerMemIntrinsics.h
> +/// TODO: Aligned memory instructions are cheaper than misaligned, so consider
Could you kindly add CPR-714 after TODO, same below? It's my fault: we haven't had practice to track todo with tickets back to the days it was implemented.

2023-07-13 08:28 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMISelLowering.cpp
> +  // if (CLI.IsVarArg)
Ok, I don't have strong opinion if we should keep commented out code here. But the empty line is redundant.

2023-07-16 16:52 UTC, PavelKopyl commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp
> +      // SyncVM local end
Done

2023-07-16 16:53 UTC, PavelKopyl commented on llvm/include/llvm/Transforms/Utils/LowerMemIntrinsics.h
> +/// TODO: Aligned memory instructions are cheaper than misaligned, so consider
Done

2023-07-16 17:01 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMISelLowering.cpp
> +  // if (CLI.IsVarArg)
Done.

2023-07-16 17:54 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-07-16 19:48 UTC, merged