Combine a definition and its spill into a single instruction
matter-labs/era-compiler-llvm pull request #255
Opened 2023-06-27 11:03 UTC by akiramenai

Fold
rN = instruction x, y
...
add rN, r0, stack; spill

into
instruction x, y, stack; compute + spill

Replace rN with stack for all other uses of rN.

The patch also introduces const mop iterators to access instruction
operands as they defined in SyncVM ISA.

2023-06-27 11:49 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.063 ║
║ Best                                6.997 ║
║ Worst                               0.000 ║
║ Total                               0.192 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.135 ║
║ Best                               14.380 ║
║ Worst                               0.000 ║
║ Total                               0.059 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.026 ║
║ Best                                8.463 ║
║ Worst                              -0.006 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.754 ║
║ Best                                6.894 ║
║ Worst                               0.000 ║
║ Total                               1.082 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.373 ║
║ Best                                4.252 ║
║ Worst                               0.000 ║
║ Total                               0.798 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.018 ║
║ Best                                0.965 ║
║ Worst                               0.000 ║
║ Total                               0.028 ║
╚═══════════════════════════════════════════╝

```

2023-06-29 10:36 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.084 ║
║ Best                               13.986 ║
║ Worst                               0.000 ║
║ Total                               0.273 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.141 ║
║ Best                               20.185 ║
║ Worst                               0.000 ║
║ Total                               0.062 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.027 ║
║ Best                               11.879 ║
║ Worst                              -0.006 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.957 ║
║ Best                               13.986 ║
║ Worst                               0.000 ║
║ Total                               1.576 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.402 ║
║ Best                                2.655 ║
║ Worst                               0.000 ║
║ Total                               1.013 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.019 ║
║ Best                                1.085 ║
║ Worst                               0.000 ║
║ Total                               0.031 ║
╚═══════════════════════════════════════════╝

```

2023-07-02 09:27 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.084 ║
║ Best                               14.084 ║
║ Worst                               0.000 ║
║ Total                               0.274 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.141 ║
║ Best                               20.185 ║
║ Worst                               0.000 ║
║ Total                               0.062 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.027 ║
║ Best                               11.879 ║
║ Worst                              -0.006 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.955 ║
║ Best                               14.084 ║
║ Worst                               0.000 ║
║ Total                               1.577 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.402 ║
║ Best                                2.655 ║
║ Worst                               0.000 ║
║ Total                               1.013 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.019 ║
║ Best                                1.085 ║
║ Worst                               0.000 ║
║ Total                               0.031 ║
╚═══════════════════════════════════════════╝

```

2023-07-02 11:21 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.084 ║
║ Best                               14.084 ║
║ Worst                               0.000 ║
║ Total                               0.274 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.141 ║
║ Best                               20.185 ║
║ Worst                               0.000 ║
║ Total                               0.062 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.027 ║
║ Best                               11.879 ║
║ Worst                              -0.006 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.955 ║
║ Best                               14.084 ║
║ Worst                               0.000 ║
║ Total                               1.577 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.402 ║
║ Best                                2.655 ║
║ Worst                               0.000 ║
║ Total                               1.013 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.019 ║
║ Best                                1.085 ║
║ Worst                               0.000 ║
║ Total                               0.031 ║
╚═══════════════════════════════════════════╝

```

2023-07-02 20:56 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.084 ║
║ Best                               14.084 ║
║ Worst                               0.000 ║
║ Total                               0.274 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.141 ║
║ Best                               20.185 ║
║ Worst                               0.000 ║
║ Total                               0.062 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.027 ║
║ Best                               11.879 ║
║ Worst                              -0.006 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.955 ║
║ Best                               14.084 ║
║ Worst                               0.000 ║
║ Total                               1.577 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.402 ║
║ Best                                2.655 ║
║ Worst                               0.000 ║
║ Total                               1.013 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.019 ║
║ Best                                1.085 ║
║ Worst                               0.000 ║
║ Total                               0.031 ║
╚═══════════════════════════════════════════╝

```

2023-07-11 21:34 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.021 ║
║ Best                                6.897 ║
║ Worst                               0.000 ║
║ Total                               0.082 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.007 ║
║ Best                                7.018 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.348 ║
║ Worst                              -0.005 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.211 ║
║ Best                                6.884 ║
║ Worst                               0.000 ║
║ Total                               0.407 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.085 ║
║ Best                                0.789 ║
║ Worst                               0.000 ║
║ Total                               0.127 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.004 ║
║ Best                                0.266 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-07-12 13:48 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.022 ║
║ Best                                6.897 ║
║ Worst                               0.000 ║
║ Total                               0.084 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.007 ║
║ Best                                7.018 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.348 ║
║ Worst                              -0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.212 ║
║ Best                                6.884 ║
║ Worst                               0.000 ║
║ Total                               0.410 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.085 ║
║ Best                                0.789 ║
║ Worst                               0.000 ║
║ Total                               0.127 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.004 ║
║ Best                                0.259 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-07-13 14:34 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.021 ║
║ Best                                6.814 ║
║ Worst                               0.000 ║
║ Total                               0.085 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.007 ║
║ Best                                7.018 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.348 ║
║ Worst                              -0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.213 ║
║ Best                                6.814 ║
║ Worst                               0.000 ║
║ Total                               0.412 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.085 ║
║ Best                                0.789 ║
║ Worst                               0.000 ║
║ Total                               0.127 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.004 ║
║ Best                                0.259 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-07-15 07:27 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.021 ║
║ Best                                6.814 ║
║ Worst                               0.000 ║
║ Total                               0.085 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.007 ║
║ Best                                7.018 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.348 ║
║ Worst                              -0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.213 ║
║ Best                                6.814 ║
║ Worst                               0.000 ║
║ Total                               0.412 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.085 ║
║ Best                                0.789 ║
║ Worst                               0.000 ║
║ Total                               0.127 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.004 ║
║ Best                                0.259 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-07-16 20:51 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.021 ║
║ Best                                6.814 ║
║ Worst                               0.000 ║
║ Total                               0.085 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.007 ║
║ Best                                7.018 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.348 ║
║ Worst                              -0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.213 ║
║ Best                                6.814 ║
║ Worst                               0.000 ║
║ Total                               0.412 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.085 ║
║ Best                                0.789 ║
║ Worst                               0.000 ║
║ Total                               0.127 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.004 ║
║ Best                                0.259 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-07-17 21:09 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.480 ║
║ Best                                5.587 ║
║ Worst                             -41.989 ║
║ Total                              -1.255 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.334 ║
║ Best                               25.758 ║
║ Worst                               0.000 ║
║ Total                               0.130 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.130 ║
║ Best                               17.887 ║
║ Worst                             -12.884 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -2.268 ║
║ Best                                1.081 ║
║ Worst                             -12.414 ║
║ Total                              -2.418 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.591 ║
║ Best                                9.450 ║
║ Worst                               0.000 ║
║ Total                               1.367 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.216 ║
║ Best                                4.040 ║
║ Worst                              -0.444 ║
║ Total                               0.028 ║
╚═══════════════════════════════════════════╝

```

2023-07-17 21:45 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.024 ║
║ Best                                7.856 ║
║ Worst                              -0.648 ║
║ Total                               0.091 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.008 ║
║ Best                                7.049 ║
║ Worst                              -1.667 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.348 ║
║ Worst                              -0.852 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.263 ║
║ Best                                7.856 ║
║ Worst                               0.000 ║
║ Total                               0.474 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.091 ║
║ Best                                0.789 ║
║ Worst                               0.000 ║
║ Total                               0.142 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.005 ║
║ Best                                0.259 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-07-28 13:45 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.024 ║
║ Best                                7.856 ║
║ Worst                              -0.324 ║
║ Total                               0.092 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.008 ║
║ Best                                7.049 ║
║ Worst                              -0.947 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.301 ║
║ Worst                              -0.050 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.249 ║
║ Best                                7.856 ║
║ Worst                               0.000 ║
║ Total                               0.472 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.090 ║
║ Best                                0.785 ║
║ Worst                               0.000 ║
║ Total                               0.136 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.005 ║
║ Best                                0.263 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-08-04 10:10 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.024 ║
║ Best                                7.856 ║
║ Worst                              -0.324 ║
║ Total                               0.092 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.008 ║
║ Best                                7.049 ║
║ Worst                              -0.947 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.301 ║
║ Worst                              -0.050 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.245 ║
║ Best                                7.856 ║
║ Worst                               0.000 ║
║ Total                               0.464 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.090 ║
║ Best                                0.791 ║
║ Worst                               0.000 ║
║ Total                               0.136 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.005 ║
║ Best                                0.263 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-08-05 18:47 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.024 ║
║ Best                                7.856 ║
║ Worst                              -0.324 ║
║ Total                               0.092 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.008 ║
║ Best                                7.049 ║
║ Worst                              -0.947 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.301 ║
║ Worst                              -0.050 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.245 ║
║ Best                                7.856 ║
║ Worst                               0.000 ║
║ Total                               0.464 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.090 ║
║ Best                                0.791 ║
║ Worst                               0.000 ║
║ Total                               0.136 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.005 ║
║ Best                                0.263 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-08-06 11:02 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.024 ║
║ Best                                7.856 ║
║ Worst                              -0.324 ║
║ Total                               0.092 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.008 ║
║ Best                                7.049 ║
║ Worst                              -0.947 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.301 ║
║ Worst                              -0.050 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.245 ║
║ Best                                7.856 ║
║ Worst                               0.000 ║
║ Total                               0.464 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.090 ║
║ Best                                0.791 ║
║ Worst                               0.000 ║
║ Total                               0.136 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.005 ║
║ Best                                0.263 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-08-07 11:33 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.024 ║
║ Best                                7.856 ║
║ Worst                              -0.324 ║
║ Total                               0.092 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.008 ║
║ Best                                7.049 ║
║ Worst                              -0.947 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.301 ║
║ Worst                              -0.050 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.245 ║
║ Best                                7.856 ║
║ Worst                               0.000 ║
║ Total                               0.464 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.090 ║
║ Best                                0.791 ║
║ Worst                               0.000 ║
║ Total                               0.136 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.005 ║
║ Best                                0.263 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-08-08 18:01 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.024 ║
║ Best                                7.856 ║
║ Worst                              -0.324 ║
║ Total                               0.092 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.008 ║
║ Best                                7.049 ║
║ Worst                              -0.947 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.301 ║
║ Worst                              -0.050 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.245 ║
║ Best                                7.856 ║
║ Worst                               0.000 ║
║ Total                               0.464 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.090 ║
║ Best                                0.791 ║
║ Worst                               0.000 ║
║ Total                               0.136 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.005 ║
║ Best                                0.263 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-08-08 20:29 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.025 ║
║ Best                                7.856 ║
║ Worst                              -0.324 ║
║ Total                               0.092 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.008 ║
║ Best                                7.049 ║
║ Worst                              -0.947 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.301 ║
║ Worst                              -0.050 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.245 ║
║ Best                                7.856 ║
║ Worst                               0.000 ║
║ Total                               0.465 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.090 ║
║ Best                                0.791 ║
║ Worst                               0.000 ║
║ Total                               0.136 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.005 ║
║ Best                                0.263 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-08-09 11:20 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.025 ║
║ Best                                7.856 ║
║ Worst                              -0.324 ║
║ Total                               0.092 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.008 ║
║ Best                                7.049 ║
║ Worst                              -0.947 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.301 ║
║ Worst                              -0.050 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.245 ║
║ Best                                7.856 ║
║ Worst                               0.000 ║
║ Total                               0.465 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.090 ║
║ Best                                0.791 ║
║ Worst                               0.000 ║
║ Total                               0.136 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.005 ║
║ Best                                0.263 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-08-10 11:49 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +/// Implements a pass that combines combine instructions into one with more
Redundant 'combine'?

2023-08-10 11:49 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  /// Put the resulting instruction after \p Use.
It's a bit not clear, where is the 'Use' in the function declaration? I guess I understand this is the instruction we combine reload with. If so, we insert a new instruction before Use.

2023-08-10 11:49 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  void replaceIn1(MachineInstr &Base,
According to what the functions does, for me it would be more natural name 'swapAndReplace'. But that's up to you)

2023-08-10 11:49 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +                 std::next(Use->getIterator())->dump(););
I think here we should use std::prev instead of std::next, because replaceIn* functions actually insert a new combined instruction before Use. Please, check the following example: 
```
declare i256 @foo()

; Function Attrs: nounwind
define i256 @spill_addr(i256 %a, i256 %b) #0 {
  %x = add i256 %a, %b
  %c = call i256 @foo()
  %res = add i256 %x, %c
  ret i256 %res
}

llc --mtriple=syncvm addrmode_test.ll -debug-only=syncvm-combine-addressing-mode
== Combine reload  $r2 = ADDsrr_s $sp, 32, -1, $r0, 0 :: (load (s256) from %stack.0)
   and use:  $r1 = ADDrrr_s killed $r2, killed $r1, 0
 **into:  RET implicit $r1**
== Combine def  $r1 = ADDrrr_s killed $r1, killed $r2, 0
   and spill:  ADDrrs_s killed $r1, $r0, $sp, 32, -1, 0 :: (store (s256) into %stack.0)
   into:  ADDrrs_s killed $r1, killed $r2, $sp, 32, -1, 0
```

I think `$r1 = ADDsrr_s $sp, 32, -1, killed $r1, 0` should be here instead of  `RET implicit $r1`

2023-08-10 12:03 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  /// I.e. an instruction of form `add stack, r0, rN`.
This comment should be `add rN, r0, stack`?

2023-08-10 12:03 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +void SyncVMCombineAddressingMode::replaceIn0(
Is it worth to combine this with `replaceIn1` with boolean parameter that will tell whether we are replacing In0 or In1?

2023-08-10 12:03 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  if (!isSpillInst(Spill))
Maybe change this to assert, because we have already checked it on line 410?

2023-08-10 12:03 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +      // assert(find(DefUses, &MI) != DefUses.end() &&
Let's be more paranoid and add this check instead of assert. What do you think?

2023-08-10 12:03 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +      if (!all_of(DefUses, [&MI, DefMI, &UsesToUpdate,
Nice 🔥

2023-08-10 12:03 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  // assert(isReloadInst(Reload));
Leftover artifact?

2023-08-10 13:08 UTC, vladimirradosavljevic requested changes
~~Test that would fail if we don't check whether Spilled register is used between Def and Spill instructions.~~

2023-08-10 13:08 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +                      return areEqualStackSlots(SyncVM::out0Iterator(Def),
Since Def doesn't have to have AddressingMode (e.g. `spill_multiple` test), it seems to me that we are missing some checks.

If I understand correctly, we should check following:
1. Check if Spilled register is not used between Def and Spill instructions. Is this needed or we can leave this to `canCombineUse` function to cover it?
2. If Def uses stack slot, check if they are not equal. <- This is partially implemented, as we always assume in code that Def has Addressing Mode.
3. Check if spilled stack slot and stack slot from CurMI are not equal (this is maybe too paranoid)?

2023-08-10 13:55 UTC, PavelKopyl commented
> Test that would fail if we don't check whether Spilled register is used between Def and Spill instructions. Command: `llc -x mir -run-pass=syncvm-combine-addressing-mode -verify-machineinstrs test.mir -o test.S` Test:
> 
> ```
> --- |
> 
>   define void @foo(i256 %a, i256 %b, i256 %c) { ret void }
> 
> ...
> ---
> name:            foo
> tracksRegLiveness: true
> body:             |
>   bb.0:
>     liveins: $r1, $r2, $r3
>     NOPSP 2, 0, implicit-def $sp, implicit $sp
>     $r1 = ADDrrr_s killed $r1, killed $r2, 0
>     ADDrrs_s $r1, killed $r3, $sp, i256 0, -2, 0
>     ADDrrs_s killed $r1, $r0, $sp, 32, -1, 0
>     CALL $r0, @foo, implicit-def $r1, implicit-def dead $r2, implicit-def dead $r3, implicit-def dead $r4, implicit-def dead $r5, implicit-def dead $r6, implicit-def dead $r7, implicit-def dead $r8, implicit-def dead $r9, implicit-def dead $r10, implicit-def dead $r11, implicit-def dead $r12, implicit-def dead $r13, implicit-def dead $r14, implicit-def dead $r15, implicit-def dead $flags, implicit $sp
>     $r2 = ADDsrr_s $sp, 32, -1, $r0, 0
>     $r1 = ADDrrr_s killed $r2, killed $r1, 0
>     RET implicit $r1
> ```

Hm... I cannot reproduce the error here. Do you mean that after transformation we will have
` ADDrrs_s $r1, killed $r3, $sp, i256 0, -2, 0` without the definition of $r1?

2023-08-10 13:59 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  /// Return whether \p MI is a spill instruction.
It may be reasonable to move isReloadInst, isReloadInst to SynVMInstInfo if they are going to be used anywhere else.

2023-08-10 13:59 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  // It's expected that if there are more then one reaching def,
s/then/than/

2023-08-10 13:59 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +      // assert(find(DefUses, &MI) != DefUses.end() &&
I didn't get why this check is disabled? Because of sporadic fails?

2023-08-10 14:11 UTC, vladimirradosavljevic commented
> > Test that would fail if we don't check whether Spilled register is used between Def and Spill instructions. Command: `llc -x mir -run-pass=syncvm-combine-addressing-mode -verify-machineinstrs test.mir -o test.S` Test:
> > ```
> > --- |
> > 
> >   define void @foo(i256 %a, i256 %b, i256 %c) { ret void }
> > 
> > ...
> > ---
> > name:            foo
> > tracksRegLiveness: true
> > body:             |
> >   bb.0:
> >     liveins: $r1, $r2, $r3
> >     NOPSP 2, 0, implicit-def $sp, implicit $sp
> >     $r1 = ADDrrr_s killed $r1, killed $r2, 0
> >     ADDrrs_s $r1, killed $r3, $sp, i256 0, -2, 0
> >     ADDrrs_s killed $r1, $r0, $sp, 32, -1, 0
> >     CALL $r0, @foo, implicit-def $r1, implicit-def dead $r2, implicit-def dead $r3, implicit-def dead $r4, implicit-def dead $r5, implicit-def dead $r6, implicit-def dead $r7, implicit-def dead $r8, implicit-def dead $r9, implicit-def dead $r10, implicit-def dead $r11, implicit-def dead $r12, implicit-def dead $r13, implicit-def dead $r14, implicit-def dead $r15, implicit-def dead $flags, implicit $sp
> >     $r2 = ADDsrr_s $sp, 32, -1, $r0, 0
> >     $r1 = ADDrrr_s killed $r2, killed $r1, 0
> >     RET implicit $r1
> > ```
> 
> Hm... I cannot reproduce the error here. Do you mean that after transformation we will have ` ADDrrs_s $r1, killed $r3, $sp, i256 0, -2, 0` without the definition of $r1?

Currently, transformation wont happen because `areEqualStackSlots` will return true for Def that doesn't have Addressing Mode. Maybe this is intentional?
If we revisit that check, we are actually getting good generation of code as it would first generate spill, then stack reuse:
```
ADDrrs_s killed $r1, killed $r2, $sp, 32, -1, 0
ADDsrs_s $sp, 32, -1, killed $r3, $sp, i256 0, -2, 0
```
Sorry for the noise, will remove this test, but I think we shouldn't call `areEqualStackSlots` if Def doesn't have Addressing Mode, and this reordering could be fragile.

2023-08-10 14:38 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  void replaceIn1(MachineInstr &Base,
Will prefer to keep as is. The intent is to replace in1, swap is an implementation necessity because of addressing modes restriction. On a call-site a reader doesn't need to know this detail.

2023-08-10 14:40 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +                 std::next(Use->getIterator())->dump(););
Thanks for noticing!

2023-08-10 17:36 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  /// Return whether \p MI is a spill instruction.
I don't have any idea of any other pass using it. I prefer to move it when such a pass appear

2023-08-10 19:09 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +/// Implements a pass that combines combine instructions into one with more
removed

2023-08-10 19:09 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  /// Put the resulting instruction after \p Use.
Updated

2023-08-10 19:10 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  void replaceIn1(MachineInstr &Base,
Refactored as @vladimirradosavljevic suggested.

2023-08-10 19:10 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +                 std::next(Use->getIterator())->dump(););
Fixed

2023-08-10 19:10 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +void SyncVMCombineAddressingMode::replaceIn0(
Worth. Done.

2023-08-10 19:12 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  // assert(isReloadInst(Reload));
Yes, removed

2023-08-10 19:13 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  /// I.e. an instruction of form `add stack, r0, rN`.
Fixed

2023-08-10 19:13 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  // It's expected that if there are more then one reaching def,
Fixed

2023-08-10 20:02 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.025 ║
║ Best                                7.856 ║
║ Worst                              -0.324 ║
║ Total                               0.092 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.008 ║
║ Best                                7.049 ║
║ Worst                              -0.947 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.301 ║
║ Worst                              -0.050 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.245 ║
║ Best                                7.856 ║
║ Worst                               0.000 ║
║ Total                               0.465 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.090 ║
║ Best                                0.791 ║
║ Worst                               0.000 ║
║ Total                               0.136 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.005 ║
║ Best                                0.263 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-08-11 05:48 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  if (!isSpillInst(Spill))
Done

2023-08-11 06:27 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.025 ║
║ Best                                7.856 ║
║ Worst                              -0.324 ║
║ Total                               0.092 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.008 ║
║ Best                                7.049 ║
║ Worst                              -0.947 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.301 ║
║ Worst                              -0.050 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.245 ║
║ Best                                7.856 ║
║ Worst                               0.000 ║
║ Total                               0.465 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.090 ║
║ Best                                0.791 ║
║ Worst                               0.000 ║
║ Total                               0.136 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.005 ║
║ Best                                0.263 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-08-11 13:51 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +      // assert(find(DefUses, &MI) != DefUses.end() &&
Yes. Enabled after locality is checked.

2023-08-11 13:52 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +      // assert(find(DefUses, &MI) != DefUses.end() &&
Restored assert after locality is checked.

2023-08-11 14:26 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +                      return areEqualStackSlots(SyncVM::out0Iterator(Def),
Added check for Def's AM. 
As for (1) if I get it right you want to remove code duplication. Could you clarify how?

2023-08-11 15:02 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.025 ║
║ Best                                7.856 ║
║ Worst                              -0.324 ║
║ Total                               0.092 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.008 ║
║ Best                                7.049 ║
║ Worst                              -0.947 ║
║ Total                               0.004 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.301 ║
║ Worst                              -0.050 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.245 ║
║ Best                                7.856 ║
║ Worst                               0.000 ║
║ Total                               0.465 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.090 ║
║ Best                                0.791 ║
║ Worst                               0.000 ║
║ Total                               0.136 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.005 ║
║ Best                                0.263 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-08-11 15:30 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +                      return areEqualStackSlots(SyncVM::out0Iterator(Def),
Sorry, I made a little bit confusion here.

If I understand correctly, in order to safely combine Def with Spill, we need to check if `reg0/stack` and `reg1` are not defined or used between Def and Spill in the following example:
```
Def: inst reg0/stack, reg1, regDef
...
Spill: add regDef, r0, stackSpillSlot
```
After that, if there are more uses of `regDef` after Spill instruction, we are checking with `canCombineUse` to see whether we can reuse `stackSpillSlot` instead of `regDef`, and if that is true, we are performing this combine.
Is this correct?

I assume that LLVM will place Spill just after Def and these checks are not needed, but I'm more into paranoia and to check everything, just in case.

2023-08-11 19:20 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +                      return areEqualStackSlots(SyncVM::out0Iterator(Def),
1. That's right on what we check.
2. Spill and def aren't always adjacent. There might be uses in between.

2023-08-14 10:26 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +                      return areEqualStackSlots(SyncVM::out0Iterator(Def),
If I didn't miss something, here we need to call `areEqualStackSlots` for `CurMI` and `Spill` not for `CurMI` and `Def`, and I assume we need something like this:
```
  if (std::any_of(std::next(Def.getIterator()), Spill.getIterator(),
                  [&Spill](const MachineInstr &CurMI) {
                    if (SyncVM::hasSROutAddressingMode(CurMI) &&
                        areEqualStackSlots(SyncVM::out0Iterator(Spill),
                                           SyncVM::out0Iterator(CurMI)))
                      return true;
                    if (SyncVM::hasSRInAddressingMode(CurMI) &&
                        areEqualStackSlots(SyncVM::out0Iterator(Spill),
                                           SyncVM::in0Iterator(CurMI)))
                      return true;
                    return false;
                  }))
```
With the current implementation, we are missing following combine opportunity:
```
Command:
llc -x mir -run-pass=syncvm-combine-addressing-mode -verify-machineinstrs test.mir -o test.S

Test:
--- |

  define void @foo(i256 %a, i256 %b, i256 %c) { ret void }

...
---
name:            foo
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r1, $r2, $r3, $r4
    NOPSP 2, 0, implicit-def $sp, implicit $sp
    $r1 = ADDrrr_s killed $r1, killed $r2, 0
    ADDrrs_s killed $r4, killed $r3, $sp, i256 0, -2, 0
    ADDrrs_s killed $r1, $r0, $sp, 32, -1, 0
    RET

```

2023-08-14 21:23 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.025 ║
║ Best                                7.856 ║
║ Worst                              -0.324 ║
║ Total                               0.094 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.029 ║
║ Best                                7.049 ║
║ Worst                              -0.947 ║
║ Total                               0.015 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.003 ║
║ Best                                4.301 ║
║ Worst                              -0.050 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.247 ║
║ Best                                7.856 ║
║ Worst                               0.000 ║
║ Total                               0.471 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.104 ║
║ Best                                0.791 ║
║ Worst                               0.000 ║
║ Total                               0.144 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.005 ║
║ Best                                0.263 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-08-15 08:34 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +                      return areEqualStackSlots(SyncVM::out0Iterator(Def),
Thanks a lot for your attention! It's a bug, though because out0 of def is not a stack slot, it only inhibited optimization opportunities. Anyway I believe if we haven't started to review so thoroughly we haven't had noticed that bug.

2023-08-15 08:48 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +                      return areEqualStackSlots(SyncVM::out0Iterator(Def),
Oh, glad we spot it on time!

2023-08-15 08:49 UTC, vladimirradosavljevic approved these changes
LGTM. @PavelKopyl could you also approve it?

2023-08-15 08:49 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  if (!SyncVM::hasAnyOutAddressingMode(Def))
Maybe this is not needed as we are checking `SyncVM::hasRROutAddressingMode` on line 297?

2023-08-15 09:02 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.025 ║
║ Best                                7.856 ║
║ Worst                              -0.324 ║
║ Total                               0.094 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.029 ║
║ Best                                7.049 ║
║ Worst                              -0.947 ║
║ Total                               0.015 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.003 ║
║ Best                                4.301 ║
║ Worst                              -0.050 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.247 ║
║ Best                                7.856 ║
║ Worst                               0.000 ║
║ Total                               0.471 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.104 ║
║ Best                                0.791 ║
║ Worst                               0.000 ║
║ Total                               0.144 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.005 ║
║ Best                                0.263 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-08-15 09:37 UTC, PavelKopyl approved these changes
LGTM. Thank you!

2023-08-15 09:37 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  /// Put the resulting instruction after \p Base.
Nitpicking: As I see, this function actually puts the instruction before \Base. Could you please, check that? The same is true for 'mergeSelect'.

2023-08-15 09:38 UTC, PavelKopyl commented
> LGTM. @PavelKopyl could you also approve it?

@vladimirradosavljevic Thank you for exhaustive and detailed review!

2023-08-15 10:54 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  /// Put the resulting instruction after \p Base.
Fixed the wording

2023-08-15 10:54 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMCombineAddressingMode.cpp
> +  if (!SyncVM::hasAnyOutAddressingMode(Def))
Removed. Thanks.

2023-08-15 11:27 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.025 ║
║ Best                                7.856 ║
║ Worst                              -0.324 ║
║ Total                               0.094 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.029 ║
║ Best                                7.049 ║
║ Worst                              -0.947 ║
║ Total                               0.015 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.003 ║
║ Best                                4.301 ║
║ Worst                              -0.050 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.247 ║
║ Best                                7.856 ║
║ Worst                               0.000 ║
║ Total                               0.471 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.104 ║
║ Best                                0.791 ║
║ Worst                               0.000 ║
║ Total                               0.144 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.005 ║
║ Best                                0.263 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-08-16 14:29 UTC, merged