Refactor SyncVMBytesToCells pass
matter-labs/era-compiler-llvm pull request #273
Opened 2023-08-05 16:39 UTC by lialan

* refactor BytesToCells pass and modernize it
* eliminate early bytes to cells transformation
* updated test cases

2023-08-05 17:11 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-06 02:17 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-06 15:13 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-06 20:29 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-07 02:18 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-07 03:35 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-07 13:45 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +  bool handleCopyToPhyReg(MachineInstr &MI) const;
Worth documenting declarations.

2023-08-07 13:45 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +  void multiplyByCellSize(MachineInstr::mop_iterator Mop) const;
Perhaps [convert]toBytes / toCells more directly reflects the intent.

2023-08-07 13:45 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +  bool isCopyReturnValue(MachineInstr &MI) const;
const MI&?

2023-08-07 13:45 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +  void scalingHelper(MachineInstr::mop_iterator Mop, unsigned Opcode) const;
Nitpicking. doConvertion or something sounds more idiomatic and should start with a verb as having a side effect.

2023-08-07 13:45 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +  // from GEP. For constant operations, the base reg is the second operand;
Is it possible to avoid GEP assumption? Unless unavoidable it's good to support what arbitrary C program might have (to steal more tests in future).

2023-08-07 13:45 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +    // we are collecting arguments on machine level. To identify arguments,
We.
Thanks! I like this doc.

2023-08-07 13:45 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +         !SyncVM::out0Iterator(MI)->getReg().isVirtual() &&
isPhysical w/o negation is better.

2023-08-07 13:45 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +  MayContainCells.clear();
They must be default constructed by the spec, so clear is redundant.

2023-08-07 13:45 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +  void collectArgumentsAsRegisters(MachineFunction &MF);
I don't insist, but conceptually it collects some info and instead of doing a side effect, it might return as value, and the objects it fills together with accessors might be extracted into `ArgumentInfo` class or something alike.

2023-08-07 17:31 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-08 01:08 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-09 09:14 UTC, akiramenai requested changes

2023-08-09 09:14 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +/// LLVM will emit byte addressing for stack accesses, and on SyncVM the stack
will emit -> emits.

2023-08-09 09:14 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +/// space is addressed in cells (32 bytes per cell). Without this pass the
Nitpicking. Perhaps it makes sense to put the purpose first and then explain what the pass is doing. And the second sentence here largely duplicates the first one. It also makes sense to mention precondition we had discussed, although all addresses are in bytes before the pass, it's guaranteed that they are cell aligned in MIR. All necessary work on unaligned access in stack is done on IR and legalisation phases.

2023-08-09 09:14 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +  bool convertStackAccesses(MachineFunction &MF);
When I ask for documenting declarations, I mean to put general descriptions on what functions do and why here. Technically a definition is a declaration in terms of C++ spec, yet when the term is used it usually means a declaration which is not the definition.
Also if unclear it's expected to document the signature, for this particular function what does the return value means.
While on the definition side I expect to see clarification of particular implementation like why we skipped on CALL in the previous iteration of this review.

2023-08-09 09:14 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +MachineInstr::mop_iterator getStackAccess(MachineInstr &MI) {
I doesn't look to me as universal as the rest of mop iterators. I I suggest to move it inside bytes to cells pass.

2023-08-09 09:14 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +      MI.getOpcode() == SyncVM::ADDframe ||
It doesn't looks good to me to provide only `out0Iterator` for the selected pseudos. Even manual handling is better than that.

2023-08-09 09:14 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +  if (MO0Reg.isReg()) {
Worth documenting SP-relative stack address.

2023-08-09 09:14 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +    if (DefMI->getOpcode() == SyncVM::SHLxrr_s &&
Nitpicking: worth extracting into a function to simplify reading `convertStackMachineInstr`. It often ok just to know that we optimize shl+shr w/o knowing the particular details and continue reading `convertStackMachineInstr` without the distraction.

2023-08-09 09:14 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +      auto DefIt = [DefBB, &MI]() {
Doesn't need to be a lambda anymore. Doesn't need to use find. It's just MI.getIterator.
Could we kindly try to not to overlook such outrageous redundancy. I realise that I was a person who wrote it one day because of stupidity (shame for me), but it's expected from a refactoring patch to really eliminate such foolish code.

2023-08-09 09:14 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +      BuildMI(*DefBB, DefIt, MI.getDebugLoc(), TII->get(SyncVM::SHRxrr_s))
It worth mentioning that we actually have 2 sensible options here in terms where to put the conversion instruction. And earlybytestocells proved to be worse. It also makes sense to double check that fact. The pass was implemented long ago when we hadn't as many benchmarks as we have now.

2023-08-09 15:19 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +  bool convertStackAccesses(MachineFunction &MF);
Ooops, sorry this function is not being used. removed.

2023-08-09 15:40 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +      MI.getOpcode() == SyncVM::ADDframe ||
@akiramenai I think this reveals that the original code is bugged. We should swap the testing order:
1. first try to test if it is SR out addressing mode, return `in1Iterator(MI) + argumentSize(ArgumentKind::In1, MI);`, because it is the only case where we could have an out in non-def operands.
2. then the rest of the cases, where defs are at the beginning of the code.

2023-08-09 15:49 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +MachineInstr::mop_iterator getStackAccess(MachineInstr &MI) {
Okay, moved them inside the pass.

2023-08-09 15:49 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +    if (DefMI->getOpcode() == SyncVM::SHLxrr_s &&
done.

2023-08-09 15:51 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +      auto DefIt = [DefBB, &MI]() {
My fault not looking closely on such code. It is actually simplified after eliminating early conversions.

2023-08-09 15:53 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +/// LLVM will emit byte addressing for stack accesses, and on SyncVM the stack
done.

2023-08-09 16:04 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +  if (MO0Reg.isReg()) {
done.

2023-08-09 16:10 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +      BuildMI(*DefBB, DefIt, MI.getDebugLoc(), TII->get(SyncVM::SHRxrr_s))
Let's see if the case still holds: https://github.com/matter-labs/compiler-llvm/pull/276

2023-08-09 16:50 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-09 16:51 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +      BuildMI(*DefBB, DefIt, MI.getDebugLoc(), TII->get(SyncVM::SHRxrr_s))
@akiramenai well we have slight regression, but it does not affect benchmark numbers: https://github.com/matter-labs/compiler-llvm/pull/276#issuecomment-1671779982

2023-08-09 18:06 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +/// space is addressed in cells (32 bytes per cell). Without this pass the
Updated.

2023-08-10 14:27 UTC, akiramenai requested changes
Please update the tests

2023-08-10 14:27 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.h
> +/// accesses, return an empty iterator.
It still a part of Instruction info. Haven't we agreed to move it to the pass?

2023-08-10 14:27 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.h
> +
redundant empty line

2023-08-10 14:27 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +  /// accesses, return an empty iterator.
empty -> default constructed

2023-08-10 14:27 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/bytes2cells.ll
> +;	CHECK: shr.s   5, r[[REG]], r[[REG]]
Redundant spaces / tabs. Also please fix formatting everywhere in the file.

2023-08-10 14:27 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/bytes2cells.ll
> +; CHECK: mul
It looks like the test hasn't been updated since we switch to shifts. Here and below.

2023-08-10 14:27 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/compound.ll
> +; CHECK-NOT: div.s 32, r1, r1, r0
shift?

2023-08-10 14:32 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +      MI.getOpcode() == SyncVM::ADDframe ||
Sorry, I didn't get. Could you illustrate the bug with an example?

2023-08-10 14:33 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +/// space is addressed in cells (32 bytes per cell). Without this pass the
Thanks

2023-08-10 14:33 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +  if (MO0Reg.isReg()) {
I don't see in the code. I meant documenting the ifstmt.

2023-08-10 18:45 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.h
> +/// accesses, return an empty iterator.
duh, it was moved, just the function declaration was still there. removed.

2023-08-10 19:21 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +      MI.getOpcode() == SyncVM::ADDframe ||
Not all register out instructions is included in the checking of `hasRROutAddressingMode`. for example, pseudos and load instructions are not.

It is safer to check the reverse condition instead. Also it is canonical to put def in the front of operand list, SR addressing mode instructions are the exception here.

2023-08-10 19:28 UTC, lialan commented on llvm/test/CodeGen/SyncVM/bytes2cells.ll
> +;	CHECK: shr.s   5, r[[REG]], r[[REG]]
it was a tab! removed.

2023-08-10 19:29 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +  /// accesses, return an empty iterator.
done

2023-08-10 19:30 UTC, lialan commented on llvm/test/CodeGen/SyncVM/compound.ll
> +; CHECK-NOT: div.s 32, r1, r1, r0
reverted and check shift instead. This was actually from passing pointers in cells attempt.

2023-08-10 19:31 UTC, lialan commented on llvm/test/CodeGen/SyncVM/bytes2cells.ll
> +; CHECK: mul
It is actually from expanding `ADDframe` so not in this pass. I tried to change it into shift left, but there is a failure in moonswap. 

So I reverted the change and created ticket https://linear.app/matterlabs/issue/CPR-1261/mul-by-32-and-shift-left-by-5-equivalency to track it separately.

2023-08-10 19:31 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.h
> +
removed

2023-08-10 20:05 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMBytesToCells.cpp
> +  if (MO0Reg.isReg()) {
I documented the context.sp part....

Any way also documented this part as well.

2023-08-11 00:41 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-11 02:04 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-11 09:33 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMInstrInfo.cpp
> +      MI.getOpcode() == SyncVM::ADDframe ||
It's indeed only cover the mappings and select. Other instructions aren't supposed to be used with these checks. Perhaps needs enforcement with assert.

2023-08-11 09:34 UTC, akiramenai approved these changes
There are still formatting inconsistencies in tests. Could you fix and check it with GitHub interface before merging?

2023-08-11 15:27 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-11 19:40 UTC, merged