[SyncVM] Add '__sha3' wrapper to the stdlib.
matter-labs/era-compiler-llvm pull request #285
Opened 2023-08-23 12:23 UTC by PavelKopyl

2023-08-23 12:28 UTC, hedgar2017 requested changes
LGTM! Let me test.

2023-08-23 12:36 UTC, PavelKopyl commented
Sorry, I've missed two failed tests. Will fix now.

2023-08-23 12:58 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-23 13:42 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-24 09:38 UTC, hedgar2017 requested changes

2023-08-24 09:38 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define void @__exit_revert(i256 %0, i256 %1, i256 %2) #2 personality ptr @__personality {
Is there `__exit_return` as well?

2023-08-24 09:38 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define void @__cxa_throw(ptr %addr, ptr, ptr) noinline {
Can we do it later?
Not sure if the Rust library supports it.

2023-08-24 09:39 UTC, hedgar2017 requested changes

2023-08-24 09:39 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define i256 @__keccak256(i256 %0, i256 %1, i1 %throw_at_failure) #1 personality ptr @__personality {
Let's rename to `__sha3` to match EVM.

2023-08-24 10:08 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define void @__cxa_throw(ptr %addr, ptr, ptr) noinline {
Anyway, it should not crash - that `ptr` type should match any pointer.

2023-08-24 10:09 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define void @__cxa_throw(ptr %addr, ptr, ptr) noinline {
Where the CI error is coming from?
```
warning: ptr type is only supported in -opaque-pointers mode
define void @__cxa_throw(ptr %addr, ptr, ptr) noinline {
                         ^
Unable to parse syncvm-runtime.ll, syncvm-stdlib.ll: error: expected type
define void @__cxa_throw(ptr %addr, ptr, ptr) noinline {
```

2023-08-24 13:36 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define void @__exit_revert(i256 %0, i256 %1, i256 %2) #2 personality ptr @__personality {
Thanks. I've added it, though it's not used.

2023-08-24 13:42 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define void @__cxa_throw(ptr %addr, ptr, ptr) noinline {
OK, I returned back the typed pointers. The problem in the CI the mosts probably means that we have a mixture of typed and opaque pointers in LLVM IR.  I think we should completely switch to opaque pointers. As I understand, Rust library supports the, because LLVM IR after zksloc contains only opaque pointers.

2023-08-24 13:42 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define i256 @__keccak256(i256 %0, i256 %1, i1 %throw_at_failure) #1 personality ptr @__personality {
OK, done.

2023-08-24 14:19 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-24 15:13 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define void @__cxa_throw(ptr %addr, ptr, ptr) noinline {
So where the error is coming from and how to use this ` -opaque-pointers` mode?

2023-08-24 15:15 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define void @__cxa_throw(ptr %addr, ptr, ptr) noinline {
Currently I am still using pointer types. The only restriction is that I cannot get their type from the LLVM IR repr, so I'm keeping this info separately on FE.

2023-08-24 16:05 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define void @__cxa_throw(ptr %addr, ptr, ptr) noinline {
> Currently I am still using pointer types. The only restriction is that I cannot get their type from the LLVM IR repr, so I'm keeping this info separately on FE.
>So where the error is coming from and how to use this  -opaque-pointers mode?

Got it. Hm.. It needs to be checked what LLVM API is used by Rust, but I think LLVM automatically converts typed pointers to opaque ones (at least Documentation says about this). 
LLVM can work in two modes: 1) typed pointers, 2) opaque pointers.
In the first mode only typed pointers are allowed. In the the second all the pointers should  be opaque. This is a default mode. If LLVM IR contains typed pointers, opaque mode is automatically disabled. In case we have a mixture of typed and opaque pointers we get the error above. To be honest, I cannot find from the log which test causes it, apparently we get LLVM IR like below:
```
define i32* @func(i32* %p) noinline {
  %p2 = getelementptr i32, i32* %p, i32 1
  ret i32* %p2
}

define void @test(ptr %p) {
  %p2 = call ptr @func(ptr %p)
  store i32 127, ptr %p2 
  ret void               
}     
```
Here LLVM switches to typed mode and raises the error, because it expects the pointer type in the expression `ptr %p` instead on just 'ptr'.

To overcome this issue we need to use '-opaque-pointers', it forces to convert typed pointer to opaque one.

```
opt -O2 -S --mtriple=syncvm  ptr.ll -opaque-pointers
...
define ptr @func(ptr readnone %p) local_unnamed_addr #0 {
  %p2 = getelementptr i32, ptr %p, i256 1
  ret ptr %p2
}

; Function Attrs: mustprogress nofree norecurse nosync willreturn writeonly
define void @test(ptr writeonly %p) local_unnamed_addr #1 {
  %p2 = tail call ptr @func(ptr %p)
  store i32 127, ptr %p2, align 4
  ret void
}
```

2023-08-24 16:08 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define void @__cxa_throw(ptr %addr, ptr, ptr) noinline {
Thanks a lot for the explanation!
So I have to either convert all pointers to opaque or pass this option to LLVM C interface which can be also problematic.
It's totally unrelated to our current activity so let's do it in another patch.

2023-08-24 16:15 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define void @__cxa_throw(ptr %addr, ptr, ptr) noinline {
> Thanks a lot for the explanation!
> So I have to either convert all pointers to opaque or pass this option to LLVM C interface which can be also problematic.
> It's totally unrelated to our current activity so let's do it in another patch.

You are right. Yep, this is unrelated activity. I just thought it could be done iteratively, but no, we need to fix all (runtime, stdlib and LIT tests) instantly.

2023-08-25 10:03 UTC, hedgar2017 requested changes

2023-08-25 10:03 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define void @__exit_revert(i256 %0, i256 %1, i256 %2) #1 personality i32()* @__personality {
One last change I overlooked: let's rename it to just `__revert`.

2023-08-25 10:03 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define void @__exit_return(i256 %0, i256 %1, i256 %2) #1 personality i32()* @__personality {
One last change I overlooked: let's rename it to just `__return`.

2023-08-25 10:30 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define void @__exit_revert(i256 %0, i256 %1, i256 %2) #1 personality i32()* @__personality {
OK.

2023-08-25 11:14 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +define void @__exit_return(i256 %0, i256 %1, i256 %2) #1 personality i32()* @__personality {
Added tests to check elimination of the last argument where this is possible.

2023-08-25 11:47 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-25 15:35 UTC, hedgar2017 approved these changes

2023-08-25 16:19 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-27 07:27 UTC, akiramenai commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +  %3 = tail call i256 @llvm.umin.i256(i256 %0, i256 4294967295)
Can we check if we can wrap repeated calculations into a function w/o losing performance? If so, let's avoid code duplication.

2023-08-27 07:27 UTC, akiramenai commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +  %abi_data_offset_and_length = or i256 %abi_data_input_length_shifted, %abi_data_input_offset_shifted
Nitpicking: consistency. Could we stick with either `or` or `add` everywhere to combine "bit fields" into a single i256.

2023-08-27 07:27 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/sha3-arg3-elimination3.ll
> +; FIXME: we may need to perform code duplication of the __sha3
May we stick with TODO ticket number? And create a ticket?

2023-08-27 09:09 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +  %3 = tail call i256 @llvm.umin.i256(i256 %0, i256 4294967295)
Worth making a try.

2023-08-28 14:14 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +  %3 = tail call i256 @llvm.umin.i256(i256 %0, i256 4294967295)
Thanks. Done.

2023-08-28 14:14 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/syncvm-stdlib.ll
> +  %abi_data_offset_and_length = or i256 %abi_data_input_length_shifted, %abi_data_input_offset_shifted
Done.

2023-08-28 14:17 UTC, PavelKopyl commented on llvm/test/CodeGen/SyncVM/sha3-arg3-elimination3.ll
> +; FIXME: we may need to perform code duplication of the __sha3
I removed this TODO, as actually this is not an issue. As @hedgar2017 explained, in an LLVM IR module we either use revert or throw, but not their mix.

2023-08-28 14:50 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-29 12:25 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-30 12:15 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-08-30 15:59 UTC, merged