Implementation of stdlib functions
matter-labs/era-compiler-llvm pull request #290
Opened 2023-08-30 16:17 UTC by PavelKopyl

Implementation of stdlib functions

2023-08-30 16:53 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                2.410 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                5.769 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                2.817 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-09-01 02:14 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.277 ║
║ Best                               22.404 ║
║ Worst                             -211.429 ║
║ Total                              -0.177 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                5.769 ║
║ Worst                             -1255.814 ║
║ Total                              -0.033 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                2.817 ║
║ Worst                             -580.922 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.054 ║
║ Best                               22.404 ║
║ Worst                             -12.336 ║
║ Total                               0.083 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.369 ║
║ Best                                0.000 ║
║ Worst                             -17.355 ║
║ Total                              -3.314 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.127 ║
║ Best                                0.174 ║
║ Worst                             -12.345 ║
║ Total                              -0.138 ║
╚═══════════════════════════════════════════╝

```

2023-09-01 08:31 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.277 ║
║ Best                               22.404 ║
║ Worst                             -211.429 ║
║ Total                              -0.177 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                5.769 ║
║ Worst                             -1255.814 ║
║ Total                              -0.033 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                2.817 ║
║ Worst                             -580.922 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.054 ║
║ Best                               22.404 ║
║ Worst                             -12.336 ║
║ Total                               0.083 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.369 ║
║ Best                                0.000 ║
║ Worst                             -17.355 ║
║ Total                              -3.314 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.127 ║
║ Best                                0.174 ║
║ Worst                             -12.345 ║
║ Total                              -0.138 ║
╚═══════════════════════════════════════════╝

```

2023-09-01 10:55 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.078 ║
║ Best                               22.404 ║
║ Worst                             -12.336 ║
║ Total                              -0.067 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.035 ║
║ Best                                5.769 ║
║ Worst                             -23.124 ║
║ Total                              -0.017 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.033 ║
║ Best                                2.817 ║
║ Worst                             -28.162 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.031 ║
║ Best                               22.404 ║
║ Worst                             -12.336 ║
║ Total                               0.054 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.340 ║
║ Best                                5.755 ║
║ Worst                             -17.355 ║
║ Total                              -3.270 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.124 ║
║ Best                                0.174 ║
║ Worst                             -12.345 ║
║ Total                              -0.136 ║
╚═══════════════════════════════════════════╝

```

2023-09-01 12:54 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.078 ║
║ Best                               22.404 ║
║ Worst                             -12.336 ║
║ Total                              -0.067 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.035 ║
║ Best                                5.769 ║
║ Worst                             -23.124 ║
║ Total                              -0.017 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.033 ║
║ Best                                2.817 ║
║ Worst                             -28.162 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.031 ║
║ Best                               22.404 ║
║ Worst                             -12.336 ║
║ Total                               0.054 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.340 ║
║ Best                                5.755 ║
║ Worst                             -17.355 ║
║ Total                              -3.270 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.124 ║
║ Best                                0.174 ║
║ Worst                             -12.345 ║
║ Total                              -0.136 ║
╚═══════════════════════════════════════════╝

```

2023-09-01 13:41 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.052 ║
║ Best                                2.410 ║
║ Worst                             -49.977 ║
║ Total                              -0.070 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.015 ║
║ Best                                5.769 ║
║ Worst                             -11.129 ║
║ Total                              -0.005 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.015 ║
║ Best                                2.817 ║
║ Worst                             -13.149 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.179 ║
║ Best                                0.000 ║
║ Worst                             -49.977 ║
║ Total                              -0.415 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.230 ║
║ Best                                0.000 ║
║ Worst                             -11.129 ║
║ Total                              -0.831 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.054 ║
║ Best                                0.000 ║
║ Worst                              -5.642 ║
║ Total                              -0.036 ║
╚═══════════════════════════════════════════╝

```

2023-09-01 14:25 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.078 ║
║ Best                               22.404 ║
║ Worst                             -12.336 ║
║ Total                              -0.067 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.035 ║
║ Best                                5.769 ║
║ Worst                             -23.124 ║
║ Total                              -0.017 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.033 ║
║ Best                                2.817 ║
║ Worst                             -28.162 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.031 ║
║ Best                               22.404 ║
║ Worst                             -12.336 ║
║ Total                               0.054 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.340 ║
║ Best                                5.755 ║
║ Worst                             -17.355 ║
║ Total                              -3.270 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.124 ║
║ Best                                0.174 ║
║ Worst                             -12.345 ║
║ Total                              -0.136 ║
╚═══════════════════════════════════════════╝

```

2023-09-01 15:10 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.027 ║
║ Best                               22.404 ║
║ Worst                             -12.336 ║
║ Total                              -0.014 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.020 ║
║ Best                                5.769 ║
║ Worst                             -14.583 ║
║ Total                              -0.007 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                               -0.018 ║
║ Best                                2.817 ║
║ Worst                             -12.602 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.041 ║
║ Best                               22.404 ║
║ Worst                             -12.336 ║
║ Total                               0.063 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.099 ║
║ Best                                5.755 ║
║ Worst                             -12.772 ║
║ Total                              -1.372 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.058 ║
║ Best                                0.174 ║
║ Worst                              -8.502 ║
║ Total                              -0.049 ║
╚═══════════════════════════════════════════╝

```

2023-09-01 16:17 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.000 ║
║ Best                                2.410 ║
║ Worst                             -12.426 ║
║ Total                              -0.004 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                5.769 ║
║ Worst                              -2.514 ║
║ Total                              -0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                2.817 ║
║ Worst                              -2.535 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.038 ║
║ Best                                0.297 ║
║ Worst                             -12.426 ║
║ Total                              -0.090 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.003 ║
║ Best                                0.006 ║
║ Worst                              -1.319 ║
║ Total                              -0.031 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.001 ║
║ Best                                0.001 ║
║ Worst                              -0.234 ║
║ Total                              -0.001 ║
╚═══════════════════════════════════════════╝

```

2023-09-01 18:07 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                2.410 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                5.769 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                2.817 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-09-02 09:36 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                2.410 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                5.769 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                2.817 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-09-06 11:30 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                2.410 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                5.769 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                2.817 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-09-06 15:33 UTC, PavelKopyl commented
Please, note:
1. [[SyncVM] Add implementation of '__(div|sdiv|mod|smod)'](https://github.com/matter-labs/compiler-llvm/pull/290/commits/6360410dadbaaa795c21c734a02d5eda4ff054d2) has been already reviewed and approved. 
2. [[SyncVM] Add '__sha3' wrapper to the stdlib.](https://github.com/matter-labs/compiler-llvm/pull/290/commits/3da94f740534944fee1d8461e4d939f52a44b6a9) has been reviewed and also approved, but I slightly updated it according to there review notes.

2023-09-06 15:39 UTC, hedgar2017 approved these changes

2023-09-07 13:03 UTC, akiramenai requested changes
I haven't checked the tests assuming they are borrowed.

2023-09-07 13:03 UTC, akiramenai commented on llvm/lib/Analysis/ConstantFolding.cpp
> +static Constant *ConstantFoldSHLCall(Type *Ty, const APInt &Shift,
Could you explain why Shift > 255 doesn't reach here?

2023-09-07 13:03 UTC, akiramenai commented on llvm/lib/Analysis/ConstantFolding.cpp
> +static Constant *ConstantFoldByteCall(Type *Ty, const APInt &ByteIdx,
Same for ByteIdx > 31.

2023-09-07 13:03 UTC, akiramenai commented on llvm/lib/Target/SyncVM/CMakeLists.txt
> +  LTO
?

2023-09-07 13:03 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMLinkRuntime.cpp
> +    const StringSet<> LibFuncsCanBeInlined = {
Also could we add a todo and a ticket here. I don't see why should we decide it here instead of inliner, i.e. what is so special for sys lib functions in terms of whether to inline. IMO, better to tune inliner for all functions if we aren't satisfied with Os/Oz rather that for hand picked ones here.

2023-09-07 13:03 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMLinkRuntime.cpp
> +        if (!F.hasFnAttribute(Attribute::MinSize))
Checks are redundant, attributes are sets.

2023-09-07 13:03 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMLinkRuntime.cpp
> +    const StringSet<> LibFuncsCanBeInlined = {
I also really dislike listing function names. Can we use an attribute or something to distinguish?

2023-09-07 13:03 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/sha3-arg3-elimination.ll
> +target datalayout = "E-p:256:256-i8:256:256:256-i256:256:256-S32-a:256:256"
Nitpicking: Can we come up with something more descriptive than 1, 2, 3 in filename?

2023-09-07 13:03 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/constant-folding-earlycse.ll
> +declare i256 @__div(i256, i256) #0
Nitpicking: I suggest to split the file by testing functions, otherwise it's way too long.

2023-09-07 13:03 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMLinkRuntime.cpp
> +    const StringSet<> LibFuncsCanBeInlined = {
Finally, have we measured the effect of this particular piece of code?

2023-09-07 13:47 UTC, PavelKopyl commented on llvm/lib/Analysis/ConstantFolding.cpp
> +static Constant *ConstantFoldSHLCall(Type *Ty, const APInt &Shift,
Actually we can have Shift > 255 here, but I rely on APInt::shl(const APInt &ShiftAmt) implementation that returns 0 in this case. It's done by:
1. limiting the shift amount by the bitwidth
` *this <<= (unsigned)shiftAmt.getLimitedValue(BitWidth);`
2. using tcShiftLeft() function that has not limits in the short amount

OK, I'll add explicit handling of this case to make the code more clear.

2023-09-07 13:52 UTC, PavelKopyl commented on llvm/lib/Analysis/ConstantFolding.cpp
> +static Constant *ConstantFoldByteCall(Type *Ty, const APInt &ByteIdx,
Please, see the explanation above.
OK, I'll add explicit handling of this case.

2023-09-07 14:36 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/CMakeLists.txt
> +  LTO
Thank you for pointing this.  'LTO' actually needs to be replaced with 'Passes' library.

This  required to avoid linkage error: 
```
Undefined symbols for architecture arm64:
  "llvm::OptimizationLevel::Oz", referenced from:
      llvm::SyncVMLinkRuntimePass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) in libLLVMSyncVMCodeGen.a(SyncVMLinkRuntime.cpp.o)
```

'OptimizationLevel::Oz' is defined in libLLVMPasses.a.

2023-09-07 14:42 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMLinkRuntime.cpp
> +        if (!F.hasFnAttribute(Attribute::MinSize))
OK, thanks.

2023-09-07 14:42 UTC, PavelKopyl commented on llvm/test/CodeGen/SyncVM/sha3-arg3-elimination.ll
> +target datalayout = "E-p:256:256-i8:256:256:256-i256:256:256-S32-a:256:256"
Sure, will do.

2023-09-07 14:43 UTC, PavelKopyl commented on llvm/test/CodeGen/SyncVM/constant-folding-earlycse.ll
> +declare i256 @__div(i256, i256) #0
Yep, now I also want to do this.

2023-09-07 17:49 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMLinkRuntime.cpp
> +    const StringSet<> LibFuncsCanBeInlined = {
I'll try to answer all the 3 questions.
First, I'd like to explain the motivation behind this patch.
Originally (before moving runtime lib functionality to BE), FE were emitting stdlib functions by itself. 
Some of these functions were emitted as function definitions, other were used in-place (inlined). It's interesting that such kind of inlining was absolute - it didn't depend on the optimization level.
Also, at the 'Oz' optimization level FE were adding 'noinline' attribute to the function definitions from stdlib; and 'minsize' + 'optforsize' attributes for all other functions. Such a distribution of attributes gave good (balanced) size/perf results. So, it was FE who partially took responsibility over controll of inlining. My goal was just to mimic this behavior somehow in order to not cause size/perf regression after moving runtime functionality to stdlib.
@hedgar2017, is that right?
I think that playing with heuristics of inliner will be harder, because it's easy to break them. By the way, 'Oz' doesn't prevent inlining.
'LibFuncsCanBeInlined' contains functions that should not be inlined at 'Oz' opt level. To be honest, I do not know how to make this better. Using speciall attribytes? But their semantic will be quite strange: "do not prevent inlining of this function at Oz".  Instead of functions names I could use enum, like 'LibFunc_xvm_shl'. Will it be better? 

>have we measured the effect of this particular piece of code?

My first goal was not to cause size/perf regressions in this PR. Actuall performance numbers are measured on both FE+BE patches. Please, see [PR-303](https://github.com/matter-labs/compiler-tester/pull/303).

2023-09-07 18:55 UTC, akiramenai commented on llvm/lib/Analysis/ConstantFolding.cpp
> +static Constant *ConstantFoldSHLCall(Type *Ty, const APInt &Shift,
What confused me is https://llvm.org/doxygen/APInt_8h_source.html#l00763. And `shl` calls it. Perhaps the assert was added in newer LLVM - I haven't checked.

2023-09-07 19:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMLinkRuntime.cpp
> +    const StringSet<> LibFuncsCanBeInlined = {
I would say that attribute name isn't more strange than the logic itself. But actually the inverse attribute sounds well enough: `noinline-oz`.
As for the rest I agree to start with the logic as literally close to the FE's one as possible, but I still would vote for a TODO + a ticket. Handpicking some library functions to not to be inlined is weird anyway. What if there is the only callsite for a function in a contract? Still `noinline`?

2023-09-08 05:57 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/SyncVMLinkRuntime.cpp
> +    const StringSet<> LibFuncsCanBeInlined = {
@PavelKopyl thanks, everything you said is correct.

Indeed FE emits these attributes for Mz as it has proven to give much better size. FE is unable to check how many calls are there - I believe it's more of a task for LLVM.
Maybe the situation has changed since then, so I strongly support the follow-up ticket to play with attributes.

2023-09-08 05:58 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/SyncVMLinkRuntime.cpp
> +    const StringSet<> LibFuncsCanBeInlined = {
For our stdlib, we should now emit `noinline` for **all** functions in the Oz mode.

2023-09-08 10:21 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMLinkRuntime.cpp
> +    const StringSet<> LibFuncsCanBeInlined = {
> For our stdlib, we should now emit noinline for all functions in the Oz mode.

@hedgar2017, sure I'll do this (this will even simplify the logic of this patch), but that will probably cause perf regressions in the Oz mode, because originally FE were inlining most of this functions. Is it OK?

2023-09-08 10:42 UTC, PavelKopyl commented on llvm/lib/Analysis/ConstantFolding.cpp
> +static Constant *ConstantFoldSHLCall(Type *Ty, const APInt &Shift,
You are right, there is an assertion there (even in our llvm version), but that's is not a problem, because actually call stack is following:
1. `APInt shl(const APInt &ShiftAmt)`, it doesn't check anything and just calls the following function:
2.
```
 APInt &APInt::operator<<=(const APInt &shiftAmt) {                
  // It's undefined behavior in C to shift by BitWidth or greater.
  *this <<= (unsigned)shiftAmt.getLimitedValue(BitWidth);
  return *this;                
} 
```
This very function limits shift value to 256 if it exceeds 256. 256 - is still a bad value, but this case is handled by the next function.
3. 
  ```
APInt &operator<<=(unsigned ShiftAmt) {                         
    assert(ShiftAmt <= BitWidth && "Invalid shift amount");       
    if (isSingleWord()) {                                
      if (ShiftAmt == BitWidth)
        U.VAL = 0;   
      else                        
        U.VAL <<= ShiftAmt;                 
      return clearUnusedBits();                
    }                                                             
    shlSlowCase(ShiftAmt);                              
    return *this;                              
  }                          
```  

Again, I'm not insisting on relying on this implementation, I'll add handling of this case directly to ConstantFoldSHLCall.

2023-09-08 11:00 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/SyncVMLinkRuntime.cpp
> +    const StringSet<> LibFuncsCanBeInlined = {
Yes. FE's policy for this was mostly random and historical, so it's an activity for another task.

2023-09-08 13:27 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMLinkRuntime.cpp
> +    const StringSet<> LibFuncsCanBeInlined = {
@hedgar2017 I just curious, why do we not put 'minsize' and 'optforsize' attributes also on stdlib functions?
@akiramenai I removed the 'LibFuncsCanBeInlined' set, as we need to put 'noinline' attribute on all the stdlib functions, so this isn't a problem anymore.

2023-09-08 13:30 UTC, PavelKopyl commented on llvm/lib/Analysis/ConstantFolding.cpp
> +static Constant *ConstantFoldSHLCall(Type *Ty, const APInt &Shift,
@akiramenai I've tried to add explicit handling of the case Shift > 255 to ConstantFoldSHLCall and other functions, but I realized this just duplicated the functionality of the corresponding APInt functions. I suggest just add comments, explaining why does this work as expected. Is it fine for you?

2023-09-08 14:08 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.276 ║
║ Best                               22.404 ║
║ Worst                             -211.429 ║
║ Total                              -0.172 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                5.769 ║
║ Worst                             -1255.814 ║
║ Total                              -0.034 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                 -inf ║
║ Best                                2.817 ║
║ Worst                             -580.922 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.098 ║
║ Best                               22.404 ║
║ Worst                              -2.457 ║
║ Total                               0.184 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                               -0.367 ║
║ Best                                0.000 ║
║ Worst                             -17.523 ║
║ Total                              -3.385 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                               -0.126 ║
║ Best                                0.174 ║
║ Worst                             -12.395 ║
║ Total                              -0.139 ║
╚═══════════════════════════════════════════╝

```

2023-09-08 16:19 UTC, hedgar2017 requested changes
Hmm, such a cycle regression is bad indeed.
Let me run the FE benchmark.

2023-09-08 16:57 UTC, akiramenai commented on llvm/lib/Analysis/ConstantFolding.cpp
> +static Constant *ConstantFoldSHLCall(Type *Ty, const APInt &Shift,
Yes

2023-09-11 14:33 UTC, PavelKopyl commented
> Hmm, such a cycle regression is bad indeed.
> Let me run the FE benchmark.

I think the regression is mostly caused by not inlining relatively small functions like shift operations.

2023-09-11 16:14 UTC, hedgar2017 commented
> > Hmm, such a cycle regression is bad indeed.
> 
> > Let me run the FE benchmark.
> 
> 
> 
> I think the regression is mostly caused by not inlining relatively small functions like shift operations.

Yes, let's inline them back.

2023-09-12 18:51 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                2.410 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                5.769 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                2.817 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-09-13 12:47 UTC, akiramenai approved these changes
LGTM, thanks

2023-09-13 12:50 UTC, hedgar2017 requested changes
Nice.
Please squash!

2023-09-13 15:10 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                2.410 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                5.769 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                2.817 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-09-13 15:13 UTC, merged