[SyncVM] Support modeling storage operations as memory
matter-labs/era-compiler-llvm pull request #292
Opened 2023-09-05 14:00 UTC by vladimirradosavljevic

2023-09-05 14:34 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.359 ║
║ Best                               41.026 ║
║ Worst                             -18.121 ║
║ Total                               0.363 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               54.545 ║
║ Worst                             -16.993 ║
║ Total                               0.600 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.184 ║
║ Best                               33.236 ║
║ Worst                             -16.508 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.942 ║
║ Best                               32.258 ║
║ Worst                              -0.886 ║
║ Total                               0.238 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.010 ║
║ Best                                4.040 ║
║ Worst                              -1.980 ║
║ Total                               0.692 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.041 ║
║ Best                                1.881 ║
║ Worst                              -0.005 ║
║ Total                               0.019 ║
╚═══════════════════════════════════════════╝

```

2023-09-07 19:06 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.741 ║
║ Best                               89.676 ║
║ Worst                             -248.980 ║
║ Total                               0.795 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -22.917 ║
║ Total                               0.703 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.321 ║
║ Best                               99.558 ║
║ Worst                             -16.508 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.093 ║
║ Best                               32.258 ║
║ Worst                             -63.958 ║
║ Total                               0.465 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.127 ║
║ Best                                9.023 ║
║ Worst                              -1.980 ║
║ Total                               0.804 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.053 ║
║ Best                                2.250 ║
║ Worst                              -0.142 ║
║ Total                               0.023 ║
╚═══════════════════════════════════════════╝

```

2023-09-08 12:02 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               86.554 ║
║ Worst                             -177.143 ║
║ Total                               2.036 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               88.411 ║
║ Worst                             -4538.095 ║
║ Total                               0.597 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.168 ║
║ Best                               83.675 ║
║ Worst                             -2684.507 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.870 ║
║ Best                               32.258 ║
║ Worst                              -0.613 ║
║ Total                               2.320 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.051 ║
║ Best                                5.973 ║
║ Worst                              -4.514 ║
║ Total                               0.718 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.056 ║
║ Best                                3.361 ║
║ Worst                              -0.190 ║
║ Total                               0.025 ║
╚═══════════════════════════════════════════╝

```

2023-09-08 13:10 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.021 ║
║ Worst                             -137.143 ║
║ Total                               2.066 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -3878.571 ║
║ Total                               0.636 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.199 ║
║ Best                               99.558 ║
║ Worst                             -2294.366 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.866 ║
║ Best                               32.258 ║
║ Worst                              -0.613 ║
║ Total                               2.311 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.057 ║
║ Best                                5.973 ║
║ Worst                              -4.514 ║
║ Total                               0.639 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.055 ║
║ Best                                3.366 ║
║ Worst                              -0.190 ║
║ Total                               0.023 ║
╚═══════════════════════════════════════════╝

```

2023-09-08 15:20 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.885 ║
║ Best                               89.021 ║
║ Worst                             -168.992 ║
║ Total                               1.387 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -719.048 ║
║ Total                               0.691 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.263 ║
║ Best                               99.558 ║
║ Worst                             -425.352 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.088 ║
║ Best                               32.258 ║
║ Worst                             -63.958 ║
║ Total                               0.457 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.127 ║
║ Best                                9.023 ║
║ Worst                              -1.980 ║
║ Total                               0.723 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.052 ║
║ Best                                2.248 ║
║ Worst                              -0.142 ║
║ Total                               0.021 ║
╚═══════════════════════════════════════════╝

```

2023-09-11 09:37 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.676 ║
║ Worst                             -75.862 ║
║ Total                               1.665 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -719.048 ║
║ Total                               0.682 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.283 ║
║ Best                               99.558 ║
║ Worst                             -425.352 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.591 ║
║ Best                               32.258 ║
║ Worst                              -0.613 ║
║ Total                               1.468 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.126 ║
║ Best                                9.054 ║
║ Worst                              -1.980 ║
║ Total                               0.721 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.057 ║
║ Best                                2.999 ║
║ Worst                              -0.005 ║
║ Total                               0.024 ║
╚═══════════════════════════════════════════╝

```

2023-09-11 15:15 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.879 ║
║ Best                               89.676 ║
║ Worst                             -98.690 ║
║ Total                               1.308 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -364.879 ║
║ Total                               0.683 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.307 ║
║ Best                               99.558 ║
║ Worst                             -292.753 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.359 ║
║ Best                               32.258 ║
║ Worst                             -34.338 ║
║ Total                               1.199 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.127 ║
║ Best                                9.054 ║
║ Worst                              -1.980 ║
║ Total                               0.723 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.055 ║
║ Best                                2.733 ║
║ Worst                              -0.062 ║
║ Total                               0.023 ║
╚═══════════════════════════════════════════╝

```

2023-09-11 16:47 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.772 ║
║ Best                               89.676 ║
║ Worst                             -174.312 ║
║ Total                               1.027 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -229.348 ║
║ Total                               0.700 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.318 ║
║ Best                               99.558 ║
║ Worst                             -55.282 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.333 ║
║ Best                               32.258 ║
║ Worst                             -34.338 ║
║ Total                               1.101 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.126 ║
║ Best                                9.054 ║
║ Worst                              -1.980 ║
║ Total                               0.721 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.056 ║
║ Best                                2.999 ║
║ Worst                              -0.062 ║
║ Total                               0.023 ║
╚═══════════════════════════════════════════╝

```

2023-09-12 09:06 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.851 ║
║ Best                               89.676 ║
║ Worst                             -172.093 ║
║ Total                               1.378 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -719.048 ║
║ Total                               0.694 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.313 ║
║ Best                               99.558 ║
║ Worst                             -425.352 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.482 ║
║ Best                               32.258 ║
║ Worst                             -18.611 ║
║ Total                               1.374 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.126 ║
║ Best                                9.054 ║
║ Worst                              -1.980 ║
║ Total                               0.721 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.057 ║
║ Best                                2.999 ║
║ Worst                              -0.020 ║
║ Total                               0.023 ║
╚═══════════════════════════════════════════╝

```

2023-09-12 15:09 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.814 ║
║ Best                               89.676 ║
║ Worst                             -46.272 ║
║ Total                               1.134 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -364.879 ║
║ Total                               0.686 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.304 ║
║ Best                               99.558 ║
║ Worst                             -292.753 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.393 ║
║ Best                               32.258 ║
║ Worst                             -34.338 ║
║ Total                               1.303 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.126 ║
║ Best                                9.054 ║
║ Worst                              -1.980 ║
║ Total                               0.721 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.057 ║
║ Best                                2.999 ║
║ Worst                              -0.062 ║
║ Total                               0.023 ║
╚═══════════════════════════════════════════╝

```

2023-09-12 16:45 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.676 ║
║ Worst                             -100.062 ║
║ Total                               1.937 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -994.118 ║
║ Total                               0.676 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.259 ║
║ Best                               99.558 ║
║ Worst                             -535.092 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.748 ║
║ Best                               32.258 ║
║ Worst                              -0.613 ║
║ Total                               1.933 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.093 ║
║ Best                                5.973 ║
║ Worst                              -4.476 ║
║ Total                               0.691 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.056 ║
║ Best                                3.844 ║
║ Worst                              -0.005 ║
║ Total                               0.024 ║
╚═══════════════════════════════════════════╝

```

2023-09-13 08:41 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.676 ║
║ Worst                             -99.688 ║
║ Total                               1.701 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -719.048 ║
║ Total                               0.680 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.276 ║
║ Best                               99.558 ║
║ Worst                             -425.352 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.598 ║
║ Best                               32.258 ║
║ Worst                              -0.613 ║
║ Total                               1.497 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.125 ║
║ Best                                9.054 ║
║ Worst                              -1.980 ║
║ Total                               0.720 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.057 ║
║ Best                                3.046 ║
║ Worst                              -0.005 ║
║ Total                               0.024 ║
╚═══════════════════════════════════════════╝

```

2023-09-13 09:25 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.676 ║
║ Worst                             -75.862 ║
║ Total                               1.666 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -719.048 ║
║ Total                               0.682 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.283 ║
║ Best                               99.558 ║
║ Worst                             -425.352 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.591 ║
║ Best                               32.258 ║
║ Worst                              -0.613 ║
║ Total                               1.468 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.126 ║
║ Best                                9.054 ║
║ Worst                              -1.980 ║
║ Total                               0.721 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.057 ║
║ Best                                2.999 ║
║ Worst                              -0.005 ║
║ Total                               0.024 ║
╚═══════════════════════════════════════════╝

```

2023-09-13 10:25 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.021 ║
║ Worst                             -89.655 ║
║ Total                               2.019 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -994.118 ║
║ Total                               0.674 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.248 ║
║ Best                               99.558 ║
║ Worst                             -535.092 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.802 ║
║ Best                               32.258 ║
║ Worst                              -0.613 ║
║ Total                               2.152 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.081 ║
║ Best                                5.973 ║
║ Worst                              -4.514 ║
║ Total                               0.678 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.055 ║
║ Best                                3.269 ║
║ Worst                              -0.005 ║
║ Total                               0.024 ║
╚═══════════════════════════════════════════╝

```

2023-09-13 11:24 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.021 ║
║ Worst                             -131.429 ║
║ Total                               2.058 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -2061.905 ║
║ Total                               0.667 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.233 ║
║ Best                               99.558 ║
║ Worst                             -1219.718 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.825 ║
║ Best                               32.258 ║
║ Worst                              -0.613 ║
║ Total                               2.240 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.071 ║
║ Best                                5.973 ║
║ Worst                              -4.514 ║
║ Total                               0.670 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.056 ║
║ Best                                3.256 ║
║ Worst                              -0.005 ║
║ Total                               0.024 ║
╚═══════════════════════════════════════════╝

```

2023-09-13 13:40 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.021 ║
║ Worst                             -131.429 ║
║ Total                               2.058 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -2061.905 ║
║ Total                               0.671 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.240 ║
║ Best                               99.558 ║
║ Worst                             -1219.718 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.811 ║
║ Best                               32.258 ║
║ Worst                              -0.613 ║
║ Total                               2.185 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.080 ║
║ Best                                5.973 ║
║ Worst                              -4.514 ║
║ Total                               0.676 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.055 ║
║ Best                                3.282 ║
║ Worst                              -0.005 ║
║ Total                               0.024 ║
╚═══════════════════════════════════════════╝

```

2023-09-13 16:33 UTC, hedgar2017 commented
@vladimirradosavljevic please rebase!

2023-09-13 17:12 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.021 ║
║ Worst                             -89.655 ║
║ Total                               2.128 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -994.118 ║
║ Total                               0.682 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.322 ║
║ Best                               99.558 ║
║ Worst                             -535.092 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                2.118 ║
║ Best                               40.623 ║
║ Worst                              -0.489 ║
║ Total                               2.150 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.088 ║
║ Best                                5.653 ║
║ Worst                              -4.613 ║
║ Total                               0.754 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.056 ║
║ Best                                3.163 ║
║ Worst                              -0.005 ║
║ Total                               0.025 ║
╚═══════════════════════════════════════════╝

```

2023-09-18 11:12 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.021 ║
║ Worst                             -79.207 ║
║ Total                               1.814 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -719.048 ║
║ Total                               0.687 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.350 ║
║ Best                               99.558 ║
║ Worst                             -425.352 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                2.006 ║
║ Best                               40.623 ║
║ Worst                              -0.489 ║
║ Total                               1.742 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.108 ║
║ Best                                8.338 ║
║ Worst                              -4.613 ║
║ Total                               0.776 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.054 ║
║ Best                                2.350 ║
║ Worst                              -0.005 ║
║ Total                               0.025 ║
╚═══════════════════════════════════════════╝

```

2023-09-18 11:52 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.614 ║
║ Worst                             -75.862 ║
║ Total                               1.731 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -719.048 ║
║ Total                               0.691 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.364 ║
║ Best                               99.558 ║
║ Worst                             -425.352 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.960 ║
║ Best                               40.623 ║
║ Worst                              -0.489 ║
║ Total                               1.636 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.125 ║
║ Best                                8.338 ║
║ Worst                              -2.105 ║
║ Total                               0.790 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.058 ║
║ Best                                3.014 ║
║ Worst                              -0.005 ║
║ Total                               0.025 ║
╚═══════════════════════════════════════════╝

```

2023-09-18 12:31 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.021 ║
║ Worst                             -75.862 ║
║ Total                               2.120 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -719.048 ║
║ Total                               0.683 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.345 ║
║ Best                               99.558 ║
║ Worst                             -425.352 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                2.118 ║
║ Best                               40.623 ║
║ Worst                              -0.489 ║
║ Total                               2.150 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.088 ║
║ Best                                5.653 ║
║ Worst                              -4.613 ║
║ Total                               0.754 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.056 ║
║ Best                                3.163 ║
║ Worst                              -0.005 ║
║ Total                               0.025 ║
╚═══════════════════════════════════════════╝

```

2023-09-18 12:32 UTC, hedgar2017 commented
> Benchmark results:
> 
> ```
> ╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
> ║ Mean                              100.000 ║
> ║ Best                               89.021 ║
> ║ Worst                             -75.862 ║
> ║ Total                               2.120 ║
> ╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
> ║ Mean                              100.000 ║
> ║ Best                               99.840 ║
> ║ Worst                             -719.048 ║
> ║ Total                               0.683 ║
> ╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
> ║ Mean                                0.345 ║
> ║ Best                               99.558 ║
> ║ Worst                             -425.352 ║
> ║ Total                               0.000 ║
> ╚═══════════════════════════════════════════╝
> 
> ╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
> ║ Mean                                2.118 ║
> ║ Best                               40.623 ║
> ║ Worst                              -0.489 ║
> ║ Total                               2.150 ║
> ╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
> ║ Mean                                1.088 ║
> ║ Best                                5.653 ║
> ║ Worst                              -4.613 ║
> ║ Total                               0.754 ║
> ╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
> ║ Mean                                0.056 ║
> ║ Best                                3.163 ║
> ║ Worst                              -0.005 ║
> ║ Total                               0.025 ║
> ╚═══════════════════════════════════════════╝
> ```

This one is good!
We are seriously interested in cycles here, so we may sacrifice size a little bit.

2023-09-18 12:38 UTC, vladimirradosavljevic commented
> > Benchmark results:
> > ```
> > ╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
> > ║ Mean                              100.000 ║
> > ║ Best                               89.021 ║
> > ║ Worst                             -75.862 ║
> > ║ Total                               2.120 ║
> > ╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
> > ║ Mean                              100.000 ║
> > ║ Best                               99.840 ║
> > ║ Worst                             -719.048 ║
> > ║ Total                               0.683 ║
> > ╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
> > ║ Mean                                0.345 ║
> > ║ Best                               99.558 ║
> > ║ Worst                             -425.352 ║
> > ║ Total                               0.000 ║
> > ╚═══════════════════════════════════════════╝
> > 
> > ╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
> > ║ Mean                                2.118 ║
> > ║ Best                               40.623 ║
> > ║ Worst                              -0.489 ║
> > ║ Total                               2.150 ║
> > ╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
> > ║ Mean                                1.088 ║
> > ║ Best                                5.653 ║
> > ║ Worst                              -4.613 ║
> > ║ Total                               0.754 ║
> > ╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
> > ║ Mean                                0.056 ║
> > ║ Best                                3.163 ║
> > ║ Worst                              -0.005 ║
> > ║ Total                               0.025 ║
> > ╚═══════════════════════════════════════════╝
> > ```
> 
> This one is good! We are seriously interested in cycles here, so we may sacrifice size a little bit.

Yeah, I have the same opinion that this last one gives really good results.

2023-09-18 13:28 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.021 ║
║ Worst                             -75.862 ║
║ Total                               2.094 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -719.048 ║
║ Total                               0.682 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.347 ║
║ Best                               99.558 ║
║ Worst                             -425.352 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                1.999 ║
║ Best                               40.623 ║
║ Worst                              -1.766 ║
║ Total                               2.062 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.075 ║
║ Best                                5.868 ║
║ Worst                              -4.613 ║
║ Total                               0.759 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.065 ║
║ Best                                3.163 ║
║ Worst                              -0.022 ║
║ Total                               0.025 ║
╚═══════════════════════════════════════════╝

```

2023-09-18 18:47 UTC, akiramenai requested changes

2023-09-18 18:47 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMAliasAnalysis.h
> +/// A simple AA result that uses TBAA metadata to answer queries.
TBAA? Looks like a copy-pasted doc.

2023-09-18 18:47 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMAliasAnalysis.h
> +                  FunctionAnalysisManager::Invalidator &Inv) {
`Inv` is unused

2023-09-18 18:47 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMAliasAnalysis.cpp
> +  auto GetStartLoc = [](const MemoryLocation &Loc) -> Optional<APInt> {
Can we extract it as a function (`getStartLocIfConstFor` or something)? I generally against named anonymous functions as it even sounds like an abuse of the feature (the oneliner below could be an exception from that). When you encounter one in code you are reading other function implementation and it's a distraction from it. You need to save your mental context to stack and read the definition or scroll and skip.

2023-09-18 18:47 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMAliasAnalysis.cpp
> +    // FIXME: Should we enable cases that are not 256-bit pointers?
Yes for completeness. I'd recommend TODO + a low priority ticket to our backlog.

2023-09-18 18:47 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMAliasAnalysis.cpp
> +    }
Should we handle inttoptr instruction case? We are unlikely to face it in optimised code, but perhaps it's weird to behave differently wrt corresponding operator.

2023-09-18 18:47 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMTargetMachine.cpp
> +    FAM.registerPass([&] { return SyncVMAA(); });
Do we need to capture?

2023-09-18 18:47 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/memory-opt.ll
> +}
Negative test case for a dynamic address is missing, and also maybe worth adding a check that a fallback AA works when our AA fails to decide on aliasing (don't require it for LGTM if it needs substantial work).

2023-09-18 18:47 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/storage.ll
> +}
Sorry for that request as it not entirely in the scope of this patch and I should have done it long ago, but could we check llc pipeline with a test for O0, O3, Oz as we're manipulating it?

2023-09-19 15:44 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMAliasAnalysis.h
> +/// A simple AA result that uses TBAA metadata to answer queries.
Fixed comment.

2023-09-19 15:44 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMAliasAnalysis.h
> +                  FunctionAnalysisManager::Invalidator &Inv) {
Removed `Inv` parameter.

2023-09-19 15:45 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMAliasAnalysis.cpp
> +  auto GetStartLoc = [](const MemoryLocation &Loc) -> Optional<APInt> {
Extracted this to a function.

2023-09-19 15:45 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMAliasAnalysis.cpp
> +    }
Makes sense. Added support for `inttoptr` instruction.

2023-09-19 15:45 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMAliasAnalysis.cpp
> +    // FIXME: Should we enable cases that are not 256-bit pointers?
Added TODO + ticket number.

2023-09-19 15:46 UTC, vladimirradosavljevic commented on llvm/lib/Target/SyncVM/SyncVMTargetMachine.cpp
> +    FAM.registerPass([&] { return SyncVMAA(); });
I copied this code from AMDGPU backend, but indeed, we don't need to capture.

2023-09-19 15:48 UTC, vladimirradosavljevic commented on llvm/test/CodeGen/SyncVM/memory-opt.ll
> +}
Added new `aa-eval.ll` to cover all cases that we implemented in our custom AA + the fallback test.

2023-09-19 15:49 UTC, vladimirradosavljevic commented on llvm/test/CodeGen/SyncVM/storage.ll
> +}
No problem at all! Since llc doesn't accept Oz, I added new tests with `minsize` attribute, and runs with O0 and O3. Is this OK with you?

2023-09-19 16:20 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.021 ║
║ Worst                             -75.862 ║
║ Total                               2.120 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -719.048 ║
║ Total                               0.683 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.345 ║
║ Best                               99.558 ║
║ Worst                             -425.352 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                2.118 ║
║ Best                               40.623 ║
║ Worst                              -0.489 ║
║ Total                               2.150 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.088 ║
║ Best                                5.653 ║
║ Worst                              -4.613 ║
║ Total                               0.754 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.056 ║
║ Best                                3.163 ║
║ Worst                              -0.005 ║
║ Total                               0.025 ║
╚═══════════════════════════════════════════╝

```

2023-09-19 21:56 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/storage.ll
> +}
Ok. It's not what I meant, but I'll create a ticket for what I meant. Let's finish with this work and do the pipeline tests separately.

2023-09-19 21:58 UTC, akiramenai approved these changes
Fantastic work. Thank you!

2023-09-20 08:58 UTC, vladimirradosavljevic commented on llvm/test/CodeGen/SyncVM/storage.ll
> +}
Sure, I reverted back to the original test, so we can change it properly in the new task.

2023-09-20 08:59 UTC, vladimirradosavljevic commented
> Fantastic work. Thank you!

Thank you so much for the detailed review! I will use this PR just a little bit more to tweak Unroll parameters.

2023-09-20 09:32 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.021 ║
║ Worst                             -75.862 ║
║ Total                               2.132 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -719.048 ║
║ Total                               0.696 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.358 ║
║ Best                               99.558 ║
║ Worst                             -425.352 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                2.120 ║
║ Best                               40.623 ║
║ Worst                              -0.489 ║
║ Total                               2.162 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.089 ║
║ Best                                5.653 ║
║ Worst                              -4.613 ║
║ Total                               0.762 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.056 ║
║ Best                                3.164 ║
║ Worst                              -0.005 ║
║ Total                               0.025 ║
╚═══════════════════════════════════════════╝

```

2023-09-20 13:15 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                              100.000 ║
║ Best                               89.021 ║
║ Worst                             -75.862 ║
║ Total                               2.132 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               99.840 ║
║ Worst                             -719.048 ║
║ Total                               0.696 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.358 ║
║ Best                               99.558 ║
║ Worst                             -425.352 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                2.120 ║
║ Best                               40.623 ║
║ Worst                              -0.489 ║
║ Total                               2.162 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                1.089 ║
║ Best                                5.653 ║
║ Worst                              -4.613 ║
║ Total                               0.762 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.056 ║
║ Best                                3.164 ║
║ Worst                              -0.005 ║
║ Total                               0.025 ║
╚═══════════════════════════════════════════╝

```

2023-09-20 13:49 UTC, vladimirradosavljevic commented
@akiramenai I pushed [the commit](https://github.com/matter-labs/compiler-llvm/pull/292/commits/42668719f3d77eefeb270351de2df3d6c80aebc7) to remove sstore and sload intrinsics. Could you please review it?

2023-09-21 13:27 UTC, akiramenai commented
@vladimirradosavljevic LGTM assuming relevant FE changes.

2023-09-22 11:30 UTC, merged