Constant folding implementation for __sha3 stdlib function
matter-labs/era-compiler-llvm pull request #305
Opened 2023-09-26 10:45 UTC by PavelKopyl

2023-09-26 11:18 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.413 ║
║ Best                               68.702 ║
║ Worst                              -8.805 ║
║ Total                               0.701 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               96.932 ║
║ Worst                             -26.446 ║
║ Total                               0.282 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.130 ║
║ Best                               78.161 ║
║ Worst                              -3.261 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.703 ║
║ Best                                7.815 ║
║ Worst                              -5.922 ║
║ Total                               0.625 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.516 ║
║ Best                               40.602 ║
║ Worst                              -1.091 ║
║ Total                               0.160 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.134 ║
║ Best                               40.392 ║
║ Worst                              -0.012 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

```

2023-09-26 13:49 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.413 ║
║ Best                               68.702 ║
║ Worst                              -8.805 ║
║ Total                               0.701 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               96.932 ║
║ Worst                             -26.446 ║
║ Total                               0.282 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.130 ║
║ Best                               78.161 ║
║ Worst                              -3.261 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.703 ║
║ Best                                7.815 ║
║ Worst                              -5.922 ║
║ Total                               0.625 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.516 ║
║ Best                               40.602 ║
║ Worst                              -1.091 ║
║ Total                               0.160 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.134 ║
║ Best                               40.392 ║
║ Worst                              -0.012 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

```

2023-09-26 14:46 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.413 ║
║ Best                               68.702 ║
║ Worst                              -8.805 ║
║ Total                               0.701 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               96.932 ║
║ Worst                             -26.446 ║
║ Total                               0.282 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.130 ║
║ Best                               78.161 ║
║ Worst                              -3.261 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.703 ║
║ Best                                7.815 ║
║ Worst                              -5.922 ║
║ Total                               0.625 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.516 ║
║ Best                               40.602 ║
║ Worst                              -1.091 ║
║ Total                               0.160 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.134 ║
║ Best                               40.392 ║
║ Worst                              -0.012 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

```

2023-09-26 19:11 UTC, akiramenai commented
Rebased

2023-09-26 19:43 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.413 ║
║ Best                               68.702 ║
║ Worst                              -8.805 ║
║ Total                               0.701 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               96.932 ║
║ Worst                             -26.446 ║
║ Total                               0.282 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.130 ║
║ Best                               78.161 ║
║ Worst                              -3.261 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.703 ║
║ Best                                7.815 ║
║ Worst                              -5.922 ║
║ Total                               0.625 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.516 ║
║ Best                               40.602 ║
║ Worst                              -1.091 ║
║ Total                               0.160 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.134 ║
║ Best                               40.392 ║
║ Worst                              -0.012 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

```

2023-09-26 22:13 UTC, PavelKopyl commented
PR has two mostly independent commits:
1. Implementation of keccak256 hash function. This implementation was reviewed here: https://github.com/matter-labs/compiler-llvm/pull/275
2. __sha3 constant folding itself.

2023-09-27 09:38 UTC, vladimirradosavljevic commented on llvm/test/CodeGen/SyncVM/sha3-constant-folding.ll
> +; Memory locations of store instructions do alias with each other, so no
As far as I can see, here we have partial aliasing, and our custom Alias Analysis should return that result. I'm not sure how frequently we have this pattern, but I'm wondering whether we can use that information to actually do folding as we should be able to recreate constant? If this makes sense to you, what do you think about creating TODO + ticket to do that in the future? Also, I assume we could use the same optimization and implement it in the InstCombine to remove some loads.

2023-09-27 12:04 UTC, akiramenai requested changes
Good work, thank you, but require some cleanup.
I finished reading around `getKeccak256Hash` as I think 30 comments is enough for the first iteration. If some stylistic issues apply to it and the code after please apply.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +struct MemClobber {
Readability. Documentation is of help.
The meaning of Value is guessable, but a reader still might feel he needs to double check and start looking the context. Perhaps renaming Value to Clobber also helps.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  MemClobber(uint64_t Start, uint64_t Size, APInt Value)
POD types are list initializable.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  void getUseClobbers(MemoryUse *MU, MemoryLocation Loc,
Readability: explicit interfaces. RVO/NRVO makes return by value preferable.

Undefined and unused. `collectUseClobbers` is used instead.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +struct FoldingState {
class + fields encapsulation is preferred.
Also might worth to extract interfaces and move them up.
Documentation would also be of help to understand how the state works without going deep into implementation details

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +        CallInst *Call = dyn_cast<CallInst>(&I);
Readability. Might worth to wrap all checks into a function that checks if the instruction is a call to LibFunc_xvm_sha3. Optionally also use a filtering iterator as it expresses intent better.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +    // FIXME: we can relax this constraint in the future if it turns out we miss
TODO + ticket number please

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +      if (MemoryDef *Def = dyn_cast<MemoryDef>(MA)) {
`auto*` as type is in the RHS.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  /// for a given \p Use.
the parameter is named MU.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +    // live on entry (nothing to do, load is not clobbered), MemoryDef, or
Could you explain the logic with MemoryDef here (rephrasing is very welcome here as the sentence is too long) or when adding a value to the working list.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +            Walker->getClobberingMemoryAccess(Def->getDefiningAccess(), Loc));
Do we need a list at all? It looks like it always contain 1 element at most.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +        if (!DebugCounter::shouldExecute(SHA3Counter)) {
I apologise, I'm not familiar with debug counters, could you educate my why we skip here?

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  /// Try to simplify instructions of the functions. Candidates for
you mean function F?

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +                                   const MemoryLocation &MemUseLoc) {
const?

Same for other methods where applicable.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +    // If the dependency is within the same block or loop level (being careful
Could we spread the comment among the code. Otherwise you need first to put into the memory as a whole, and then check the logic. Also it looks like we don't check irreducible loop when in the same BB, etc. So more precise description would be better.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +      return I->getParent()->isEntryBlock();
Could you explain why we only consider entry instruction as loop invariant?

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  /// Return 'OW_Complete' if a store to the \p ClobberLoc location (by \p
Looks like a good documentation for the enumeration itself.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +                              const Instruction *Clobber,
please clang-format

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +    auto getPointerAsInt = [](const Value *Ptr) -> std::optional<uint64_t> {
Please extract as a utility function. IMO, a named anonymous function is almost always the feature abuse.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +                              int64_t &MemUseOff, int64_t &ClobberOff) {
Perhaps it make sense to make it a part of the return value.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +    auto getPointerAsInt = [](const Value *Ptr) -> std::optional<uint64_t> {
Also to the best of my memory @vladimirradosavljevic wrote something alike in the past. So perhaps can be unified to an utility function.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +        return OL_Unknown;
Why can it happen?

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +                              int64_t &MemUseOff, int64_t &ClobberOff) {
Also `Offset` is preferred as `Off` is not a widely accepted shortcut for it.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +      // Make sure that the MemUseSize size is >= the ClobberSize size.
What if not? Is it expected and just handled below?

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +        MemUseOff = static_cast<uint64_t>(MemUsePtrInt);
int64_t?

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +          return cast<ConstantInt>(C)->getZExtValue();
We have i256 pointers. Shouldn't we have some guards in the pass?

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +      if (uint64_t(ClobberOff - MemUseOff) + ClobberSize <= MemUseSize) {
`static_cast` instead of C-style one.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  bool sortAndCheckMemoryClobbers(SmallVector<MemClobber> &MemClobbers,
Can we split sort and check as it violates single responsibility rule? Perhaps the check function can require input to be sorted.

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  /// clobber heap memory. For example, a memcpy to AS other than heap.
It's the only example. Have we missed a TODO here?

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  /// clobber heap memory. For example, a memcpy to AS other than heap.
Also what if not an intrinsic but a mere load / store?

2023-09-27 12:04 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +      // TODO: needs to check for flaws in this logic. In fact this is
+ticket

2023-09-27 14:02 UTC, PavelKopyl commented on llvm/test/CodeGen/SyncVM/sha3-constant-folding.ll
> +; Memory locations of store instructions do alias with each other, so no
Yep, our AA detects this case, but I decided not to support this it for simplicity, because I haven't seen it in tests (thought I didn't check all of them).
@hedgar2017, probably you know more about __sha3. Can we have the following case, and how frequent it may be in a real life:


```
|---Store1---|
     |---Store2--|
                 |---------Store3----|
   |--------sha3 memory ------| 

```

?

Currently, this pass supports only the following case:

```
|---Store1---|
             |---Store2--|
                         |-Store3----|
|--------sha3 memory ----------------| 
```

2023-09-27 16:55 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +struct MemClobber {
OK. Added description and renamed Value -> Clobber.

2023-09-27 16:58 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  MemClobber(uint64_t Start, uint64_t Size, APInt Value)
OK. I just wanted to use emplace_back, but let's use push_back.

2023-09-27 17:26 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  void getUseClobbers(MemoryUse *MU, MemoryLocation Loc,
Yep, thank you!

2023-09-27 18:54 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.413 ║
║ Best                               68.702 ║
║ Worst                              -8.805 ║
║ Total                               0.701 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               96.932 ║
║ Worst                             -26.446 ║
║ Total                               0.282 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.130 ║
║ Best                               78.161 ║
║ Worst                              -3.261 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.703 ║
║ Best                                7.815 ║
║ Worst                              -5.922 ║
║ Total                               0.625 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.516 ║
║ Best                               40.602 ║
║ Worst                              -1.091 ║
║ Total                               0.160 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.134 ║
║ Best                               40.392 ║
║ Worst                              -0.012 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

```

2023-09-27 20:12 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +        CallInst *Call = dyn_cast<CallInst>(&I);
OK. I moved the check to a function.

2023-09-28 15:58 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +struct FoldingState {
Done.

2023-09-28 15:59 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +    // FIXME: we can relax this constraint in the future if it turns out we miss
Done.

2023-09-28 15:59 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +      if (MemoryDef *Def = dyn_cast<MemoryDef>(MA)) {
Done.

2023-09-28 15:59 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  /// for a given \p Use.
Yes, thank you.

2023-09-28 16:01 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +    // live on entry (nothing to do, load is not clobbered), MemoryDef, or
Added their more detailed description, but anyway it's also worth to check MemorySSA documentation.

2023-09-28 16:01 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +            Walker->getClobberingMemoryAccess(Def->getDefiningAccess(), Loc));
You are right, this left from my previous experiments. Thank you, fixed.

2023-09-28 16:02 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +        if (!DebugCounter::shouldExecute(SHA3Counter)) {
I answered to slack)

2023-09-28 16:02 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  /// Try to simplify instructions of the functions. Candidates for
Yep, done.

2023-09-28 16:02 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +                                   const MemoryLocation &MemUseLoc) {
Done.

2023-09-28 16:03 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +    // If the dependency is within the same block or loop level (being careful
Done. By the way, I was inspired by DeadStoreElimination pass, where I took this code.

2023-09-28 16:04 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  /// Return 'OW_Complete' if a store to the \p ClobberLoc location (by \p
Yes, I added it also to the enum.

2023-09-28 16:05 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +                              const Instruction *Clobber,
Done.

2023-09-28 16:14 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +    auto getPointerAsInt = [](const Value *Ptr) -> std::optional<uint64_t> {
OK, I extracted this code to a wrapper function. Yes, this code is almost identical to what Vladimir implemented in SyncVM AA, so it's reasonable to move this helper into a common code. I've created a ticked for this, CPR-1380.

2023-09-28 16:14 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +                              int64_t &MemUseOff, int64_t &ClobberOff) {
Agreed, done.

2023-09-28 16:15 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +        return OL_Unknown;
You must be right, I added an assert for this

2023-09-28 16:16 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +      // Make sure that the MemUseSize size is >= the ClobberSize size.
Yes, this case should be handled below.

2023-09-28 16:16 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +        MemUseOff = static_cast<uint64_t>(MemUsePtrInt);
Yep.

2023-09-28 16:21 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +          return cast<ConstantInt>(C)->getZExtValue();
Yep, but do you mean it may be the case that the integer offset with require more that 64 bits...? For simplicity I used uint64_t for the offsets, but sure I can switch to APInt.

2023-09-28 16:21 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +      if (uint64_t(ClobberOff - MemUseOff) + ClobberSize <= MemUseSize) {
Done.

2023-09-28 16:21 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  bool sortAndCheckMemoryClobbers(SmallVector<MemClobber> &MemClobbers,
Done.

2023-09-28 16:32 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  /// clobber heap memory. For example, a memcpy to AS other than heap.
Then store instructions will be handled by the code below. Stores that were proven by MemorySSA analysis to not alias with __sha3 are excluded from the consideration. This is magic of MemorySSA.

2023-09-28 16:33 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +      // TODO: needs to check for flaws in this logic. In fact this is
Actually, I removed this TODO, as this check seems to be fine.

2023-09-28 16:36 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.413 ║
║ Best                               68.702 ║
║ Worst                              -8.805 ║
║ Total                               0.703 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               96.932 ║
║ Worst                             -26.446 ║
║ Total                               0.282 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.130 ║
║ Best                               78.162 ║
║ Worst                              -3.261 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.695 ║
║ Best                                7.815 ║
║ Worst                              -5.922 ║
║ Total                               0.624 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.517 ║
║ Best                               40.602 ║
║ Worst                              -1.031 ║
║ Total                               0.160 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.134 ║
║ Best                               40.392 ║
║ Worst                              -0.008 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

```

2023-09-28 17:12 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.413 ║
║ Best                               68.702 ║
║ Worst                              -8.805 ║
║ Total                               0.703 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               96.932 ║
║ Worst                             -26.446 ║
║ Total                               0.282 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.130 ║
║ Best                               78.162 ║
║ Worst                              -3.261 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.695 ║
║ Best                                7.815 ║
║ Worst                              -5.922 ║
║ Total                               0.624 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.517 ║
║ Best                               40.602 ║
║ Worst                              -1.031 ║
║ Total                               0.160 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.134 ║
║ Best                               40.392 ║
║ Worst                              -0.008 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

```

2023-09-29 21:37 UTC, akiramenai requested changes
It became much better, thank you.
But there are still some things to address.

2023-09-29 21:37 UTC, akiramenai commented on llvm/lib/Support/KECCAK.cpp
> +static uint64_t load64(const uint8_t *x) {
static in an anonymous ns is a bit too much. LLVM [recommends](https://llvm.org/docs/CodingStandards.html#anonymous-namespaces) static.

2023-09-29 21:37 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/sha3-constant-folding.ll
> +; Memory locations of store instructions do alias with each other, so no
@PavelKopyl I believe it's a rare case which doesn't give us much. If it needs effort to implement, I'd go for a todo + a low priority ticket.

@akiramenai You are right, I've even checked this on out test suite and couldn't find such cases. Nevertheless, I mentioned this case in the CPR-1370.

2023-09-29 21:37 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +/// (in current implementation - a store instruction) and put it in a
If a memory intrinsic we skip the transformation?

2023-09-29 21:37 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  enum OverlapType {
enum class is preferred.

2023-09-29 21:37 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  bool isLibFuncCall(const Instruction *I, LibFunc F) const;
If I remember right, we also used something similar in one of your previous patches. If there are other use cases, it might worth to extract as a utility. Just a comment.

2023-09-29 21:37 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  /// Return 'OW_Complete' if a store to the \p ClobberLoc location (by \p
Thank you. We could actually make this one shorter as the enum is documented. Like return overlap status of MemUseLoc and ClobberLoc or something, though it's clear from the signature.

2023-09-29 21:37 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  /// TODO: CPR-1380.
Nitpicking.
A brief text describing the issue is of use for those who doesn't want to lookup the ticket.
As we are going to unify it anyway, it's ok to keep as it is.

2023-09-29 21:37 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  ContainsIrreducibleLoops = mayContainIrreducibleControl(F, &LI);
It could be put to the initializer list and made `const`. One less suspicion for a reader.

2023-09-29 21:37 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  for (;;) {
Why not to move what leads to break to the loop condition and change to while? Isn't `for (;;)` kind of exotic?

2023-09-29 21:37 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  // memory dependency. (Both at the function level, outside of any loop,
I didn't quite get about compilation time.
We request `getLoopFor` for both `MemUse` and `Clobber` bbs. Shouldn't these calls return `nullptr` in case of outside of any loop. Can't we rely on it?

2023-09-29 21:37 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +          return cast<ConstantInt>(C)->getZExtValue();
We shall not ICE when user writes something to let's say 1234567890123456789. We can just stop optimising because the contract will eat all gas, but we shouldn't fail to compile. So it's up to you guard or switch to APInt.

2023-09-29 21:37 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +                              int64_t &MemUseOff, int64_t &ClobberOff) {
Not everywhere.

2023-09-29 21:37 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  // Okay, we have stores to two completely different pointers.  Try to
Two spaces. Here and below.

2023-09-29 21:37 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +    if (It == Begin)
Why can't we initialise TotalSize with Begin->Size, and It with std::next(Begin) thus removing this check?

2023-09-29 21:37 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +      LLVM_DEBUG(dbgs() << "\tclobbers do alias, or there is a gep: ["
gap?

2023-09-29 21:37 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  for (;;) {
do while?

2023-10-02 09:18 UTC, PavelKopyl commented on llvm/lib/Support/KECCAK.cpp
> +static uint64_t load64(const uint8_t *x) {
Yep, thank you.

2023-10-02 09:21 UTC, hedgar2017 commented on llvm/test/CodeGen/SyncVM/sha3-constant-folding.ll
> +; Memory locations of store instructions do alias with each other, so no
> Yep, our AA detects this case, but I decided not to support this it for simplicity, because I haven't seen it in tests (thought I didn't check all of them).
> 
> @hedgar2017, probably you know more about __sha3. Can we have the following case, and how frequent it may be in a real life:
> 
> 
> 
> 
> 
> ```
> 
> |---Store1---|
> 
>      |---Store2--|
> 
>                  |---------Store3----|
> 
>    |--------sha3 memory ------| 
> 
> 
> 
> ```
> 
> 
> 
> ?
> 
> 
> 
> Currently, this pass supports only the following case:
> 
> 
> 
> ```
> 
> |---Store1---|
> 
>              |---Store2--|
> 
>                          |-Store3----|
> 
> |--------sha3 memory ----------------| 
> 
> ```
> 
> 

Would be nice to have actually. Can be done in a follow-up ticket.

2023-10-02 09:31 UTC, PavelKopyl commented on llvm/test/CodeGen/SyncVM/sha3-constant-folding.ll
> +; Memory locations of store instructions do alias with each other, so no
OK, I've mentioned this case in the [CRP-1370](https://linear.app/matterlabs/issue/CPR-1370/extent-sha3-constant-folding).

2023-10-02 10:15 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +/// (in current implementation - a store instruction) and put it in a
Yes, we skip the transformation in this case, because:
 - I haven't found such cases among the tests in our CI (as an experiment, I added llvm_unreachable() for this case, but no falls were observed)
 - This will require additional analysis to be implemented.
 
 An example, of such an example is shown below:
```
 declare void @llvm.memcpy.p1i256.p3i256.i256(ptr addrspace(1) noalias nocapture writeonly, ptr addrspace(3) noalias nocapture readonly, i256, i1 immarg)
 
define i256 @sha3_test_1() nounwind {
entry:
  store i256 304594385234, ptr addrspace(3) null, align 4294967296
  store i256 56457598675863654, ptr addrspace(3) inttoptr (i256 32 to ptr addrspace(3)), align 32
  call void @llvm.memcpy.p1i256.p3i256.i256(ptr addrspace(1) null, ptr addrspace(3) null, i256 64, i1 false)
  %hash = tail call i256 @__sha3(ptr addrspace(1) null, i256 64, i1 true)
  ret i256 %hash
}
declare i256 @__sha3(ptr addrspace(1), i256, i1) #0
attributes #0 = { argmemonly nofree nounwind null_pointer_is_valid readonly}
```

2023-10-02 10:42 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  enum OverlapType {
OK, done.

2023-10-02 10:44 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  bool isLibFuncCall(const Instruction *I, LibFunc F) const;
Yes, we have similar functionality in the SyncVMLinkRuntime pass. I've created a [ticket](https://linear.app/matterlabs/issue/CPR-1386/move-syncvmsha3constfoldingislibfunccall-function-to-a-common-code) for this.

2023-10-02 10:46 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  /// TODO: CPR-1380.
OK, I added a small comment here.

2023-10-02 10:59 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  ContainsIrreducibleLoops = mayContainIrreducibleControl(F, &LI);
OK, moved to the initializer list.

2023-10-02 15:27 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +      return I->getParent()->isEntryBlock();
Sorry, re-check again, as I found a mistake in the function declaration. It should be

```
bool isGuaranteedLoopIndependent(const Instruction *Clobber,
                                   const Instruction *MemUse,
                                   const MemoryLocation &ClobberLoc) const;
```

So, the check means that if a Clobber's base address value is within the F's entry block the Clobber considered as a loop invariant. It looks reasonable. By the way, I took this check from DSE pass and the discussion about it is here: https://reviews.llvm.org/D100464.

2023-10-02 15:27 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +                              int64_t &MemUseOff, int64_t &ClobberOff) {
Fixed other cases of "Off".

2023-10-02 15:27 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +          return cast<ConstantInt>(C)->getZExtValue();
Agreed, done.

2023-10-02 15:28 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  for (;;) {
Done.

2023-10-02 15:33 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  // Okay, we have stores to two completely different pointers.  Try to
Fexed.

2023-10-02 15:33 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +      LLVM_DEBUG(dbgs() << "\tclobbers do alias, or there is a gep: ["
Fixed.

2023-10-02 16:32 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  // memory dependency. (Both at the function level, outside of any loop,
Sorry, I removed this part regarding the time, as it has no big meaning for this pass.
Yep, getLoopFor can return nullptr. As for the case where both MemUse's Loop and the Clobbers's Loop are both nullptr... it's an interesting case. At first glance, this looks like we are loop invariant, but in general case we have to consider irreducible CFG. Initial author of this check seems to has no clear understanding when to do in this case:
"I was originally more worried about opening the door to any number of unrelated issues coming up from allowing DSE from different blocks were both LI's return nullptr." (See it here: https://reviews.llvm.org/D100464?id=337391#inline-947892). On the other hand, if our front end doesn't generate irreducible CFG we may drop isGuaranteedLoopInvariant, I guess. I'll make an experiment with the removed check isGuaranteedLoopIndependent.

2023-10-02 16:44 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  /// Return 'OW_Complete' if a store to the \p ClobberLoc location (by \p
OK, done.

2023-10-02 16:59 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +    if (It == Begin)
Done, thank you.

2023-10-02 23:35 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.413 ║
║ Best                               68.702 ║
║ Worst                              -8.805 ║
║ Total                               0.702 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                              100.000 ║
║ Best                               96.932 ║
║ Worst                             -26.446 ║
║ Total                               0.282 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.130 ║
║ Best                               78.162 ║
║ Worst                              -3.261 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.695 ║
║ Best                                7.815 ║
║ Worst                              -5.922 ║
║ Total                               0.624 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.517 ║
║ Best                               40.602 ║
║ Worst                              -1.031 ║
║ Total                               0.160 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.134 ║
║ Best                               40.392 ║
║ Worst                              -0.008 ║
║ Total                               0.007 ║
╚═══════════════════════════════════════════╝

```

2023-10-03 00:57 UTC, PavelKopyl commented on llvm/lib/Target/SyncVM/SyncVMSHA3ConstFolding.cpp
> +  for (;;) {
Actually, I came back to `for` loop, but I moved this two break conditions into for loop condition.

2023-10-03 14:28 UTC, akiramenai approved these changes
LGTM, thanks

2023-10-03 14:30 UTC, akiramenai commented
> I'll make an experiment with the removed check isGuaranteedLoopIndependent

Have you tried?

2023-10-03 14:32 UTC, akiramenai commented
I see, it's an another PR.

2023-10-03 14:34 UTC, merged