Coalescing select patterns
matter-labs/era-compiler-llvm pull request #309
Opened 2023-09-27 02:17 UTC by lialan

[CPR-1344](https://linear.app/matterlabs/issue/CPR-1344/coalesce-select-values) 

Optimization specifically for Elliptic Curve computation, which contains opportunity to fold expanded select instruction.

Yielding ~4% for ECAdd (from 6387 cycles to 6182, normal execution path).

2023-09-27 02:52 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                3.077 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.001 ║
║ Best                                1.235 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.758 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.044 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.008 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-09-27 17:43 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                3.077 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.001 ║
║ Best                                1.235 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.758 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.044 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.008 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-09-28 16:52 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                3.077 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.001 ║
║ Best                                1.235 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.758 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.044 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.008 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-09-29 04:18 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-09-29 12:15 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +/// add     ra, rb, rc
This one unlikely to give us much. The one we should look for is
```
[add value1, r0, rN]
add.cc value2, r0, rN
...
op rN, rM, out
```

2023-09-29 14:20 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +/// add     ra, rb, rc
@akiramenai are you referring to [CPR-1342](https://linear.app/matterlabs/issue/CPR-1342/eliminate-select-pattern#comment-b6d05957) and [CPR-1129](https://linear.app/matterlabs/issue/CPR-1129/fold-op-selectcc-x-y-z-into-op-y-z-opcc-x-z) and alike? 

Working on it at the moment. They are similar and have a few variations, so we should cover as many of them as possible in one shot.

2023-09-29 14:46 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +/// add     ra, rb, rc
Ok, I probably missed your initial comment and looked at benches first. Have we merged ECAdd, ECMul test cases? If so why zeroes?

2023-09-29 14:54 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +/// add     ra, rb, rc
test cases are [here](https://github.com/matter-labs/compiler-tests/pull/225). @hedgar2017 prefer using the system contract version (which is the same but not checked in) instead of this one. 

For now, you have to manually cherry-pick it locally. Note that the test cases contain many corner cases, which is not  what we are focusing on. The test traces we are focusing on runs around 6000 cycles.

2023-09-29 15:57 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +  if (!TII->isAdd(PrevMI) ||
Given that we are folding a conditional move, I think this can be relaxed.

2023-09-29 17:58 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.057 ║
║ Best                                4.651 ║
║ Worst                               0.000 ║
║ Total                               0.033 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.029 ║
║ Best                                2.930 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.021 ║
║ Best                                2.809 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.000 ║
║ Best                                0.088 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.062 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.007 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-09-29 22:44 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.058 ║
║ Best                                4.651 ║
║ Worst                               0.000 ║
║ Total                               0.034 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.032 ║
║ Best                                6.478 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.022 ║
║ Best                                6.210 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.001 ║
║ Best                                0.088 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.001 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.015 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-09-30 23:26 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.058 ║
║ Best                                4.651 ║
║ Worst                               0.000 ║
║ Total                               0.034 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.032 ║
║ Best                                6.478 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.022 ║
║ Best                                6.210 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.001 ║
║ Best                                0.088 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.001 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.015 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-10-01 17:09 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +  // we are combining two insructions so only consider adjacent ones.
It will be not trivial to check more combining opportunities backwards because of the registers carry dependencies. One example is in the comment of [CPR-1129](https://linear.app/matterlabs/issue/CPR-1129/fold-op-selectcc-x-y-z-into-op-y-z-opcc-x-z) where folding requires moving around instructions and assign new registers.

We need a more comprehensive approach to this. Will consider it in doing CPR-1129 instead of here.

2023-10-02 12:24 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +/// add     ra, rb, rc
@hedgar2017 how soon do we expect the system contract to be checked in? If it will take a while, could we perhaps accept @lialan patch to tests temporary to be able to track performance numbers on CI instead of doing it manually?

2023-10-02 12:35 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +/// add     ra, rb, rc
@akiramenai ok, let's temporarily merge them.

2023-10-02 12:38 UTC, hedgar2017 commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +/// add     ra, rb, rc
Merged & updated the compiler-tester.

2023-10-02 18:20 UTC, akiramenai reviewed
Generally looks good to me, but makes sense to relax constraints a bit and improve readability.

2023-10-02 18:20 UTC, akiramenai commented on llvm/lib/Target/SyncVM/CMakeLists.txt
> +  SyncVMPeephole.cpp
Perhaps `SyncVMOptimizeSelect` would be more precise. I don't sure that we need to put all different post-ra combines into a single pass.

2023-10-02 18:20 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +/// at the las minute.
last, and please address formatting issues everywhere.

2023-10-02 18:20 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +/// Return a safety checked folding-candidate out register from PrevMI
1. Could we move the purpose documentation to the declaration?
2. Could you elaborate on safety checked?

2023-10-02 18:20 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +  // Only fold ADDrrr_s because for now, SEL pseudos  only expands into it.
two spaces

2023-10-02 18:20 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +  // First we detect `add.xx rc (killed), r0, rb` pattern:
Inverting the condition wrt what is written in the comment is a bit confusing. Don't insist, but recommend to extract the predicate as a function `isConditionalMove` and do `if (!conditionalMov(MI)) return false;`

2023-10-02 18:20 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +  // we are combining two insructions so only consider adjacent ones.
Can't we use RDA the same way it's done in combine addressing mode and postpone cases where more completed changes are needed. Only adjacent is unnecessary strict, imo.

2023-10-02 18:20 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +/// add     ra, rb, rc
The pattern in the comment is more narrow than the pass actually consider. The pass isn't exclusively work with add.

2023-10-02 18:20 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +  // not safe.
Could you elaborate on that.

2023-10-02 18:20 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +/// Return a safety checked folding-candidate out register from PrevMI
Also maybe `getOutRegToFold(MI)` or something. The current name is too cryptic, imo.

2023-10-03 23:41 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +  // First we detect `add.xx rc (killed), r0, rb` pattern:
updated and extracted the logic into a function.

2023-10-04 00:36 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +  // not safe.
updated.

2023-10-04 04:18 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.044 ║
║ Best                                4.651 ║
║ Worst                               0.000 ║
║ Total                               0.026 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.033 ║
║ Best                                6.478 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.023 ║
║ Best                                6.210 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.039 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.024 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.030 ║
║ Best                                5.128 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.021 ║
║ Best                                4.891 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.001 ║
║ Best                                0.080 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.014 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.001 ║
║ Best                                0.088 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.119 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.015 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-10-05 03:52 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.044 ║
║ Best                                4.651 ║
║ Worst                               0.000 ║
║ Total                               0.026 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.033 ║
║ Best                                6.478 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.023 ║
║ Best                                6.210 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.039 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.024 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.030 ║
║ Best                                5.128 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.021 ║
║ Best                                4.891 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.001 ║
║ Best                                0.080 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.014 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.001 ║
║ Best                                0.088 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.119 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.015 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-10-05 04:39 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.044 ║
║ Best                                4.651 ║
║ Worst                               0.000 ║
║ Total                               0.026 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.033 ║
║ Best                                6.478 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.023 ║
║ Best                                6.210 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.039 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.024 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.030 ║
║ Best                                5.128 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.021 ║
║ Best                                4.891 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.001 ║
║ Best                                0.080 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.014 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.001 ║
║ Best                                0.088 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.119 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.015 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-10-05 16:51 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.044 ║
║ Best                                4.651 ║
║ Worst                               0.000 ║
║ Total                               0.026 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.033 ║
║ Best                                6.478 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.023 ║
║ Best                                6.210 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.039 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.024 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.030 ║
║ Best                                5.128 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.021 ║
║ Best                                4.891 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.001 ║
║ Best                                0.080 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.014 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.001 ║
║ Best                                0.088 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.119 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.015 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-10-05 22:45 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +/// Return a safety checked folding-candidate out register from PrevMI
done

2023-10-05 23:38 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.044 ║
║ Best                                4.651 ║
║ Worst                               0.000 ║
║ Total                               0.026 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.033 ║
║ Best                                6.478 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.023 ║
║ Best                                6.210 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.039 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.024 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.030 ║
║ Best                                5.128 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.021 ║
║ Best                                4.891 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.001 ║
║ Best                                0.080 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.014 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.001 ║
║ Best                                0.088 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.119 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.015 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-10-06 09:17 UTC, akiramenai requested changes

2023-10-06 09:17 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMInstrInfo.h
> +  static bool isFlagSettingInstruction(MachineInstr& MI) {
[`inline`](https://stackoverflow.com/questions/22102919/static-vs-inline-for-functions-implemented-in-header-files)

2023-10-06 09:17 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +//===-- EraVMOptimizeSelect.cpp - Optimize select ---------===//
misformatting

2023-10-06 09:17 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +/// be folded with a previous instruction.
You relaxed this.

2023-10-06 09:17 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +/// Returns a folding-candidate out register from PrevMI.
Though LLVM doesn't technically impose any requirements on private members documentation, I still think it make sense put it before the declaration rather than before to the definition. A reader doesn't always need to read the definition and for the sake of consistency.
Same applies to other methods.

2023-10-06 09:17 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +class EraVMOptimizeSelect : public MachineFunctionPass {
Could we set some expectations by documenting what pass is doing here?

2023-10-06 09:17 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  if (EraVM::hasSROutAddressingMode(PrevMI))
Though `TII->isArithmetic` guarantees us that `!SR == RR`, I feel anxious and have to double check by looking up the context, `!hasRROutAddressingMode` is safer as not every instruction is in the map. And the replacement would remove aforementioned precondition.

2023-10-06 09:17 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +/// null if no such candidate found.
It makes sense to add what qualifies as a folding candidate.

2023-10-06 09:17 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  // Can only handle folding in single MBB, single definition:
Could you please add todo to make it global. Please search if we already have a ticket for the problem before creating a new one. Set low priority if we resort to creating.

2023-10-06 09:17 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  if (Uses.count(MI) != 1)
assert?

2023-10-06 09:17 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  if (Uses.size() != 1)
It can be relaxed, can't it? Low priority follow up.

2023-10-06 09:17 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  if (Uses.size() != 1)
Overall I think that all non-trivial constraints worth documenting to clarify 1) whether it's a TODO or a fundamental limit and 2) _why_  it's here. I did my best to make addressing mode improving pass an example of this idea.

2023-10-06 09:17 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +    if (I.isCall())
A call defines all registers, so can it really be in between a definition and its usage?

2023-10-06 09:17 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +    for (const MachineOperand &Opnd : I.operands()) {
any_of

2023-10-06 09:17 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +EraVMOptimizeSelect::getOutRegToFold(const MachineInstr &PrevMI) const {
It's not previous anymore.

2023-10-06 09:17 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +      getImmOrCImm(*EraVM::ccIterator(*DefMI)) != EraVMCC::COND_NONE)
A bit out of scope, but this one is quite frequent idiom. Perhaps worth to be extracted to a function moved to the header and substituted (my suggestion is to rename `isPredicatedInstr` to `isPredicable` and name this one `isPredicated`). Ok to do in a separate ticket.

2023-10-06 09:17 UTC, akiramenai commented on llvm/test/CodeGen/EraVM/select_fold.ll
> +; RUN: llc < %s | FileCheck %s
Could we remove what is not needed from this ll? Also can wee add minimal test cases for the foldings the way we did for addressing modes for example?

2023-10-06 13:13 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +//===-- EraVMOptimizeSelect.cpp - Optimize select ---------===//
Done.

2023-10-06 13:13 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMInstrInfo.h
> +  static bool isFlagSettingInstruction(MachineInstr& MI) {
okay, added them and similar functions.

2023-10-06 13:17 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +/// Returns a folding-candidate out register from PrevMI.
Good suggestion. Updated.

2023-10-06 13:33 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  if (Uses.size() != 1)
@akiramenai Cannot be further relaxed. We are going to eliminate the use register here, so there must be only 1 use.

2023-10-06 13:58 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +      getImmOrCImm(*EraVM::ccIterator(*DefMI)) != EraVMCC::COND_NONE)
Created ticket: [CPR-1399](https://linear.app/matterlabs/issue/CPR-1399/generalize-frequent-predicable-instruction-idioms)

2023-10-06 14:08 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +    for (const MachineOperand &Opnd : I.operands()) {
done.

2023-10-06 14:08 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +EraVMOptimizeSelect::getOutRegToFold(const MachineInstr &PrevMI) const {
updated

2023-10-06 14:08 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +/// be folded with a previous instruction.
done.

2023-10-06 14:09 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +class EraVMOptimizeSelect : public MachineFunctionPass {
Okay, updated

2023-10-06 14:16 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  if (Uses.count(MI) != 1)
right. used assert here.

2023-10-06 14:17 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  if (EraVM::hasSROutAddressingMode(PrevMI))
Double checked it as well. using `!hasRROutAddressingMode()` is safer, so I updated it.

2023-10-06 14:27 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  // Can only handle folding in single MBB, single definition:
@akiramenai I honestly think if we are going to do global folding, we should do it before RA. Here this pass is rather too late in the pipeline.
Some other thoughts:
1. after block placement, majority of the branches will be conditional, which means the flags will be set
2. In our backend, predicated instructions always comes with a local flag setting instruction, using a flag passed from other MBB is not guaranteed conformant.

2023-10-06 14:28 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +    if (I.isCall())
right, the register will be spilled and reloaded. so this is redundant. removed.

2023-10-06 15:14 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.050 ║
║ Best                                4.651 ║
║ Worst                               0.000 ║
║ Total                               0.040 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.042 ║
║ Best                                6.478 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.026 ║
║ Best                                6.210 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.057 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.050 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.041 ║
║ Best                                5.641 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.025 ║
║ Best                                4.891 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.038 ║
║ Best                                0.314 ║
║ Worst                               0.000 ║
║ Total                               0.033 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.011 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.008 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.029 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.061 ║
║ Best                                0.385 ║
║ Worst                               0.000 ║
║ Total                               0.066 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.045 ║
║ Best                                0.890 ║
║ Worst                               0.000 ║
║ Total                               0.177 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.007 ║
║ Best                                0.301 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-10-07 10:20 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMInstrInfo.h
> +  static bool isFlagSettingInstruction(MachineInstr& MI) {
I meant that we should prefer `inline` to `static` as it seems to be strictly better for the job in a header. See the link for the details. `static inline` works as `static`.

2023-10-09 16:27 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.050 ║
║ Best                                4.651 ║
║ Worst                               0.000 ║
║ Total                               0.040 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.042 ║
║ Best                                6.478 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.026 ║
║ Best                                6.210 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.057 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.050 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.041 ║
║ Best                                5.641 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.025 ║
║ Best                                4.891 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.038 ║
║ Best                                0.314 ║
║ Worst                               0.000 ║
║ Total                               0.033 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.011 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.008 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.029 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.061 ║
║ Best                                0.385 ║
║ Worst                               0.000 ║
║ Total                               0.066 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.045 ║
║ Best                                0.890 ║
║ Worst                               0.000 ║
║ Total                               0.177 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.007 ║
║ Best                                0.301 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-10-10 18:33 UTC, lialan commented on llvm/lib/Target/SyncVM/SyncVMPeephole.cpp
> +/// add     ra, rb, rc
updated

2023-10-10 21:15 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.050 ║
║ Best                                4.651 ║
║ Worst                               0.000 ║
║ Total                               0.040 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.042 ║
║ Best                                6.478 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.026 ║
║ Best                                6.210 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.057 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.050 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.041 ║
║ Best                                5.641 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.025 ║
║ Best                                4.891 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.038 ║
║ Best                                0.314 ║
║ Worst                               0.000 ║
║ Total                               0.033 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.011 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.008 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.029 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.061 ║
║ Best                                0.385 ║
║ Worst                               0.000 ║
║ Total                               0.066 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.045 ║
║ Best                                0.890 ║
║ Worst                               0.000 ║
║ Total                               0.177 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.007 ║
║ Best                                0.301 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-10-11 00:09 UTC, lialan commented on llvm/test/CodeGen/EraVM/select_fold.ll
> +; RUN: llc < %s | FileCheck %s
@akiramenai Tried to minimize this test, but it is hard to grasp the situation and create exactly the scenario we want, particularly, it seems without a loop and phi nodes, it is not getting what we want.

I also added a whole bunch of similar tests in this file to test the folding with various arithmetic operations. From the point of functionality, the unit tests work as intended; from aesthetic point of view, they are ugly and perhaps unnecessarily complicated. 

We could improve their formats, to make it even more simplified, but it is just labor work.

2023-10-11 10:45 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMInstrInfo.h
> +  static bool isFlagSettingInstruction(MachineInstr& MI) {
May I ask you to avoid resolving conversations started by me? I will do it by myself and it's simpler to check if things are done this way.

2023-10-11 11:00 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  // Can only handle folding in single MBB, single definition:
Then worth replace "can" with it's only profitable ... because since we really _can_ do it globally, but it doesn't worth.

2023-10-11 13:33 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMInstrInfo.h
> +  static bool isFlagSettingInstruction(MachineInstr& MI) {
@akiramenai I see what you meant. Originally I wanted to make it static because the underlying function is static, hence some confusion.

Now they are tagged `inline`, like other functions.

2023-10-11 13:34 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMInstrInfo.h
> +  static bool isFlagSettingInstruction(MachineInstr& MI) {
As for resolving conversations, I will leave them to be resolved by you.

2023-10-11 13:37 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  // Can only handle folding in single MBB, single definition:
done.

2023-10-11 13:42 UTC, akiramenai requested changes
Please add MIR tests and squash. After that LGTM.

2023-10-11 13:42 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  if (Uses.size() != 1)
I see. Probably worth replacing `UseReg must only be used once, which is in MI` which is the rephrasing of the code with this explaination.

2023-10-11 13:42 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +                    [&](const MachineOperand &Opnd) {
We only capture registers here, so by value is preferable, explicit capturing list is preferable as well.

2023-10-11 13:42 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  if (!TII->isPredicatedInstr(*DefMI) ||
I think it worth moving above to the single definition check. They are technically related despite we don't track conditional instructions as multiple definitions like RDF does.

2023-10-11 13:42 UTC, akiramenai commented on llvm/test/CodeGen/EraVM/select_fold.ll
> +; RUN: llc < %s | FileCheck %s
Ok I see, it's indeed probably hard to replicate. May we add MIR tests in that case?

2023-10-11 14:09 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.050 ║
║ Best                                4.651 ║
║ Worst                               0.000 ║
║ Total                               0.040 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.042 ║
║ Best                                6.478 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.026 ║
║ Best                                6.210 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.057 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.050 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.041 ║
║ Best                                5.641 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.025 ║
║ Best                                4.891 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.038 ║
║ Best                                0.314 ║
║ Worst                               0.000 ║
║ Total                               0.033 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.011 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.008 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.029 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.061 ║
║ Best                                0.385 ║
║ Worst                               0.000 ║
║ Total                               0.066 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.045 ║
║ Best                                0.890 ║
║ Worst                               0.000 ║
║ Total                               0.177 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.007 ║
║ Best                                0.301 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-10-13 03:07 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  if (!TII->isPredicatedInstr(*DefMI) ||
Done.

2023-10-13 03:07 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +                    [&](const MachineOperand &Opnd) {
good observation, updated.

2023-10-13 03:41 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.050 ║
║ Best                                4.651 ║
║ Worst                               0.000 ║
║ Total                               0.040 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.042 ║
║ Best                                6.478 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.026 ║
║ Best                                6.210 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.057 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.050 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.041 ║
║ Best                                5.641 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.025 ║
║ Best                                4.891 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.038 ║
║ Best                                0.314 ║
║ Worst                               0.000 ║
║ Total                               0.033 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.011 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.008 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.029 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.061 ║
║ Best                                0.385 ║
║ Worst                               0.000 ║
║ Total                               0.066 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.045 ║
║ Best                                0.890 ║
║ Worst                               0.000 ║
║ Total                               0.177 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.007 ║
║ Best                                0.301 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-10-13 04:52 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.050 ║
║ Best                                4.651 ║
║ Worst                               0.000 ║
║ Total                               0.040 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.042 ║
║ Best                                6.478 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.026 ║
║ Best                                6.210 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.057 ║
║ Best                                4.444 ║
║ Worst                               0.000 ║
║ Total                               0.050 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.041 ║
║ Best                                5.641 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.025 ║
║ Best                                4.891 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.038 ║
║ Best                                0.314 ║
║ Worst                               0.000 ║
║ Total                               0.033 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.011 ║
║ Best                                0.142 ║
║ Worst                               0.000 ║
║ Total                               0.008 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.029 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.061 ║
║ Best                                0.385 ║
║ Worst                               0.000 ║
║ Total                               0.066 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.045 ║
║ Best                                0.890 ║
║ Worst                               0.000 ║
║ Total                               0.177 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.007 ║
║ Best                                0.301 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-10-13 12:14 UTC, lialan commented
@akiramenai added succinct MIR tests. Can you take another look?

2023-10-15 13:13 UTC, akiramenai requested changes
Please improve tests.

2023-10-15 13:13 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMInstrInfo.h
> +  inline bool isFlagSettingInstruction(const MachineInstr &MI) {
Why to have non-const version? Why to make these function class members at all (including the original `isFlagSettingInstruction`)?

2023-10-15 13:13 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +/// This pass folds conditional move from an expanded select instructions,  with
two spaces

2023-10-15 13:13 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +/// a previous instruction.
not a previous anymore

2023-10-15 13:13 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  /// add.cc   rc, r0, rd
three spaces

2023-10-15 13:13 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  /// 4. does not have control flow diversion between the candidate and MI.
We removed this check as redundancy haven't we. Any call sets flags.

2023-10-15 13:13 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +    if (std::any_of(I.operands_begin(), I.operands_end(),
nitpicking: `[llvm::]any_if(I.operands())`. But ok as it.

2023-10-15 13:13 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  const Register PrevOutReg = getOutRegToFold(CandidateInstr);
`Prev` is no longer there here and below. Better is to replace with `Candidate`.

2023-10-15 13:13 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +bool EraVMOptimizeSelect::foldConditionalMove(MachineInstr &MI) const {
Can we const qualify `MI`?

2023-10-15 13:13 UTC, akiramenai commented on llvm/test/CodeGen/EraVM/select_fold.mir
> +...
Could we at least cover `rr` forms of other instructions we expect to fold? Negative tests for different bail out reasons are also of use here.

2023-10-15 16:31 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +bool EraVMOptimizeSelect::foldConditionalMove(MachineInstr &MI) const {
Unfortunately it is on purpose, because it will call RDA functions, which do not take const arguments.

2023-10-15 16:36 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMInstrInfo.h
> +  inline bool isFlagSettingInstruction(const MachineInstr &MI) {
1. Because RDA in the context cannot take const.
2. I did made them `static`, and you wanted to make them `inline`.

2023-10-15 19:49 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMInstrInfo.h
> +  inline bool isFlagSettingInstruction(const MachineInstr &MI) {
The function returns bool and just wraps `EraVMInstrInfo::isFlagSettingInstruction`, how does it connected with RDA?

2023-10-16 02:38 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMInstrInfo.h
> +  inline bool isFlagSettingInstruction(const MachineInstr &MI) {
sorry for not explaining clearly. It is connected to the other comment you made. in a function we got a `MachineInstr*` was returned from RDA and I had to use `isFlagSettingInstruction` on it. For completeness I just added the const version.

Guess I should just use the unwrapped uint64_t function for such check, it will make things less confusing.

2023-10-16 07:39 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMInstrInfo.h
> +  inline bool isFlagSettingInstruction(const MachineInstr &MI) {
The question is about why we have non const version of the method itself, i.e. not const qualified `this`. We don't change anything and return bool. Even better why to have it as methods at all if we don't need anything from the class. Ok I got your initial `static` intent, it wan't about ODR breakage due to definition in the header was it?

2023-10-17 04:16 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMInstrInfo.h
> +  inline bool isFlagSettingInstruction(const MachineInstr &MI) {
right, `static` function was my intend. and it was that simple because they are just wrappers, and the way it should be.  Let me just make it the way it should be.

2023-10-20 02:29 UTC, lialan commented on llvm/test/CodeGen/EraVM/select_fold.mir
> +...
So I added `rr` forms and other negative test forms to test various cases.

2023-10-20 02:29 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMOptimizeSelect.cpp
> +  const Register PrevOutReg = getOutRegToFold(CandidateInstr);
replaced.

2023-10-20 03:06 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.046 ║
║ Best                                5.405 ║
║ Worst                               0.000 ║
║ Total                               0.039 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.053 ║
║ Best                                6.584 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.031 ║
║ Best                                6.310 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.046 ║
║ Best                                4.255 ║
║ Worst                               0.000 ║
║ Total                               0.042 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.046 ║
║ Best                               11.135 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.027 ║
║ Best                                4.993 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.021 ║
║ Best                                0.359 ║
║ Worst                               0.000 ║
║ Total                               0.022 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.010 ║
║ Best                                0.155 ║
║ Worst                               0.000 ║
║ Total                               0.008 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.029 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.037 ║
║ Best                                0.304 ║
║ Worst                               0.000 ║
║ Total                               0.041 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.040 ║
║ Best                                0.890 ║
║ Worst                               0.000 ║
║ Total                               0.175 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.006 ║
║ Best                                0.301 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

```

2023-10-20 19:20 UTC, akiramenai approved these changes

2023-10-20 19:23 UTC, merged