[WIP][EraVM] Add a pass to recognize mem-ops for their indexed version
matter-labs/era-compiler-llvm pull request #313
Opened 2023-10-01 03:52 UTC by TerryGuo

Find mem-ops that can be optimized to indexed version, re-write them into patterns that can be recognized by the subsequent combine pass where the original mem-ops will be replaced by their indexed version.

2023-10-02 10:39 UTC, akiramenai reviewed
The overall approach looks good to me, thank you @TerryGuo. Two caveats:
1. I'm sure if we need to stick with existing selection patterns because they make the transformation local.
2. It looks like we don't consider possibility to use incremented index as the index for the loop itself. I mean transforming
```
for (int I = 0; I < E; ++I)
  a[I] = LoopInvariant;
```
into
```
for (int I = 0; I < E * 32;)
  storeandincrement(a[I], LoopInvariant, &I)
```
Where `storeandincrement` lifts semantic of an indexed operation to a higher level.

I also commented on some stylistic issues. I see this is a draft, but just to show the expectations early. I hope these comments will be of help.

2023-10-02 10:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +class SyncVMIndexedMemOpsRecognize : public LoopPass {
As far as I understand we find a gep a spilt loop independent part from the one which depends on index, and then we reuse selection patterns added by @lialan. Am I at least approximately right?
Could we add the whole design description here to simplify further reading?

2023-10-02 10:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +  bool RemoveLoopVariantFromGEP(Instruction *GEPInst);
Style: Could we follow [LLVM coding style](https://llvm.org/docs/CodingStandards.html#name-types-functions-variables-and-enumerators-properly)?

2023-10-02 10:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +  bool RemoveLoopVariantFromGEP(Instruction *GEPInst);
Methods also worth documenting.

2023-10-02 10:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +  bool IsIncByOneCell(Value *BasePtrValue);
const?

2023-10-02 10:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +  bool RewriteToFavorIndexedLdST(Value *BasePtrValue, Instruction *currentI,
Maintainability: Having `currentBB`, `currentL` depend on `currentI` I suggest to remove this redundancy from the interface to not to break `currentBB == currentI ->getParent()`, etc. invariants., and infer what is needed inside the function. The performance drawback shouldn't be significant if at all.
I wouldn't also use word `current` in the interface as it suggest some mutable state in considered, imo `MemoryInst` would be a better name.

2023-10-02 10:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +bool SyncVMIndexedMemOpsRecognize::RemoveLoopVariantFromGEP(Instruction *GEPInst) {
Please `clang-format` (LLVM style)

2023-10-02 10:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +    Value *IndiceOp = GEPInst->getOperand(Op);
`IndexOp`

2023-10-02 10:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +    const SCEV *Ptr = SE->getSCEV(IndiceOp);
Could be done inside `if` since we use C++17.

2023-10-02 10:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +      GEPInst->setOperand(Op, ConstantInt::get(IndiceOp->getType(), 0U));
It looks like we only replace the first occurrence of non-const GEP index for which we can get SCEV. Looks very error-prone to me unless there are some invariant for `getSCEV` I'm unaware of. Worth adding things like `gep variable1, const1, variable2`, etc to tests.

2023-10-02 10:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +// This GEP instruction is used to define base ptr of followed load
Better is to rephrase because a reader expects a function doc here. While GEP you refer to is a parameter.

2023-10-02 10:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +  auto *GEPInst = dyn_cast<GetElementPtrInst>(BasePtrValue);
As it's a precondition, better is to put it to the signature and assert nonull.

2023-10-02 10:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +  // of load/store instruction.
This is due to our selection pattern restrictions, right?
When we manage to get correctness, it worth to check if we can benefit from relaxing it e.g. using an intrinsic.

2023-10-02 10:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +  // This is simple case of GEP which contains only one operand in indice.
Comments that literally repeat what is written in the next LOC only create line noise.

2023-10-02 10:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +    BasicBlock *PreheaderBB = currentL->getLoopPreheader();
Could we unify code duplicated in `if` and `else`?

2023-10-02 10:39 UTC, akiramenai commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +  if (!isa<GetElementPtrInst>(BasePtrValue))
Also worth put `GetElementPtrInst` to the signature to make it more explicit.

2023-10-02 10:39 UTC, akiramenai commented on llvm/test/CodeGen/SyncVM/indexedMemOps.ll
> +
Could we add as well minimal examples for indexed load and store which doesn't involve intrinsic expansion?

2023-10-11 11:34 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.008 ║
║ Best                                6.897 ║
║ Worst                              -4.878 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.046 ║
║ Best                               12.329 ║
║ Worst                              -0.758 ║
║ Total                               0.015 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.021 ║
║ Best                                6.740 ║
║ Worst                              -0.641 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.072 ║
║ Best                                7.299 ║
║ Worst                              -4.651 ║
║ Total                               0.102 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.087 ║
║ Best                               31.496 ║
║ Worst                             -24.625 ║
║ Total                               0.023 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.032 ║
║ Best                               19.769 ║
║ Worst                             -13.463 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.013 ║
║ Best                                0.669 ║
║ Worst                              -0.025 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.012 ║
║ Best                                1.331 ║
║ Worst                               0.000 ║
║ Total                               0.152 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                                0.341 ║
║ Worst                              -0.001 ║
║ Total                               0.003 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.065 ║
║ Best                                2.020 ║
║ Worst                              -0.107 ║
║ Total                               0.061 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.032 ║
║ Best                                1.294 ║
║ Worst                              -0.078 ║
║ Total                               0.146 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.004 ║
║ Best                                0.437 ║
║ Worst                              -0.001 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

```

2023-10-12 14:26 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.008 ║
║ Best                                6.897 ║
║ Worst                              -4.878 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.046 ║
║ Best                               12.329 ║
║ Worst                              -0.758 ║
║ Total                               0.015 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.021 ║
║ Best                                6.740 ║
║ Worst                              -0.641 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.072 ║
║ Best                                7.299 ║
║ Worst                              -4.651 ║
║ Total                               0.102 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.087 ║
║ Best                               31.496 ║
║ Worst                             -24.625 ║
║ Total                               0.023 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.032 ║
║ Best                               19.769 ║
║ Worst                             -13.463 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.013 ║
║ Best                                0.669 ║
║ Worst                              -0.025 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.012 ║
║ Best                                1.331 ║
║ Worst                               0.000 ║
║ Total                               0.152 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                                0.341 ║
║ Worst                              -0.001 ║
║ Total                               0.003 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.065 ║
║ Best                                2.020 ║
║ Worst                              -0.107 ║
║ Total                               0.061 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.032 ║
║ Best                                1.294 ║
║ Worst                              -0.078 ║
║ Total                               0.146 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.004 ║
║ Best                                0.437 ║
║ Worst                              -0.001 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

```

2023-10-12 18:29 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.008 ║
║ Best                                6.897 ║
║ Worst                              -4.878 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.046 ║
║ Best                               12.329 ║
║ Worst                              -0.758 ║
║ Total                               0.015 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.021 ║
║ Best                                6.740 ║
║ Worst                              -0.641 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.072 ║
║ Best                                7.299 ║
║ Worst                              -4.651 ║
║ Total                               0.102 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.087 ║
║ Best                               31.496 ║
║ Worst                             -24.625 ║
║ Total                               0.023 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.032 ║
║ Best                               19.769 ║
║ Worst                             -13.463 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.013 ║
║ Best                                0.669 ║
║ Worst                              -0.025 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.012 ║
║ Best                                1.331 ║
║ Worst                               0.000 ║
║ Total                               0.152 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                                0.341 ║
║ Worst                              -0.001 ║
║ Total                               0.003 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.065 ║
║ Best                                2.020 ║
║ Worst                              -0.107 ║
║ Total                               0.061 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.032 ║
║ Best                                1.294 ║
║ Worst                              -0.078 ║
║ Total                               0.146 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.004 ║
║ Best                                0.437 ║
║ Worst                              -0.001 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

```

2023-10-12 23:35 UTC, TerryGuo commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +  bool RewriteToFavorIndexedLdST(Value *BasePtrValue, Instruction *currentI,
The currentI is changed to MemOpInst now and the currentBB can be got from MemOpInst->getParent(). However the currentL which means current loop is still required, seems to me there is no other way to get it.

2023-10-12 23:36 UTC, TerryGuo commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +  bool IsIncByOneCell(Value *BasePtrValue);
Indeed. Added now.

2023-10-12 23:41 UTC, TerryGuo commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +class SyncVMIndexedMemOpsRecognize : public LoopPass {
You are absolutely right. The algorithm is all about how to find such load/store instruction and GEP instruction, once we find them, we need to properly handle/re-write GEP instruction, in the end we will generate new GEP instructions, those new GEP instructions together with the original load/store instructions will be recognised by lialan's pass to generate indexed load/store instruction.
I added such description in the head of my source file.

2023-10-13 01:15 UTC, TerryGuo commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +// This GEP instruction is used to define base ptr of followed load
Move comment to where this function is declared.

2023-10-13 01:16 UTC, TerryGuo commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +  // of load/store instruction.
This restriction is removed now.

2023-10-13 01:17 UTC, TerryGuo commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +  if (!isa<GetElementPtrInst>(BasePtrValue))
Done.

2023-10-13 01:17 UTC, TerryGuo commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +    BasicBlock *PreheaderBB = currentL->getLoopPreheader();
Done.

2023-10-13 01:18 UTC, TerryGuo commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +  // This is simple case of GEP which contains only one operand in indice.
Removed now.

2023-10-13 01:19 UTC, TerryGuo commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +bool SyncVMIndexedMemOpsRecognize::RemoveLoopVariantFromGEP(Instruction *GEPInst) {
Sure. This function is not needed and removed now. But I will use clang-format to format the whole file.

2023-10-13 01:20 UTC, TerryGuo commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +    Value *IndiceOp = GEPInst->getOperand(Op);
This for loop is not needed and removed. Now I only check the last index operand.

2023-10-13 02:54 UTC, TerryGuo commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +    const SCEV *Ptr = SE->getSCEV(IndiceOp);
This code is not needed and removed now.

2023-10-13 02:54 UTC, TerryGuo commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +  bool RemoveLoopVariantFromGEP(Instruction *GEPInst);
Updated per comments now.

2023-10-13 03:14 UTC, TerryGuo commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +  auto *GEPInst = dyn_cast<GetElementPtrInst>(BasePtrValue);
Assert added now.

2023-10-13 03:18 UTC, TerryGuo commented on llvm/lib/Target/SyncVM/SyncVMIndexedMemOpsRecognize.cpp
> +      GEPInst->setOperand(Op, ConstantInt::get(IndiceOp->getType(), 0U));
This is changed now. The loop is removed. The new algorithm will check the last index operand of GEP instruction. We can continue the discussion against the updated patch.

2023-10-13 03:47 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.008 ║
║ Best                                6.897 ║
║ Worst                              -4.878 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.046 ║
║ Best                               12.329 ║
║ Worst                              -0.758 ║
║ Total                               0.015 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.021 ║
║ Best                                6.740 ║
║ Worst                              -0.641 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.072 ║
║ Best                                7.299 ║
║ Worst                              -4.651 ║
║ Total                               0.102 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.087 ║
║ Best                               31.496 ║
║ Worst                             -24.625 ║
║ Total                               0.023 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.032 ║
║ Best                               19.769 ║
║ Worst                             -13.463 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.013 ║
║ Best                                0.669 ║
║ Worst                              -0.025 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.012 ║
║ Best                                1.331 ║
║ Worst                               0.000 ║
║ Total                               0.152 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                                0.341 ║
║ Worst                              -0.001 ║
║ Total                               0.003 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.065 ║
║ Best                                2.020 ║
║ Worst                              -0.107 ║
║ Total                               0.061 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.032 ║
║ Best                                1.294 ║
║ Worst                              -0.078 ║
║ Total                               0.146 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.004 ║
║ Best                                0.437 ║
║ Worst                              -0.001 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

```

2023-10-13 12:24 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.008 ║
║ Best                                6.897 ║
║ Worst                              -4.878 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.046 ║
║ Best                               12.329 ║
║ Worst                              -0.758 ║
║ Total                               0.015 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.021 ║
║ Best                                6.740 ║
║ Worst                              -0.641 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.072 ║
║ Best                                7.299 ║
║ Worst                              -4.651 ║
║ Total                               0.102 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.087 ║
║ Best                               31.496 ║
║ Worst                             -24.625 ║
║ Total                               0.023 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.032 ║
║ Best                               19.769 ║
║ Worst                             -13.463 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.013 ║
║ Best                                0.669 ║
║ Worst                              -0.025 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.012 ║
║ Best                                1.331 ║
║ Worst                               0.000 ║
║ Total                               0.152 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                                0.341 ║
║ Worst                              -0.001 ║
║ Total                               0.003 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.065 ║
║ Best                                2.020 ║
║ Worst                              -0.107 ║
║ Total                               0.061 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.032 ║
║ Best                                1.294 ║
║ Worst                              -0.078 ║
║ Total                               0.146 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.004 ║
║ Best                                0.437 ║
║ Worst                              -0.001 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

```

2023-10-15 01:09 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.008 ║
║ Best                                6.897 ║
║ Worst                              -4.878 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.046 ║
║ Best                               12.329 ║
║ Worst                              -0.758 ║
║ Total                               0.015 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.021 ║
║ Best                                6.740 ║
║ Worst                              -0.641 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.072 ║
║ Best                                7.299 ║
║ Worst                              -4.651 ║
║ Total                               0.102 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.087 ║
║ Best                               31.496 ║
║ Worst                             -24.625 ║
║ Total                               0.023 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.032 ║
║ Best                               19.769 ║
║ Worst                             -13.463 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.013 ║
║ Best                                0.669 ║
║ Worst                              -0.025 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.012 ║
║ Best                                1.331 ║
║ Worst                               0.000 ║
║ Total                               0.152 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                                0.341 ║
║ Worst                              -0.001 ║
║ Total                               0.003 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.065 ║
║ Best                                2.020 ║
║ Worst                              -0.107 ║
║ Total                               0.061 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.032 ║
║ Best                                1.294 ║
║ Worst                              -0.078 ║
║ Total                               0.146 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.004 ║
║ Best                                0.437 ║
║ Worst                              -0.001 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

```

2023-10-15 10:57 UTC, TerryGuo commented on llvm/test/CodeGen/SyncVM/indexedMemOps.ll
> +
Tests added now.

2023-10-15 20:42 UTC, akiramenai reviewed
Thank you for update, Terry.
The documentation in the begging of the pass file is just awesome!
Could we do some final experiments? It also seems to me that some of my comments to the previous version of the patch remain unaddressed.

2023-10-15 20:42 UTC, akiramenai commented on llvm/test/CodeGen/EraVM/indexed-memops.ll
> +; CHECK:   add        1, [[INDEX0]], [[INDEX0]]
Can we check if we can move the pass to where the rest of loop optimizations happen? Wouldn't it allow us to remove index as redundant? Here particularly we can compare r1 or r2 with their limit value instead of using index. I think existing SCEV-based transformations should perform things like that.
Or such a move would make LLVM to transform what we've done here back?

2023-10-15 20:42 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMIndexedMemOpsPrepare.cpp
> +//   %BasePtr = GEP  %BaseAddr, %indicesX, ..., %PtrInc
two spaces here and in the line below

2023-10-19 12:06 UTC, TerryGuo commented on llvm/test/CodeGen/EraVM/indexed-memops.ll
> +; CHECK:   add        1, [[INDEX0]], [[INDEX0]]
Hi @akiramenai , sorry for my later response. I was struggling to cherry-pick some loop passes right after my pass and no luck. Now I will try to move my pass before some loop passes to see the results. Thanks for you reminding.

2023-10-23 05:42 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMIndexedMemOpsPrepare.cpp
> +//   %BasePtr = GEP  %BaseAddr, %indicesX, ..., %PtrInc
Deleted now.

2023-10-23 05:43 UTC, TerryGuo commented on llvm/test/CodeGen/EraVM/indexed-memops.ll
> +; CHECK:   add        1, [[INDEX0]], [[INDEX0]]
Patch is updated to use plain register number now.

2023-10-23 12:47 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.015 ║
║ Best                                7.407 ║
║ Worst                              -5.128 ║
║ Total                               0.029 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.074 ║
║ Best                               28.389 ║
║ Worst                              -4.348 ║
║ Total                               0.027 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.032 ║
║ Best                               22.175 ║
║ Worst                              -1.296 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.082 ║
║ Best                               18.182 ║
║ Worst                              -4.040 ║
║ Total                               0.125 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.104 ║
║ Best                               40.199 ║
║ Worst                             -16.289 ║
║ Total                               0.035 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.040 ║
║ Best                               27.794 ║
║ Worst                              -8.601 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.037 ║
║ Best                                1.159 ║
║ Worst                              -0.059 ║
║ Total                               0.082 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.048 ║
║ Best                                6.395 ║
║ Worst                               0.000 ║
║ Total                               0.198 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.009 ║
║ Best                                2.193 ║
║ Worst                              -0.001 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.076 ║
║ Best                                2.062 ║
║ Worst                              -0.512 ║
║ Total                               0.106 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.070 ║
║ Best                                6.571 ║
║ Worst                              -0.036 ║
║ Total                               0.193 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.012 ║
║ Best                                3.197 ║
║ Worst                              -0.001 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-10-23 14:06 UTC, lialan commented on llvm/test/CodeGen/EraVM/indexed-memops.ll
> +; CHECK:   add        1, r4
`add 1, r4, r4`?

2023-10-23 14:07 UTC, lialan commented on llvm/test/CodeGen/EraVM/indexed-memops.ll
> +; CHECK: .BB0_1:
use `CHECK-NEXT` can make sure we are not emitting extra things.

2023-10-23 14:24 UTC, lialan commented on llvm/test/CodeGen/EraVM/indexed-memops.ll
> +; CHECK:   shl.s      5,  r2, r5
I guess it is a separate optimization opportunity: 
we could "canonicalize" the loop index in our way (instead of adding 2 to it each time, add 2<<5) to avoid the shift. Given that cell-addressing has a lot to do with shift left by 5.

2023-10-23 15:37 UTC, akiramenai requested changes
TODO is important. The rest is mostly nitpickings, but they improve readability imo.

2023-10-23 15:37 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMIndexedMemOpsPrepare.cpp
> +//       indice operands. If it contains only one indice operand and
The singular form of indices is index. Could we correct everywhere in the comments and code?

2023-10-23 15:37 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMIndexedMemOpsPrepare.cpp
> +//       add.
Shall we add that the pass is supposed to be run after memory intrinsic expansion?

2023-10-23 15:37 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMIndexedMemOpsPrepare.cpp
> +  bool isValidGEPAndIncByOneCell(Value *BasePtr, Loop *currentL) const;
Instead of saying in the doc `BasePtr should be defined by a GEP instruction`, we could declare BasePtr datatype to be GEP instruction so we don't need to assert.
`currentL` could (and I can argue why it should if needed) be placed to the class fields.

2023-10-23 15:37 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMIndexedMemOpsPrepare.cpp
> +  const PHINode *PHI = dyn_cast<PHINode>(GEPInst->getOperand(LastIndiceIdx));
`cast`, as you dereference it anyway. Also worth putting this constraint to the doc.

2023-10-23 15:37 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMIndexedMemOpsPrepare.cpp
> +    dyn_cast<GetElementPtrInst>(IncNewBasePtr)->setIsInBounds(false);
cast

2023-10-23 15:37 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMIndexedMemOpsPrepare.cpp
> +  const bool IsGEPInBount = GEPInst->isInBounds();
typo: IsGEPInBounds

2023-10-23 15:37 UTC, akiramenai commented on llvm/test/CodeGen/EraVM/indexed-memops.ll
> +; CHECK:   add        1, r4, r4
Could we add
`TODO: CPR-1421 Remove loop index`
Here and in other places where applicable.

2023-10-23 15:37 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMIndexedMemOpsPrepare.cpp
> +  const PHINode *PHI = dyn_cast<PHINode>(GEPInst->getOperand(LastIndiceIdx));
Also redundant type duplication in LHS, auto (auto*) is preferred when type is clear from RHS.

2023-10-23 19:29 UTC, akiramenai commented on llvm/test/CodeGen/EraVM/indexed-memops.ll
> +; CHECK:   add        1, r4, r4
Also for loop index removal, I appreciate if you can share your findings in more details to decide if we should prioritise this work.

2023-10-24 14:47 UTC, TerryGuo commented on llvm/test/CodeGen/EraVM/indexed-memops.ll
> +; CHECK:   add        1, r4
Thanks Alan. Fix it now.

2023-10-24 15:17 UTC, TerryGuo commented on llvm/test/CodeGen/EraVM/indexed-memops.ll
> +; CHECK: .BB0_1:
Thanks Alan. Use CHECK-NEXT now.

2023-10-24 15:28 UTC, TerryGuo commented on llvm/test/CodeGen/EraVM/indexed-memops.ll
> +; CHECK:   shl.s      5,  r2, r5
@akiramenai did mentioned it is better to rewrite the loop-index or the loop-exit instruction. Use the already increased array address to judge the loop exit rather than the loop-index.  If indexed load/store is used, the array address will be increased along with the iteration anyway. Not sure if this is the same idea as yours.

Meanwhile this case roughly equals like:
`
for (int i = 0; i < size; i++) {
  a[i] = b[2*i];
}
`
I think the shl.s instruction inside loop is required for calculating address of element of b array.

2023-10-24 15:29 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMIndexedMemOpsPrepare.cpp
> +//       indice operands. If it contains only one indice operand and
Sure.

2023-10-24 15:46 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMIndexedMemOpsPrepare.cpp
> +//       add.
Agree. It is added now.

2023-10-24 16:08 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMIndexedMemOpsPrepare.cpp
> +  bool isValidGEPAndIncByOneCell(Value *BasePtr, Loop *currentL) const;
Patch is changed per you suggestion.

2023-10-24 16:15 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMIndexedMemOpsPrepare.cpp
> +  const PHINode *PHI = dyn_cast<PHINode>(GEPInst->getOperand(LastIndiceIdx));
Done. The constraint is already mentioned in the doc `The BasePtr is defined by a GEP instruction of which the last index operand is defined by a PHI node `

2023-10-24 16:16 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMIndexedMemOpsPrepare.cpp
> +    dyn_cast<GetElementPtrInst>(IncNewBasePtr)->setIsInBounds(false);
Fixed.

2023-10-24 16:16 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMIndexedMemOpsPrepare.cpp
> +  const bool IsGEPInBount = GEPInst->isInBounds();
Fixed.

2023-10-24 16:44 UTC, TerryGuo commented on llvm/test/CodeGen/EraVM/indexed-memops.ll
> +; CHECK:   add        1, r4, r4
TODO is added to test and code. As for loop index removal, I also have strong interest to implement it. Sharing my findings and having chances to discuss with you guys are something I am happy to do. I just want to know how to share. Via google doc or something else?

2023-10-24 17:16 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.015 ║
║ Best                                7.407 ║
║ Worst                              -5.128 ║
║ Total                               0.029 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.074 ║
║ Best                               28.389 ║
║ Worst                              -4.348 ║
║ Total                               0.027 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.032 ║
║ Best                               22.175 ║
║ Worst                              -1.296 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.082 ║
║ Best                               18.182 ║
║ Worst                              -4.040 ║
║ Total                               0.125 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.104 ║
║ Best                               40.199 ║
║ Worst                             -16.289 ║
║ Total                               0.035 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.040 ║
║ Best                               27.794 ║
║ Worst                              -8.601 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.037 ║
║ Best                                1.159 ║
║ Worst                              -0.059 ║
║ Total                               0.082 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.048 ║
║ Best                                6.395 ║
║ Worst                               0.000 ║
║ Total                               0.198 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.009 ║
║ Best                                2.193 ║
║ Worst                              -0.001 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.076 ║
║ Best                                2.062 ║
║ Worst                              -0.512 ║
║ Total                               0.106 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.070 ║
║ Best                                6.571 ║
║ Worst                              -0.036 ║
║ Total                               0.193 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.012 ║
║ Best                                3.197 ║
║ Worst                              -0.001 ║
║ Total                               0.005 ║
╚═══════════════════════════════════════════╝

```

2023-10-24 21:34 UTC, akiramenai commented on llvm/test/CodeGen/EraVM/indexed-memops.ll
> +; CHECK:   add        1, r4, r4
@TerryGuo google doc will work. Thank you.

2023-10-24 21:53 UTC, akiramenai approved these changes
LGTM, thanks!

2023-10-24 21:55 UTC, akiramenai commented on llvm/test/CodeGen/EraVM/indexed-memops.ll
> +; CHECK:   shl.s      5,  r2, r5
@lialan I think we got this shift much later in the pipeline, but the transformation makes a perfect sense in an MIR pass. Please create a ticket.

2023-10-24 21:56 UTC, merged