[SyncVM] Optimize select sequence by tying src to dst regs
matter-labs/era-compiler-llvm pull request #317
Opened 2023-10-03 14:33 UTC by lialan

2023-10-03 15:12 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.004 ║
║ Best                                5.405 ║
║ Worst                              -0.204 ║
║ Total                               0.004 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.002 ║
║ Best                                4.425 ║
║ Worst                              -0.046 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.001 ║
║ Best                                3.922 ║
║ Worst                              -0.005 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.011 ║
║ Best                                0.325 ║
║ Worst                               0.000 ║
║ Total                               0.025 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.002 ║
║ Best                                0.488 ║
║ Worst                              -0.046 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.020 ║
║ Worst                              -0.005 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-10-03 17:33 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.004 ║
║ Best                                5.405 ║
║ Worst                              -0.548 ║
║ Total                               0.005 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.003 ║
║ Best                                4.425 ║
║ Worst                              -0.771 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.001 ║
║ Best                                3.922 ║
║ Worst                              -0.575 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.009 ║
║ Best                                0.325 ║
║ Worst                              -0.326 ║
║ Total                               0.025 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.002 ║
║ Best                                0.488 ║
║ Worst                              -0.046 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.020 ║
║ Worst                              -0.005 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-10-03 18:20 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                                0.004 ║
║ Best                                5.405 ║
║ Worst                              -0.548 ║
║ Total                               0.005 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                                0.003 ║
║ Best                                4.425 ║
║ Worst                              -0.771 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.001 ║
║ Best                                3.922 ║
║ Worst                              -0.575 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                                0.009 ║
║ Best                                0.325 ║
║ Worst                              -0.326 ║
║ Total                               0.025 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.002 ║
║ Best                                0.488 ║
║ Worst                              -0.046 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.000 ║
║ Best                                0.020 ║
║ Worst                              -0.005 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-10-03 19:12 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞═════════════════════╡ All ╞═╗
║ Mean                               -0.658 ║
║ Best                                6.452 ║
║ Worst                              -8.000 ║
║ Total                              -0.396 ║
╠═╡ Cycles (-%) ╞═══════════════════╡ All ╞═╣
║ Mean                               -0.095 ║
║ Best                               12.195 ║
║ Worst                             -27.273 ║
║ Total                               0.025 ║
╠═╡ Ergs (-%) ╞═════════════════════╡ All ╞═╣
║ Mean                                0.047 ║
║ Best                                8.333 ║
║ Worst                             -18.629 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞═══════════════╡ Real life ╞═╗
║ Mean                               -0.061 ║
║ Best                                0.521 ║
║ Worst                              -2.020 ║
║ Total                              -0.033 ║
╠═╡ Cycles (-%) ╞═════════════╡ Real life ╞═╣
║ Mean                                0.186 ║
║ Best                                4.615 ║
║ Worst                              -2.326 ║
║ Total                               0.047 ║
╠═╡ Ergs (-%) ╞═══════════════╡ Real life ╞═╣
║ Mean                                0.066 ║
║ Best                                2.970 ║
║ Worst                              -1.330 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

```

2023-10-06 01:44 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.696 ║
║ Best                                6.452 ║
║ Worst                              -6.593 ║
║ Total                               0.643 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.725 ║
║ Best                                5.769 ║
║ Worst                             -13.056 ║
║ Total                               0.183 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.263 ║
║ Best                                4.960 ║
║ Worst                             -12.072 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.596 ║
║ Best                                6.452 ║
║ Worst                              -1.600 ║
║ Total                               0.556 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.726 ║
║ Best                               12.195 ║
║ Worst                             -26.818 ║
║ Total                               0.173 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.294 ║
║ Best                                8.333 ║
║ Worst                             -15.259 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.280 ║
║ Best                                0.988 ║
║ Worst                               0.000 ║
║ Total                               0.331 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.495 ║
║ Best                                3.509 ║
║ Worst                               0.000 ║
║ Total                               0.176 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.079 ║
║ Best                                2.326 ║
║ Worst                               0.000 ║
║ Total                               0.006 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.181 ║
║ Best                                0.771 ║
║ Worst                               0.000 ║
║ Total                               0.231 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                1.049 ║
║ Best                                6.154 ║
║ Worst                               0.000 ║
║ Total                               0.539 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.209 ║
║ Best                                3.960 ║
║ Worst                               0.000 ║
║ Total                               0.016 ║
╚═══════════════════════════════════════════╝

```

2023-10-09 15:10 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.696 ║
║ Best                                6.452 ║
║ Worst                              -6.593 ║
║ Total                               0.643 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.725 ║
║ Best                                5.769 ║
║ Worst                             -13.056 ║
║ Total                               0.183 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.263 ║
║ Best                                4.960 ║
║ Worst                             -12.072 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.596 ║
║ Best                                6.452 ║
║ Worst                              -1.600 ║
║ Total                               0.556 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.726 ║
║ Best                               12.195 ║
║ Worst                             -26.818 ║
║ Total                               0.173 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.294 ║
║ Best                                8.333 ║
║ Worst                             -15.259 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.280 ║
║ Best                                0.988 ║
║ Worst                               0.000 ║
║ Total                               0.331 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.495 ║
║ Best                                3.509 ║
║ Worst                               0.000 ║
║ Total                               0.176 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.079 ║
║ Best                                2.326 ║
║ Worst                               0.000 ║
║ Total                               0.006 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.181 ║
║ Best                                0.771 ║
║ Worst                               0.000 ║
║ Total                               0.231 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                1.049 ║
║ Best                                6.154 ║
║ Worst                               0.000 ║
║ Total                               0.539 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.209 ║
║ Best                                3.960 ║
║ Worst                               0.000 ║
║ Total                               0.016 ║
╚═══════════════════════════════════════════╝

```

2023-10-09 16:00 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.696 ║
║ Best                                6.452 ║
║ Worst                              -6.593 ║
║ Total                               0.643 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.725 ║
║ Best                                5.769 ║
║ Worst                             -13.056 ║
║ Total                               0.183 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.263 ║
║ Best                                4.960 ║
║ Worst                             -12.072 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.596 ║
║ Best                                6.452 ║
║ Worst                              -1.600 ║
║ Total                               0.556 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.726 ║
║ Best                               12.195 ║
║ Worst                             -26.818 ║
║ Total                               0.173 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.294 ║
║ Best                                8.333 ║
║ Worst                             -15.259 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.280 ║
║ Best                                0.988 ║
║ Worst                               0.000 ║
║ Total                               0.331 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.495 ║
║ Best                                3.509 ║
║ Worst                               0.000 ║
║ Total                               0.176 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.079 ║
║ Best                                2.326 ║
║ Worst                               0.000 ║
║ Total                               0.006 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.181 ║
║ Best                                0.771 ║
║ Worst                               0.000 ║
║ Total                               0.231 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                1.049 ║
║ Best                                6.154 ║
║ Worst                               0.000 ║
║ Total                               0.539 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.209 ║
║ Best                                3.960 ║
║ Worst                               0.000 ║
║ Total                               0.016 ║
╚═══════════════════════════════════════════╝

```

2023-10-10 21:19 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.694 ║
║ Best                                6.452 ║
║ Worst                              -6.593 ║
║ Total                               0.640 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.725 ║
║ Best                                5.769 ║
║ Worst                             -13.056 ║
║ Total                               0.183 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.262 ║
║ Best                                4.960 ║
║ Worst                             -12.072 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.592 ║
║ Best                                6.452 ║
║ Worst                              -1.600 ║
║ Total                               0.552 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.726 ║
║ Best                               12.195 ║
║ Worst                             -26.818 ║
║ Total                               0.173 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.293 ║
║ Best                                8.333 ║
║ Worst                             -15.259 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.269 ║
║ Best                                0.988 ║
║ Worst                               0.000 ║
║ Total                               0.302 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.495 ║
║ Best                                3.509 ║
║ Worst                               0.000 ║
║ Total                               0.176 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.079 ║
║ Best                                2.326 ║
║ Worst                               0.000 ║
║ Total                               0.006 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.175 ║
║ Best                                0.771 ║
║ Worst                               0.000 ║
║ Total                               0.219 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                1.049 ║
║ Best                                6.154 ║
║ Worst                               0.000 ║
║ Total                               0.540 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.209 ║
║ Best                                3.960 ║
║ Worst                               0.000 ║
║ Total                               0.016 ║
╚═══════════════════════════════════════════╝

```

2023-10-11 23:04 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.676 ║
║ Best                                6.452 ║
║ Worst                              -6.593 ║
║ Total                               0.623 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.725 ║
║ Best                                5.769 ║
║ Worst                             -13.056 ║
║ Total                               0.182 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.253 ║
║ Best                                4.960 ║
║ Worst                             -12.072 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.578 ║
║ Best                                6.452 ║
║ Worst                              -2.105 ║
║ Total                               0.542 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.726 ║
║ Best                               12.195 ║
║ Worst                             -26.818 ║
║ Total                               0.172 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.284 ║
║ Best                                8.333 ║
║ Worst                             -15.259 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.263 ║
║ Best                                0.988 ║
║ Worst                               0.000 ║
║ Total                               0.304 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.489 ║
║ Best                                3.509 ║
║ Worst                               0.000 ║
║ Total                               0.172 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.079 ║
║ Best                                2.326 ║
║ Worst                               0.000 ║
║ Total                               0.006 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.176 ║
║ Best                                0.771 ║
║ Worst                               0.000 ║
║ Total                               0.224 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                1.037 ║
║ Best                                6.154 ║
║ Worst                               0.000 ║
║ Total                               0.532 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.209 ║
║ Best                                3.960 ║
║ Worst                               0.000 ║
║ Total                               0.016 ║
╚═══════════════════════════════════════════╝

```

2023-10-12 00:37 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.005 ║
║ Best                                5.405 ║
║ Worst                               0.000 ║
║ Total                               0.006 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.003 ║
║ Best                                3.226 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                                1.630 ║
║ Worst                              -0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.003 ║
║ Best                                4.651 ║
║ Worst                              -0.548 ║
║ Total                               0.004 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                                4.425 ║
║ Worst                              -0.046 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                3.922 ║
║ Worst                              -0.005 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.012 ║
║ Best                                0.201 ║
║ Worst                               0.000 ║
║ Total                               0.032 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.103 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.020 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.009 ║
║ Best                                0.325 ║
║ Worst                               0.000 ║
║ Total                               0.017 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.004 ║
║ Best                                0.488 ║
║ Worst                              -0.046 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.005 ║
║ Worst                              -0.005 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-10-12 14:38 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.676 ║
║ Best                                6.452 ║
║ Worst                              -6.593 ║
║ Total                               0.623 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.725 ║
║ Best                                5.769 ║
║ Worst                             -13.056 ║
║ Total                               0.182 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.253 ║
║ Best                                4.960 ║
║ Worst                             -12.072 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.578 ║
║ Best                                6.452 ║
║ Worst                              -2.105 ║
║ Total                               0.542 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.726 ║
║ Best                               12.195 ║
║ Worst                             -26.818 ║
║ Total                               0.172 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.284 ║
║ Best                                8.333 ║
║ Worst                             -15.259 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.263 ║
║ Best                                0.988 ║
║ Worst                               0.000 ║
║ Total                               0.304 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.489 ║
║ Best                                3.509 ║
║ Worst                               0.000 ║
║ Total                               0.172 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.079 ║
║ Best                                2.326 ║
║ Worst                               0.000 ║
║ Total                               0.006 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.176 ║
║ Best                                0.771 ║
║ Worst                               0.000 ║
║ Total                               0.224 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                1.037 ║
║ Best                                6.154 ║
║ Worst                               0.000 ║
║ Total                               0.532 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.209 ║
║ Best                                3.960 ║
║ Worst                               0.000 ║
║ Total                               0.016 ║
╚═══════════════════════════════════════════╝

```

2023-10-12 21:30 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.676 ║
║ Best                                6.452 ║
║ Worst                              -6.593 ║
║ Total                               0.623 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.725 ║
║ Best                                5.769 ║
║ Worst                             -13.056 ║
║ Total                               0.182 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.253 ║
║ Best                                4.960 ║
║ Worst                             -12.072 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.578 ║
║ Best                                6.452 ║
║ Worst                              -2.105 ║
║ Total                               0.542 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.726 ║
║ Best                               12.195 ║
║ Worst                             -26.818 ║
║ Total                               0.172 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.284 ║
║ Best                                8.333 ║
║ Worst                             -15.259 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.263 ║
║ Best                                0.988 ║
║ Worst                               0.000 ║
║ Total                               0.304 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.489 ║
║ Best                                3.509 ║
║ Worst                               0.000 ║
║ Total                               0.172 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.079 ║
║ Best                                2.326 ║
║ Worst                               0.000 ║
║ Total                               0.006 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.176 ║
║ Best                                0.771 ║
║ Worst                               0.000 ║
║ Total                               0.224 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                1.037 ║
║ Best                                6.154 ║
║ Worst                               0.000 ║
║ Total                               0.532 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.209 ║
║ Best                                3.960 ║
║ Worst                               0.000 ║
║ Total                               0.016 ║
╚═══════════════════════════════════════════╝

```

2023-10-14 05:38 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.630 ║
║ Best                                6.452 ║
║ Worst                              -6.593 ║
║ Total                               0.606 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.725 ║
║ Best                                5.769 ║
║ Worst                              -1.587 ║
║ Total                               0.173 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.258 ║
║ Best                                4.960 ║
║ Worst                              -0.826 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.392 ║
║ Best                                6.452 ║
║ Worst                              -3.390 ║
║ Total                               0.432 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.726 ║
║ Best                               12.195 ║
║ Worst                              -1.486 ║
║ Total                               0.163 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.288 ║
║ Best                                8.333 ║
║ Worst                              -0.004 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.264 ║
║ Best                                0.947 ║
║ Worst                               0.000 ║
║ Total                               0.303 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.479 ║
║ Best                                3.509 ║
║ Worst                               0.000 ║
║ Total                               0.166 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.079 ║
║ Best                                2.326 ║
║ Worst                               0.000 ║
║ Total                               0.006 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.188 ║
║ Best                                0.651 ║
║ Worst                               0.000 ║
║ Total                               0.243 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                1.039 ║
║ Best                                6.154 ║
║ Worst                               0.000 ║
║ Total                               0.536 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.209 ║
║ Best                                3.960 ║
║ Worst                               0.000 ║
║ Total                               0.016 ║
╚═══════════════════════════════════════════╝

```

2023-10-20 05:09 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.166 ║
║ Best                                7.407 ║
║ Worst                              -7.018 ║
║ Total                               0.101 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.229 ║
║ Best                                7.317 ║
║ Worst                              -1.852 ║
║ Total                               0.043 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.092 ║
║ Best                                4.967 ║
║ Worst                              -0.809 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.207 ║
║ Best                                6.452 ║
║ Worst                              -1.130 ║
║ Total                               0.234 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.253 ║
║ Best                                9.639 ║
║ Worst                              -1.724 ║
║ Total                               0.042 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.102 ║
║ Best                                7.742 ║
║ Worst                              -1.111 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.037 ║
║ Best                                0.570 ║
║ Worst                              -0.122 ║
║ Total                               0.078 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.062 ║
║ Best                                0.433 ║
║ Worst                               0.000 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.044 ║
║ Worst                              -0.127 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.134 ║
║ Best                                0.768 ║
║ Worst                               0.000 ║
║ Total                               0.177 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.501 ║
║ Best                                5.556 ║
║ Worst                               0.000 ║
║ Total                               0.421 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.081 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.010 ║
╚═══════════════════════════════════════════╝

```

2023-10-20 16:21 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                               -0.158 ║
║ Best                               16.552 ║
║ Worst                             -214.028 ║
║ Total                              -0.600 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.031 ║
║ Best                               19.608 ║
║ Worst                             -580.357 ║
║ Total                               0.018 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                               -0.039 ║
║ Best                               14.634 ║
║ Worst                             -1496.774 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.074 ║
║ Best                                9.607 ║
║ Worst                             -84.058 ║
║ Total                               0.010 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.191 ║
║ Best                               19.934 ║
║ Worst                             -169.027 ║
║ Total                               0.035 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.068 ║
║ Best                               11.648 ║
║ Worst                             -397.133 ║
║ Total                              -0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                               -0.129 ║
║ Best                                3.908 ║
║ Worst                             -28.489 ║
║ Total                              -0.084 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.061 ║
║ Best                                0.433 ║
║ Worst                              -0.103 ║
║ Total                               0.019 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                               -0.000 ║
║ Best                                0.044 ║
║ Worst                              -0.127 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                               -0.017 ║
║ Best                                2.151 ║
║ Worst                             -28.407 ║
║ Total                               0.011 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.502 ║
║ Best                                5.556 ║
║ Worst                              -0.422 ║
║ Total                               0.404 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.080 ║
║ Best                                2.996 ║
║ Worst                              -0.201 ║
║ Total                               0.009 ║
╚═══════════════════════════════════════════╝

```

2023-10-20 19:16 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.165 ║
║ Best                                7.407 ║
║ Worst                              -7.018 ║
║ Total                               0.101 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.229 ║
║ Best                                7.317 ║
║ Worst                              -1.852 ║
║ Total                               0.043 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.092 ║
║ Best                                4.967 ║
║ Worst                              -0.809 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.208 ║
║ Best                                6.452 ║
║ Worst                              -1.130 ║
║ Total                               0.237 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.253 ║
║ Best                                8.791 ║
║ Worst                              -1.724 ║
║ Total                               0.042 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.102 ║
║ Best                                6.851 ║
║ Worst                              -1.111 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.031 ║
║ Best                                0.570 ║
║ Worst                              -0.122 ║
║ Total                               0.076 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.062 ║
║ Best                                0.433 ║
║ Worst                               0.000 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.044 ║
║ Worst                              -0.127 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.134 ║
║ Best                                0.768 ║
║ Worst                               0.000 ║
║ Total                               0.185 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.501 ║
║ Best                                5.556 ║
║ Worst                               0.000 ║
║ Total                               0.421 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.081 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.010 ║
╚═══════════════════════════════════════════╝

```

2023-10-20 23:27 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.116 ║
║ Best                                7.407 ║
║ Worst                              -7.018 ║
║ Total                               0.059 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.176 ║
║ Best                                7.317 ║
║ Worst                              -6.982 ║
║ Total                               0.040 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.061 ║
║ Best                                4.967 ║
║ Worst                              -6.629 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.161 ║
║ Best                                6.452 ║
║ Worst                              -4.444 ║
║ Total                               0.195 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.207 ║
║ Best                                8.791 ║
║ Worst                             -12.531 ║
║ Total                               0.039 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.075 ║
║ Best                                6.851 ║
║ Worst                              -5.256 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.006 ║
║ Best                                0.466 ║
║ Worst                              -0.393 ║
║ Total                               0.048 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.052 ║
║ Best                                0.433 ║
║ Worst                               0.000 ║
║ Total                               0.033 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.016 ║
║ Worst                              -0.127 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.095 ║
║ Best                                0.768 ║
║ Worst                               0.000 ║
║ Total                               0.137 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.461 ║
║ Best                                5.556 ║
║ Worst                              -0.127 ║
║ Total                               0.246 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.075 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.006 ║
╚═══════════════════════════════════════════╝

```

2023-10-21 22:20 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.066 ║
║ Best                                7.407 ║
║ Worst                              -6.061 ║
║ Total                              -0.057 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.202 ║
║ Best                                7.317 ║
║ Worst                              -2.995 ║
║ Total                               0.042 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.066 ║
║ Best                                4.967 ║
║ Worst                              -2.885 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.168 ║
║ Best                                6.452 ║
║ Worst                              -4.444 ║
║ Total                               0.207 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.219 ║
║ Best                                8.791 ║
║ Worst                              -3.448 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.080 ║
║ Best                                6.851 ║
║ Worst                              -2.834 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.031 ║
║ Best                                0.570 ║
║ Worst                              -0.360 ║
║ Total                               0.075 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.060 ║
║ Best                                0.433 ║
║ Worst                              -0.035 ║
║ Total                               0.039 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.026 ║
║ Worst                              -0.127 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.117 ║
║ Best                                1.152 ║
║ Worst                               0.000 ║
║ Total                               0.160 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.501 ║
║ Best                                5.556 ║
║ Worst                              -0.127 ║
║ Total                               0.420 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.081 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.010 ║
╚═══════════════════════════════════════════╝

```

2023-10-24 14:14 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.094 ║
║ Best                                7.407 ║
║ Worst                              -6.061 ║
║ Total                              -0.004 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.205 ║
║ Best                                7.317 ║
║ Worst                             -13.987 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.071 ║
║ Best                                4.967 ║
║ Worst                             -13.364 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.168 ║
║ Best                                6.452 ║
║ Worst                              -4.444 ║
║ Total                               0.203 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.223 ║
║ Best                                8.791 ║
║ Worst                             -12.449 ║
║ Total                               0.040 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.085 ║
║ Best                                6.851 ║
║ Worst                             -10.430 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.026 ║
║ Best                                0.639 ║
║ Worst                              -0.360 ║
║ Total                               0.087 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.057 ║
║ Best                                0.433 ║
║ Worst                              -0.035 ║
║ Total                               0.039 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.048 ║
║ Worst                              -0.127 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.103 ║
║ Best                                0.768 ║
║ Worst                               0.000 ║
║ Total                               0.163 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.504 ║
║ Best                                5.556 ║
║ Worst                               0.000 ║
║ Total                               0.425 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.081 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.010 ║
╚═══════════════════════════════════════════╝

```

2023-10-24 23:49 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.094 ║
║ Best                                7.407 ║
║ Worst                              -6.061 ║
║ Total                              -0.002 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.205 ║
║ Best                                7.317 ║
║ Worst                             -13.987 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.071 ║
║ Best                                4.967 ║
║ Worst                             -13.364 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.172 ║
║ Best                                6.452 ║
║ Worst                              -4.444 ║
║ Total                               0.208 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.224 ║
║ Best                               15.000 ║
║ Worst                             -12.449 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.085 ║
║ Best                               11.960 ║
║ Worst                             -10.430 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.026 ║
║ Best                                0.639 ║
║ Worst                              -0.360 ║
║ Total                               0.089 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.057 ║
║ Best                                0.433 ║
║ Worst                              -0.035 ║
║ Total                               0.039 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.048 ║
║ Worst                              -0.127 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.112 ║
║ Best                                0.771 ║
║ Worst                               0.000 ║
║ Total                               0.174 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.504 ║
║ Best                                5.556 ║
║ Worst                               0.000 ║
║ Total                               0.426 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.081 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.010 ║
╚═══════════════════════════════════════════╝

```

2023-10-25 01:56 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.094 ║
║ Best                                7.407 ║
║ Worst                              -6.061 ║
║ Total                              -0.002 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.205 ║
║ Best                                7.317 ║
║ Worst                             -13.987 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.071 ║
║ Best                                4.967 ║
║ Worst                             -13.364 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.172 ║
║ Best                                6.452 ║
║ Worst                              -4.444 ║
║ Total                               0.208 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.224 ║
║ Best                               15.000 ║
║ Worst                             -12.449 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.085 ║
║ Best                               11.960 ║
║ Worst                             -10.430 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.026 ║
║ Best                                0.639 ║
║ Worst                              -0.360 ║
║ Total                               0.089 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.057 ║
║ Best                                0.433 ║
║ Worst                              -0.035 ║
║ Total                               0.039 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.048 ║
║ Worst                              -0.127 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.112 ║
║ Best                                0.771 ║
║ Worst                               0.000 ║
║ Total                               0.174 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.504 ║
║ Best                                5.556 ║
║ Worst                               0.000 ║
║ Total                               0.426 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.081 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.010 ║
╚═══════════════════════════════════════════╝

```

2023-10-25 03:53 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.094 ║
║ Best                                7.407 ║
║ Worst                              -6.061 ║
║ Total                              -0.002 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.205 ║
║ Best                                7.317 ║
║ Worst                             -13.987 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.071 ║
║ Best                                4.967 ║
║ Worst                             -13.364 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.172 ║
║ Best                                6.452 ║
║ Worst                              -4.444 ║
║ Total                               0.208 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.224 ║
║ Best                               15.000 ║
║ Worst                             -12.449 ║
║ Total                               0.041 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.085 ║
║ Best                               11.960 ║
║ Worst                             -10.430 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.026 ║
║ Best                                0.639 ║
║ Worst                              -0.360 ║
║ Total                               0.089 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.057 ║
║ Best                                0.433 ║
║ Worst                              -0.035 ║
║ Total                               0.039 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.048 ║
║ Worst                              -0.127 ║
║ Total                               0.001 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.112 ║
║ Best                                0.771 ║
║ Worst                               0.000 ║
║ Total                               0.174 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.504 ║
║ Best                                5.556 ║
║ Worst                               0.000 ║
║ Total                               0.426 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.081 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.010 ║
╚═══════════════════════════════════════════╝

```

2023-10-26 08:07 UTC, akiramenai requested changes
Great patch. Thank you.
A single code duplication issue needs correction.

Questions:
1. Have you checked how constraints alone affect performance?
2. They aren't mere hints right? So it could be clarified in the commit message.
3. It looks like some regression tests show perf regressions (e.g. sdiv) in some cases. Do you know why?
4. Have you measured impact on the EC precompiles. Especially ecmul.

2023-10-26 08:07 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMTieSelectOperands.cpp
> +    auto NewMI =
Code duplication with the previous `if` clause. Can we extract a function here or unify this code by any other means?

2023-10-30 19:54 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.094 ║
║ Best                                7.407 ║
║ Worst                              -6.061 ║
║ Total                              -0.000 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.231 ║
║ Best                                7.317 ║
║ Worst                             -13.987 ║
║ Total                               0.054 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.072 ║
║ Best                                4.967 ║
║ Worst                             -13.364 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.171 ║
║ Best                                6.452 ║
║ Worst                              -4.444 ║
║ Total                               0.211 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.250 ║
║ Best                               15.000 ║
║ Worst                             -12.449 ║
║ Total                               0.053 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.086 ║
║ Best                               11.960 ║
║ Worst                             -10.430 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.816 ║
║ Worst                              -0.362 ║
║ Total                               0.077 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.072 ║
║ Best                                0.435 ║
║ Worst                               0.000 ║
║ Total                               0.049 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.049 ║
║ Worst                              -0.127 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.105 ║
║ Best                                0.771 ║
║ Worst                              -1.097 ║
║ Total                               0.169 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.516 ║
║ Best                                5.556 ║
║ Worst                               0.000 ║
║ Total                               0.430 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.081 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.010 ║
╚═══════════════════════════════════════════╝

```

2023-10-31 00:33 UTC, lialan commented on llvm/lib/Target/EraVM/EraVMTieSelectOperands.cpp
> +    auto NewMI =
refactored.

2023-10-31 00:36 UTC, lialan commented
> 2. They aren't mere hints right? So it could be clarified in the commit message.

Done.

> 3. It looks like some regression tests show perf regressions (e.g. sdiv) in some cases. Do you know why?

I found that even with the `tieOperand`, the backend cannot guarantee they be assigned to a single register if the two are both virtual registers. I am going to look into it.

2023-10-31 01:15 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.094 ║
║ Best                                7.407 ║
║ Worst                              -6.061 ║
║ Total                              -0.000 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.231 ║
║ Best                                7.317 ║
║ Worst                             -13.987 ║
║ Total                               0.054 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.072 ║
║ Best                                4.967 ║
║ Worst                             -13.364 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.171 ║
║ Best                                6.452 ║
║ Worst                              -4.444 ║
║ Total                               0.211 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.250 ║
║ Best                               15.000 ║
║ Worst                             -12.449 ║
║ Total                               0.053 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.086 ║
║ Best                               11.960 ║
║ Worst                             -10.430 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.816 ║
║ Worst                              -0.362 ║
║ Total                               0.077 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.072 ║
║ Best                                0.435 ║
║ Worst                               0.000 ║
║ Total                               0.049 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.049 ║
║ Worst                              -0.127 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.105 ║
║ Best                                0.771 ║
║ Worst                              -1.097 ║
║ Total                               0.169 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.516 ║
║ Best                                5.556 ║
║ Worst                               0.000 ║
║ Total                               0.430 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.081 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.010 ║
╚═══════════════════════════════════════════╝

```

2023-11-01 16:40 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.094 ║
║ Best                                7.407 ║
║ Worst                              -6.061 ║
║ Total                              -0.000 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.231 ║
║ Best                                7.317 ║
║ Worst                             -13.987 ║
║ Total                               0.054 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.072 ║
║ Best                                4.967 ║
║ Worst                             -13.364 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.171 ║
║ Best                                6.452 ║
║ Worst                              -4.444 ║
║ Total                               0.211 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.250 ║
║ Best                               15.000 ║
║ Worst                             -12.449 ║
║ Total                               0.053 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.086 ║
║ Best                               11.960 ║
║ Worst                             -10.430 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.816 ║
║ Worst                              -0.362 ║
║ Total                               0.077 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.072 ║
║ Best                                0.435 ║
║ Worst                               0.000 ║
║ Total                               0.049 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.049 ║
║ Worst                              -0.127 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.105 ║
║ Best                                0.771 ║
║ Worst                              -1.097 ║
║ Total                               0.169 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.516 ║
║ Best                                5.556 ║
║ Worst                               0.000 ║
║ Total                               0.430 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.081 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.010 ║
╚═══════════════════════════════════════════╝

```

2023-11-01 21:19 UTC, akiramenai approved these changes

2023-11-01 21:59 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.094 ║
║ Best                                7.407 ║
║ Worst                              -6.061 ║
║ Total                              -0.000 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.231 ║
║ Best                                7.317 ║
║ Worst                             -13.987 ║
║ Total                               0.054 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.072 ║
║ Best                                4.967 ║
║ Worst                             -13.364 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.171 ║
║ Best                                6.452 ║
║ Worst                              -4.444 ║
║ Total                               0.211 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.250 ║
║ Best                               15.000 ║
║ Worst                             -12.449 ║
║ Total                               0.053 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.086 ║
║ Best                               11.960 ║
║ Worst                             -10.430 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.816 ║
║ Worst                              -0.362 ║
║ Total                               0.077 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.072 ║
║ Best                                0.435 ║
║ Worst                               0.000 ║
║ Total                               0.049 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.049 ║
║ Worst                              -0.127 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.105 ║
║ Best                                0.771 ║
║ Worst                              -1.097 ║
║ Total                               0.169 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.516 ║
║ Best                                5.556 ║
║ Worst                               0.000 ║
║ Total                               0.430 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.081 ║
║ Best                                2.996 ║
║ Worst                              -0.121 ║
║ Total                               0.010 ║
╚═══════════════════════════════════════════╝

```

2023-11-02 06:56 UTC, merged