[EraVM] Hoist flag setting instructions
matter-labs/era-compiler-llvm pull request #364
Opened 2023-11-27 14:43 UTC by vladimirradosavljevic

2023-11-27 15:23 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.021 ║
║ Best                                9.524 ║
║ Worst                              -0.525 ║
║ Total                               0.041 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.041 ║
║ Best                               16.207 ║
║ Worst                              -0.928 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.027 ║
║ Best                               12.830 ║
║ Worst                              -0.478 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.015 ║
║ Best                                6.452 ║
║ Worst                              -0.273 ║
║ Total                               0.011 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.027 ║
║ Best                               10.950 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.020 ║
║ Best                               10.801 ║
║ Worst                              -0.001 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                                0.550 ║
║ Best                                0.797 ║
║ Worst                               0.000 ║
║ Total                               0.502 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                1.056 ║
║ Best                                9.234 ║
║ Worst                               0.000 ║
║ Total                               1.445 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                1.052 ║
║ Best                                9.188 ║
║ Worst                               0.000 ║
║ Total                               0.133 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.036 ║
║ Best                                1.070 ║
║ Worst                               0.000 ║
║ Total                               0.071 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.033 ║
║ Best                                1.494 ║
║ Worst                               0.000 ║
║ Total                               0.185 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                                0.195 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.001 ║
║ Best                                0.088 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.006 ║
║ Best                                0.253 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.001 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-11-27 17:33 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.021 ║
║ Best                                9.524 ║
║ Worst                              -0.525 ║
║ Total                               0.041 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.041 ║
║ Best                               16.207 ║
║ Worst                              -0.928 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.027 ║
║ Best                               12.830 ║
║ Worst                              -0.478 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.015 ║
║ Best                                6.452 ║
║ Worst                              -0.273 ║
║ Total                               0.011 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.027 ║
║ Best                               10.950 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.020 ║
║ Best                               10.801 ║
║ Worst                              -0.001 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                                0.550 ║
║ Best                                0.797 ║
║ Worst                               0.000 ║
║ Total                               0.502 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                1.056 ║
║ Best                                9.234 ║
║ Worst                               0.000 ║
║ Total                               1.445 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                1.052 ║
║ Best                                9.188 ║
║ Worst                               0.000 ║
║ Total                               0.133 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.036 ║
║ Best                                1.070 ║
║ Worst                               0.000 ║
║ Total                               0.071 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.033 ║
║ Best                                1.494 ║
║ Worst                               0.000 ║
║ Total                               0.185 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                                0.195 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.001 ║
║ Best                                0.088 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.006 ║
║ Best                                0.253 ║
║ Worst                               0.000 ║
║ Total                               0.003 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.001 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-11-28 16:53 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.021 ║
║ Best                                9.524 ║
║ Worst                              -0.525 ║
║ Total                               0.051 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.041 ║
║ Best                               16.207 ║
║ Worst                              -0.928 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.027 ║
║ Best                               12.830 ║
║ Worst                              -0.478 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.015 ║
║ Best                                6.452 ║
║ Worst                              -0.273 ║
║ Total                               0.012 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.027 ║
║ Best                               10.950 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.020 ║
║ Best                               10.801 ║
║ Worst                              -0.001 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                                0.550 ║
║ Best                                0.797 ║
║ Worst                               0.000 ║
║ Total                               0.502 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                1.056 ║
║ Best                                9.234 ║
║ Worst                               0.000 ║
║ Total                               1.445 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                1.052 ║
║ Best                                9.188 ║
║ Worst                               0.000 ║
║ Total                               0.133 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.057 ║
║ Best                                1.982 ║
║ Worst                               0.000 ║
║ Total                               0.257 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.033 ║
║ Best                                1.494 ║
║ Worst                               0.000 ║
║ Total                               0.187 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                                0.195 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.091 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.006 ║
║ Best                                0.253 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.002 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-11-28 19:48 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.021 ║
║ Best                                9.524 ║
║ Worst                              -0.525 ║
║ Total                               0.051 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.041 ║
║ Best                               16.207 ║
║ Worst                              -0.928 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.027 ║
║ Best                               12.830 ║
║ Worst                              -0.478 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.015 ║
║ Best                                6.452 ║
║ Worst                              -0.273 ║
║ Total                               0.012 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.027 ║
║ Best                               10.950 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.020 ║
║ Best                               10.801 ║
║ Worst                              -0.001 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                                0.550 ║
║ Best                                0.797 ║
║ Worst                               0.000 ║
║ Total                               0.502 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                1.056 ║
║ Best                                9.234 ║
║ Worst                               0.000 ║
║ Total                               1.445 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                1.052 ║
║ Best                                9.188 ║
║ Worst                               0.000 ║
║ Total                               0.133 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.057 ║
║ Best                                1.982 ║
║ Worst                               0.000 ║
║ Total                               0.257 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.033 ║
║ Best                                1.494 ║
║ Worst                               0.000 ║
║ Total                               0.187 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                                0.195 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.091 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.006 ║
║ Best                                0.253 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.002 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-11-29 13:14 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.021 ║
║ Best                                9.524 ║
║ Worst                              -0.525 ║
║ Total                               0.051 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.041 ║
║ Best                               16.207 ║
║ Worst                              -0.928 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.027 ║
║ Best                               12.830 ║
║ Worst                              -0.478 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.015 ║
║ Best                                6.452 ║
║ Worst                              -0.273 ║
║ Total                               0.012 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.027 ║
║ Best                               10.950 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.020 ║
║ Best                               10.801 ║
║ Worst                              -0.001 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                                0.550 ║
║ Best                                0.797 ║
║ Worst                               0.000 ║
║ Total                               0.502 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                1.056 ║
║ Best                                9.234 ║
║ Worst                               0.000 ║
║ Total                               1.445 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                1.052 ║
║ Best                                9.188 ║
║ Worst                               0.000 ║
║ Total                               0.133 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.057 ║
║ Best                                1.982 ║
║ Worst                               0.000 ║
║ Total                               0.257 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.033 ║
║ Best                                1.494 ║
║ Worst                               0.000 ║
║ Total                               0.187 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                                0.195 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.091 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.006 ║
║ Best                                0.253 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.002 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-11-29 21:35 UTC, akiramenai requested changes

2023-11-29 21:35 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +    if (Op.isReg())
Shouldn't it be an assert?

2023-11-29 21:35 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +  switch (MI.getOpcode()) {
Could you explain why these instructions?

2023-11-29 21:35 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +  for (unsigned I = 1; I < PHI.getNumOperands(); I += 2) {
We shouldn't recompute `PHI.getNumOperands` every iteration.

2023-11-29 21:35 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +    MachineInstr *MI = MRI->getUniqueVRegDef(PHI.getOperand(I).getReg());
It looks like we rely on some canonical form of a MachineLoop PHI clause ordering. Could we be more explicit about it with asserts and/or documentation?
Also worth mentioning why a non-reg can't reach there.

2023-11-29 21:35 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +// a phi instruction which operand corresponds to the latch block, and see
The phi is given, we look for an arithmetic/bitwise/ldinc/stinc.

2023-11-29 21:35 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +// Implements a pass to hoist flag setting instructions above induction variable
an induction variable.

2023-11-29 21:35 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +// register allocator.
Should we reduce an inference chain for a reader? The hoisting makes the register allocated for an induction variable killed before the next iteration value is computed, so the register allocator is able to avoid using a temporary register. Or something alike.

2023-11-29 21:35 UTC, akiramenai commented on llvm/test/CodeGen/EraVM/hoist-flag-setting.ll
> +}
Can we add a non self-loop example?
Also if I got it right with a select the transformation could be triggered more than once for a single header BB. If so a test case for that is also welcome.

2023-11-30 11:30 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +    if (Op.isReg())
Since flagsetting instruction can have immediate operands (e.g. cond code), we need to check if operand is register. I have filtered out flags register here, since we are explicitly checking in the loop.

2023-11-30 11:30 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +  switch (MI.getOpcode()) {
I looked at the our ISA and added some instructions with side effects. If you think we don't need this check, I will remove it.

2023-11-30 11:31 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +  for (unsigned I = 1; I < PHI.getNumOperands(); I += 2) {
Done.

2023-11-30 11:35 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +    MachineInstr *MI = MRI->getUniqueVRegDef(PHI.getOperand(I).getReg());
Added comment regarding non-reg.
Could you please clarify what you have in mind with asserts? Since we can't use SCEV on MIR level to find induction variable, best thing I found is [here](https://github.com/matter-labs/compiler-llvm/blob/ff8c1afc51b987e44ba271c10780ca55659333c3/llvm/lib/Target/Hexagon/HexagonHardwareLoops.cpp#L432) how to detect it. Also, for optimization passes I would like to avoid adding asserts, since they are not pivotal.

2023-11-30 11:36 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +// a phi instruction which operand corresponds to the latch block, and see
Updated the comment.

2023-11-30 11:36 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +// Implements a pass to hoist flag setting instructions above induction variable
Done.

2023-11-30 11:36 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +// register allocator.
Updated comment. Thanks for the suggestion!

2023-11-30 11:40 UTC, vladimirradosavljevic commented on llvm/test/CodeGen/EraVM/hoist-flag-setting.ll
> +}
Added non self-loop example. Regarding select, could you please clarify? If you meant select as an induction variable, I explicitly added check that induction variable can be arithmetic/bitwise/ldinc/stinc, to avoid unpredicted behaviour.

2023-11-30 12:06 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.021 ║
║ Best                                9.524 ║
║ Worst                              -0.525 ║
║ Total                               0.051 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.041 ║
║ Best                               16.207 ║
║ Worst                              -0.928 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.027 ║
║ Best                               12.830 ║
║ Worst                              -0.478 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.015 ║
║ Best                                6.452 ║
║ Worst                              -0.273 ║
║ Total                               0.012 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.027 ║
║ Best                               10.950 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.020 ║
║ Best                               10.801 ║
║ Worst                              -0.001 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                                0.550 ║
║ Best                                0.797 ║
║ Worst                               0.000 ║
║ Total                               0.502 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                1.056 ║
║ Best                                9.234 ║
║ Worst                               0.000 ║
║ Total                               1.445 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                1.052 ║
║ Best                                9.188 ║
║ Worst                               0.000 ║
║ Total                               0.133 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.057 ║
║ Best                                1.982 ║
║ Worst                               0.000 ║
║ Total                               0.257 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.033 ║
║ Best                                1.494 ║
║ Worst                               0.000 ║
║ Total                               0.187 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                                0.195 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.091 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.006 ║
║ Best                                0.253 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.002 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-11-30 12:23 UTC, akiramenai commented on llvm/test/CodeGen/EraVM/hoist-flag-setting.ll
> +}
Got it. I was thinking if there could be foldings with something different from flag setting for branching. It looks like such foldings can't happen. Right? Perhaps worth mention explicitly in the documentation.

2023-11-30 12:35 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +  switch (MI.getOpcode()) {
We don't ourselves introduce any side effect that could be in conflict with these instruction, do we? So it might worth trying to relax this constraint, but aside from that could we somehow generalise `hasSideEffect` query instead of using `switch`?

2023-11-30 12:40 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +    MachineInstr *MI = MRI->getUniqueVRegDef(PHI.getOperand(I).getReg());
I wasn't aware about MIR PHI constraints on constant. Thank you for educating me.

2023-11-30 13:06 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMHoistFlagSetting.cpp
> +  switch (MI.getOpcode()) {
Yeah, this is me being too paranoid, and added this check. I removed this function, and left only isCall.
For MIR to check `hasSideEffect` we would need to call `hasUnmodeledSideEffects`, but then I saw that a lot of our instructions have `MCID::UnmodeledSideEffects`, so that would discard a lot of opportunities to do this transformation.

2023-11-30 13:07 UTC, vladimirradosavljevic commented on llvm/test/CodeGen/EraVM/hoist-flag-setting.ll
> +}
To the best of my knowledge, I can't think of the case where conditional branch is fed other than with flag setting instruction.

2023-11-30 13:54 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.021 ║
║ Best                                9.524 ║
║ Worst                              -0.525 ║
║ Total                               0.051 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.041 ║
║ Best                               16.207 ║
║ Worst                              -0.928 ║
║ Total                               0.002 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.027 ║
║ Best                               12.830 ║
║ Worst                              -0.478 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.015 ║
║ Best                                6.452 ║
║ Worst                              -0.273 ║
║ Total                               0.012 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.027 ║
║ Best                               10.950 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.020 ║
║ Best                               10.801 ║
║ Worst                              -0.001 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                                0.550 ║
║ Best                                0.797 ║
║ Worst                               0.000 ║
║ Total                               0.502 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                1.056 ║
║ Best                                9.234 ║
║ Worst                               0.000 ║
║ Total                               1.445 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                1.052 ║
║ Best                                9.188 ║
║ Worst                               0.000 ║
║ Total                               0.133 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.000 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.057 ║
║ Best                                1.982 ║
║ Worst                               0.000 ║
║ Total                               0.257 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.033 ║
║ Best                                1.494 ║
║ Worst                               0.000 ║
║ Total                               0.187 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                                0.195 ║
║ Worst                               0.000 ║
║ Total                               0.004 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.091 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.006 ║
║ Best                                0.253 ║
║ Worst                               0.000 ║
║ Total                               0.005 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.002 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-11-30 15:13 UTC, akiramenai approved these changes

2023-12-01 09:49 UTC, merged