Add a pass to fold select zero
matter-labs/era-compiler-llvm pull request #365
Opened 2023-11-27 15:03 UTC by TerryGuo

2023-11-29 06:30 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.008 ║
║ Best                               12.579 ║
║ Worst                               0.000 ║
║ Total                               0.034 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                               14.184 ║
║ Worst                               0.000 ║
║ Total                               0.013 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.003 ║
║ Best                               14.178 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.006 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                               0.012 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                               11.546 ║
║ Best                               12.579 ║
║ Worst                               0.000 ║
║ Total                              11.921 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.584 ║
║ Best                               14.184 ║
║ Worst                               0.000 ║
║ Total                              11.324 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.425 ║
║ Best                               14.178 ║
║ Worst                               0.000 ║
║ Total                               1.052 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                9.411 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               9.690 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.362 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                              11.011 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.152 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               1.054 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.282 ║
║ Worst                               0.000 ║
║ Total                               0.008 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.310 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.017 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.266 ║
║ Worst                               0.000 ║
║ Total                               0.011 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.274 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.018 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-11-29 08:27 UTC, vladimirradosavljevic reviewed
Great work! I know this is a WIP, but I added two comments to simplify this transformation.

2023-11-29 08:27 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +      NewMI->getOperand(2).setIsKill(NonSelectOutOpnd->isKill());
If we run this pass before `LiveVariables`, we don't need to worry about updating kills.

2023-11-29 08:27 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +      // Add an implicit tie
I think we don't need to add implicit register to tie with the output and we can do it directly to the existing register. In this case I assume we should do `NewMI->tieOperands(0, 2);`.

2023-11-29 10:30 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +      NewMI->getOperand(2).setIsKill(NonSelectOutOpnd->isKill());
Thanks. The updating is removed now.

2023-11-29 10:31 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +      // Add an implicit tie
Update to use it now.

2023-11-29 10:34 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMTargetMachine.cpp
>      addPass(&LiveVariablesID);
You should run `FoldSelectZero` before this one, because `TieSelect` depends on correct info from `LiveVariables`.

2023-11-29 10:38 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMTargetMachine.cpp
>      addPass(&LiveVariablesID);
Got it. Thanks.

2023-11-29 11:15 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.008 ║
║ Best                               12.579 ║
║ Worst                               0.000 ║
║ Total                               0.034 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                               14.184 ║
║ Worst                               0.000 ║
║ Total                               0.013 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.003 ║
║ Best                               14.178 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.006 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                               0.012 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                               11.546 ║
║ Best                               12.579 ║
║ Worst                               0.000 ║
║ Total                              11.921 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.584 ║
║ Best                               14.184 ║
║ Worst                               0.000 ║
║ Total                              11.324 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.425 ║
║ Best                               14.178 ║
║ Worst                               0.000 ║
║ Total                               1.052 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                9.411 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               9.690 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.362 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                              11.011 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.152 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               1.054 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.282 ║
║ Worst                               0.000 ║
║ Total                               0.008 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.310 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.017 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.266 ║
║ Worst                               0.000 ║
║ Total                               0.011 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.274 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.018 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-11-29 11:43 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +      // Add an implicit tie
Ah, it seems that we need to use implicit trick to pass the verifier. Sorry for the confusion!

2023-11-29 11:59 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +
Btw, we should also preserve implicit operands from select, since there is an implicit use of flags, and we are relying on that to check whether some instruction uses flags in some passes.

2023-11-29 12:16 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +      // Add an implicit tie
No problem. I just updated the code.

2023-11-29 12:22 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +
Good catch. Thanks. Added now.

2023-11-29 13:08 UTC, vladimirradosavljevic requested changes
Thanks for working on this! I have few more comments.

2023-11-29 13:08 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +//===-- EraVMFoldSelectZero.cpp - Fold special select -----------*- C++ -*-===//
Maybe we should name this pass more generic, as we presumably will use it to do more folding of select instruction. Something like EraVMFoldSelect?

2023-11-29 13:08 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +    for (MachineInstr &MI : MBB) {
Since we presumably will use this pass to do more folding of select, I think we should move this transformation into a new function and traverse through the MBB. We don't need to worry about making this transformation global (between different MBBs) right now.
If we do this, we can simply to:
```
for (MachineBasicBlock &MBB : MF)
  Changed |= newFunction(MBB);
```

2023-11-29 13:08 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +      if (std::any_of(MI.getIterator(), UseMI.getIterator(),
I think this is a good candidate to move into a new function something like [this](https://github.com/matter-labs/compiler-llvm/blob/ff8c1afc51b987e44ba271c10780ca55659333c3/llvm/lib/Target/EraVM/EraVMCombineFlagSetting.cpp#L111), to unify code in our backend.

2023-11-29 13:08 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +      NewMI.addReg(NonSelectOutOpnd->getReg(), RegState::Implicit);
I don't have strong preference, but maybe we can move this while creating NewMI above (maybe before Flags), and tie registers in the next line:
`NewMI->tieOperands(0, NewMI->getNumOperands() - 2);`

2023-11-29 13:08 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +  return ToBeRemoved.empty();
This should be `return !ToBeRemoved.empty();`? If we move this code to a new function, we can use it to detect whether we changed something.

2023-11-29 13:08 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +  std::vector<MachineInstr *> ToBeRemoved;
With this approach, while we are traversing MBBs we are adding new instructions and traversing over them, which I think it is not needed. What do you think about first finding candidates, then doing transformation, and if we put this code in a new function, we don't need to worry about memory since we won't have many candidates as we will do this transformation locally.

2023-11-29 13:08 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +        return false;
This should be continue?

2023-11-29 13:18 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.008 ║
║ Best                               12.579 ║
║ Worst                               0.000 ║
║ Total                               0.034 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                               14.184 ║
║ Worst                               0.000 ║
║ Total                               0.013 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.003 ║
║ Best                               14.178 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.006 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                               0.012 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                               11.546 ║
║ Best                               12.579 ║
║ Worst                               0.000 ║
║ Total                              11.921 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.584 ║
║ Best                               14.184 ║
║ Worst                               0.000 ║
║ Total                              11.324 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.425 ║
║ Best                               14.178 ║
║ Worst                               0.000 ║
║ Total                               1.052 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                9.411 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               9.690 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.362 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                              11.011 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.152 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               1.054 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.282 ║
║ Worst                               0.000 ║
║ Total                               0.008 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.310 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.017 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.266 ║
║ Worst                               0.000 ║
║ Total                               0.011 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.274 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.018 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-11-29 13:34 UTC, vladimirradosavljevic commented
Btw, if we change approach to first find candidates and then to transform, we should check whether `UseMI` (`ADDrrr_s` instruction) is pending for transformation.

Please take a look at the following example to demonstrate the possible issue (even though first candidate will fail because there is a def flag between sel and use, I don't mind adding paranoia checks for pending transformation 😄):
```
define i256 @test(i256 %0, i256 %1, i256 %2, i256 %3) {
entry:
  %cmp1 = icmp eq i256 %2, %3
  %sel1 = select i1 %cmp1, i256 1, i256 0
  %cmp2 = icmp eq i256 %0, %1
  %sel2 = select i1 %cmp2, i256 1, i256 0
  %ret = add i256 %sel1, %sel2
  ret i256 %ret
}
```
Please note that currently we are not performing transformation because of the `return false` instead of `continue`.

2023-11-29 15:48 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +//===-- EraVMFoldSelectZero.cpp - Fold special select -----------*- C++ -*-===//
EraVMFoldSelect is better.

2023-11-29 15:49 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +    for (MachineInstr &MI : MBB) {
Code is refactored per suggestion.

2023-11-29 15:50 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +      if (std::any_of(MI.getIterator(), UseMI.getIterator(),
Move it into a new function now.

2023-11-29 15:50 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +      NewMI.addReg(NonSelectOutOpnd->getReg(), RegState::Implicit);
Done. Changed per suggestion.

2023-11-29 15:51 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +  return ToBeRemoved.empty();
Good spot. The code is moved into a new function now.

2023-11-29 15:52 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +        return false;
Another good spot. Thanks very much. Move code into a new function now.

2023-11-29 15:58 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +  std::vector<MachineInstr *> ToBeRemoved;
Agree. However code like below will cause LLVM crash:

```c++
for (MachineInstr &MI : llvm::make_early_inc_range(MBB)) {
   ...
   MI.eraseFromParent();
  UseMI.eraseFromParent();
}
``` 

It seems to me that only the current MI can be deleted from current iteration. Deleting UseMI will cause LLVM crash. So I have to record them in a smallset and then delete them late. As you suggested, now I check whether UseMI is already marked as deleted.

2023-11-29 16:02 UTC, TerryGuo commented
> Btw, if we change approach to first find candidates and then to transform, we should check whether `UseMI` (`ADDrrr_s` instruction) is pending for transformation.
> 
> Please take a look at the following example to demonstrate the possible issue (even though first candidate will fail because there is a def flag between sel and use, I don't mind adding paranoia checks for pending transformation 😄):
> 
> ```
> define i256 @test(i256 %0, i256 %1, i256 %2, i256 %3) {
> entry:
>   %cmp1 = icmp eq i256 %2, %3
>   %sel1 = select i1 %cmp1, i256 1, i256 0
>   %cmp2 = icmp eq i256 %0, %1
>   %sel2 = select i1 %cmp2, i256 1, i256 0
>   %ret = add i256 %sel1, %sel2
>   ret i256 %ret
> }
> ```
> 
> Please note that currently we are not performing transformation because of the `return false` instead of `continue`.

Great comments. Thanks. I borrowed your code into my lit test.

2023-11-29 16:27 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.008 ║
║ Best                               12.579 ║
║ Worst                               0.000 ║
║ Total                               0.034 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                               14.184 ║
║ Worst                               0.000 ║
║ Total                               0.013 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.003 ║
║ Best                               14.178 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.006 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                               0.012 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                               11.546 ║
║ Best                               12.579 ║
║ Worst                               0.000 ║
║ Total                              11.921 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.584 ║
║ Best                               14.184 ║
║ Worst                               0.000 ║
║ Total                              11.324 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.425 ║
║ Best                               14.178 ║
║ Worst                               0.000 ║
║ Total                               1.052 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                9.411 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               9.690 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.362 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                              11.011 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.152 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               1.054 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.282 ║
║ Worst                               0.000 ║
║ Total                               0.008 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.310 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.017 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.266 ║
║ Worst                               0.000 ║
║ Total                               0.011 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.274 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.018 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-11-29 18:19 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelectZero.cpp
> +  std::vector<MachineInstr *> ToBeRemoved;
I would assume it is crashing in case where MI is followed by UseMI, and in next iteration, it is accessing UseMI but we deleted it in the previous iteration.

2023-11-29 18:39 UTC, vladimirradosavljevic approved these changes
Amazing work! LGTM when comments are addressed. Please also wait for @akiramenai to do the review.

2023-11-29 18:39 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +    if (UseMI.getOpcode() != EraVM::ADDrrr_s || UseMI.getParent() != &MBB ||
It looks like that we are checking whether MI and UseMI are in the same BB in two places, here, and in `hasFlagsDefBetween`. I would remove this check, and leave one in the `hasFlagsDefBetween`.

2023-11-29 18:39 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +    NewMI->tieOperands(0, NewMI->getNumOperands() - 2);
Nitpick: For reading the code, maybe it would be easier to move this line just after we create NewMI?

2023-11-29 18:39 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +  SmallPtrSet<MachineInstr *, 4> ToRemove;
Ah, sorry for the confusion.
What I had in mind is similar to [this](https://github.com/matter-labs/compiler-llvm/blob/ff8c1afc51b987e44ba271c10780ca55659333c3/llvm/lib/Target/EraVM/EraVMCombineAddressingMode.cpp#L334). Have one `vector<pair<Select, Use>>` (we don't need `SmallPtrSet` for uses, since we will have only one use) to do the folding after we finish with BB traversing and one `SmallPtrSet<UsesToUpdate>` as a paranoia check not to fold twice to the same instruction, and do this transformation in two parts:
1. Find instructions to fold (part to the 136 line).
2. Do folding and removing in separate loop.

Since for other transformations we might reuse majority of this code, I think it is safer to do it this way, since removing from `SmallPtrSet` is totally fine in this situation, in other situations could lead to non-determinism.

2023-11-29 22:01 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +  DenseMap<unsigned, unsigned> InverseCond{
Copied from `EraVMExpandSelect.cpp` and already present in slightly different form in `EraVMInstrInfo.cpp`. Can we avoid duplication? Removing from `EraVMExpandSelect.cpp` is also very welcome.

2023-11-29 22:01 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +    return true;
`return std::any_of...`
Does the patch rebased on top of `dev-15`? I expect `clang-tidy` should have informed about such simplifications.

2023-11-29 22:01 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +    if (MI.getOpcode() != EraVM::SELiir)
The patch largely triggered on the precompiles only which makes me doubt if testing coverage is sufficient.

2023-11-29 22:01 UTC, akiramenai commented on llvm/test/CodeGen/EraVM/select-zero.ll
> +}
A negative test for multiple uses is missing

2023-11-30 06:15 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +    if (MI.getOpcode() != EraVM::SELiir)
So my suggestion here is to expand on all the select forms with imm 0, and to all the instructions for which 0 is neutral with expectation that more tests are triggered and the coverage improves. It shouldn't be hard, should it?

2023-11-30 13:58 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +    if (UseMI.getOpcode() != EraVM::ADDrrr_s || UseMI.getParent() != &MBB ||
Done. Removed it.

2023-11-30 14:13 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +    NewMI->tieOperands(0, NewMI->getNumOperands() - 2);
Done.

2023-11-30 14:16 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +    return true;
Add it now.

2023-11-30 15:02 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +    return true;
@akiramenai  This is llvm::any_of, not the std::any_of. It's used to iterate the operands. The code is rebased on top of dev-15.

2023-11-30 15:59 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +  DenseMap<unsigned, unsigned> InverseCond{
Hi @akiramenai , I updated the code per your suggestion. Would you please check if it is expected?

2023-11-30 16:34 UTC, TerryGuo commented on llvm/test/CodeGen/EraVM/select-zero.ll
> +}
Test added now.

2023-12-01 07:28 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +    return true;
I meant the enclosing one. The point is the we have an expression of form
```
if (Predicate)
  return true;
return false;
```
Which is equivalent to `return Predicate;` I just expected `clang-tidy` to complain about it but it doesn't seem to be the case. Anyway shouldn't we rewrite?
One more thing. @vladimirradosavljevic don't we have a similar predicate in your code? Should we perhaps move it to instruction info?

2023-12-01 09:56 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +  DenseMap<unsigned, unsigned> InverseCond{
Hi @akiramenai , we have `InverseCond` map from [EraVMExpandSelect.cpp](https://github.com/matter-labs/compiler-llvm/blob/ff8c1afc51b987e44ba271c10780ca55659333c3/llvm/lib/Target/EraVM/EraVMExpandSelect.cpp#L84) and `ReverseMap` from [EraVMInstrInfo.cpp](https://github.com/matter-labs/compiler-llvm/blob/ff8c1afc51b987e44ba271c10780ca55659333c3/llvm/lib/Target/EraVM/EraVMInstrInfo.cpp#L1091C68-L1091C78). However they are not equal:

```c++
  DenseMap<unsigned, unsigned> InverseCond{
      {EraVMCC::COND_E, EraVMCC::COND_NE},
      {EraVMCC::COND_NE, EraVMCC::COND_E},
      {EraVMCC::COND_LT, EraVMCC::COND_GE},
      {EraVMCC::COND_LE, EraVMCC::COND_GT},
      {EraVMCC::COND_GT, EraVMCC::COND_LE},
      {EraVMCC::COND_GE, EraVMCC::COND_LT},
      // COND_OF is an alias for COND_LT
      {EraVMCC::COND_OF, EraVMCC::COND_GE},
  };
``` 

```c++
  const std::unordered_map<EraVMCC::CondCodes, EraVMCC::CondCodes> ReverseMap =
      {
          {EraVMCC::COND_E, EraVMCC::COND_NE},
          {EraVMCC::COND_NE, EraVMCC::COND_E},
          {EraVMCC::COND_LT, EraVMCC::COND_GE},
          {EraVMCC::COND_GE, EraVMCC::COND_LT},
          {EraVMCC::COND_LE, EraVMCC::COND_GT},
          {EraVMCC::COND_GT, EraVMCC::COND_LE},
      };
``` 

Is it correct to add `{EraVMCC::COND_OF, EraVMCC::COND_GE}` into `ReverseMap `

I tried to add it and observed below buggy transformation, code like
```
jump.of @.BB0_20
jump    @.BB0_9 
``` 
will be transformed to:
```
jump.ge @.BB0_9
``` 
and then causes test failed.

Is this a new bug or should I keep `ReverseMap` as it is and put `InverseCond` into a new function?

2023-12-01 10:05 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +    return true;
Yes, I have something similar to detect whether instruction uses or defines Flags. We could move this code to instruction info and reuse across the codebase. Please note that here we only check for defines but in HoistFlagSetting and CombineFlagSetting we also check for uses, so that needs to be handled.

2023-12-01 11:18 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +  DenseMap<unsigned, unsigned> InverseCond{
@TerryGuo 
This need to be investigated. Let's roll back and I create a ticket to reduce tech debt.

2023-12-01 15:53 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +  DenseMap<unsigned, unsigned> InverseCond{
Got it. Thanks.

2023-12-01 16:30 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.007 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                               0.033 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.876 ║
║ Worst                               0.000 ║
║ Total                               0.012 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.003 ║
║ Best                               13.870 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.006 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                               0.012 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                               11.329 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                              11.652 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.568 ║
║ Best                               13.876 ║
║ Worst                               0.000 ║
║ Total                              11.176 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.409 ║
║ Best                               13.870 ║
║ Worst                               0.000 ║
║ Total                               1.024 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                9.411 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               9.690 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.362 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                              11.011 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.152 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               1.054 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.324 ║
║ Worst                               0.000 ║
║ Total                               0.009 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.310 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.017 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.266 ║
║ Worst                               0.000 ║
║ Total                               0.011 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.274 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.018 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-12-02 02:17 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.007 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                               0.033 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.876 ║
║ Worst                               0.000 ║
║ Total                               0.012 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.003 ║
║ Best                               13.870 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.006 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                               0.012 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                               11.329 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                              11.652 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.568 ║
║ Best                               13.876 ║
║ Worst                               0.000 ║
║ Total                              11.176 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.409 ║
║ Best                               13.870 ║
║ Worst                               0.000 ║
║ Total                               1.024 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                9.411 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               9.690 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.362 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                              11.011 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.152 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               1.054 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.324 ║
║ Worst                               0.000 ║
║ Total                               0.009 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.310 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.017 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.266 ║
║ Worst                               0.000 ║
║ Total                               0.011 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.274 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.018 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-12-02 08:15 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.007 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                               0.033 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.876 ║
║ Worst                               0.000 ║
║ Total                               0.012 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.003 ║
║ Best                               13.870 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.006 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               0.019 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                               0.012 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.002 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                               11.329 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                              11.652 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.568 ║
║ Best                               13.876 ║
║ Worst                               0.000 ║
║ Total                              11.176 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.409 ║
║ Best                               13.870 ║
║ Worst                               0.000 ║
║ Total                               1.024 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                9.411 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               9.690 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.362 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                              11.011 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.152 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               1.054 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.324 ║
║ Worst                               0.000 ║
║ Total                               0.009 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.310 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.017 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.002 ║
║ Best                                0.266 ║
║ Worst                               0.000 ║
║ Total                               0.011 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.274 ║
║ Worst                               0.000 ║
║ Total                               0.001 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.000 ║
║ Best                                0.018 ║
║ Worst                               0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

```

2023-12-02 09:12 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.009 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                               0.036 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.174 ║
║ Best                               14.103 ║
║ Worst                               0.000 ║
║ Total                               0.088 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.015 ║
║ Best                               14.058 ║
║ Worst                              -0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.008 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               0.023 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.169 ║
║ Best                               13.844 ║
║ Worst                              -0.633 ║
║ Total                               0.081 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.013 ║
║ Best                               13.724 ║
║ Worst                              -0.003 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                               11.329 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                              11.652 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.927 ║
║ Best                               14.103 ║
║ Worst                               0.000 ║
║ Total                              11.211 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.590 ║
║ Best                               14.058 ║
║ Worst                               0.000 ║
║ Total                               1.028 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                9.411 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               9.690 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.705 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                              11.045 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.313 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               1.058 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.006 ║
║ Best                                0.324 ║
║ Worst                               0.000 ║
║ Total                               0.020 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.102 ║
║ Best                                0.929 ║
║ Worst                               0.000 ║
║ Total                               0.071 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.026 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.007 ║
║ Best                                0.858 ║
║ Worst                               0.000 ║
║ Total                               0.014 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.097 ║
║ Best                                0.823 ║
║ Worst                               0.000 ║
║ Total                               0.057 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.026 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

```

2023-12-02 11:27 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.009 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                               0.036 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.174 ║
║ Best                               14.103 ║
║ Worst                               0.000 ║
║ Total                               0.088 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.015 ║
║ Best                               14.058 ║
║ Worst                              -0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.008 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               0.023 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.169 ║
║ Best                               13.844 ║
║ Worst                              -0.633 ║
║ Total                               0.081 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.013 ║
║ Best                               13.724 ║
║ Worst                              -0.003 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                               11.329 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                              11.652 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.927 ║
║ Best                               14.103 ║
║ Worst                               0.000 ║
║ Total                              11.211 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.590 ║
║ Best                               14.058 ║
║ Worst                               0.000 ║
║ Total                               1.028 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                9.411 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               9.690 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.705 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                              11.045 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.313 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               1.058 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.006 ║
║ Best                                0.324 ║
║ Worst                               0.000 ║
║ Total                               0.020 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.102 ║
║ Best                                0.929 ║
║ Worst                               0.000 ║
║ Total                               0.071 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.026 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.007 ║
║ Best                                0.858 ║
║ Worst                               0.000 ║
║ Total                               0.014 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.097 ║
║ Best                                0.823 ║
║ Worst                               0.000 ║
║ Total                               0.057 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.026 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

```

2023-12-02 12:08 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.011 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                               0.038 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.176 ║
║ Best                               14.103 ║
║ Worst                               0.000 ║
║ Total                               0.088 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.016 ║
║ Best                               14.058 ║
║ Worst                              -0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.009 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               0.024 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.170 ║
║ Best                               13.844 ║
║ Worst                              -0.633 ║
║ Total                               0.081 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.014 ║
║ Best                               13.724 ║
║ Worst                              -0.003 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                               11.329 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                              11.652 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.927 ║
║ Best                               14.103 ║
║ Worst                               0.000 ║
║ Total                              11.211 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.590 ║
║ Best                               14.058 ║
║ Worst                               0.000 ║
║ Total                               1.028 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                9.411 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               9.690 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.705 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                              11.045 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.313 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               1.058 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.006 ║
║ Best                                0.324 ║
║ Worst                               0.000 ║
║ Total                               0.020 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.102 ║
║ Best                                0.929 ║
║ Worst                               0.000 ║
║ Total                               0.071 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.026 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.007 ║
║ Best                                0.858 ║
║ Worst                               0.000 ║
║ Total                               0.014 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.097 ║
║ Best                                0.823 ║
║ Worst                               0.000 ║
║ Total                               0.057 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.026 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

```

2023-12-02 14:21 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.011 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                               0.038 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.176 ║
║ Best                               14.103 ║
║ Worst                               0.000 ║
║ Total                               0.088 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.016 ║
║ Best                               14.058 ║
║ Worst                              -0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.009 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               0.024 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.170 ║
║ Best                               13.844 ║
║ Worst                              -0.633 ║
║ Total                               0.081 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.014 ║
║ Best                               13.724 ║
║ Worst                              -0.003 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                               11.329 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                              11.652 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.927 ║
║ Best                               14.103 ║
║ Worst                               0.000 ║
║ Total                              11.211 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.590 ║
║ Best                               14.058 ║
║ Worst                               0.000 ║
║ Total                               1.028 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                9.411 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               9.690 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.705 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                              11.045 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.313 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               1.058 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.006 ║
║ Best                                0.324 ║
║ Worst                               0.000 ║
║ Total                               0.020 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.102 ║
║ Best                                0.929 ║
║ Worst                               0.000 ║
║ Total                               0.071 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.026 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.007 ║
║ Best                                0.858 ║
║ Worst                               0.000 ║
║ Total                               0.014 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.097 ║
║ Best                                0.823 ║
║ Worst                               0.000 ║
║ Total                               0.057 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.026 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

```

2023-12-02 14:25 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +    if (MI.getOpcode() != EraVM::SELiir)
The constraint is relaxed.

2023-12-02 14:26 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +    return true;
Changed to use `return std::any`  now.

2023-12-02 14:33 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +  SmallPtrSet<MachineInstr *, 4> ToRemove;
Got your point and learnt something new. I see the difference now. Thanks very much. I will adopt the solution you suggested in the future work.

2023-12-02 16:59 UTC, akiramenai approved these changes
LGTM

2023-12-02 16:59 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +//
Nitpicking redundant empty line.

2023-12-02 16:59 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +      EraVM::SHRrrr_s,
For the sake of completeness, rotates should also be here. Though I don't think it will affect integration tests anyhow.

2023-12-02 16:59 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +    ;
?

2023-12-03 01:20 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +//
Removed now.

2023-12-03 01:21 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +      EraVM::SHRrrr_s,
Add bit rotation: ROR and ROL along with tests in MIR file.

2023-12-03 01:21 UTC, TerryGuo commented on llvm/lib/Target/EraVM/EraVMFoldSelect.cpp
> +    ;
Good catch. Removed it now.

2023-12-03 02:03 UTC, zksync-admin-bot2 commented
Benchmark results:
```
╔═╡ Size (-%) ╞════════════════╡ All M3B3 ╞═╗
║ Mean                                0.011 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                               0.038 ║
╠═╡ Cycles (-%) ╞══════════════╡ All M3B3 ╞═╣
║ Mean                                0.176 ║
║ Best                               14.103 ║
║ Worst                               0.000 ║
║ Total                               0.088 ║
╠═╡ Ergs (-%) ╞════════════════╡ All M3B3 ╞═╣
║ Mean                                0.016 ║
║ Best                               14.058 ║
║ Worst                              -0.000 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════════════╡ All MzB3 ╞═╗
║ Mean                                0.009 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               0.024 ║
╠═╡ Cycles (-%) ╞══════════════╡ All MzB3 ╞═╣
║ Mean                                0.170 ║
║ Best                               13.844 ║
║ Worst                              -0.633 ║
║ Total                               0.081 ║
╠═╡ Ergs (-%) ╞════════════════╡ All MzB3 ╞═╣
║ Mean                                0.014 ║
║ Best                               13.724 ║
║ Worst                              -0.003 ║
║ Total                               0.000 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles M3B3 ╞═╗
║ Mean                               11.329 ║
║ Best                               12.211 ║
║ Worst                               0.000 ║
║ Total                              11.652 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.927 ║
║ Best                               14.103 ║
║ Worst                               0.000 ║
║ Total                              11.211 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles M3B3 ╞═╣
║ Mean                                4.590 ║
║ Best                               14.058 ║
║ Worst                               0.000 ║
║ Total                               1.028 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞════════╡ Precompiles MzB3 ╞═╗
║ Mean                                9.411 ║
║ Best                               10.847 ║
║ Worst                               0.000 ║
║ Total                               9.690 ║
╠═╡ Cycles (-%) ╞══════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.705 ║
║ Best                               13.844 ║
║ Worst                               0.000 ║
║ Total                              11.045 ║
╠═╡ Ergs (-%) ╞════════╡ Precompiles MzB3 ╞═╣
║ Mean                                4.313 ║
║ Best                               13.724 ║
║ Worst                               0.000 ║
║ Total                               1.058 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life M3B3 ╞═╗
║ Mean                                0.006 ║
║ Best                                0.324 ║
║ Worst                               0.000 ║
║ Total                               0.020 ║
╠═╡ Cycles (-%) ╞════════╡ Real life M3B3 ╞═╣
║ Mean                                0.102 ║
║ Best                                0.929 ║
║ Worst                               0.000 ║
║ Total                               0.071 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life M3B3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.026 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

╔═╡ Size (-%) ╞══════════╡ Real life MzB3 ╞═╗
║ Mean                                0.007 ║
║ Best                                0.858 ║
║ Worst                               0.000 ║
║ Total                               0.014 ║
╠═╡ Cycles (-%) ╞════════╡ Real life MzB3 ╞═╣
║ Mean                                0.097 ║
║ Best                                0.823 ║
║ Worst                               0.000 ║
║ Total                               0.057 ║
╠═╡ Ergs (-%) ╞══════════╡ Real life MzB3 ╞═╣
║ Mean                                0.001 ║
║ Best                                0.026 ║
║ Worst                               0.000 ║
║ Total                               0.002 ║
╚═══════════════════════════════════════════╝

```

2023-12-03 14:28 UTC, merged