[EraVM] Optimize patterns in precompiles
matter-labs/era-compiler-llvm pull request #387
Opened 2024-02-06 11:33 UTC by vladimirradosavljevic

2024-02-06 11:35 UTC, vladimirradosavljevic commented
@akiramenai FYI, in precompiles there are only patterns of instructions that uses constant pools, other cases are added to generalize implementation.

2024-02-06 17:30 UTC, akiramenai requested changes
I haven't finished reading (and I'm continuing) but as my comment requires investigation, I post it now. I suspect LLVM must have functionality to remove identical instructions. @vladimirradosavljevic can we use it instead of our own logic to detect identical `sub.s`es?

2024-02-06 17:30 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +// This file implements a pre-ra pass to optimize SELECT and CMP instructions.
More explicit documentation is welcome here.

2024-02-06 17:30 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +  bool isImmSubWithFlags(const MachineInstr &MI) const;
Maybe `SubS` / `Subs`/`SwappedSub`? Swap is essential here. And the doc should reflect it too.

2024-02-06 17:30 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +  bool areSubsIdentical(const MachineInstr &FirstSub,
Shouldn't we generalise and consider other cases of identical `sub`s?

2024-02-06 17:30 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +  bool tryReplaceOpWithCmp(MachineBasicBlock &MBB);
This one looks very generic in potential. We narrow it to subs, but it principle given no side effects any two consecutive identical instructions are to be removed. Doesn't LLVM's peephole optimizer do so? Can we use it?

2024-02-06 20:51 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +         !(EraVM::in0Iterator(MI) + 1)->getImm() &&
Why don't we support static offsets here?

2024-02-06 20:51 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +  for (auto [Add, Use] : Deleted) {
This is largely duplicated code. Wouldn't you mind to create a ticket to handle it?

2024-02-06 20:51 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +    auto NewMI = BuildMI(*Use->getParent(), Use, Use->getDebugLoc(),
Could you try to lift `replace...` auxiliary functions from `EraVMCombineAddressingMode` to our `InstrInfo` header and apply it here (and to @TerryGuo part as well)?

2024-02-06 20:51 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +    // unlikely that this instructions is select, where folding is feasible.
What makes us to restrict it anyway? We are doing the check below and the comment just says that we are to bail out because this check is likely to fail. Would it work if they are in different BBs?

2024-02-07 08:36 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +// This file implements a pre-ra pass to optimize SELECT and CMP instructions.
Will add it.

2024-02-07 08:36 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +  bool isImmSubWithFlags(const MachineInstr &MI) const;
Will do it.

2024-02-07 08:45 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +  bool areSubsIdentical(const MachineInstr &FirstSub,
Yes, I missed `EraVMcmp` cases where we can match regs, `load_code` and `load_stack`. Will add them.

2024-02-07 09:00 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +  bool tryReplaceOpWithCmp(MachineBasicBlock &MBB);
We are doing only SUB instructions that were generated from CMP, since other identical instructions should be CSEd during LLVM IR optimizations and `ISel` phase.
Before I decided to implement it like this, I did investigate whether we can do use other LLVM passes, and here are my findings:
1. We can do this during `ISel` phase, but this can be bug prone since we are changing `cmp` with `add` instruction that can have more uses. I don't think this is a good place to do it, since for this to be profitable, we will need to call `ReplaceAllUsesOfValueWith` for add, and we can face the same issue as before.
2. In `MachineCSE` pass, but in this case, we would need to replace `cmp` instruction with `add`. This also could be bug prone, since add would need to set flags, and between `cmp` and `add` can be another instruction that sets flag.
3. In `PeepholeOptimizer::optimizeCmpInstr`, but this optimization is removing `cmp` in case it is not needed.

For these kind of optimizations where we are optimizing CMP or SELECT, in case there is no common pass that suits our needs (to take into account all cases of manipulating flags), I would prefer creating our own pass to do it.
Did I miss something?

2024-02-07 09:14 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +         !(EraVM::in0Iterator(MI) + 1)->getImm() &&
We are only generating memop with constant pool entries with offset 0, so I limited this check to zero offset.

2024-02-07 09:16 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +    auto NewMI = BuildMI(*Use->getParent(), Use, Use->getDebugLoc(),
I will refactor out replacing code in this pass, and will check how it matches with `replace...` auxiliary functions from `EraVMCombineAddressingMode`. In case we need to spend more time in matching these functions, I will create a ticket for it. Wdyt?

2024-02-07 09:17 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +  for (auto [Add, Use] : Deleted) {
If you mean it is identical with code from `tryFoldSelectZero`, yes I will refactor out. In case you didn't mean that, could you please clarify it more?

2024-02-07 09:19 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +    // unlikely that this instructions is select, where folding is feasible.
I expect that LLVM will move code closer to it's use, so I added this restriction. I managed to create example where use is in another BB, but if I put it through the opt pipeline, it will move it just before it's use.
I can remove this restriction as this will work if use is in the different BB. Wdyt?

2024-02-07 09:23 UTC, vladimirradosavljevic commented
> I haven't finished reading (and I'm continuing) but as my comment requires investigation, I post it now. I suspect LLVM must have functionality to remove identical instructions. @vladimirradosavljevic can we use it instead of our own logic to detect identical `sub.s`es?

Thanks for the review! I added explanation why I chose to implement it this way in the comment.

2024-02-07 09:41 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +    // unlikely that this instructions is select, where folding is feasible.
I think it's better to remove. It doesn't save us tons of compilation time while it increases maintenance burden.

2024-02-07 09:42 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +    auto NewMI = BuildMI(*Use->getParent(), Use, Use->getDebugLoc(),
sgtm

2024-02-07 09:51 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +  for (auto [Add, Use] : Deleted) {
This structure of transformation originated from post-RA RDA-based passes. If to grep `for (auto \[.*Deleted` or similar I expect you to find other places where this code is replicated. We probably can do better, though I don't insist doing it in the scope of this work.

2024-02-07 10:24 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +  bool tryReplaceOpWithCmp(MachineBasicBlock &MBB);
Ok, I found the cause of my confusion. It's the word "identical" in the doc and the methods names. They aren't. So it would be great to replace it with "foldable" or something because if one instruction sets flags and another one is not, they aren't identical or even equivalent (we shouldn't claim that `add` is identical to `sub`).

But as a general consideration
> since other identical instructions should be CSEd during LLVM IR optimizations and ISel phase

This is also imprecise. After isel we have pseudos that can be even if by coincidence become _foldable_ with an adjacent instruction. If one can specify in generic manner where to fold, the combining logic might be extracted away and generalised to work on any MIR (pre RA or post RA and any target). If it's missing in upstream, it can be upstreamed too.
It indeed sounds like more work than profit, but probably worth tracking. Wdyt?

2024-02-07 10:25 UTC, akiramenai approved these changes
Assuming "identical" will become less misleading, LGTM.

2024-02-07 19:18 UTC, vladimirradosavljevic commented
@akiramenai This is not the final version yet, I just want to check the CI. Will update you when it is ready for the review.

2024-02-08 13:16 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +  bool tryReplaceOpWithCmp(MachineBasicBlock &MBB);
As we agreed offline, I moved this optimization into the separate `EraVMFoldSimilarInstructions` pass and generalize implementation for the sub instructions. I have created the ticket (CPR-1544) to move this pass into the common code.

2024-02-08 13:19 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +  for (auto [Add, Use] : Deleted) {
I chose this approach because it is the safest solution where we won't ever run into issues with accessing invalidated iterator since here we are removing 2 and adding 1 instruction. Yes, this can't happen in this situation, but I wanted to make code more uniform throughout our backend.
Please note that I changed this approach to be similar with the `tryFoldSelectZero` implementation.

2024-02-08 13:21 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +    auto NewMI = BuildMI(*Use->getParent(), Use, Use->getDebugLoc(),
I have refactored out replacing code, but it is different than in `replace...` auxiliary functions from `EraVMCombineAddressingMode`, since in one place we are mixing operands of 2 instructions, and in other we are using same operands.

2024-02-08 13:21 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMOptimizeSelectCmpPreRA.cpp
> +    // unlikely that this instructions is select, where folding is feasible.
Done.

2024-02-08 13:21 UTC, vladimirradosavljevic commented
@akiramenai PTAL.

2024-02-08 22:25 UTC, akiramenai approved these changes
LGTM.
My initial thoughts around `EraVMFoldSimilarInstructions` were to make it less idiosyncratic and more abstract. `TII` is to tell when to fold, and the pass is to fold in otherwise target agnostic way.
But the more I think about it the more I understand that our design on flags in many cases is incompatible with mainstream architectures and the aforementioned pass is about optimising flag setting sequence.
Yet name of the pass now implies some generality while it's not here and it's unlikely to be needed. `FoldFlagSettingSequence` would be a good alternative but similar is already used.

2024-02-08 22:25 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMFoldSimilarInstructions.cpp
> +  /// SkipSecondLastImplicitDef is true, we expect that the last implicit
Wouldn't it be better to name `IgnoreFlagSetting`.
In the implementation we can also check all implicit operands I believe instead of assuming the exact position.

2024-02-08 22:25 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMFoldSimilarInstructions.cpp
> +         areOperandsIdentical(FirstSub, SecondSub, isSimilarToFlagSettingPair);
Looks like a formatting issue.

2024-02-08 22:25 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMFoldSimilarInstructions.cpp
> +// but this search can be expanded.
Also worth mentioning that it only work with subs and adds.

2024-02-08 22:25 UTC, akiramenai commented on llvm/test/CodeGen/EraVM/fold-add-to-select.ll
> +; CHECK:       nop stack+=[1]
Redundant check as the test is not supposed to check frame structure and we already check it elsewhere.

2024-02-09 10:38 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSimilarInstructions.cpp
> +// but this search can be expanded.
Done.

2024-02-09 10:39 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSimilarInstructions.cpp
> +  /// SkipSecondLastImplicitDef is true, we expect that the last implicit
Changed the name to `IgnoreFlagSetting` and removed the assumption that implicit flags reg is the last operand.

2024-02-09 10:41 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMFoldSimilarInstructions.cpp
> +         areOperandsIdentical(FirstSub, SecondSub, isSimilarToFlagSettingPair);
clang-format did this change, and it looks good to me because indentation in brackets looks good and first line after the bracket is aligned to the open bracket.

2024-02-09 10:41 UTC, vladimirradosavljevic commented on llvm/test/CodeGen/EraVM/fold-add-to-select.ll
> +; CHECK:       nop stack+=[1]
Removed frame structure checks.

2024-02-09 10:51 UTC, vladimirradosavljevic commented
> LGTM. My initial thoughts around `EraVMFoldSimilarInstructions` were to make it less idiosyncratic and more abstract. `TII` is to tell when to fold, and the pass is to fold in otherwise target agnostic way. But the more I think about it the more I understand that our design on flags in many cases is incompatible with mainstream architectures and the aforementioned pass is about optimising flag setting sequence. Yet name of the pass now implies some generality while it's not here and it's unlikely to be needed. `FoldFlagSettingSequence` would be a good alternative but similar is already used.

Let's rethink about this pass when we start working on the overflow reverts.

2024-02-09 13:37 UTC, merged