[EVM] Back End
matter-labs/era-compiler-llvm pull request #390
Opened 2024-02-13 14:31 UTC by PavelKopyl

# Code Review Checklist

## Purpose

## Ticket Number

## Requirements
- [ ] Have the requirements been met?
- [ ] Have stakeholder(s) approved the change?

## Implementation
- [ ] Does this code change accomplish what it is supposed to do?
- [ ] Can this solution be simplified?
- [ ] Does this change add unwanted compile-time or run-time dependencies?
- [ ] Could an additional framework, API, library, or service improve the solution?
- [ ] Could we reuse part of LLVM instead of implementing the patch or a part of it?
- [ ] Is the code at the right abstraction level?
- [ ] Is the code modular enough?
- [ ] Can a better solution be found in terms of maintainability, readability, performance, or security?
- [ ] Does similar functionality already exist in the codebase? If yes, why isn’t it reused?
- [ ] Are there any best practices, design patterns or language-specific patterns that could substantially improve this code? 

## Logic Errors and Bugs
- [ ] Can you think of any use case in which the
code does not behave as intended?
- [ ] Can you think of any inputs or external events
that could break the code?

## Error Handling and Logging
- [ ] Is error handling done the correct way?
- [ ] Should any logging or debugging information
be added or removed?
- [ ] Are error messages user-friendly?
- [ ] Are there enough log events and are they
written in a way that allows for easy
debugging?

## Maintainability
- [ ] Is the code easy to read?
- [ ] Is the code not repeated (DRY Principle)?
- [ ] Is the code method/class not too long?

## Dependencies
- [ ] Were updates to documentation, configuration, or readme files made as required by this change?
- [ ] Are there any potential impacts on other parts of the system or backward compatibility?

## Security
- [ ] Does the code introduce any security vulnerabilities?

## Performance
- [ ] Do you think this code change decreases
system performance?
- [ ] Do you see any potential to improve the
performance of the code significantly?

## Testing and Testability
- [ ] Is the code testable?
- [ ] Have automated tests been added, or have related ones been updated to cover the change?
	- [ ] For changes to mutable state
- [ ] Do tests reasonably cover the code change (unit/integration/system tests)? 
	- [ ] Line Coverage
	- [ ] Region Coverage
	- [ ] Branch Coverage
- [ ] Are there some test cases, input or edge cases
that should be tested in addition?

## Readability
- [ ] Is the code easy to understand?
- [ ] Which parts were confusing to you and why?
- [ ] Can the readability of the code be improved by
smaller methods?
- [ ] Can the readability of the code be improved by
different function, method or variable names?
- [ ] Is the code located in the right
file/folder/package?
- [ ] Do you think certain methods should be
restructured to have a more intuitive control
flow?
- [ ] Is the data flow understandable?
- [ ] Are there redundant or outdated comments?
- [ ] Could some comments convey the message
better?
- [ ] Would more comments make the code more
understandable?
- [ ] Could some comments be removed by making the code itself more readable?
- [ ] Is there any commented-out code?

## Documentation
- [ ] Is there sufficient documentation?
- [ ] Is the ReadMe.md file up to date?

## Best Practices
- [ ] Follow Single Responsibility principle?
- [ ] Are different errors handled correctly?
- [ ] Are errors and warnings logged?
- [ ] Magic values avoided?
- [ ] No unnecessary comments?
- [ ] Minimal nesting used?

## Experts' Opinion
- [ ] Do you think a specific expert, like a security
expert or a usability expert, should look over
the code before it can be accepted?
- [ ] Will this code change impact different teams, and should they review the change as well?

2024-02-14 11:44 UTC, akiramenai commented on llvm/include/llvm/IR/IntrinsicsEVM.td
> +def int_evm_msize : Intrinsic<[llvm_i256_ty], [], []>;
Similar to what we have done in EraVM we should consider IntrInaccessibleMemOnly [+ IntrNoMerge]. Could we create a ticket for that and optionally add a TODO?

2024-02-14 11:46 UTC, akiramenai commented on llvm/include/llvm/IR/IntrinsicsEVM.td
> +// TODO: Ensure the gasprice is fixed while a function execution.
@hedgar2017 do you know if it is the case?

2024-02-14 12:34 UTC, akiramenai commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +  // EVM local begin
Could we explain this local change? It looks suspicious.

2024-02-14 12:36 UTC, akiramenai commented on llvm/lib/Support/Triple.cpp
> +
Probably you reformatted too much or something.

2024-02-14 12:41 UTC, akiramenai commented on llvm/lib/Target/EVM/EVM.h
> +struct EVMLinkRuntimePass : PassInfoMixin<EVMLinkRuntimePass> {
Could we create a ticket to get rid of this duplication?

2024-02-14 12:43 UTC, akiramenai commented
@vladimirradosavljevic we need to put license to every file. Am I right?

2024-02-14 12:52 UTC, PavelKopyl commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +  // EVM local begin
Sure.
For EVM all the memcpy, memmove intrinsics should be lowered into appropriate machine instructions. There is one-to-one correspondence (unlike of EraVM where some of them are expanded into loops). For this, I overrided SelectionDAGTargetInfo::EmitTargetCodeForMemcpy, EmitTargetCodeForMemmove. I need these methods to always be invoked no matter if the memory size of constant or not, see line 72098. But the logic of SelectionDAG::getMemcpy (getMemmove) first checks if the size is constant and if it is, tries to expand the intrinsic into a sequence of plain LD/ST. This change disables this behavior for EVM.

2024-02-14 12:55 UTC, vladimirradosavljevic commented
> @vladimirradosavljevic we need to put license to every file. Am I right?

Yes, we should always put the licence at the beginning of new files.

2024-02-14 13:40 UTC, vladimirradosavljevic commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +  // EVM local begin
Sorry for jumping in, but can we avoid these local changes by creating pre-isel pass (e.g. EVMCodeGenPrepare) to convert memcpy and memmove calls to the EVM specific intrinsics? Just an idea to think about.

2024-02-14 13:58 UTC, vladimirradosavljevic commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +  // EVM local begin
I checked the implementations of `getMemcpyLoadsAndStores` and `getMemmoveLoadsAndStores` and it seems to me that if we override `findOptimalMemOpLowering` and return false for memcpy and memmove, it will always end up calling EmitTargetCodeForMemcpy or EmitTargetCodeForMemmove, so we don't need pre-isel pass or these local changes.

2024-02-14 14:07 UTC, PavelKopyl commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +  // EVM local begin
> Sorry for jumping in, but can we avoid these local changes by creating pre-isel pass (e.g. EVMCodeGenPrepare) to convert memcpy and memmove calls to the EVM specific intrinsics? Just an idea to think about.

Thank you, Vladimir! That's a nice way to get rig of this change.

2024-02-14 14:11 UTC, PavelKopyl commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +  // EVM local begin
> I checked the implementations of `getMemcpyLoadsAndStores` and `getMemmoveLoadsAndStores` and it seems to me that if we override `findOptimalMemOpLowering` and return false for memcpy and memmove, it will always end up calling EmitTargetCodeForMemcpy or EmitTargetCodeForMemmove, so we don't need pre-isel pass or these local changes.

Thank you. That would work, but as I see we well get an assertion when calling:
```
    SDValue Result = getMemcpyLoadsAndStores(
        *this, dl, Chain, Dst, Src, ConstantSize->getZExtValue(), Alignment,
        isVol, false, DstPtrInfo, SrcPtrInfo, AAInfo, AA);
```
because of 
` ConstantSize->getZExtValue()`,

when ConstantSize takes more that 64 bits. This case is difficult to imagine, but anyway..

2024-02-14 14:13 UTC, vladimirradosavljevic commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +  // EVM local begin
Ah, makes sense why we should avoid this approach. Thanks for looking into it 🙏

2024-02-14 16:35 UTC, akiramenai commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +  // EVM local begin
So are we going to proceed with a pass?

2024-02-14 16:48 UTC, PavelKopyl commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +  // EVM local begin
I guess so, especially if such changes in a common code are highly undesirable, but this will require more code.

2024-02-15 23:07 UTC, akiramenai commented on llvm/test/CodeGen/Generic/2013-03-20-APFloatCrash.ll
> +; UNSUPPORTED: evm
eravm is not supported too. I wonder how does it compile.

2024-02-15 23:07 UTC, akiramenai commented on llvm/test/CodeGen/Generic/multiple-return-values-cross-block-with-invoke.ll
> +; EVM has no support of returning multiple values from a call
Is it the matter of not yet implemented calling conventions or is it a VM restriction?

2024-02-15 23:07 UTC, akiramenai commented on llvm/test/CodeGen/EVM/logical.ll
> +; RUN: llc --mtriple=evm --evm-keep-registers < %s | FileCheck %s
nitpicking: bitwise, not logical.

2024-02-15 23:07 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMRegColoring.cpp
> +  // TODO: Does EVM need to care about setjmp for register coloring?
No, afaik there aren't exceptions / error recovery mechanism within a contract.

2024-02-15 23:07 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMRegColoring.cpp
> +    // If we reassigned the stack pointer, update the debug frame base info.
?

2024-02-15 23:07 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMISelLowering.cpp
> +  SDValue Mask = DAG.getConstant(APInt::getLowBitsSet(Bits, HalfBits), DL, VT);
If we don't have executable tests on it yet, please create a ticket to write them.

2024-02-15 23:07 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMInstrInfo.cpp
> +  // TODO: Try to add support for branch reversing. The main problem is that
Do we have a ticket for that?

2024-02-15 23:07 UTC, akiramenai commented on llvm/lib/MC/ELFObjectWriter.cpp
> +  // HACK!!! For EVM target we don't need the whole EFL file,
Is there a way to guard it against our target?
We would need something similar for EraVM. 
@hedgar2017 did it come from the fact that we want to ship a single binary? Is it going to change with disassembler and maybe other tools?

2024-02-16 13:58 UTC, akiramenai commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +  // EVM local begin
Ok, a ticket is ok for now

2024-02-16 14:02 UTC, akiramenai requested changes
Could we make sure the license is in every file we created?

2024-02-16 14:02 UTC, akiramenai commented on llvm/lib/Target/EVM/EVM.td
> +//
license

2024-02-16 14:02 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMArgumentMove.cpp
> +//
license

2024-02-16 14:02 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMAsmPrinter.cpp
> +//
license

2024-02-16 14:02 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMFrameLowering.cpp
> +//
license

2024-02-16 14:02 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMFrameLowering.h
> +//
license

2024-02-16 14:02 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMISD.def
> +//
license

2024-02-16 16:33 UTC, PavelKopyl commented on llvm/test/CodeGen/Generic/2013-03-20-APFloatCrash.ll
> +; UNSUPPORTED: evm
Unlike EVM, EraVM BE calls GlobalDCEPass that removes completely this function (because it has 'internal' visibility and is not called by any other functions in the module).
For EVM gets crashed inside MC (on an assertion), because of an undefined symbol. This symbol corresponds to an FP math library call.

2024-02-16 16:36 UTC, PavelKopyl commented on llvm/test/CodeGen/Generic/multiple-return-values-cross-block-with-invoke.ll
> +; EVM has no support of returning multiple values from a call
Thank you, I removed this restriction. Now EVM BE can compile this.

2024-02-16 16:36 UTC, PavelKopyl commented on llvm/test/CodeGen/EVM/logical.ll
> +; RUN: llc --mtriple=evm --evm-keep-registers < %s | FileCheck %s
Thank you:)

2024-02-16 16:37 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMRegColoring.cpp
> +  // TODO: Does EVM need to care about setjmp for register coloring?
Thanks.

2024-02-16 16:38 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMRegColoring.cpp
> +    // If we reassigned the stack pointer, update the debug frame base info.
Removed this.

2024-02-16 16:50 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMISelLowering.cpp
> +  SDValue Mask = DAG.getConstant(APInt::getLowBitsSet(Bits, HalfBits), DL, VT);
There are some tests from compiler-tester that required multiplication of i512 types.

2024-02-16 17:13 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMInstrInfo.cpp
> +  // TODO: Try to add support for branch reversing. The main problem is that
Not yet. Created.

2024-02-16 17:13 UTC, PavelKopyl commented on llvm/include/llvm/IR/IntrinsicsEVM.td
> +def int_evm_msize : Intrinsic<[llvm_i256_ty], [], []>;
Added TODO with the ticket.

2024-02-16 17:13 UTC, PavelKopyl commented on llvm/lib/Support/Triple.cpp
> +
Yep, thank you.

2024-02-16 17:14 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVM.h
> +struct EVMLinkRuntimePass : PassInfoMixin<EVMLinkRuntimePass> {
Added.

2024-02-16 18:02 UTC, PavelKopyl commented on llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp
> +  // EVM local begin
I've already added a final solution for this, please see changes in EVMCodegenPrepare.cpp, EVMISelLowering.cpp (LowerINTRINSIC_VOID) and IntrinsicsEVM.td.

2024-02-16 20:05 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMSingleUseExpression.cpp
> +  if (EVM::isCatch(DefI->getOpcode()))
?

2024-02-16 20:05 UTC, akiramenai commented on llvm/lib/Target/EVM/TargetInfo/EVMTargetInfo.h
> +//
license

2024-02-16 22:17 UTC, PavelKopyl commented
> Could we make sure the license is in every file we created?

I've just checked this via the following bash cmd-s:
Get the list of newly added files that are not tests and among them shows those that have no "Apache-2.0" string:
`git diff -U0 remotes/origin/dev-15 --name-only --diff-filter=A | grep -v test | xargs -nr -I{} grep -rL "Apache\-2\.0" {}`

I got the following list:
```
llvm/lib/Target/EVM/CMakeLists.txt
llvm/lib/Target/EVM/Disassembler/CMakeLists.txt
llvm/lib/Target/EVM/MCTargetDesc/CMakeLists.txt
llvm/lib/Target/EVM/TargetInfo/CMakeLists.txt
llvm/lib/Target/EVM/evm-stdlib.ll
```
These files do not need a license head (am I right?), which means the license was added to all the required files.

2024-02-16 22:20 UTC, PavelKopyl commented on llvm/lib/Target/EVM/TargetInfo/EVMTargetInfo.h
> +//
Thank you, fixe. I've just run a one-line script to find files with missing license. This file and its .cpp one were that last two files with missing license.

2024-02-17 09:44 UTC, akiramenai reviewed
I'd say EVMStackify could be refactored and documented better. It's hard to read now. But let's not be blocked by that especially if we plan to improve stackification, we can move to better design gradually.
Licence problem is resolved. So can we create a ticket for EVMStackify and squash the commits so they reflect what we actually plan to land on top of `dev-15`? Then I approve.

2024-02-17 09:44 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +// The algorithm is quite simple and straightforward. It doesn't involve any
Nitpicking
Only the last sentence of this paragraph carries information. I'd even specify on needed optimizations.

2024-02-17 09:44 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +//     %vreg7 = ADD %arg1 kill, %arg2 kill
%arg1 -> %vreg1
%arg2 -> %vreg2

2024-02-17 09:44 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +//     - %vreg1 is dead after the instruction, so it theoretically should be
Can we avoid copying it from L-stack in the first place? I mean can we swap it or something?

2024-02-17 09:44 UTC, akiramenai commented on llvm/lib/Support/Triple.cpp
> +
Still here.

2024-02-17 09:44 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +  StackLocation allocateStackModelLoc(const Register &Reg);
Documentation improvement is welcome here, but it's ok to postpone and create a ticket for that.

2024-02-17 09:44 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +    return std::optional<StackLocation>{{StackType::L, Depth}};
Wouldn't `return {StackType::L, Depth}` work?

2024-02-17 09:44 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +  // Try to make a small optimization if MI has two args and both are
Could we avoid evaluative judgements in documentation (big, small, important, etc). They aren't informative while create line noice. `If both instruction arguments are on the top of stack, try ...`.
Ok to add to general doc improvement ticket I asked to create before.

2024-02-17 09:44 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +  for (unsigned I = 0; I < RegLocs.size(); ++I)
We can erase `size()` elements instead of this loop.

2024-02-17 09:44 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +  const unsigned NumDeadRegs = std::count_if(
Better is to extract the logic below of swapping live and dead registers to a function. Name and document it properly.

2024-02-17 09:44 UTC, akiramenai commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +      std::count_if(Uses.begin(), Uses.end(), [Reg](const MachineOperand &MO) {
Nipicking
We can use `llvm::` counterpart for algorithms to use ranges.
(Or maybe we should go for C++20 if it works with LLVM ranges, as it looks like LLVM is going to switch soon anyway. @vladimirradosavljevic, @PavelKopyl wdyt?)

2024-02-17 14:38 UTC, hedgar2017 commented on llvm/lib/Target/EVM/EVMISelLowering.cpp
> +  SDValue Mask = DAG.getConstant(APInt::getLowBitsSet(Bits, HalfBits), DL, VT);
Those are for EraVM only. EVM doesn't support 2-register output.

2024-02-17 14:42 UTC, hedgar2017 commented on llvm/lib/MC/ELFObjectWriter.cpp
> +  // HACK!!! For EVM target we don't need the whole EFL file,
Shipping a single binary is critical for UX. `solc` is coming in single binary, and the mere need of shipping `zksolc` in addition to it creates a lot of invariants for plugins, tooling, and project configs.

So we should put as much effort as possible to keep compilation a single command to a single executable.

2024-02-17 16:52 UTC, akiramenai commented on llvm/lib/MC/ELFObjectWriter.cpp
> +  // HACK!!! For EVM target we don't need the whole EFL file,
Just to clarify to have a single binary and to have a single command for compilation are 2 different goals. `rustc` or even better `cargo` are examples of the latter w.o. the former.
Do we plan to have a separate binary for disassembler for EraVM or do you want to link it into `zksolc`? If the former, we are to break single binary shipment anyway.

2024-02-17 19:48 UTC, hedgar2017 commented on llvm/lib/MC/ELFObjectWriter.cpp
> +  // HACK!!! For EVM target we don't need the whole EFL file,
Good point.
I'd like to have everything linked to zksolc, that is to have a single binary with multiple commands for different purposes.

2024-02-19 09:14 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMISelLowering.cpp
> +  SDValue Mask = DAG.getConstant(APInt::getLowBitsSet(Bits, HalfBits), DL, VT);
Hm.. as I remember there was some tests from tests/solidity/simple, whose LLVM IR contained something like:
`%prode = mul i512 %arg1e, %arg2e`
 To lower this IR into the machine IR, I supported UMUL_LOHI primitive, which is used by Instruction Selection to represent multiplication of wider types than are natively supported by a target machine.
 But you are right, I also used eravm-stdlib.ll code, which contains `mul i512` operation, as a test for EVM.

2024-02-19 09:34 UTC, PavelKopyl commented on llvm/lib/MC/ELFObjectWriter.cpp
> +  // HACK!!! For EVM target we don't need the whole EFL file,
Technically, I'll remove this particular change after finishing with EVM arch support in LLD
 linker (I'll move this functionality to LLD).
 
 I'd like to list some technical moments we need to have a single binary with a toolchain functionality:

-  extend assembler, disassembler and linker tools (in case of EVM) to have them as shared libraries.
    Only LLD has such a functionality out of a box (starting from llvm-17, I guess). All other modifications need to be implemented and maintained by ourselves.
-  Extend LLVM API to reflect new functionality
-  Extend and maintain `inkwell` package accordingly, as eventually all the toolchain functionality will be invoked from Rust.
-  Support new functionality in the `zksolc` cmd line.

@hedgar2017, do I understand it right?

2024-02-19 10:16 UTC, hedgar2017 commented on llvm/lib/Target/EVM/EVMISelLowering.cpp
> +  SDValue Mask = DAG.getConstant(APInt::getLowBitsSet(Bits, HalfBits), DL, VT);
i512 will never be generated for EVM.

For EraVM it is not a native type either, but `mul` can write output to two registers (low and high), although inputs are i256.

2024-02-19 10:17 UTC, hedgar2017 commented on llvm/lib/MC/ELFObjectWriter.cpp
> +  // HACK!!! For EVM target we don't need the whole EFL file,
@PavelKopyl yes, exactly.

2024-02-20 14:30 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +    return std::optional<StackLocation>{{StackType::L, Depth}};
Sure, it will. Thank you.

2024-02-20 14:30 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +  // Try to make a small optimization if MI has two args and both are
Removed that.

2024-02-20 14:30 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +  for (unsigned I = 0; I < RegLocs.size(); ++I)
Thanks, done.

2024-02-20 14:31 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +      std::count_if(Uses.begin(), Uses.end(), [Reg](const MachineOperand &MO) {
I've added this question to the ticket.

2024-02-20 14:31 UTC, PavelKopyl commented on llvm/lib/Support/Triple.cpp
> +
Fixed.

2024-02-20 14:32 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +//     %vreg7 = ADD %arg1 kill, %arg2 kill
Thanks, fixed.

2024-02-20 18:16 UTC, hedgar2017 commented on llvm/include/llvm/IR/IntrinsicsEVM.td
> +// TODO: Ensure the gasprice is fixed while a function execution.
If it should've been `within a function`, yes. `gasprice` isn't changing within a transaction.

2024-02-20 18:44 UTC, PavelKopyl commented on llvm/include/llvm/IR/IntrinsicsEVM.td
> +// TODO: Ensure the gasprice is fixed while a function execution.
Thank you. So, the attributes are fine.

2024-02-20 22:06 UTC, akiramenai approved these changes
LGTM, thanks.

2024-02-20 22:12 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMSingleUseExpression.cpp
> +  if (EVM::isCatch(DefI->getOpcode()))
Removed that.

2024-02-20 22:21 UTC, PavelKopyl commented
> I'd say EVMStackify could be refactored and documented better. It's hard to read now. But let's not be blocked by that especially if we plan to improve stackification, we can move to better design gradually. Licence problem is resolved. So can we create a ticket for EVMStackify and squash the commits so they reflect what we actually plan to land on top of `dev-15`? Then I approve.

You are right, this version of stackification is just an intermediate step (mostly with draft ideas) towards more a sophisticated algorithm.
It allows to compile more-or-less complicated tests which gives a base line for perf, code size, and so on.

2024-02-20 22:27 UTC, hedgar2017 approved these changes

2024-02-21 14:28 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +// The algorithm is quite simple and straightforward. It doesn't involve any
Fixed that.

2024-02-21 14:28 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +  const unsigned NumDeadRegs = std::count_if(
Sure, will do as a part of refactoring.

2024-02-21 14:32 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMStackify.cpp
> +//     - %vreg1 is dead after the instruction, so it theoretically should be
If I got the question right, we can swap only the top stack item with an item in the depths.

2024-02-21 15:38 UTC, PavelKopyl commented on llvm/lib/Target/EVM/EVMISelLowering.cpp
> +  SDValue Mask = DAG.getConstant(APInt::getLowBitsSet(Bits, HalfBits), DL, VT);
I've added a ticket to remove this functionality later (https://linear.app/matterlabs/issue/CPR-1567/remove-umul-lohi-primitive-from-isel)

2024-02-22 09:03 UTC, vladimirradosavljevic commented
All changes from `.github/workflows/compiler-integration-tests.yml` should be reverted before merging, right? What is the reason of adding `; UNSUPPORTED: evm` in EraVM tests? Is it because `lit.local.cfg` file is missing in EraVM folder, or something else?

2024-02-22 10:37 UTC, PavelKopyl commented
> All changes from `.github/workflows/compiler-integration-tests.yml` should be reverted before merging, right? What is the reason of adding `; UNSUPPORTED: evm` in EraVM tests? Is it because `lit.local.cfg` file is missing in EraVM folder, or something else?

You are right, I'll remove compiler-integration-tests.yml, as we are not going to support EVM BE in CI right now (though it would be better to support).

While working on EVM I used to build and run lit tests (`ninja check-llvm`) for both targets EraVM and EVM (in order not to cause regressions in EraVM).  I added `; UNSUPPORTED: evm` to some (those that do explicitly specify triple = eravm) EraVM test, otherwise they fail for EVM.  But we can remove that, as anyway EVM is not in CI.

2024-02-22 15:55 UTC, vladimirradosavljevic commented
We should also add config files for the EVM LIT tests.

2024-02-22 16:04 UTC, PavelKopyl commented
> We should also add config files for the EVM LIT tests.

Yep, thank you for recalling!
I've checked another build +  test config. It looks like `machine-outliner-tail.mir`, `machine-outliner.mir` need explicit triple specification.

2024-03-05 15:27 UTC, merged