ci: optimizations and ccache support
matter-labs/era-compiler-llvm pull request #400
Opened 2024-02-23 10:28 UTC by antonbaliasnikov

# Code Review Checklist

## Purpose

CI pipeline optimizations.

Key changes:
* Add `ccache` support for LLVM builds speedining up re-compilation up to 90%
* Report `lit` tests in `xunit` format as part of PR check as additional comment to have visibility of executed unit tests
* Combine code duplications in one `build` action and re-use across the workflows
* Simplify workflows while keeping the same functionality
* Use open source `matterlabs/llvm_runner:ubuntu22-llvm15-latest` image without private credentials

## Ticket Number

N/A

## Requirements
- [ ] Have the requirements been met?
- [ ] Have stakeholder(s) approved the change?

## Implementation
- [ ] Does this code change accomplish what it is supposed to do?
- [ ] Can this solution be simplified?
- [ ] Does this change add unwanted compile-time or run-time dependencies?
- [ ] Could an additional framework, API, library, or service improve the solution?
- [ ] Could we reuse part of LLVM instead of implementing the patch or a part of it?
- [ ] Is the code at the right abstraction level?
- [ ] Is the code modular enough?
- [ ] Can a better solution be found in terms of maintainability, readability, performance, or security?
- [ ] Does similar functionality already exist in the codebase? If yes, why isn’t it reused?
- [ ] Are there any best practices, design patterns or language-specific patterns that could substantially improve this code? 

## Logic Errors and Bugs
- [ ] Can you think of any use case in which the
code does not behave as intended?
- [ ] Can you think of any inputs or external events
that could break the code?

## Error Handling and Logging
- [ ] Is error handling done the correct way?
- [ ] Should any logging or debugging information
be added or removed?
- [ ] Are error messages user-friendly?
- [ ] Are there enough log events and are they
written in a way that allows for easy
debugging?

## Maintainability
- [ ] Is the code easy to read?
- [ ] Is the code not repeated (DRY Principle)?
- [ ] Is the code method/class not too long?

## Dependencies
- [ ] Were updates to documentation, configuration, or readme files made as required by this change?
- [ ] Are there any potential impacts on other parts of the system or backward compatibility?

## Security
- [ ] Does the code introduce any security vulnerabilities?

## Performance
- [ ] Do you think this code change decreases
system performance?
- [ ] Do you see any potential to improve the
performance of the code significantly?

## Testing and Testability
- [ ] Is the code testable?
- [ ] Have automated tests been added, or have related ones been updated to cover the change?
	- [ ] For changes to mutable state
- [ ] Do tests reasonably cover the code change (unit/integration/system tests)? 
	- [ ] Line Coverage
	- [ ] Region Coverage
	- [ ] Branch Coverage
- [ ] Are there some test cases, input or edge cases
that should be tested in addition?

## Readability
- [ ] Is the code easy to understand?
- [ ] Which parts were confusing to you and why?
- [ ] Can the readability of the code be improved by
smaller methods?
- [ ] Can the readability of the code be improved by
different function, method or variable names?
- [ ] Is the code located in the right
file/folder/package?
- [ ] Do you think certain methods should be
restructured to have a more intuitive control
flow?
- [ ] Is the data flow understandable?
- [ ] Are there redundant or outdated comments?
- [ ] Could some comments convey the message
better?
- [ ] Would more comments make the code more
understandable?
- [ ] Could some comments be removed by making the code itself more readable?
- [ ] Is there any commented-out code?

## Documentation
- [ ] Is there sufficient documentation?
- [ ] Is the ReadMe.md file up to date?

## Best Practices
- [ ] Follow Single Responsibility principle?
- [ ] Are different errors handled correctly?
- [ ] Are errors and warnings logged?
- [ ] Magic values avoided?
- [ ] No unnecessary comments?
- [ ] Minimal nesting used?

## Experts' Opinion
- [ ] Do you think a specific expert, like a security
expert or a usability expert, should look over
the code before it can be accepted?
- [ ] Will this code change impact different teams, and should they review the change as well?

2024-02-26 18:06 UTC, hedgar2017 requested changes

2024-02-26 18:06 UTC, hedgar2017 commented on .github/workflows/compiler-integration-tests.yml
> +          SLACK_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK }}
Is this mattermost supposed to be replaced?

2024-02-26 19:43 UTC, antonbaliasnikov commented on .github/workflows/compiler-integration-tests.yml
> +          SLACK_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK }}
To be discussed, probably, we need to open a new ITS ticket for testing webhook, because the one we've got is only for release notifications.

2024-02-26 22:43 UTC, hedgar2017 commented on .github/workflows/compiler-integration-tests.yml
> +          SLACK_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK }}
@antonbaliasnikov understood.
Could you please open it? At least to clarify these namings first.

2024-02-27 09:40 UTC, antonbaliasnikov commented on .github/workflows/compiler-integration-tests.yml
> +          SLACK_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK }}
I believe we could just remove these as we agree in Slack?

This is job notifications defined for all PRs sent in one place in Slack, I don't think it's useful that way. What we can implement later is to run workflows for `main` and report only failures happened there.

2024-02-27 19:12 UTC, hedgar2017 commented on .github/workflows/compiler-integration-tests.yml
> +          SLACK_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK }}
Let's do it this way:
https://linear.app/matterlabs/issue/CPR-1586/fix-ci-reports-that-are-sent-to-info-compiler-ci

2024-03-04 09:25 UTC, hedgar2017 approved these changes

2024-03-11 15:21 UTC, hedgar2017 approved these changes

2024-03-11 15:21 UTC, hedgar2017 commented on .github/actions/build/action.yml
> +      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
Just curious, why do we need this Windows thing here?

2024-03-11 15:59 UTC, antonbaliasnikov commented on .github/actions/build/action.yml
> +      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
Good catch, for this special case it should be just `bash` here, I'll fix

2024-03-11 16:16 UTC, antonbaliasnikov commented
Compiler benchmarks failure is expected, because there is no bug fix for the reference branch. It's tested with the previous version, so, it's safe to merge if integration tests all pass.

2024-03-11 16:39 UTC, hedgar2017 commented
@antonbaliasnikov the `candidate` was canceled for some reason. Is it OK?

2024-03-11 16:54 UTC, antonbaliasnikov commented
> @antonbaliasnikov the `candidate` was canceled for some reason. Is it OK?

Yes, `reference` failed and `candidate` was cancelled as nothing to compare the results to.

2024-03-11 18:04 UTC, hedgar2017 commented
@antonbaliasnikov gotcha, could you squash?

2024-03-11 18:58 UTC, antonbaliasnikov commented
> @antonbaliasnikov gotcha, could you squash?

Done. I believe we can merge. Are we always `Rebase and merge` here with manual squashes?

2024-03-11 19:21 UTC, hedgar2017 commented
> > @antonbaliasnikov gotcha, could you squash?
> 
> Done. I believe we can merge. Are we always `Rebase and merge` here with manual squashes?

Yes, it's to keep linear history in LLVM.
Unfortunately, GH doesn't provide `Squash and rebase and merge`, unless I'm missing something.

2024-03-11 19:21 UTC, merged

2024-03-11 19:41 UTC, antonbaliasnikov commented
> > > @antonbaliasnikov gotcha, could you squash?
> > 
> > 
> > Done. I believe we can merge. Are we always `Rebase and merge` here with manual squashes?
> 
> Yes, it's to keep linear history in LLVM. Unfortunately, GH doesn't provide `Squash and rebase and merge`, unless I'm missing something.

@hedgar2017 , I believe I was able to achieve this by enabling `main` branch protection rule:
<img width="426" alt="image" src="https://github.com/matter-labs/compiler-llvm/assets/22070213/5eef8be8-84f7-4f97-a6fa-8e085dbb17d0">

And then configuring PR merges like that:
<img width="508" alt="image" src="https://github.com/matter-labs/compiler-llvm/assets/22070213/57b54e6f-6b3e-4890-96a7-d9ab7d315879">
<img width="720" alt="image" src="https://github.com/matter-labs/compiler-llvm/assets/22070213/51a53e0e-56af-41c2-8d0c-520265a47288">

2024-03-11 19:51 UTC, hedgar2017 commented
@antonbaliasnikov cool, let's try it out next time.