[DO NOT MERGE] 16-bit immediate remat with folding PostRA
matter-labs/era-compiler-llvm pull request #474
Opened 2024-04-08 12:54 UTC by vladimirradosavljevic

2024-04-25 19:36 UTC, akiramenai requested changes

2024-04-25 19:36 UTC, akiramenai commented on llvm/test/CodeGen/EraVM/fold-move-imm.ll
> +define i256 @test_pos(i256 %arg) {
Can we minimize the test cases?

2024-04-25 19:36 UTC, akiramenai commented on llvm/lib/Target/EraVM/EraVMCombineAddressingMode.cpp
> +    // TODO: CPR-1669 If all users are COPY, don't create a constant pool entry.
We run the pass in post-ra.

2024-04-26 08:35 UTC, vladimirradosavljevic commented on llvm/lib/Target/EraVM/EraVMCombineAddressingMode.cpp
> +    // TODO: CPR-1669 If all users are COPY, don't create a constant pool entry.
Updated comment.

2024-04-26 08:43 UTC, vladimirradosavljevic commented on llvm/test/CodeGen/EraVM/fold-move-imm.ll
> +define i256 @test_pos(i256 %arg) {
I saw this pattern in one of our benchmarks, and I minimize it as much as possible. I know that for this purpose is more complex than it should be, so if you want I can create smaller MIR test.

2024-04-26 09:42 UTC, akiramenai approved these changes

2024-04-26 11:06 UTC, merged