ci: Remove unsupported verify options
matter-labs/era-compiler-llvm pull request #486
Opened 2024-04-19 05:56 UTC by akiramenai

Remove `--vplan-verify-hcfg`, `--loop-distribute-verify` llc options as no longer supported.

2024-04-19 10:08 UTC, antonbaliasnikov reviewed
It looks like `LLVM :: CodeGen/EraVM/fatpointer-align-assert.ll` test started to fail. @akiramenai , could you, please, take a look?

2024-04-19 11:18 UTC, akiramenai commented
@antonbaliasnikov fixed

2024-04-19 16:32 UTC, FlashSheridan commented
Explanation for `-verify-cfg-preserved` ⇒ `-verify-analysis-invalidation`: “[StandardInstrumentations] Rename -verify-cfg-preserved -> -verify-analysis-invalidation” https://reviews.llvm.org/D146069, linked from the change Anton posted, https://github.com/matter-labs/era-compiler-llvm/commit/361cba22b2013f66e5b18896ffcf2564b332ab7b.

2024-04-19 16:40 UTC, FlashSheridan commented
Given that this now includes a non-test fix, “[[EVM] Fix analyses invalidation in EVMLinkRuntime](https://github.com/matter-labs/era-compiler-llvm/pull/486/commits/b1ae6859d182d1868efa2e0d561b55adf1c1c3f7),” should “ci:” be removed from the title?

2024-04-19 17:04 UTC, FlashSheridan commented
`--loop-distribute-verify` seems to be hidden, not removed:

```
static cl::opt<bool>
LDistVerify("loop-distribute-verify", cl::Hidden,
cl::desc("Turn on DominatorTree and LoopInfo verification "
```
(https://github.com/llvm/llvm-project/blob/cd9f98de7309bf94369929b0bd957cd6f5e5a9ed/llvm/lib/Transforms/Scalar/LoopDistribute.cpp#L88)

```
flash@Astrophage llvm % ../target-llvm/build-final/bin/llc --help-hidden | grep loop-distribute-verify
  --loop-distribute-verify                                              - Turn on DominatorTree and LoopInfo verification after Loop Distribution
```

It’s accepted in my local build from 4139547:
```
flash@Astrophage llvm % ../target-llvm/build-final/bin/llc --loop-distribute-verify  llvm/test/CodeGen/EraVM/pointer.ll
Astrophage ~/Documents/Code/compiler-tester/llvm                                                      24-04-19 12:56:38
[../target-llvm/build-final/bin/llc --loop-distribute-verify  llvm/test/CodeGen/EraVM/pointer.ll]
flash@Astrophage llvm % echo $?
0

```

2024-04-19 17:06 UTC, FlashSheridan requested changes
I think the title needs to be updated, and would like to see `--loop-distribute-verify` preserved, per comments, if practical.

2024-04-19 17:46 UTC, akiramenai commented
@FlashSheridan makes sense. Let me fraction non-CI part, so we can release earlier.

2024-04-21 20:41 UTC, akiramenai commented
@FlashSheridan could you double check the build you mention is indeed based on LLVM 17? `LoopDistribute` is linked to `Scalar` while `llc` doesn't link this component (`opt` does). I also checked it locally:
```
❯ ./bin/llc --loop-distribute-verify memset.log.ll
llc: Unknown command line argument '--loop-distribute-verify'.  Try: './bin/llc --help'
llc: Did you mean '--disable-verify'?
❯ bin/llc --help-hidden | grep loop-distribute-verify
```

2024-04-22 15:22 UTC, FlashSheridan commented
> @FlashSheridan could you double check the build you mention is indeed based on LLVM 17? 

You’re right, I hadn’t rebuilt that binary, but the option is accepted by both my 17.0.6 and  upstream 19.0.0 versions:

```
flash@Astrophage llvm-project % ~/Documents/Code/external_code/Alive2_17/llvm-project/build/bin/llc --loop-distribute-verify ~/Documents/Code/compiler-tester/llvm/llvm/test/Analysis/AliasSet/argmemonly.ll
Astrophage ~/Documents/Code/external_code/ToT_LLVM/llvm-project                                       24-04-22 11:20:04
[~/Documents/Code/external_code/Alive2_17/llvm-project/build/bin/llc --loop-distribute-verify ~/Documents/Code/compiler-tester/llvm/llvm/test/Analysis/AliasSet/argmemonly.ll]
flash@Astrophage llvm-project % echo $?
0



~/Documents/Code/external_code/Alive2_17/llvm-project/build/bin/llc --version
LLVM (http://llvm.org/):
  LLVM version 17.0.6
…
```

```
flash@Astrophage llvm-project % ~/Documents/Code/external_code/ToT_LLVM/llvm-project/build/bin/llc --loop-distribute-verify ~/Documents/Code/compiler-tester/llvm/llvm/test/Analysis/AliasSet/argmemonly.ll
Astrophage ~/Documents/Code/external_code/ToT_LLVM/llvm-project                                       24-04-22 11:21:06
[~/Documents/Code/external_code/ToT_LLVM/llvm-project/build/bin/llc --loop-distribute-verify ~/Documents/Code/compiler-tester/llvm/llvm/test/Analysis/AliasSet/argmemonly.ll]
flash@Astrophage llvm-project % echo $?
0
…

~/Documents/Code/external_code/ToT_LLVM/llvm-project/build/bin/llc --version
LLVM (http://llvm.org/):
  LLVM version 19.0.0git
```

2024-04-22 15:43 UTC, FlashSheridan commented
> You’re right, I hadn’t rebuilt that binary, but the option is accepted by both my 17.0.6 and **upstream** 19.0.0 versions:…

On the third hand, I do get the error you do with _our_ 17.0.6 (861014):

```
flash@Astrophage llvm-project % ~/Documents/Code/Alive17Open/era-compiler-tester/target-llvm/build-final/bin/llc  --loop-distribute-verify ~/Documents/Code/compiler-tester/llvm/llvm/test/Analysis/AliasSet/argmemonly.ll
llc: Unknown command line argument '--loop-distribute-verify'.  Try: '/Users/flash/Documents/Code/Alive17Open/era-compiler-tester/target-llvm/build-final/bin/llc --help'
llc: Did you mean '--disable-verify'?
Astrophage ~/Documents/Code/external_code/ToT_LLVM/llvm-project                                       24-04-22 11:40:26
[~/Documents/Code/Alive17Open/era-compiler-tester/target-llvm/build-final/bin/llc  --loop-distribute-verify ~/Documents/Code/compiler-tester/llvm/llvm/test/Analysis/AliasSet/argmemonly.ll]
flash@Astrophage llvm-project % echo $?
1
Astrophage [echo $?] ~/Documents/Code/external_code/ToT_LLVM/llvm-project                             24-04-22 11:40:28
flash@Astrophage llvm-project % ~/Documents/Code/Alive17Open/era-compiler-tester/target-llvm/build-final/bin/llc --version
Matter Labs LLVM version 17.0.6
  Git: 861014d07d3130964284aecc918085188a0dc70d


```

2024-04-22 20:24 UTC, akiramenai commented
@FlashSheridan what is the list of targets you have for non-our LLVM? Perhaps one of them link Scalar.

2024-04-22 20:27 UTC, akiramenai commented
AArch64 links it.
```
  LINK_COMPONENTS
  AArch64Desc
  AArch64Info
  AArch64Utils
  Analysis
  AsmPrinter
  CFGuard
  CodeGen
  CodeGenTypes
  Core
  GlobalISel
  MC
  Scalar
  SelectionDAG
  Support
  Target
  TargetParser
  TransformUtils
```
But I tend to exclude as we don't use this pass in our code generator.

2024-04-22 21:53 UTC, FlashSheridan commented
@FlashSheridan what is the list of targets you have for non-our LLVM?On Apr 22, 2024, at 4:27 PM, Dmitry Borisenkov ***@***.***> wrote:AArch64 links it.Can’t check from the train station, but I think so.  So removing that option LGTM. 

2024-04-22 23:26 UTC, FlashSheridan approved these changes
LGTM once the tests complete.

2024-04-23 10:53 UTC, merged